### ISSUE TITLE
Error when using {include} within {capture}

### ISSUE THREAD

**Issue by lemon-juice** [smarty-php/smarty#100]
A most basic template to reproduce:

```
{capture}
	{include file="admin/included.tpl"}
{/capture}
```

Smarty complains with this error: Not matching {capture} open/close in "file:admin/included.tpl".

The contents of the included template does not matter, it can even be an empty file.

This error occurs in the newest build 3.1.28-dev/71 but as far as I can see the bug is a few months old - however, 3.1.27 works fine in this respect.

**Comment by uwetews** [comment]
Hi,  I can't reproduce it.  (now at 3.1.28-dev/72)

**Comment by lemon-juice** [comment]
I decoupled the code from my application to be sure that nothing else influences the result and the problem seems easily reproducible. [Here is](https://dl.dropboxusercontent.com/u/13230070/smarty-test.zip) the minimalist application that exhibits the problem, it contains smarty 
3.1.28-dev/72 - just run test.php in a browser and the page displays:

> Fatal error: Uncaught --> Smarty: Not matching {capture} open/close in "file:admin/included.tpl" <-- thrown in /home/users/user1/public_html/test-smarty/lib/smarty/sysplugins/smarty_internal_template.php on line 254

The same thing happens on my local windows installation PHP 5.5.23 and on a linux remote host (PHP 5.6.14).

**Comment by uwetews** [comment]
the fix is now in the master branch

**Comment by lemon-juice** [comment]
Thanks, it works well now.
