### ISSUE TITLE
PHP Deprecated:  Using Smarty::loadFilter() to load filters is deprecated and will be removed in a future release. 

### ISSUE THREAD

**Issue by courou** [smarty-php/smarty#1009]
Bonjour,

J'utilisais ceci avec smaty avant de passer en smarty5
$smarty->loadFilter('output','trimwhitespace');

mais avec php 8.2 j'ai le message suivant 
PHP Deprecated:  Using Smarty::loadFilter() to load filters is deprecated and will be removed in a future release. 
Use Smarty::addExtension() to add an extension or Smarty::registerFilter to quickly register a 
filter using a callback function. in /vendor/smarty/smarty/src/Smarty.php on line 1817

Quelqu'un pourrais - il m'aider car je n'ai rien trouvé dans la doc

**Comment by devthisath** [comment]
Bonjour,

Si tu n'as pas encore trouvé la solution, voici ce que tu peux faire :
1. Déclare la classe du filtre : `use Smarty\Filter\Output\TrimWhitespace;`
2. Enregistre le filtre avec la nouvelle méthode : `$smarty->registerFilter('output', [new TrimWhitespace(), 'filter']);`

Cela vous permet de continuer à utiliser le filtre de sortie « trimwhitespace » sans omettre l'avis d'obsolescence.
