### ISSUE TITLE
Smarty v5 Error: {section} Tag First Argument Type Mismatch when opening and closing tag on NoCache

### ISSUE THREAD

**Issue by Khem** [smarty-php/smarty#1034]
Error: `Smarty\Compile\Base::openTag(): Argument #1 ($compiler) must be of type Smarty\Compiler\Template, string given, called in /var/www/html/vendor/smarty/smarty/src/Compile/Tag/Section.php on line 102.`

We have a string passed on [$this->openTag('nocache')](https://github.com/smarty-php/smarty/blob/master/src/Compile/Tag/Section.php#L102) but expects [`Template $compiler`](https://github.com/smarty-php/smarty/blob/master/src/Compile/Base.php#L173). Must be the same situation when closing the tag.

Thanks

**Comment by wisskid** [comment]
Do you have an example of the Smarty code that triggers this error?

**Comment by Khem** [comment]
`{section name=module start=0 loop=1 nocache}`

**Comment by wisskid** [comment]
@Khem thanx for your report. The issue has been fixed and released in v5.3.1.
