### ISSUE TITLE
Smarty Not Working

### ISSUE THREAD

**Issue by Ezzytechs** [smarty-php/smarty#1037]
Get this error while I download and try to lunch demo project on my pc using xamp
Parse error: syntax error, unexpected variable "$smarty" in C:\Program Files\XAMPP\htdocs\smarty-master\demo\index.php on line 8. How do i solve this error?

**Comment by wisskid** [comment]
Show us the source of this index.php file?

I don't know the "lunch demo" project that you are referring to.

**Comment by Ezzytechs** [comment]
okay. thank you for your assistance. the demo project I am talking about is the default demo folder in the smarty file when I download it. The file refuse to open my browser while i navigate to it using XAMPP via local host. The index.php is in the root directory of my own project im trying to create using smarty. thanks

**Comment by wisskid** [comment]
In that case you may be using an outdated PHP version. Also, you need to follow the [installation instructions](https://smarty-php.github.io/smarty/stable/getting-started/)
