### ISSUE TITLE
Fatal Error When Active Debug Mode ('debug_left_delimiter')

### ISSUE THREAD

**Issue by yassereldeghidy** [smarty-php/smarty#104]
Smarty 3.1.27
i' have get Fatal Error When Enable Debug mode By Using 
$smarty=new smarty;
$smarty->debug=true;
'debug_left_delimiter'
 ``` 
Fatal error: Uncaught --> Smarty: template property 'debug_left_delimiter' does not exist. <-- thrown in C:\AppServ\www\Zimos\plugins\libs\sysplugins\smarty_internal_template.php on line 910
```

**Comment by uwetews** [comment]
Smarty does not use this property.
Can you find out where it is used in your project?

**Comment by yassereldeghidy** [comment]
thanks uwetews find solve
