### ISSUE TITLE
How to use '|' as '||'?

### ISSUE THREAD

**Issue by pmsl987** [smarty-php/smarty#1041]
`{if $a|$b } `
the code is can work in smarty2.1,but in smarty5.x has error:
`Unexpected "$b", expected one of: "id, name" , "@" `
There are a lot of similar codes in my project, I can't use '||' replace it.

**Comment by wisskid** [comment]
I'm afraid you can't. The `|` has a special meaning in Smarty. It activates a modifier. I think that it was unintentional that this worked in Smarty 2. But Smarty 3 is a long long time ago, so I can't really be sure.
