### ISSUE TITLE
How it's possible to modifiy tpl_vars subkey inside a plugin function

### ISSUE THREAD

**Issue by Zakwil** [smarty-php/smarty#1042]
In smarty 4 I used a function to modify subkey of tpl_vars, but I tried to transfert this one in a method and I think my reference on $smarty is not working anymore. And the value in tpl_vars is not modified after the fetch

Previous (smarty4) : 
```
function smarty_function_assign_subkey($params, &$smarty)
{
	$vVar		= trim($params['var'], "'");
	$vSubkey	= trim($params['subkey'], "'");
	$vValue		= trim($params['value'], "'");

	if (!isset($params['cat'])) {
		$smarty->tpl_vars[$vVar]->value[$vSubkey] = $vValue;
	} else {
		$smarty->tpl_vars[$vVar]->value[$vSubkey] .= ','.$vValue;
	}
}//smarty_function_assign_subkey

```
New (smarty5) :
```
public static function assign_subkey($params, $smarty) {
	$vVar		= trim($params['var'], "'");
	$vSubkey	= trim($params['subkey'], "'");
	$vValue		= trim($params['value'], "'");

	if (!isset($params['cat'])) {
		$smarty->getSmarty()->tpl_vars[$vVar]->value[$vSubkey] = $vValue;
	} else {
		$smarty->getSmarty()->tpl_vars[$vVar]->value[$vSubkey] .= ','.$vValue;
	}
}//assign_subkey
```

**Comment by wisskid** [comment]
Please use $smarty->assign() instead of accessing tpl_vars directly: https://smarty-php.github.io/smarty/5.x/api/variables/assigning/

**Comment by Zakwil** [comment]
Ok I tried $smarty->getSmarty()->append('data', array($vSubkey => $vValue), 1);
But the scope of the object is related to the fetch, I do 2 fetch : one with the body of the page and the other with the main structure.
And the 1st fetch doesn't modify the object and the 2nd fetch don't have the value.

**Comment by Zakwil** [comment]
Ok I saved the var and pass it to my object.
