### ISSUE TITLE
unknown modifier 'var_dump' and unknown modifier 'print_r'

### ISSUE THREAD

**Issue by ManuelWohlstreicher** [smarty-php/smarty#1052]
Hi, 
i updatet my project from Smarty 3 to 5, without Composer.

Everything works fine so far but when i write something like {var_dump($Terminplan->Termine)} or {$Terminplan->Termine|@print_r} i always get a fatal error "unknown modifier 'var_dump' or 'print_r'" and i cant see the problem, how can i fix this?

thx

**Comment by wisskid** [comment]
Please read the upgrading instructions, especially https://smarty-php.github.io/smarty/5.x/upgrading/#using-native-php-functions-or-userland-functions-in-your-templates

Thanks
