### ISSUE TITLE
include file behavior change with V5

### ISSUE THREAD

**Issue by ephenyxshop** [smarty-php/smarty#1058]
Hi
I have several tzmplates who use sub template, till 4 version, I used : 
{include file='./input_text_lang.tpl'}
input_text_lang.tpl is in the same directopry.
Sinve V5, nothing work any longer
Any assista,nce please ?

**Comment by wisskid** [comment]
Are you seeing any error messages?

**Comment by wisskid** [comment]
Closed because of inactivity.
