### ISSUE TITLE
{foreach} non-null values are treated as arrays

### ISSUE THREAD

**Issue by arleslie** [smarty-php/smarty#107]
When using ```{foreach}/{foreachelse}``` and a non-array value is passed as the assigned value, ```{foreachelse}``` is not processed.

```$smarty->assign('array', false);```

```
{foreach from=$array item=v}
    {$v}
{foreachelse}
    no values
{/foreach}
```

The above code will render nothing being outputted.

~~In the documentation it shows that a PDO response with no values will throw to ```{foreachelse}``` but a PDO result that has no values is ```false```.~~
PDOStatement::fetchAll() with errors and PDOStatement::fetch() with no results will return ```false```.

It appears that the check being done to see if it should throw to ```{foreachelse}``` is ```isset()``` instead of ```!empty()``` as a ```null``` value will throw to ```{foreachelse}```.

Note: empty arrays are treated correctly.

**Comment by uwetews** [comment]
It's a historic behavior that all none object values are converted into array. Modifying the check to empty() would break backward compatibility for values like 0 or others. This is not a good idea.

Regarding PDO don't call PDOStatement::fetchAll(), just assign the PDOStatement object. It's Traversable and can be looped over.
You may need to call PDOStatement::setFetchMode() to configure the format of the row results.

**Comment by arleslie** [comment]
Not really sure why anyone would want ints or booleans to be converted to an array as it just wouldn't work. 

```
foreach (array(false) as $value) {
    echo $value;
}
```

Would output nothing. 

Using just the PDOStatement does appear to be a valid workaround though.

**Comment by uwetews** [comment]
Your assumption that the {foreach} item value is used just for output is wrong.
It could be used in {if} conditions so booleans or other values make sense.
