### ISSUE TITLE
@link from plugins/modifiercompiler.strip_tags.php leads to smarty2 manual

### ISSUE THREAD

**Issue by ildar-aim** [smarty-php/smarty#108]
### The file is 
plugins/modifiercompiler.strip_tags.php

### The current link is 
http://www.smarty.net/manual/en/language.modifier.strip.tags.php
which is redirected to 
http://www.smarty.net/docsv2/en/language.modifier.strip.tags

### The expected link is 
http://www.smarty.net/docs/en/language.modifier.strip.tags.tpl

**Comment by uwetews** [comment]
done
