### ISSUE TITLE
strftime deprecated in PHP8.1

### ISSUE THREAD

**Issue by happit-jannes** [smarty-php/smarty#1080]
According to the smarty 5 docs, `date_format` still uses `strftime` under the hood.

This function has been deprecated by PHP.

We either need a backwards compatible implementation, or deprecate `date_format` for a more modern alternative.

Personally suggest using `IntlDateFormatter` if the intl extension is installed with a fallback on regular `DateTime::format`. However, both use a different API (PHP's date format VS ICU), and both are also incompatible with `strftime`'s format.

What's the official stance on this?

**Comment by wisskid** [comment]
please see https://github.com/smarty-php/smarty/issues/810
