### ISSUE TITLE
strip-tag strips white space innside tag if its next to a newline

### ISSUE THREAD

**Issue by mem76** [smarty-php/smarty#111]
If a white-space is near a newline, both the newline and the white-space will be removed, resulting in a unknown html-tag.

Se attached image for example with Smarty 3.1.27.

![smarty-strip_bug](https://cloud.githubusercontent.com/assets/16096631/11498429/b017ce84-981f-11e5-8304-5fae05ca19fd.png)

**Comment by uwetews** [comment]
The fix is now in the master branch and will be in included in the next release 3.1.28

**Comment by uwetews** [comment]
The master branch is updated once again because some html tags must be excluded from stripping
