### ISSUE TITLE
Smarty doesn't reflect an update in a template on first run

### ISSUE THREAD

**Issue by ccerrillo** [smarty-php/smarty#112]
When a template is modified, when it is loaded in browser the old contents are shown, but compiled template in compiled dir reflects the change

### VERSION
3.1.27 with default options

### STEPS TO REPRODUCE
1. Create index.tpl in templates dir
2. Load page in browser
3. Modify content from index.tpl
4. Load page in browser

### EXPECTED
Show new content

### RESULT
Show old content

**Comment by ccerrillo** [comment]
As a workaround i need to set force compile:
`$tpl->setForceCompile(true);`

**Comment by uwetews** [comment]
I confirm the bug that 3.1.27 does show a modified template with a delay of one page call.
Normally this should have little impact.
Using forceCompile is a bad workaround as it will recompile the template on each page call.

This is fixed already in the master branch.
