### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by SilverFire** [smarty-php/smarty#113]
Hello, team!
PHP7 has been released almost a week ago, but your last stable release is incompatible with PHP7 because of the problem in [smarty_internal_templatecompilerbase.php:555](https://github.com/smarty-php/smarty/blob/v3.1.27/libs/sysplugins/smarty_internal_templatecompilerbase.php#L555). This line causes `Array to string conversion`, and [is fixed in the @dev version](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatecompilerbase.php#L572)

I'm kindly ask you to tag a new release, if it's possible. Thank you!

**Comment by uwetews** [comment]
3.1.28 is now released

**Comment by SilverFire** [comment]
Thank you very much :)
