### ISSUE TITLE
{function} doesn't work with {extend} in 3.1.28

### ISSUE THREAD

**Issue by pikusov** [smarty-php/smarty#114]
Parent template file named index.tpl:

```php
<html>
<head>
{block 'head'}
	<title>Example</title>
{/block}
</head>
<body>
	<div id="menu">
		{block 'menu'}{/block}
	</div>
	<div id="main">
		{block 'main'}{/block}
	</div>
</body>
</html>
```

Child template named page1.tpl:
```php
{extends 'index.tpl'}
{block name='menu'}

	{function name=category_select level=0}
	<ul>
		{foreach $categories as $category}
		<li>
			{$category->name}
			{category_select categories=$category->subcategories level=$level+1} 
		</li>
		{/foreach}		
	</ul>
	{/function}
	{category_select categories=$categories}

{/block}
```

Another child template named page2.tpl:
```php
{extends 'index.tpl'}

{block name='menu'}

	{function name=category_select2 level=0}
	<ul>
		{foreach $categories as $category}
		<li>
			{$category->name}
			{category_select2 categories=$category->subcategories level=$level+1} 
		</li>
		{/foreach}		
	</ul>
	{/function}
	{category_select2 categories=$categories}

{/block}
```

1) Open page1.php (which $smarty->fetch('page1.tpl'))
Page displayed ok
2) Open page2.php (which $smarty->fetch('page2.tpl'))
Get "Fatal error: Uncaught --> Smarty: Unable to find template function 'category_select2' <-- thrown in ***/smarty_internal_runtime_tplfunction.php on line 45"
3) Clear all compiled templates files
4) Open page2.php
Page displayed ok
5) Open page1.php
Get Fatal error: Uncaught --> Smarty: Unable to find template function 'category_select' <-- thrown in ***/smarty_internal_runtime_tplfunction.php on line 45
6) Clear all compiled templates files again
7) Open page1.php
Page displayed ok
8) Do any change in page1.tpl
9) Open page1.php
Get Fatal error: Uncaught --> Smarty: Unable to find template function 'category_select' <-- thrown in ***/smarty_internal_runtime_tplfunction.php on line 45

**Comment by uwetews** [comment]
The fix is now in the master branch.
Note:
The {function}...{/function} can and should better be placed outside {block)...{/block}
