### ISSUE TITLE
Illegal offset type in isset or empty in libs/Smarty.class.php on line 849

### ISSUE THREAD

**Issue by jjmakin** [smarty-php/smarty#115]
This gets logged to my error logs every time a page is loaded.

        if ($index !== null) {
            return isset($this->{$type}[$index]) ? $this->{$type}[$index] : null;
        }

Could the middle line be rewritten, please?

**Comment by uwetews** [comment]
Does it happen on $smarty->display()?  How does your template name look like?
Which Smarty / PHP version?

**Comment by jjmakin** [comment]
It appears to happen just the first time I call $smarty->display(), regardless of how many times I call display.
I am using php 5.6.14 on el6.

**Comment by jjmakin** [comment]
I can also replicate this behaviour on php 5.5.30 - I also meant to say latest Smarty, as I pulled straight from github.

**Comment by jjmakin** [comment]
I recently moved from 3.1.17 to latest, and I'm probably using deprecated calls.
I'm now reading up on http://www.smarty.net/docs/en/variable.template.dir.tpl

Some of my code contained:
        $smarty->template_dir = array('../custom_templates', '../templates', 'templates');
Which I think is no longer the way to do it.

**Comment by jjmakin** [comment]
Please accept my apologies, this was my mistake
I changed the line above to
$smarty->setTemplateDir(array('../custom_templates', '../templates', 'templates'));
and now everything works without any errors.
