### ISSUE TITLE
modifiers should be case sensitive or plugin loader should handle case folds

### ISSUE THREAD

**Issue by Gamesh** [smarty-php/smarty#116]
if you have a modifier.userinfo.php:
```php
function smarty_modifier_userinfo(){}
```
and in smarty template use `{$var|userinfo}` and then in some other part accidently `{$var2|userInfo}` (notice uppercase lettter I), smarty thinks that the later plugin is not yet loaded and tries to load it again and produces a fatal error:
```
 Fatal error: Cannot re-declare smarty_modifier_userinfo() (previously declared in .../plugins/modifier.userInfo.php:9) in .../plugins/modifier.userinfo.php on line 16
```
as the FS is not case sensitive, it load the same file and the file whether it's modifier.userInfo.php or modifier.userinfo.php exists.

the desired behavior would be if modifiers would be case sensitive or the loader would lowercase all loaded modifier plugin names so that it wouldn't see these as two different. Maybe the second one would be less BC breaking, as this modifiers are not case sensitive.

**Comment by uwetews** [comment]
The Windows file system is not case sensitive, but the Linux file system is.
As there is a chance that Linux users use modifier names with uppercase characters we can't lowercase the names. We could use include_once instead include but this would have an impact on performance. I think that the problem you have seen should be very rare that we should make such change.
