### ISSUE TITLE
Regression in 3.1.28 - Unable to load template file

### ISSUE THREAD

**Issue by remicollet** [smarty-php/smarty#121]
Updating from 3.1.27 to 3.1.28

     PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file 'index.tpl' <-- \n  thrown in /usr/share/php/Smarty/sysplugins/smarty_internal_template.php on line 139

**Comment by uwetews** [comment]
The template file could not be found.
Did you extend the Smarty class and over load the Smarty::$template_dir property instead using the
Smarty::setTemplateDir() method?

**Comment by remicollet** [comment]
>  Did you extend the Smarty class and over load the Smarty::$template_dir property instead using the
Yes
I fix it with https://github.com/remicollet/rpmphp/commit/1be373d489817ff91e077c97ac91779ebc1c8e22

**Comment by blaaat** [comment]
http://www.smarty.net/docs/en/variable.template.dir.tpl
As of Smarty 3.1 the attribute $template_dir is no longer accessible directly. Use getTemplateDir(), setTemplateDir() and addTemplateDir() instead.

Wouldn't it be a great idea to make this variable inaccessible, so a proper error message is displayed?

**Comment by remicollet** [comment]
> Wouldn't it be a great idea to make this variable inaccessible, so a proper error message is displayed?
+1

BTW, such change/break in minor version seems bad. Please http://semver.org/

**Comment by uwetews** [comment]
It was a bug. Setting $smarty->template_dir directly should have called setTemplateDir() internally..

The fix is in the master branch
