### ISSUE TITLE
$smarty.cookie access

### ISSUE THREAD

**Issue by d2one** [smarty-php/smarty#122]
Updating from 3.1.27 to 3.1.28
Using v3.1.2.8 a have problem with cookies access
I have a cookie 'offers_favorites' => string '[7265850,7220473,7215264,7201342,7200429]' (length=41)
When i try to get this value in tpl, 
{assign var='favoritesOffers' value=$smarty.cookies.offers_favorites|json_decode}
i've got an error 
Warning: json_decode() expects parameter 1 to be string, array given
<?php $_smarty_tpl->tpl_vars['favoritesOffers'] = new Smarty_Variable(json_decode($_COOKIE), null);
  
I can't access to cookie key...

**Comment by uwetews** [comment]
orry that it got broken.
The fix is now in the master branch
