### ISSUE TITLE
Regression in 3.1.28 - extendsall resource type before template file name doesn't work

### ISSUE THREAD

**Issue by chilek** [smarty-php/smarty#123]
When we use
```smarty
{include file="extendsall:template.html"}
```
in our template, extendsall is not supported at all in 3.1.28.
File which defines extendsall resource type is original **resource.extendsall.php** file from tgz package (**demos/plugins/resource_extendsall.php**) and is placed in **/path/to/application/plugins** directory added to plugin dirs by the following code:
```php
$smarty->addPluginsDir('/path/to/application/plugins');
```

In 3.1.27 workaround with prefilter replacing **{include file="template.html"}** by **{include file="extendsall:template.html"}** was a solution.

**Comment by uwetews** [comment]
I can't reproduce your problem. If I use something like
```php
{include file="extendsall:template.html"}
```
the resource gets loaded from the plugins folder.

Note: The file name is resource.extendsall.php, not resource_extendsall.php or was it just a typo?

**Comment by chilek** [comment]
First of all - of course I've made mistake with extendsall resource plugin file - it was and it's named resource.extendsall.php ;-)

In 3.1.27 I've used the following code:
```php
class Smarty_Prefilter_Extendsall_Include {
	static public function prefilter_extendsall_include($tpl_source, Smarty_Internal_Template $template) {
		if (is_array($template->smarty->template_dir) === false)
			return $tpl_source;
		// prepend all files in {include} blocks with resource type 'extendsall:'
		return preg_replace('#(\{include\s*file=[\'"])(?:(?![a-z]+:|/|\{))(.+)([\'"][^}]*\})#i', '$1extendsall:$2$3', $tpl_source);
	}
}
```
to automatically prepend template file name with 'extendsall:' in all inclusions inside template file.
That doesn't work anymore with 3.1.28 :(
Simply I don't want to change all include's in templates prepending their names with 'extendsall'.
How could I do that with 3.1.28?

**Comment by uwetews** [comment]
How did you make the filter known?
I tried    
```php
 $smarty->registerFilter('pre',array('Smarty_Prefilter_Extendsall_Include', 'prefilter_extendsall_include'));
```
and it worked.

**Comment by chilek** [comment]
Exactly the same as you wrote.
You mean 'it worked' as prepended all included templates with 'extendsall:' and loaded them properly?

**Comment by chilek** [comment]
Uwe, have a look at problem demonstration which I've prepared. You can download it from:
https://www.chilan.com/smarty-3.1.28-extendsall-test.tar.xz

**Comment by uwetews** [comment]
You have general design problem.
By using extendsall in your example "data1.html" get loaded from both template folders template1 and template2. "data1.html" contains {extends 'data1.html'}. 
Two problems:
A) A template should never call extends with same name. 
B) Using extendsall on templates which contain {extends} with same template name will create endless loops.
It did work accidentally in previous Smarty versions by the way how Smarty resolved {block} tag replacement at compile time.
With Smarty 3.1.28 template inheritance was changed to run time processing the resolved previous shortcomings. Now all the design flaws are popping up.

I would also get rid of the pre-filter as you may get results you don't expect by the template code.

**Comment by chilek** [comment]
The assumption with previous smarty version was that when I extend 'data1.html' first time I can modify content from dynamically loaded plugins - templates2 in such example is plugin template directory (first directory from template directory list), so data1.html from templates2 had been used already and smarty, knowing about that, took into account data1.html from templates1 avoiding endless loop / recursion. That was very cool feature which allows us to construct plugins which hide original template from application core, but at the same time allow to use template content from core without rewriting all...

**Comment by uwetews** [comment]
I need to think about it, might take a few days....

**Comment by chilek** [comment]
Nice to hear that. Uwe, who personally gets payments after clicking "Donate" (Paypal) on smarty.net www site?

**Comment by uwetews** [comment]
Perhaps I get a Christmas present.... lol
I think I do understand your basic idea. But as I said before your solution did work so far by some internal behavior of Smarty and not really because of template and application code. Lets see if ther is a clean solution.

**Comment by uwetews** [comment]
Why do you need the {extends 'data1.html'} in templates2/data1.html ?
If you remove that it does work.
Because of some patches use the master branch version for testing.

**Comment by chilek** [comment]
I've asked about "Donate" button, because I'd like to pay voluntarily 10$ monthly. I know that open source projects always suffer from underfunding, so when most smarty users would pay 10$ monthly (I'm pretty sure they do their bussiness quite well thank to Smarty) the project would be much more vital ;-)

**Comment by chilek** [comment]
> Why do you need the {extends 'data1.html'} in templates2/data1.html ?
> If you remove that it does work.
> Because of some patches use the master branch version for testing.

So if I'll remove {extends file="data1.html'} from templates2/data1.html from templates1/data1.html
it will take templates2/data1.html and append its contents to templates1/data1.html?
So I'd use more template dirs i.e. templatesN/data1.html, ..., templates3/data1.html, templates2/data1.html, template1/data1.html smarty will use all data1.html in "chain" as they appear?

**Comment by uwetews** [comment]
As I said before  {extends} must never use same template name as the calling one.
Because of your template_dir order {extends file="data1.html'} from templates2/data1.html it does find
 templates2/data1.html as the first matching file and so calling itself and causing an endless loop.
The extendsall resource does load all template files in chain as they appear. It works similar to the extends resource where all temple names are the same but uses the template_dir order to define child and parent relation ships.
In your case the {extends} is only useful if you need to extend a template file which will be not loaded by extendsall.

Instead of using the prefilter can
```php
$smarty->setDefaultResourceType('extendsall');
```
to change the default resource type from file to extendsall.

Your donates will be always wellcome.

**Comment by chilek** [comment]
>Why do you need the {extends 'data1.html'} in templates2/data1.html ?
>If you remove that it does work.
>Because of some patches use the master branch version for testing.

As I see when I'll use data1.html localised by template dir chain in this order:
```
templates2/data1.html, templates1/data1.html 
```
templates2/data1.html will be loaded only and templates1/data1.html will not?
When I used:
```smarty
{extends file="data1.html"}
```
both file were loaded, and first one could manipulate block contents defined in second one.
When I remove above {extends ...} from templates2/data1.html it won't be possible to modify templates1/data1.html and in fact this last file will not be loaded at all.
Am I missed something?

In Smarty < 3.1.28:
```php
$smarty->setDefaultResourceType('extendsall');
```
caused template file load errors so as workaround I had to use prefilter.
I'll try this again with 3.1.28 and with master branch head.

**Comment by chilek** [comment]
Ok I've changed index.php from previous test application to:
```php
include('smarty.git/libs/Autoloader.php');
Smarty_Autoloader::register();

$SMARTY = new Smarty;

$SMARTY->addPluginsDir('SmartyPlugins');

$SMARTY->setDefaultResourceType('extendsall');

$SMARTY->setTemplateDir(null);
$SMARTY->AddTemplateDir(array('templates2', 'templates1'));
$SMARTY->setCompileDir('templates_c');

$SMARTY->display('template.html');
```
and this is the only changed file.
I tried smarty 3.1.28 and smarty from git master HEAD (smarty.git is clone of github's smarty).
In both cases I got HTTP 500 error.
Then commented out:
```php
$SMARTY->setDefaultResourceType('extendsall');
```
and with git master HEAD the generated content is blank (no HTTP error). With 3.1.28 content is generated partly - only from **header** block :(

**Comment by uwetews** [comment]
1.
```php
$SMARTY->setDefaultResourceType('extendsall');
```
sorry, it  did require a bugfix which is now in the master branch.

2.
You must use the newest resource.extendsall.php which you did not in the provided example

**Comment by chilek** [comment]
I did:
```bash
git pull
```
on smarty repo local copy and it seems to work ;-) Thanks a lot, Uwe!

**Comment by uwetews** [comment]
Anyway it was an interesting use case of extendsall.
So I did learn also a bit. :)

**Comment by chilek** [comment]
I've found another bug: when we prepend template dir chain with **templates_3** directory and put data1.html file there with the following content:
```smarty
{block name="content-data1" prepend}
<p>data1 from templates3</p>
{/block}
```
after reload page in web browser we get HTTP 500 error. To resolve the problem we have to clear smarty compiled templates' cache. Then it works again. Any change in template dir chain required clearing cache :(

**Comment by chilek** [comment]
PHP error log shows:
```
[20-Dec-2015 15:18:19 Europe/Warsaw] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template file '[1]template.html' in 'template.html' <-- 
  thrown in /var/www/chilan.com/htdocs/smarty-test/Smarty/libs/sysplugins/smarty_internal_template.php on line 139
```
It seems that templates are not recompiled "magically" after template directory chain, because [1]template.html is invalid if we have 3 template dirs in chain.

**Comment by uwetews** [comment]
Grr  I see what happens when you change your template_dir settings. I have today no time left. I will look into it tomorrow

**Comment by chilek** [comment]
No problem - there is no pressure :) Thanks in advance for problem investigation.

**Comment by uwetews** [comment]
The fix (resource.extendsall.php) is now in the master branch

**Comment by chilek** [comment]
I confirm that commit mentioned above resolves my problem.

**Comment by uwetews** [comment]
Me again.
There is another update in the master branch with speed optimizations.

You may also use
```php
$smarty->setMergeCompiledIncludes(true);
```
With this setting Smarty create a single compiled file containing all template code.
This executes much faster as just one file has to me  loaded.

Another note: You may place a {strip} tag at the beginning of the template files to get rid of empty lines, or enable it for certain section with {strip} {/strip}.

btw  I added your special use case to our PHPunit tests. Hopefully we not run again in future into problems like this

Regars Uwe

**Comment by chilek** [comment]
Great to hear that - after git pull works like a charm ;-) 
Thanks a lot again.

**Comment by uwetews** [comment]
By the way, I have released 3.1.29

**Comment by chilek** [comment]
Wow, I'll update smarty requirement in my application very soon ;-)

**Comment by uwetews** [comment]
It took a while to sort all things out. But the case to use extendsall over all levels of templates and sub-templates including inheritance was also a bit new to me. I think we have now removed all ambiguousness in template and script code,

Small hint

```php
$SMARTY->setTemplateDir(null);
$SMARTY->addTemplateDir(array('templates2', 'templates1'));
```
can be replaced by
```php
$SMARTY->setTemplateDir(array('templates2', 'templates1'));
```

**Comment by chilek** [comment]
Uwe, in this example we can do that, but in my real application plugins add their own template directories and I accidentally left this as two method calls ;-)

**Comment by chilek** [comment]
Hi Uwe, I've tried to port my application to Smarty 3.1.29 with hope that everything will be all right, but it didn't play well :(
I've prepared demo to demonstrate issue:
https://www.chilan.com/smarty-test2/
All files can be downloaded from:
https://www.chilan.com/smarty-3.1.29-extendsall-test.tar.xz
This time not all templates are loaded. I've found that commenting out the following line from **templates/default/layout.html** file:
```smarty
{include file="toolbar.html"}
```
causes loading all other contents after *include*.
Is it a bug in Smarty or bug in my template?

**Comment by chilek** [comment]
Hello, hello? Anybody's here? ;-)

**Comment by chilek** [comment]
Hello, Uwe.... ?
