### ISSUE TITLE
Class autoloading in templates not working anyomre since 3.1.28

### ISSUE THREAD

**Issue by sofl88** [smarty-php/smarty#124]
Since I upgraded from 3.1.27 to 3.1.28, I get a PHP fatal error like 

`Fatal error: Uncaught exception 'LogicException' with message 'Class Smarty_Internal_Data could not be loaded'`

My example project looks like this

index.php
folder1\class1.php
templates\start.tpl

in index.php

``` php
// autoloader from http://php.net/manual/de/function.spl-autoload-register.php#92514
spl_autoload_extensions('.php');
spl_autoload_register();

require 'path/to/smarty.class';

$smarty = new Smarty;
/* some settings here */
$smarty->display('start.tpl');
```

in class1.php

``` php
namespace folder1;

class class1{ 
   public static function x(){
       return 1;
   }
 }
```

in start.tpl

``` smarty
{assign 'test' folder1\class1::x()}
```

When I use a custom Autoloader like

``` php
spl_autoload_register(function($classname){
    $filename = __DIR__.DIRECTORY_SEPARATOR.$classname.'.php';
    if(file_exists($filename))
        include $filename;
});
```

...it works. Am I forced to rewrite my code here or is this actually a bug?

Thanks in advance.

**Comment by thedotedge** [comment]
Could be related (not reproducible in 3.1.27):
```
PHP Fatal error:  Class 'Smarty_Internal_Undefined' not found in /srv/freelancehunt/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 105
```

**Comment by uwetews** [comment]
If not using composer and it's autoloader Smarty always required it's own autoloader.
There are two possibilities to get it installed.
A) 
     require 'path_to_Smarty/libs/Autoloader.php';
Smarty_Autoloader::register();

**Comment by uwetews** [comment]
If not using composer and it's autoloader Smarty always required it's own autoloader.
There are two possibilities to get it installed.
A)
```php
require 'path_to_Smarty/libs/Autoloader.php';
Smarty_Autoloader::register();
```
In this case it's not required to include ore require Smarty.class.php.

or

B)
```php
include  'path_to_Smarty/libs/Smarty.class.php';   // not require
```

I currently have no idea how it could have worked in 3.1.27 differently.

**Comment by AnrDaemon** [comment]
Don't forget to include Smarty's bootstrap in addition to your own custom autoloader.

**Comment by uwetews** [comment]
Since smarty 3.1.31 bootstrap.php is included automatically and registers Smarty's autoloader if not already done
