### ISSUE TITLE
Smarty_Internal_Template::getVariable() throws Exception

### ISSUE THREAD

**Issue by logbon72** [smarty-php/smarty#125]
I have a custom plugin that uses Smarty_Internal_Template::getVariable(), with the latest update, I noticed that call to this method throws an exception:

```
SmartyException: property 'variable' does not exist.
```

Looking through the commit history, it appears the method has been removed. Is there any particular reason why a public API method was removed in a minor release? Or is this an oversight ?

What alternatives do I have to fix this?

**Comment by uwetews** [comment]
getVariable() was intended for some internal use. The official documented API method is getTemplateVars().

Note:
To reduce Smarty's memory footprint and it's load time some seldom used API methods are loaded dynamically when they are called.

**Comment by logbon72** [comment]
Perhaps the reason for the removal is justifiable, but this API is documented and must have been used in existing code. Plus this is supposed to be a patch (3.1.28), and should be backward compatible with code written in 3.1.27 according to SemVer principle.
