### ISSUE TITLE
Problem with custom function "URL"

### ISSUE THREAD

**Issue by GAngZta85** [smarty-php/smarty#131]
Since 3.1.28 the smarty autoloader tries to load the class Smarty_Internal_Compile_URL.
This will not work because URL is a custom function.

In 3.1.27 it is all ok.

My custom function (plugins/function.URL.php):

``` php
function smarty_function_URL($params, $template) {
        $sPath = ifsetter($params['path'], '');
        return MSE()->Language()->getUrl(['sPath' => $sPath]);
}
```

Template example: {URL path=$i1}

**Comment by uwetews** [comment]
On all tags Smarty does check if a class Smarty_Internal_Compile_{tag} does exist. If not it looks for a plugin in the plugin folder. This is how all Smarty 3.1 versions work. Nothing has changed there.

Your example does work at my place. 
So what kind of error do you see?

Do you have other autoloader in your application?
A problem we have seen sometimes in the past is that false was returned if the class is not found.
This is wrong implementation. An autoloader must always return without a value.

**Comment by GAngZta85** [comment]
Thanks for your reply. 
Actual we use our system autoloader and the smarty autoloader. The system autoloader returns nothing "return;"
In both autoloader I insert an echo to see what class name was passed as parameter. In the output I can see both autoloader are called. At first the system autoloader then smarty. 
The last class is called "Smarty_Internal_Compile_URL". Then I get a empty page. All neccessary plugins are available

**Comment by uwetews** [comment]
Calling the autoloader for  "Smarty_Internal_Compile_URL" is correct because the compiler does call the class_exists() method for it. That can't be the problem. It must be something else. Do you get  compiled templates? Check the PHP error_log if something is reported there.

**Comment by uwetews** [comment]
As there is no further reply this issue gets closed.

**Comment by ovidiugabriel** [comment]
I think the compiler shall not check if class Smarty_Internal_Compile_URL exists if url is registered as plugin. Suddenly my URL plugin is not working anymore. Please reopen this issue.

**Comment by uwetews** [comment]
The compiler always checks if an internal compile class does exists. if this is not the cases it checks registered plugins.

Note that plugin tag names are case sensitive.  If you use {URL} it must registered as 'URL'.

It does work at my place.

**Comment by ovidiugabriel** [comment]
I am using `{url}`, not `{URL}`. The plugin is registered as follows:
```php
$_smarty->registerPlugin(Smarty::PLUGIN_FUNCTION, 'url',  'smarty_function_url');
```
I will be back with a backtrace if the problem is still persistent.

**Comment by ovidiugabriel** [comment]
You say: "The compiler always checks if an internal compile class does exists. if this is not the cases it checks registered plugins." / It should not be the other way around: "The compiler always checks checks registered plugins, if this is not the cases,  checks if an internal compile class does exists?".

Because if I do not have the class, Smarty will throw exception and become unusable.

**Comment by uwetews** [comment]
Not sure if it could be related to https://github.com/smarty-php/smarty/issues/199

**Comment by wisskid** [comment]
This seems fixed.
