### ISSUE TITLE
3.1.28 regression?

### ISSUE THREAD

**Issue by JayBizzle** [smarty-php/smarty#132]
Don't know if this was intentional, but thought i'd mention it...

I had a template that had this in it `{$smarty.now|date_format:"%Y"-2007}` which worked pre v3.1.28

It was easily fixed by wrapping the date function in brackets like so `{($smarty.now|date_format:"%Y")-2007}`

The error was

```
Uncaught  --> Smarty Compiler: Syntax error in template "file:/home/xxxxxxx/public_html/modules/xxxxxxx/views/xxxxxxx.tpl"  on line 14 "xxxxxxx {$smarty.now|date_format:"%Y"-2007} xxxxxxx."  - Unexpected "-", expected one of: "}" <-- thrown
```

**Comment by uwetews** [comment]
This regression is now fixed in the master branch
