### ISSUE TITLE
3.1.28 {strip} space between tags

### ISSUE THREAD

**Issue by JercSi** [smarty-php/smarty#136]
Template:
```
{strip}
<ul>
    <li>
        <a href="#">BlaBla</a>
    </li>
    <li>
        <a href="#">BlaBla</a>
    </li>
</ul>
{/strip}
```
Result in 3.1.27 and previous versions:
```
<ul><li><a href="#">BlaBla</a></li><li><a href="#">BlaBla</a></li></ul>
```
Result in 3.1.28 (& master)
```
<ul> <li> <a href="#">BlaBla</a> </li> <li> <a href="#">BlaBla</a> </li> </ul>
```

I think there shouldn't be spaces between tags.

**Comment by uwetews** [comment]
I considered some input that removing spaces entirely might break poorly implemented CSS display:inline-block elements to be on the save side.
Too much safety???

**Comment by thedotedge** [comment]
For example, space removal is mandatory to avoid breaking the layout in some scenarios (where space introduces extra padding between elements), which was fine prior to 3.1.28. 
Besides, semantically it makes sense to strip everything: one handle it manually (via custom function) or refactor CSS to avoid the problem you mention instead.

**Comment by uwetews** [comment]
Okay, but would you agree not to strip the content of <script>                                                            </script>,  <textarea></textarea  and <pre></pre> sections?

**Comment by uwetews** [comment]
The fix is now in the master branch
