### ISSUE TITLE
Regression: Subclassing Smarty class with protected methods causes _callExternalMethod() in smarty_internal_extension_handler.php to generate SmartyException.

### ISSUE THREAD

**Issue by jeffreydwalter** [smarty-php/smarty#137]
I have a subclass of Smarty.class.php which has protected methods. These protected methods cause the following exception:
"PHP Error: Uncaught SmartyException in /home/jeff_walter/development/server/kboxwww/include/Smarty/libs/sysplugins/smarty_internal_extension_handler.php on line 105: SmartySubclass->ProtectedMethod() undefined method"

This is a regression from Smarty 3.1.13. ***sigh***

**Comment by uwetews** [comment]
Calling a protected function directly like
```php
SmartySubclass->ProtectedMethod();
```
would normally create a fatal error
Fatal error: Call to protected method SmartySubclass::ProtectedMethod()

Starting with 3.1.28 Smarty has an extension handler to load seldom used methods dynamically to reduce it's memory footprint and loading time.
The extension handler gets called also on illegal calls to private or protected methods.

So provide a real example where the protected function was not called.

**Comment by uwetews** [comment]
As there no further reply I close this issue
