### ISSUE TITLE
PHP mbstring extension required

### ISSUE THREAD

**Issue by orlitzky** [smarty-php/smarty#14]
The composer.json file mentions only >=php-5.2, but the use of `mb_convert_encoding` in e.g. `libs/plugins/modifier.escape.php` requires the mbstring extension. This does actually cause [a problem at runtime for me](https://bugs.gentoo.org/show_bug.cgi?id=532618), and it goes away when PHP is recompiled.

**Comment by orlitzky** [comment]
I accidentally commented on the commit 47faa63 yesterday rather than here; sorry. I have verified my suspicion using the following steps:

1. Install smarty from git
2. Install PHP with the mbstring extension
3. Visit your site, on a page that uses escaping
4. A cached template is stored in `$smarty_dir/templates_c` that makes use of `mb_convert_encoding`.
5. Reinstall PHP, this time without mbstring
6. Restart apache
7. Visit the same page
8. 500 error, missing `mb_*` functions.

**Comment by uwetews** [comment]
Smarty does generate different compiled templates if PHP has mbstring extensions or not.
If you change your environvent like exchanging PHP you should delete the compiled and cached template files. 

What you have done is not the normal use case.

I do not think that this is a shortcomming or bug of Smarty,

**Comment by orlitzky** [comment]
I wasn't suggesting that. I just wanted to point out for the search engines that the problem isn't what I initially reported.

Thanks again for your help!
