### ISSUE TITLE
Regression: nested section loops fail

### ISSUE THREAD

**Issue by bertptrs** [smarty-php/smarty#140]
Since the smarty 3.1.28 update, nested section loops (in either a foreach or a section) loops cause an error (undefined index). This is caused by the following line in compiled template code:

```php
$__section_i_0_saved = isset($_smarty_tpl->tpl_vars['__smarty_section_i']) ? $_smarty_tpl->tpl_vars['__section_i'] : false;
```

The problem arises because the code checks whether `'__smarty_section_i'` exists and then tries to read `'__section_i'`, without the smarty prefix. It only occurs in nested loops, because `isset` returns `true` the second time the loop is evaluated. 

PHP version: 5.5.9
Smarty version: 3.1.28

**Comment by TAdeJong** [comment]
Can confirm from own environment with equal versions of smarty and PHP.

**Comment by uwetews** [comment]
See https://github.com/smarty-php/smarty/issues/118

Also 3.1.29 is released with the bugfixes
