### ISSUE TITLE
Follow SemVer. BC-Breaks between Patch versions

### ISSUE THREAD

**Issue by psren** [smarty-php/smarty#142]
I recently noticed there are some BC-Breaks between ```3.1.27``` and ```3.1.28```.
For example the ```display``` on ```Smarty_Internal_TemplateBase``` disappeared completely.

**Comment by uwetews** [comment]
The display() method is there. So what exactly do you mean?
Please note also that some seldom used methods are now loaded dynamically when they are needed to reduce memory footprint and load size.
