### ISSUE TITLE
Missing $smarty->template_objects or is it removed?

### ISSUE THREAD

**Issue by catherinek** [smarty-php/smarty#143]
We have a debug tool to list all templates used on a page shown to our developers, and it was powered by $smarty->template_objects. However, after version 3.1.28, the property no longer exists. And it doesn't seem to have any alternate way to retrieve the list of used templates. 

I understand that it might have been removed for performance optimization but is it okay to restore it when debugging is on?

**Comment by uwetews** [comment]
Versions < 3.1.28 did cache all template objects for performance to reuse them in case a sub-template was called several times. However it was a wasted of memory.
3.1.28 is optimized for size and speed and the internal template object handling is completely different.
The $smarty->template_objects was removed.

When debugging is enabled some information like the template file path is can be found within the
$smarty->_debug->template_data array.

So which data will you need?

**Comment by catherinek** [comment]
Thanks @uwetews for your reply.

The $smarty->template_objects array gives me exactly what I need. However, is there any way to suppress the popup debug console?

**Comment by uwetews** [comment]
Which data from the template objects will you need?

**Comment by wisskid** [comment]
Closed because of inactivity.
