### ISSUE TITLE
error_reporting for templates not working

### ISSUE THREAD

**Issue by dattn** [smarty-php/smarty#145]
I've set error_reporting to:
$smarty->setErrorReporting(E_ALL & ~E_NOTICE);

But smarty triggers always E_NOTICE errors when a variable is not defined in templates.
This has worked for smarty 3.1.27 and does not work anymore for 3.1.29

The problem seems to be at the following line:
https://github.com/smarty-php/smarty/blob/v3.1.29/libs/sysplugins/smarty_internal_templatebase.php#L172
$this->_objType should be 2 to ignore errors in templates.

**Comment by uwetews** [comment]
The fix is now in the master branch and will later be included in 3.1.30
