### ISSUE TITLE
Fatal error: Call to undefined function smarty_modifier_ (Smarty2)

### ISSUE THREAD

**Issue by algo13** [smarty-php/smarty#146]
### Integrity of the cache in smarty_core_assemble_plugin_filepath() function.

Smarty2[smarty/libs/internals/smarty_core_assemble_plugin_filepath.php]
smarty_core_assemble_plugin_filepath() return value is dependent on the $smarty->plugins_dir(**instance value**) and is_readable.
but $_filepaths_cache is **static**.

### Example of code with problem:
```PHP
function f1() {
  $s = new Smarty();
  $s->display('test1.tpl'); //< use number_format() function of PHP.
}
function f2() {
  $s = new Smarty();
  $s->plugins_dir = array('smarty_extends'); //< have modifier.number_format.php
  $s->display('test2.tpl'); //< use smarty_modifier_number_format()
}
// --- process 1 ---
// create cache file
f2(); //< use smarty_modifier_number_format()
// --- process 2 ---
f1(); //< find modifier.number_format.php => nothing. 
f2(); //< Fatal error: Call to undefined function smarty_modifier_number_format()
```

### Proposed amendment:
1. delete $_filepaths_cache(fix)(Large impact)
2. var Smarty::$_filepaths_cache(Workaround)(Medium impact)
3. static Smarty::$_filepaths_cache(Workaround)(Small impact)(It will provide a means to clear)

**Comment by uwetews** [comment]
The fix is now in the Smarty2 dev_master branch

**Comment by algo13** [comment]
Thanks!
Even when switching the $plugins_dir by single instance, it is possible to clear the cache with this fix.

```PHP
$s = new Smarty();
if (mt_rand() % 2) {
    $s->display('test1.tpl');
}
if (mt_rand() % 2) {
  $s->plugins_dir = array('smarty_extends');
  $s->_filepaths_cache = array(); //< clear
  $s->display('test2.tpl');
}
```
