### ISSUE TITLE
Plugin names starting with "php" will be recognised as {php} tag in Templates

### ISSUE THREAD

**Issue by NoXPhasma** [smarty-php/smarty#147]
I've upgraded today from 3.1.21 to 3.1.29 and got error messages like this:
```Uncaught  --> Smarty Compiler: Syntax error in template "file:/var/www/dbpics/template/main.html"  on line 36 "<img src="thumb/{phpthumb_hash src=$pics_sql[i].bild end=$end}" alt="thumb"></a></td>" missing closing tag '{/php}' <--```

While it works fine in 3.1.21 to use function names starting with php, 3.1.29 (maybe earlier versions too) gives out that error. renaming the function to something which does not start with php fixes this. But I think this shouldn't ever happen.

**Comment by uwetews** [comment]
The fix is now in the master branch and will later be included in 3.1.30
