### ISSUE TITLE
PHP version support policy in Smarty2

### ISSUE THREAD

**Issue by algo13** [smarty-php/smarty#148]
### Requirements(Documentation)

[Smarty 2.x: PHP 4 or 5](http://www.smarty.net/download)
[Smarty requires a web server running PHP 4.0.6 or greater.](http://www.smarty.net/docsv2/en/installation.tpl)

Which is correct?
### Problem

[PHP7 raises E_DEPRECATED use __construct for compatibility](https://github.com/smarty-php/smarty/commit/e97b7d136c5667262f0fc02cb8eb7112baa01811)
PHP 4.0.6 **does not support** the `public function __construct(){}`.(Parse error)
### If supported PHP 4.0.6 or greater

e.g.

``` PHP
// Rename Smarty to Smarty0E69A2E2ED154D64A349E316A23482A7
class Smarty0E69A2E2ED154D64A349E316A23482A7
{
    function __construct() {
        // --- snip ---
    }
    // --- snip ---
}
//if (version_compare(PHP_VERSION, '5.0.0', '<')) { //< version_compare(PHP 4 >= 4.1.0, PHP 5, PHP 7)
if (strpos(PHP_VERSION, '4.') === 0) {
    class Smarty extends Smarty0E69A2E2ED154D64A349E316A23482A7
    {
        function Smarty() {
            parent::__construct();
        }
    }
} else {
    class Smarty extends Smarty0E69A2E2ED154D64A349E316A23482A7{}
}
```

**Comment by uwetews** [comment]
Smarty 2 version 2.6.28 is the latest version which does support PHP 4.
However if you want to use composer it does require as minimum PHP 5.3.

PHP 4 support has been dropped in Smarty 2 version 2.6.29 and higher.

 Smarty 2 version 2.6.29 and higher is compatible with PHP versions:
    5.2 and higher
    7.0
    7.1 
    and even the upcomming 7.2
