### ISSUE TITLE
smarty should be PSR-0 compatible for autoloading 

### ISSUE THREAD

**Issue by physcocode** [smarty-php/smarty#15]

**Comment by atayahmet** [comment]
exactly.

**Comment by bigbigant** [comment]
Looking forward to that.

**Comment by Gemorroj** [comment]
:+1:

**Comment by hlohaus** [comment]
or PSR-4 :+1:

**Comment by physcocode** [comment]
@hlohaus PSR-4 would also work !

**Comment by uwetews** [comment]
PSR-0 autoloading is deprecated.  So we will look into PSR-4 compatibility. 
This will require a change in folder structure and maybe the renaming of some classes. 
I did put this on the TODO list for one of the next releases.

**Comment by physcocode** [comment]
ok

**Comment by remicollet** [comment]
PSR-4 ? seriously ? 
then don't forget to introduce nameapace with a "vendor" top level.

**Comment by SvenRtbg** [comment]
PSR-0 works for everything that does not use namespaces, but can be made to conform to a specific file layout.

PSR-4 **requires** namespaces. Smarty doesn't use namespaces. So PSR-4 isn't available.

Switching Smarty to namespaces will be an incompatible change, which should be released as a new major version, i.e. Smarty 4.

**Comment by lunika** [comment]
+1 with @SvenRtbg

**Comment by roadster31** [comment]
:+1: @SvenRtbg

**Comment by physcocode** [comment]
Thats why i suggested plain PSR-0

**Comment by uwetews** [comment]
I agree that PSR-0 looks for now to be the better solution. But this also requires changes in the folder structure and the renaming of some classes. This will create some backward compatibility issues. 
For that reason it is not a good idea to implement it in 3.1.

I have done it in my local 3.2 version.
I expect to provide an alpha release of 3.2 within the next 2 month.

**Comment by pm-j** [comment]
Hi,
I have tried to implement psr in smarty but it seems not to work even if I have no error in my log.
Have you a psr compatible version released ?
Thanks

**Comment by SvenRtbg** [comment]
@pm-j Smarty provides it's own autoloader in addition to the Composer definition. Have you considered using it?

**Comment by caucik** [comment]
@uwetews What is the current target date for 3.2 with namespaces?

**Comment by SvenRtbg** [comment]
Smarty 3.2 cannot have namespaces because that would be an incompatible change.

**Comment by physcocode** [comment]
Any updates on getting into PSR-4 ?

**Comment by AnrDaemon** [comment]
PSR-4 requires namespacing, this is best left to Smarty 3.2.

**Comment by physcocode** [comment]
3yrs down the line , any update on this ?

**Comment by troy-rudolph** [comment]
The autoloading used with Smarty causes troubles with AspectMock.   Could you please conform to PSR-0 for now, and then do PSR-4 in a major release?  Thank you for all the hard work.

**Comment by AnrDaemon** [comment]
If AspectMock have issues with standard autoloading schemes, raise it with that AspectMock thing.

**Comment by troy-rudolph** [comment]
It does not appear to me that Smarty uses standard autoloading.

**Comment by AnrDaemon** [comment]
It does, [since December 2018](https://github.com/smarty-php/smarty/blame/master/composer.json#L33-L35).

**Comment by matiasperrone** [comment]
Shouldn't be this issue closed?

**Comment by physcocode** [comment]
Old issue- waiting for PSR 4 support
