### ISSUE TITLE
 Exists there a way when a smarty function is called, the send params to not be confounded with global params ?

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#150]
Exists there a way when a smarty function is called, the send params to not be confounded with global params ?

The call: {call buildInput label='User' elem='username' source='form'}

Or it's possible in smarty function definition to know if a variable is a sent parameter or a global variable?

**Comment by uwetews** [comment]
There is no way that the template function can detect if a variable is passed at call time or was assigned previously. However variable values passed as parameter are only seen inside the template function, template variables with same name in the calling template will not be modified.
