### ISSUE TITLE
_tag_stack no longer exists starting in Smarty 3.1.28

### ISSUE THREAD

**Issue by moseslecce** [smarty-php/smarty#151]
When a plugin attempting to access the $smarty->_tag_stack variable is used, the following error occurs:

Fatal error: Uncaught --> Smarty: template property '_tag_stack' does not exist. <-- thrown in sysplugins/smarty_internal_template.php on line 364

The manual for Smarty 3 mentions the following [found here: http://www.smarty.net/docs/en/plugins.block.functions.tpl]

"If you have nested block functions, it's possible to find out what the parent block function is by accessing $smarty->_tag_stack variable. Just do a var_dump() on it and the structure should be apparent."

and this functionality has worked until this version, and continues to work in Smarty 3.1.27.

**Comment by uwetews** [comment]
The fix is now in the master branch and will later be included in 3.1.30
