### ISSUE TITLE
Unable to load included template-file within a extended template-file

### ISSUE THREAD

**Issue by Fivedark** [smarty-php/smarty#158]
After some changes in Smarty from 3.1.27 to 3.1.28 (also 3.1.29) I got errors with my template structure. It isn't possible to include templates relative to an extended template, because the included template will be searched relative to the highest extended template. Use this simplyfied structure to rebuild the problem:
```
templates 
|-- layout
|     |-- include
|     |      |-- test.tpl
|     |-- page
|     |      |-- page.tpl
|     |-- layout.tpl
|-- index.tpl
```

index.tpl
```
{config_load file="test.conf" section="setup"}

<HTML>
<HEAD>
    <TITLE>{$title} - {$Name}</TITLE>
</HEAD>
<BODY bgcolor="#ffffff">
    {block name='content'}

    {/block}
</BODY>
</HTML>
```
layout.tpl
```
{extends file='../index.tpl'}

{block name='content'}
    <section id="main">
        {block name='main'}
        {/block}
    </section>

    <aside>
        {include file="./include/test.tpl"}
    </aside>
{/block}
```
page.tpl
```
{extends file='../layout.tpl'}

{block name='main'}
    Page-Content
{/block}
```

test.tpl
```
TEST
```

You will get the following:Fatal error: Uncaught --> Smarty: Unable to load template file './include/test.tpl' in 'file:../index.tpl' <-- thrown in /srv/www/paul.dev.ls.local/stand-alone-pages/tests/smarty/libs/sysplugins/smarty_internal_template.php on line 139

**Comment by uwetews** [comment]
The bugfix is now in the master branch and will later be included in 3.1.30
