### ISSUE TITLE
Newer versions of Smarty seem to cache the tpl content much longer

### ISSUE THREAD

**Issue by moseslecce** [smarty-php/smarty#159]
Example Code (tested on Smarty v3.1.27 & Smarty v3.1.24)

require('Smarty.class.php');
$smarty = new Smarty();
$smarty->setTemplateDir("/templates/tpls/");
$smarty->setCompileDir("/templates/tpls_c/");
$smarty->setCaching(Smarty::CACHING_OFF);
$smarty->display('test.tpl');

When changing the content in test.tpl it now takes a while for the page to display the new content (a few page refreshes), in previous versions the changes would take effect immediately.

The problem does not occur in Smarty v3.1.21

**Comment by uwetews** [comment]
What type of PHP opcode cache does your system use? APC, OPCACHE?
When gets the compiled template file in the compile dir updated? At the first page call?

**Comment by moseslecce** [comment]
We are running the following:
Zend OPcache v7.0.3

I can confirm that upon accessing the php page when the new content is in the tpl file, the compiled file does change and has the new content.  The page output is what continues to show the old content.

**Comment by uwetews** [comment]
This is strange. Does your server have any special file storage system?
If opcache is installed Smarty does call opcache_invalidate() to invalidate updated PHP files explicit independent from opcacche ini settings. We have no other reported problems about this.

You can the following ini settings:
opcache.validate_timestamps=1
opcache.revalidate_freq=0

But normally this sould not be necessary.

**Comment by moseslecce** [comment]
Thanks.  Looks like it has been fixed in Smarty v3.1.29
