### ISSUE TITLE
Undefinde index: nocache_hash

### ISSUE THREAD

**Issue by vsn4ik** [smarty-php/smarty#16]
When setup:
```php
$smarty->error_reporting = E_ALL;
```

Showing:
```
PHP Notice:  Undefined index: nocache_hash in .../smarty/libs/sysplugins/smarty_internal_compile_include.php on line 244
```

**Comment by uwetews** [comment]
Which Smarty and PHP version do you run?

**Comment by vsn4ik** [comment]
Smarty from GitHub master branch, PHP 5.6.5.

**Comment by uwetews** [comment]
It did occure on recursive {include} when $smarty->$merge_compiled_includes = true;

It's now fixed in master branch.
