### ISSUE TITLE
Getting loop property of a section throws error in 3.1.28

### ISSUE THREAD

**Issue by dirkkok** [smarty-php/smarty#161]
In Smarty 3.1.28 the `loop` property of a section is not available anymore, breaking existing code. 

Take for example the piece of code from Example 7.74 in [{section} documentation](http://www.smarty.net/docs/en/language.function.section.tpl):
```smarty
{section name=customer loop=$custid}
  {$smarty.section.customer.index} id: {$custid[customer]}<br />
{/section}
There are {$smarty.section.customer.loop} customers shown above.
```
And my PHP code:
```php
$smarty = new PortalSmarty();
$smarty->assign('custid', [0 => 'Customer 1', 1 => 'Customer 2', 2 => 'Customer 3']);
$smarty->display('path/to/file.tpl');
```

I get the following error:
```
--> Smarty Compiler: Syntax error in template "/path/to/file.tpl"  on line 6 "There are {$smarty.section.customer.loop} customers shown above." missing or illegal $smarty.section property attribute <-- 
```

Other properties like `index` or `total` do still work.

**Comment by uwetews** [comment]
The fix is now in the master branch and will later be included in 3.1.30

**Comment by jpastoor** [comment]
Thanks!

ps. Looks like the IDE / code formatter changed a lot more than just the intended change? Either way thanks for the fix!

**Comment by dirkkok** [comment]
Nice!

**Comment by uwetews** [comment]
Sorry folks
I did screw things up last night.
There is a new commit.
