### ISSUE TITLE
Fatal error using smarty/libs/plugins/shared.literal_compiler_param.php using Suhosin

### ISSUE THREAD

**Issue by w4r0** [smarty-php/smarty#162]
I have a fatal error on smarty/libs/plugins/shared.literal_compiler_param.php using Suhosin.

    Fatal error: SUHOSIN - Use of eval is forbidden by configuration in /var/www/vendors/smarty-3.1.24/plugins/shared.literal_compiler_param.php(32) : eval()'d code on line 32

Is there any workaround without using this plugin?

**Comment by uwetews** [comment]
Remove file modifiercompiler.escape.php which does use shared.literal_compiler_param.php.
Normally Smarty does try to produce optimized compiled code when using the escape modifier.
By removing the modifier compiler plugin the normal escape modifier plugin gets used.

or

Enable eval() in the SUHSIN configuration.
