### ISSUE TITLE
{break} not work properly inside foreach loop

### ISSUE THREAD

**Issue by mrsombre** [smarty-php/smarty#163]
Test code

```
{foreach $array as $i}
  {if 1}
    {break}
  {/if}
{/foreach}
```

Cause error 

```
--> Smarty Compiler: Syntax error in template "file:<file>.tpl"  on line <line> "{/if}" unclosed {if} tag <-- 
```

**Comment by uwetews** [comment]
I can't reproduce your problem. which Smarty version?

**Comment by mrsombre** [comment]
v3.1.29, php v5.6.17

**Comment by uwetews** [comment]
Strange
Your test code does compile without errors at my place.
The error message does not make sense unless there some unvisible characters in the {if} or {/if} tag.
Do you use any special charset?

**Comment by uwetews** [comment]
Closes because no more input from user
