### ISSUE TITLE
AST filter ?

### ISSUE THREAD

**Issue by JulienPalard** [smarty-php/smarty#166]
Hi,

Like the prefilter and the postfilter, as smarty3 now use a parser, why not providing an astfilter ?

**Comment by wisskid** [comment]
AST is [abstract syntax tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree)? What would be the use-case?

**Comment by JulienPalard** [comment]
TBH, I don't remember \o/

But yes, I bet at the time I wanted to edit the abstract syntax tree of my template using a hook...

This can be closed, I think, as I do no longer need it, and nobody mentionned any enthousiasm in 4 years.

**Comment by wisskid** [comment]
Alright
