### ISSUE TITLE
Problem with template inheritance and include blocks (since v3.1.28)

### ISSUE THREAD

**Issue by unreal4u** [smarty-php/smarty#167]
Hello, I have a strange issue that started to happen with Smarty v3.1.28. I have prepared an small example over here which is consistently able to reproduce the bug (if it even is a bug): 

https://github.com/unreal4u/possible-smarty-bug

When executing the code in the public folder this is the output (3.1.28+):

<pre>
    overwritten-01a
    
    
    inside over-c

    original-02a
</pre>

While any previous versions would return the following (any version prior to 3.1.28): 

<pre>
    overwritten-01a
    
    
    inside over-c

    overwritten-02a
</pre>

I have traced down the problem (with bisect) to the following commit: 

eec7639c9ce872737353ac4117252d440d3172ea - fix template scope processing

But this commit goes beyond my comprehension of Smarty itself, so I'm sorry I can't provide you with a reliable patch that doesn't also produce backwards compatibility issues.

Greetings.

PD: May be useful, git bisect log: https://gist.github.com/unreal4u/4ccdfd28ad35760eac58

**Comment by uwetews** [comment]
I can confirm that this bug does exists in 3.1.29. 
However some of the inheritance code has been rewritten for the upcoming version 3.1.30.
This does also solve your problem.

3.1.30 will be released after I have solved a couple of other open issues.
You may try the master branch version to get the latest updates.

**Comment by unreal4u** [comment]
Ok, thanks!
