### ISSUE TITLE
Problem smarty 3.1.29

### ISSUE THREAD

**Issue by pat15** [smarty-php/smarty#168]
Hi,

When i try start website using smarty 3.1.29 i received message:
Call to a member function start_render() on null ... smarty/sysplugins/smarty_template_compiled.php on line 190

When i start with smarty 3.1.26 everything it's ok and working. Where's the problem?

**Comment by uwetews** [comment]
Have you enabled debugging? ($smarty->debugging = true)
If yes was it enabled before any Smarty method calls?

**Comment by uwetews** [comment]
Seems to be same fixed problem as https://github.com/smarty-php/smarty/issues/237
