### ISSUE TITLE
use htmlspecialchars with charset

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#169]
Hi Uwe
https://github.com/smarty-php/smarty/blob/master/libs/plugins/modifier.debug_print_var.php#L74
and L81, L95 and L112 still uses the old < 5.4+ htmspecialchars() approach without a charset option, yielding empty strings with 5.4+, doesn't it?!

**Comment by uwetews** [comment]
The update is now in the master branch and will later be included in 3.1.30
