### ISSUE TITLE
Templates doubly extended in Smarty 3.1.29

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#171]
In Smarty 3.1.27, you could use {extends file="bar.tpl"} to let a file "foo.tpl" extend another file "bar.tpl" by default. This extension could then be overridden by using "extends:other.tpl|foo.tpl" when creating the template. foo.tpl would now extend other.tpl instead of bar.tpl.

In Smarty 3.1.29, foo.tpl seems to still extend bar.tpl, and then bar.tpl extends other.tpl. In particular, if you create the template using "extends:bar.tpl|foo.tpl", bar.tpl will extend itself!

**Comment by Stadly** [comment]
Here is an example showing the changed behavior:

File: child.tpl

    {extends file="parent.tpl"}
    {block name="Body"}
    A start
    A end
    {/block}

File: parent.tpl

    {block name="Body"}
    B start{$Smarty.block.child}B end
    {/block}

File: parent2.tpl

    {block name="Body"}
    C start{$Smarty.block.child}C end
    {/block}

File: index.php

    $Smarty = new Smarty();
    $Tpl = $Smarty->createTemplate('extends:child.tpl');
    $Tpl->display();
    $Tpl = $Smarty->createTemplate('extends:parent.tpl|child.tpl');
    $Tpl->display();
    $Tpl = $Smarty->createTemplate('extends:parent2.tpl|child.tpl');
    $Tpl->display();

Smarty 3.1.27 outputs

    B start
    A start
    A end
    B end
    
    B start
    A start
    A end
    B end
    
    C start
    A start
    A end
    C end

Smarty 3.1.29 outputs

    B start
    A start
    A end
    B end
    
    B start
    B start
    A start
    A end
    B end
    B end
    
    C start
    B start
    A start
    A end
    B end
    C end

**Comment by Stadly** [comment]
I don't have a strong opinion whether the 3.1.27 behavior is superior to the way it works in 3.1.29. I can see benefits and drawbacks with both.

But the changed behavior should at least be well documented, and there should be some warning that 3.1.29 is not backwards compatible (which is probably enough reason to stick with the 3.1.27 behavior).

**Comment by uwetews** [comment]
We have had some requests that templates called by the extends resource could sub extend by the {extends}. Before 3.1.28 inheritance was a compile time process where the implementation would have been not that easy. Now as it is a run time task it is straight forward.

Also I think the template should do what it says. Maintenance can get difficult if tags get ignored without obvious reason.

This overloading was never intended.

I will update the release notes for inheritance.
