### ISSUE TITLE
merge_compiled_includes throws error

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#172]
Smarty 3.1.29

If I set `$this->merge_compiled_includes = true;`
in our smarty class, I get this exception:

`<b>Fatal error</b>:  Uncaught exception 'ErrorException' with message 'Warning: get_class() expects parameter 1 to be object, string given' in /libs/sysplugins/smarty_internal_undefined.php:46
Stack trace:
#0 [internal function]: errorToExceptionHandler(2, 'get_class() exp...', '/www/test/example/...', 46, Array)
#1 /libs/sysplugins/smarty_internal_undefined.php(46): get_class('pre')
#2 [internal function]: Smarty_Internal_Undefined-&gt;__call('runFilter', Array)
#3 [internal function]: Smarty_Internal_Undefined-&gt;runFilter('pre', '{*/n     plugin_...', Object(Smarty_Internal_Template))
#4 /libs/sysplugins/smarty_internal_extension_handler.php(154): call_user_func_array(Array, Array)
#5 /libs/sysplugins/smarty_internal_compile_private_forea in <b>/libs/sysplugins/smarty_internal_undefined.php</b> on line <b>46</b><br />`

under certain conditions.

**Comment by ophian** [comment]
It was this: 
`{include file='./plugin_backend_header.tpl'}`
and within the header.tpl a
`{function name="feedback"}...{/feedback}`
and 
`{call feedback}` in all the "parent" calling tpl files.

Removing the function out, will prevent this error, though it would be good having it there again.

Will this be possible with upcoming 3.1.30?

**Comment by uwetews** [comment]
The fix is now in the master branch and will be included in 3.1.30
