### ISSUE TITLE
Hide block in Smarty 3.1.29

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#173]
It seems that `{block ... hide}` is always hiding the block in Smarty 3.1.29, even when the block is present in the subtemplate.

**Comment by uwetews** [comment]
I can't see a problem. Can you please provide an example

**Comment by Stadly** [comment]
I tested using the latest code available, and there it works, so I guess it will be fixed in the next release. It still doesn't work in 3.1.29, though. Here is an example, for the record:

File: child1.tpl

    {extends file="parent.tpl"}
    {block name="Action"}/submit.php{/block}
    {block name="Content"}
       <input name="submit" type="submit" value="Submit to other url">
    {/block}

File: child2.tpl

    {extends file="parent.tpl"}
    {block name="Content"}
       <input name="submit" type="submit" value="Submit to same url">
    {/block}

File: parent.tpl

    <form method="post" enctype="multipart/form-data"{block name="Action" hide} action="{$Smarty.block.child}"{/block}>
    {block name="Content"}{/block}
    </form>

File: index.php

    $Smarty = new Smarty();
    $Tpl = $Smarty->createTemplate('child1.tpl');
    $Tpl->display();
    $Tpl = $Smarty->createTemplate('child2.tpl');
    $Tpl->display();

In Smarty 3.1.29, none of the forms will have an action attribute.

**Comment by uwetews** [comment]
Yep it failed in 3.1.29

It does run with the master branch version of the upcoming 3.1.30
