### ISSUE TITLE
extending truncate

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#174]
Hi Uwe
Since we often use the &hellip; character entity in truncation context where every char space is of high value, I would like to have an exception for using the entity "`&hellip;`" instead of three dots "..." to the counter of truncate, so that "`&hellip;`" counts as 3 chars, or even better 1 char, and not 8 chars. (I even think this somehow "breaks" the non-word boundary parameter.)
There is a big and confusing difference in doing
`{$filename|truncate:38:"...":true}`
and
`{$filename|truncate:38:"&hellip;":true}`

What do you think about this idea?

**Comment by Stadly** [comment]
By using UTF-8, I think you should be able to do `{$filename|truncate:38:"…":true}`, so that `…` is only 1 character.

**Comment by ophian** [comment]
Yes I know, but this has to work with native or ISO langs too. Therefor the entity is a must have, or we have to completely switch to the "three dots" design only.

**Comment by uwetews** [comment]
Why do you not just create your own truncate modifier plugin?
The flexibility is there.

**Comment by ophian** [comment]
That is an-other idea. :) I thought this could be something of global interest to have.
Would still be nice if you think about it.

**Comment by wisskid** [comment]
Closed because of inactivity.
