### ISSUE TITLE
Inherit tag in 3.1.29

### ISSUE THREAD

**Issue by lichunqiang** [smarty-php/smarty#175]
Code:

__layout.html__
```
...
{block name='js'}
....
{/block}
...
```

__cms_layout.html__:

```
{extends file='layout.html'}

{block name='js'}
{$smarty.block.parent}
.....
{/block}
```

__articles.html__

```
{extends file='cms_layout.html'}

{block name='js'}
{$smarty.block.parent}
...
{/block}
```
This works well in v3.1.27, but after upgrade to v3.1.29, there throw an expcetion:

```
inheritance: tag {$smarty.block.parent} used in parent template block 'js'
```

How can i fix this?

Just call `$smarty.block.parent` in the final child template?

**Comment by uwetews** [comment]
The fix is already in the master branch and will later be included in 3.1.30
