### ISSUE TITLE
Illegal string offset after upgrade to PHP 5.6

### ISSUE THREAD

**Issue by olliiiver** [smarty-php/smarty#176]
After upgrading from PHP 5.3 to PHP 5.6 the warning "Illegal string offset 'foo'" is shown in PHP logs when using the following code:

`
{$test = "x"}
{$test.foo}
`

I know that the example above makes no sense in the first place, but Smarty code should never produce a PHP warning. Is there a workaround or fix for this?

**Comment by uwetews** [comment]
Fix your template or use the default modifier if a template variable or array index might not be assigned.

```php
{$test = "x"} {$test.foo|default} 
```
