### ISSUE TITLE
Big problem with scope variables

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#179]
I declared {$NO_ADS=1 scope='global'} in file header.tpl.

Then in main page (main.tpl) I try to use this variable and seems to not be recognized.

This happen with the last version ....30/37

**Comment by uwetews** [comment]
Read the newfeatures.txt regarding the bubble_up option flag.

```php
{$NO_ADS=1 scope='global', bubble_up}
```

**Comment by yourchoice** [comment]
Why was necesary this option bubble_up  ?

**Comment by ophian** [comment]
> Read the newfeatures.txt regarding the bubble_up option flag. `{$NO_ADS=1 scope='global', bubble_up}`

Hm, strange use of parameter quoting... The new feature docu says it is: `{$foo = 'bar' scope=global bubble_up}` without any quotes and comma, but shouldn't it be `{$foo = 'bar' scope='global, bubble_up'}` in real or anything like it?

**Comment by ophian** [comment]
@uwetews ? (see above)

**Comment by yourchoice** [comment]
so, the correct sintax is 

1) {$NO_ADS=1 scope='global', bubble_up} ? Here is a comma that not appear in NEW_FEATURES.txt

2) {$NO_ADS=1 scope='global' bubble_up}

3) {$NO_ADS=1 scope='global bubble_up'}

For me 2) working ... 

I think this feature need better documented ...

**Comment by uwetews** [comment]
Sorry,  for the compiler attribute=string is identical to attribute='string'
I should not have use this syntax option in my example.
bubble_up is a tag option flag which are never quoted. (like nocache)

I updated NEW_FEATURES.txt

**Comment by uwetews** [comment]
The master branch has been updated once again regarding scope handling.
The bubble_up option flag has been removed and variable changes are bubbled_up to the current template by default because this does make sense.

read the NEW_FEATURES.txt for the latest comments.
