### ISSUE TITLE
Again a problem with spaces...

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#180]
I have this sequence
...
[{#variable#|mb_trim}]
...

Before last ] is added a space.

Please see and https://github.com/smarty-php/smarty/issues/177 . This issue is closed, but the problem still persists.

**Comment by yourchoice** [comment]
Seems that after a smarty var is added a space. This is very ugly if we think to the forms... input  int values validation.

Starting with version 3.1.28 seems to be a lot of bugs... Now i come back to the 3.1.27 version.

**Comment by uwetews** [comment]
Can you give some full example where you still see the problem.
Please note there have been several commits for this problem, because I found myself cases where it did not work.  47237eb was the final commit for this problem

**Comment by yourchoice** [comment]
Hi,

This is the example:


```
{$text="Text"}
<span>#</span>{$text}<span>#</span>
```

The output with last dev. smarty version is : #Text #
After word "Text" there is a space

**Comment by yourchoice** [comment]
Another situation that doesn't work is:


```
{strip}
<span>#</span> {'Text'}
{/strip}
```


The output is: #Text .

In this case, between # and Text , the space is removed.


PS: sorry, I started with issue https://github.com/smarty-php/smarty/issues/177, and here I forgot to add {strip} {/strip} to be more explicit (just Ii edited my posts).

**Comment by uwetews** [comment]
{strip} is really tricky with all the different cases

Fix is in the master branch.

**Comment by yourchoice** [comment]
Again problem, I checked with  dev /40 version

`{strip}<i class="fa fa-map-marker"></i> <a href="#">Test</a>{/strip}`

This not let the space between `<i>` and `<a>` tags.
