### ISSUE TITLE
Which lexer generator does Smarty use?

### ISSUE THREAD

**Issue by vanderlee** [smarty-php/smarty#182]
A while back I was profiling Smarty, and found some performance waste in a few `in_array` statements that could have been refactored using keys (their values were guaranteed to be unique).

This was in generated code, so I think I should contact the lexer generator people if I want to submit a patch for this.

**Comment by uwetews** [comment]
Please provide the code here as I made already a couple of modifications to the original lexer generator for performance reasons.

**Comment by vanderlee** [comment]
I'll look into it when I get some test situation going, but for starters, there are a number of constructs which look like `in_array($var, array('a', 'b'))`, where the `haystack` is fixed. Extracting the haystack into a static variable in method scope using `$array = array_fill_keys(array('a', 'b'), true)` will let you use `isset($array[$var])` instead. Assuming the method is called more than a dozen times, this should be faster already.

This construct is in `Smarty_Internal_CompileBase->getAttributes` twice, in `Smarty_Internal_Configfilelexer->yy_r2_7`, in `Smarty_Internal_Configfileparser->parse_bool`, `Smarty_Internal_TemplateCompilerBase->trigger_template_error`, `Smarty_Internal_Templateparser->yy_r153`, on probably all the `Smarty_Security->isTrusted*` methods where the haystacks may be generated, but from first sight look guaranteed to be unique or atleast are treated as makes no difference to being unique for the purposes of this class.

**Comment by uwetews** [comment]
Yes in_array() is called while compiling templates several times.
But this does occur only in the rare event that a template was modified.
array_fill_keys() is also slow and in most cases slower than the in_array() call.

I think saving just a few millisecond during compiling does not account.

**Comment by vanderlee** [comment]
In my particular usecase (largely compiling from generated strings), I need the compiler to be fast :)
I remember getting double-digit performance improvements by doing basic optimizing tricks (not just `in_array`, but a couple of others), so I'll just see if I can make a pull request.

Either way, I'll see what I can optimize, and even if they're minor improvements for no cost, they'd be useful ;)

**Comment by uwetews** [comment]
I started some compiler optimizations and will get rid in_array as much as possible

**Comment by vanderlee** [comment]
Is there any performance testsuite currently? I'm using the (impressively huge) PHPUnit tests, but they're probably as a-typical as possible as far as performance goes.

I've been doing the same `in_array` optimizing changes. Will try to share them later today to prevent replication of effort. I've also done some `strlen()` to `isset()` optimizing. With the PHPUnit tests, there doesn't seem any noticable difference.

Also; following your lead that the generated code is typically far more significant than the compilation speed, I noted in the generated code there may be significant improvement by using a temporary variable like `$tmp = &$_smarty_tpl->tpl_vars;`, and probably some similar CSE optimizing for `foreach` loops. If I hack `template_c` files manually, the improvement is significant (some ~25% in my small tests; the cost of polymorphism in PHP is very high). It will take quite a lot of effort though.

**Comment by uwetews** [comment]
I  have some performance test setup where I can compare different Smarty versions and also other template engines in speed and memory usage.
$tmp = &$_smarty_tpl->tpl_vars is a very good idea.
Also the template parser will get lots of improments

**Comment by vanderlee** [comment]
It cost me quite a few headaches, but I've got the `$tmp = &$_smarty_tpl->tpl_vars` working.
It's on my fork `vanderlee/smarty`, in the branch `cse` (https://github.com/vanderlee/smarty/tree/cse).
If you want to look for the changes, just search `$_cse_vars`. 

Haven't had time to run any performance tests yet, but the unittest runs cleanly.

There are still some bits to improve on, I think I may have added a bit too much code and some postprocessing to remove unused variables would be nice too, but none of those will likely significantly affect performance.

**Comment by vanderlee** [comment]
I finally got around to doing some optimizations.
Please check pull request #202.
There are still a lot of double-quoted regular expressions in the parser, which could be single-quoted, but they'll take some more care.

**Comment by uwetews** [comment]
Hi,  Thanks for all your work. 
If you don't mind I will not merge your pull requests right now, but merge your changes to my code for Smarty 3.1.30  which will  be leased soon. 
I just had a brief view on your changes. There are some possible issues.
Your change in Smarty_Security to avoid in_array() calls will break BC for users who did extend this class.
The lexer/parser changes needs to be incorporated  in the corresponding generator tools.
And maybe others.
I will look into it ASAP.

Anyway you will get the full credit.....

Thanks again

But

**Comment by vanderlee** [comment]
No problem w/r Smarty_Security. I was under the impression that the unittest had complete coverage, so I used the unittest as my primary "judge" on code changes.

**Comment by wisskid** [comment]
Closed because of inactivity.
