### ISSUE TITLE
Again problem with spaces when I use {strip}

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#184]
Again problem with spaces when I use {strip}. This happend with dev /40 version. (https://github.com/smarty-php/smarty/issues/180)

`{strip}<i class="fa fa-map-marker"></i> <a href="#">Test</a>{/strip}`

This not let the space between `<i>` and `<a>` tags.

**Comment by uwetews** [comment]
The fix is in the master branch

**Comment by yourchoice** [comment]
I use html in the new line after {strip}, here was just an example.

```
{strip}
html code
{/strip}
```

**Comment by volkish** [comment]
@uwetews your {strip}'s changes absolutely incompatible with older version of Smarty. It adds spaces between tags and break all pages. Please stop changing behavior of the function.
