### ISSUE TITLE
Error on {config_load 'system_vars.config' section='en' scope='global'}

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#186]
Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:...\header.tpl" on line 4 "{config_load 'system_vars.config' section='en' scope='global'}" illegal value ''global'' for "scope" attribute <-- thrown in ...\smarty\sysplugins\smarty_internal_templatecompilerbase.php on line 4.

- header.tpl contain the {config_load 'system_vars.config' section='en' scope='global'}
- top.tpl include header.tpl
- index.tpl include top.tpl

How can be resolved this error? 

Thank You

**Comment by yourchoice** [comment]
Sorry, I found. Works with all bellow cases:

{config_load 'system_vars.config' section='en' scope='root'}
{config_load 'system_vars.config' section='en' scope='tpl_root'}
{config_load 'system_vars.config' section='en' scope='smarty'}

Wich is the optimal? 'tpl_root' ?

**Comment by uwetews** [comment]
It depends where the config var shall be know.
{config_load 'system_vars.config' section='en'}  Will load the vars into the current template

{config_load 'system_vars.config' section='en' scope='tpl_root'}  Will load the vars into the current and all parent templates moving down the {include} stack.

{config_load 'system_vars.config' section='en' scope='smarty'}  Will in addition update the vars in the Smarty object.

Read the NEW_FEATURES.txt in the master branch.
