### ISSUE TITLE
Auto escaping doesn't work inside a string

### ISSUE THREAD

**Issue by lunika** [smarty-php/smarty#19]
Hi,

I activated the autoescaping in my Smarty configuration and in some specific cases (if there is no output) a variable is not escaped but just cast to string.

Example : 

```
{$ID='123"><script>alert(\'Yo !\')</script>'}
Url : {url path="/a/b/c/{$ID}"}
```

$ID is not escaped and it results in a XSS at the end.

Here is the compiled result : 

```
<?php $_smarty_tpl->tpl_vars['ID'] = new Smarty_variable('123"><script>alert(\'Yo !\')</script>', null, 0);?>
    URL : <?php echo $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['url'][0][0]->generateUrlFunction(array('path'=>"/a/b/c/".((string)$_smarty_tpl->tpl_vars['ID']->value)),$_smarty_tpl);?>
```

url is a helper to retrieve an absolute url and you can see it here if you want : https://github.com/thelia-modules/TheliaSmarty/blob/master/Template/Plugins/UrlGenerator.php#L41

**Comment by uwetews** [comment]
Autoescaping does only effect variables which are echoed to output. This is not a bug. Escaping variables in other cases may not produce expected results. In your case the plugin should take care of the escaping.
