### ISSUE TITLE
Wrong _realpath with 4 or more parent-directories

### ISSUE THREAD

**Issue by SpazzMarticus** [smarty-php/smarty#190]
Hi,

I got some wierd "Smarty: Unable to load template file" errors, and I followed them to the [`_realpath`](https://github.com/smarty-php/smarty/blob/master/libs/Smarty.class.php#L1140) function in the `Smarty` class. 

I tested the function by mocking `getcwd` to always return `/0/1/2/3/4/5/6/7/8/9`, set the `DS` constant to `/` and then tested `_realpath` with `$realpath` always being set to `true`.

Path: `folder`
Realpath: `/0/1/2/3/4/5/6/7/8/9/folder`

Path: `../folder`
Realpath: `/0/1/2/3/4/5/6/7/8/folder`

Path: `../../folder`
Realpath: `/0/1/2/3/4/5/6/7/folder`

Path: `../../../folder`
Realpath: `/0/1/2/3/4/5/6/folder`

----
Wierd stuff occurs from here on:

Path: `../../../../folder`
Realpath: `/0/1/2/3/4/5/6/7/folder`
Should be: `/0/1/2/3/4/5/folder`

Path: `../../../../../folder`
Realpath: `/0/1/2/3/4/5/6/folder`
Should be: `/0/1/2/3/4/folder`

Path: `../../../../../../folder`
Realpath: `/0/1/2/3/4/5/folder`
Should be: `/0/1/2/3/folder`

Path: `../../../../../../../folder`
Realpath: `/0/1/2/3/4/5/6/folder`
Should be: `/0/1/2/folder`

Path: `../../../../../../../../folder`
Realpath: `/0/1/2/3/4/5/folder`
Should be: `/0/1/folder`

Path: `../../../../../../../../../folder`
Realpath: `/0/1/2/3/4/5/6/folder`
Should be: `/0/folder`

Can this be fixed, or is there any workaround?

**Comment by uwetews** [comment]
The fix is now in the master branch

**Comment by SpazzMarticus** [comment]
Thanks for the fix! :smiley:
