### ISSUE TITLE
SmaryBC Always Allows {php} Tags

### ISSUE THREAD

**Issue by Mike8723** [smarty-php/smarty#192]
There is no way to disable {php} tags when using the SmartyBC class. I tried setting disabling allow_php_templates, allow_php_tag at both smarty and Smarty_Security class. I also tried putting php within the disabled tags and disabled modifiers, but nothing works. Looking over the smarty_internal_compile_private_php.php script, there is no checking for any of these values. If you are not using smarty BC, it will trigger an error, otherwise, it will allow it.

**Comment by uwetews** [comment]
Set in Security disabled_tags 'private_php' that should word

**Comment by Mike8723** [comment]
That worked. Thank you. The documentation should be updated here:
http://www.smarty.net/docs/en/advanced.features.tpl
