### ISSUE TITLE
Default Global Scope

### ISSUE THREAD

**Issue by Mike8723** [smarty-php/smarty#193]
I love the idea of scopes, but I am working with code that was developed for smarty2 that did not deal with scope. It would be nice to have a feature to allow for setting the scope to global by default instead of changing every {assign} call to include scope="global". 

Within smarty_internal_compile_assign.php, I added a quick check to set scope to global if scope was not passed in, but it would be nice to have a feature like this built in.

**Comment by uwetews** [comment]
You should add scopes to {assign} only when really needed.Otherwise you may get unintended variable value changes in complex template structures.
For example use {assign scope='parent'} if the variable just needs to be returned to the template which did {include} the current one

**Comment by uwetews** [comment]
read the NEW_FEATURES.txt for the latest comments regarding scope usage.
