### ISSUE TITLE
Unable to assign global scope variables

### ISSUE THREAD

**Issue by machavity** [smarty-php/smarty#194]
I'm running the latest from the repo pull and have run across a problem. It manifested itself in being unable to pull in a subtemplate. What was odd is that the path, which relies on an assigned global variable, was being assigned in another previous subtemplate. This assignment works fine in 3.1.17 but appears to no longer work in the current version of Smarty

**SubTemplate 1**
`{assign var="product_template" value="$shareddir/Views/Product" scope="global"}`

**SubTemplate 2** (called after Template 1)
`{$product_template}`

Produces 
> Notice: Undefined index: product_template

If I assign it in each template it works... but this defeats the purpose

**Comment by uwetews** [comment]
```php
{assign var="product_template" value="$shareddir/Views/Product" scope="global" bubble_up}
```
for now,
but it will be reworked during the next couple of days for BC

**Comment by uwetews** [comment]
Using global scopes is always dangerous as you may loose overview in complex template structures.

In your case the safest solution is 

```php
{assign var="product_template" value="$shareddir/Views/Product" scope="parent"}
```
It will assign the variable just in the calling template, so that it's know when Sub Template 2 is called.

All other variable scopes are not touched.

**Comment by uwetews** [comment]
The fix is now in the master branch.

read the NEW_FEATURES.txt for details
