### ISSUE TITLE
registerDefaultPluginHandler callback not working with [ object ,  method ]

### ISSUE THREAD

**Issue by manuelcanga** [smarty-php/smarty#196]
Hi,
registerDefaultPluginHandler callback function has the following parameters: $name, $type, $template, &$callback, &$script, &$cacheable

However, $callback parameter doesn't support the option [ $object, $method ].

Regards and thanks.
Manuel Canga

**Comment by uwetews** [comment]
Yes, object methods are not supported as plugin.
See http://www.smarty.net/docs/en/api.register.default.plugin.handler.tpl and the note at the end.
The compiler has to generate code for the plugins from the default handler. If an object method would be returned, there is is no way to generate template code to access the object at render time, except to call the default plugin handler which would have bad performance.
Using a static method is the much better solution.
