### ISSUE TITLE
Plugins block functions should have content in raw in its first call

### ISSUE THREAD

**Issue by manuelcanga** [smarty-php/smarty#197]
Hi, again,

Content is null in first call to [Plugins block functions](http://www.smarty.net/docs/en/plugins.block.functions.tpl) . However, it's more useful using the content in raw in that first time, isn't it?. 

Regards
Manuel Canga

**Comment by uwetews** [comment]
This is by design. The block plugin is call before any other processing with content null to allow the execution of some initialization code upfront.
