### ISSUE TITLE
{capture} as array

### ISSUE THREAD

**Issue by posipa** [smarty-php/smarty#198]
In all my projects with Smarty v2 I use {capture} to capture all javascript code to output it at the end of <body> (for performance reason).
I've tried v3 and it crashed because {$smarty.capture} is not array any more.
My code looks like this

```
{capture name="js_widget1"}
    code ...
{/capture} 
 ...
{capture name="js_widget2"}
    code ...
{/capture} 
```
 
and at the end I put 

```
{foreach $smarty.capture as $capture}
    {if strpos($capture@key, "js_")!==false}
        {$capture}
    {/if}
{/foreach}
```

I can't do that anymore. 
Is it gonna stay this way or is it a bug?

**Comment by uwetews** [comment]
It's strange that it did work that way in Smarty2.
According to the  documentation $smarty.capture should access the $smarty.capture.default buffer.
See http://www.smarty.net/docsv2/en/language.builtin.functions.tpl#language.function.capture

However in Smarty 3 you can append several capture blocks to a variable.

```php
{capture append="js"}
    code ...
{/capture} 
 ...
{capture append="js"}
    code ...
{/capture} 

{foreach $js as $capture}
   {$capture}
{/foreach}

```

See http://www.smarty.net/docs/en/language.function.capture.tpl and example 7.23
