### ISSUE TITLE
Strange processing of built-in functions 3.1.27 vs 3.1.29

### ISSUE THREAD

**Issue by Stevad** [smarty-php/smarty#199]
I found some strange behaviour with Smarty built-in functions. For examle - `mailto`.

If I add `{mailto address='mail@mail.ua'}` somewhere in template then:

- v3.1.27 - works as expected
- v3.1.28, v3.1.29 before displaying result of the function will try to load class `Smarty_Internal_Compile_Mailto` and generates PHP warnings like these

`
Warning: include(Smarty_Internal_Compile_Mailto.php): failed to open stream: No such file or directory in /some/path/to/my/project
`

Where to look for errors? 
P.S. I am using Smarty with Yii 1.x. Smarty installed via composer.

**Comment by uwetews** [comment]
I have no idea how the autolader could run into this warning. But I reverted some autoloader changes.

The fix is in the master branch an will later be included in 3.1.30

**Comment by KarelWintersky** [comment]
Same issue with 3.1.33
