### ISSUE TITLE
{$smarty.template_object}  exception

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#201]
Smarty 3.1.30 current

I used `{$smarty.template_object}` in a template file and got
`Uncaught exception 'ErrorException' with message 'Catchable: Object of class Smarty_Internal_Template could not be converted to string' in `

Is this my fault or a bug?

**Comment by uwetews** [comment]
It's your fault. 
$smarty.template_object is a special variable to get the current template object to get access to it's properties or methods.
I don't know what you wanted to achieve with {$smarty.template_object}. You can't output it.

**Comment by ophian** [comment]
I wanted to look in. It works with `|print_r` though it gets quite huge...
Thanks.
