### ISSUE TITLE
problems with upgrade from 3.1.21 to 3.1.29 (unknown function fatal error)

### ISSUE THREAD

**Issue by gezzzan** [smarty-php/smarty#203]
Hello

Attempted to upgrade https://github.com/tikiorg/tiki/tree/15.x from smarty 3.1.21 to smarty 3.1.29 using composer (https://composer.tiki.org/#!/smarty)

Result:
`Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:C:\xampp\htdocs\tiki15\templates\layouts\classic\layout_view.tpl" on line 38 "{if zone_is_empty('left') and zone_is_empty('right')}" unknown function "zone_is_empty" <-- thrown in C:\xampp\htdocs\tiki15\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatecompilerbase.php on line 38`

It complains about not knowing about a function called "zone_is_empty", which is a custom php function written by Tiki. So far we have been extending the list of php_functions for Smarty_Security using class Tiki_Security_Policy like this: https://github.com/tikiorg/tiki/blob/15.x/lib/init/smarty.php

This works fine using 3.1.21, but upgrading to any greater smarty version fails either with memory exhaustion or with the message above

any suggestions? something changed in smarty with loading/accessing the base classes?

thanks

**Comment by uwetews** [comment]
Have you  tried Smarty's master branch?
It could be Smarty's autoloader which has been replaced

**Comment by gezzzan** [comment]
thanks for the feedback! 

I just tried dev-master, the same error comes

Can you give some hints/point me to documentation about when/how autoloader was replaced?

We will release next month our next LTS release, it would be great to ship it with the latest smarty available

thanks for your help!

**Comment by uwetews** [comment]
Can you try the dev-master version of Smarty? Or just use the Autoloader.php from there?

**Comment by uwetews** [comment]
Maybe i found the reason.
I took a brief look into the tiki code as best as I could.
The function zone_is_empty() is defined in file modlib.php. It does look like that is not necessarily loaded when Smarty does recompile all your templates.

I found in doc\devtools\release.php the following:

```php
function zone_is_empty() {
	// dummy function to keep smarty happy
}
```php

So it looks like that the function declaration was inserted there for same reason some time ago.

So make sure that you have this dummy function declaration again somewhere in your startup code.

**Comment by gezzzan** [comment]
Thanks for taking a look at Tiki's source code! 

We also investigated, quoting a fellow tiki developer: the problem seems to be the way our modules are constructed, which was done long long ago in Smarty 2 days, or before and for some reason this change from 3.1.21 to 3.1.29 seems to have uncovered some very creaky old code which now seems hard to fix without a major overhaul

So seems like the fix should be done in Tiki, closing this issue for now, 
Thanks again for your time, appreciated!
cheers
