### ISSUE TITLE
Smarty 3.1.29: quotes in template problem

### ISSUE THREAD

**Issue by ashkov** [smarty-php/smarty#204]
Hello! When moved from Smarty 2.6.21 to last Smarty through Composer( 3.1.29) I've got internal Smarty message on the page when I use a table property width=50% (without quotes)

';?>/*/%%SmartyNocache:174267686656f20984447bb8_82111757%%*/

When I added quotes width="50%", the message disappeared.

of course, this is not good practice to use width without quotes, but on old project it happens from time to time

**Comment by uwetews** [comment]
Please provide a more complete code sequence.. It does look that also a {nocache}{/nocache} section  or a nocache variable is involved involved.

**Comment by uwetews** [comment]
As you did not provide the failing template code I close this issue now
