### ISSUE TITLE
With PHP7, in template extending scenario, the compiled template misses sha1 prefix

### ISSUE THREAD

**Issue by lubobill1990** [smarty-php/smarty#205]
Hi Smarty team,

Thank you for your template engine, it helps us a lot in our project of http://MyDocumate.com. But we meet with an issue recently when we are trying to upgrade to PHP7.

For example, we have multiple layout files in different directories with the same name, main.tpl as an instance.

When there are two different templates, extending from these two different main.tpl, the anticipated file name of compiled main.php should be [some sha1 prefix]_0_main.php, but in the smarty compiled directory, only _0_main,php exists, without the sha1 prefix.

When we rollback to PHP5.6, this problem disappears.

We have tried to solve this problem, but the smarty engine is too complicated for us to debug, so I'm here asking for your help.

Best Regards

**Comment by uwetews** [comment]
I cant' reproduce your problem
Which Smarty version? which PHP7 version?

**Comment by lubobill1990** [comment]
@uwetews 
Hi uwetews,
After some check, I find that this issue is not caused by template extending, but caused by including a file path which will have to call default_template_handler_func to generate the absolute path.

**Comment by lubobill1990** [comment]
@uwetews after some debug work, I find that it's because the $source->uid is not calculated after call_user_func_array to $default_handler

**Comment by lubobill1990** [comment]
@uwetews my proposed fix is like https://github.com/smarty-php/smarty/pull/217 , is it right?

**Comment by uwetews** [comment]
Your fix is now in the master branch

**Comment by lubobill1990** [comment]
Thanks
