### ISSUE TITLE
Magic method in Smarty_Undefined_Variable

### ISSUE THREAD

**Issue by vanderlee** [smarty-php/smarty#207]
`Smarty_Undefined_Variable` used a magic method `__get()` to return `false` for `nocache` and `null` for everything (read; `name` and `value`) else.

Wouldn't it be easier (and faster) to just copy the interface of `Smarty_Variable` using these values, without the need for a magic method?

Also, wouldn't you just need exactly one instance of this class instead of creating new ones?

**Comment by uwetews** [comment]
Smarty_Undefined_Variable is needed by the compiler to handle some rare cases when a variable is undefined during compilation. One reason for __get() is that Smarty my add additional properties to Smarty_Variable (for example when you use the new style [foreach} and attributes like $foo@iteration.
Okay it might look at the moment odd to use __get() on nocache and value. Don't use a single instance. It might  break some planned improvement on error handling. It's also no performance issue as it's used i very rare  cases during compilation.

**Comment by uwetews** [comment]
FYI also making large progress in preparing Smarty 3.1.30 including most of your proposed improvements and other.
