### ISSUE TITLE
{strip} tags seems not strip js code between <script> tags. Same for html custom function like {hml_select_date}.

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#209]
{strip} tags seems not strip js code between `<script>` tags.

Maybe that is in idea when js code line is not ended by ; , to avoid js errors;

For me was ok before because want entire output code to be striped. Maybe better is to add a parameter to the {strip force=true} tag , that will strip js.

Another thing that do {strip} now, is a space between tags. I think better is just between tag attributes or just in text.

Also, seems that strip not strip code from html_select_date. Maybe and for another html custom function.

**Comment by jsmad** [comment]
Are you using {literal}? 

Because {strip} works fine here and strips white-space from within <script> tags, except when I use {literal}.

**Comment by wisskid** [comment]
Closed because of inactivity.
