### ISSUE TITLE
{$smarty.capture.name} doesn't work on last version 3.1.30-dev/59

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#210]
I updated to version 3.1.30-dev/59, and I saw that all smaty captures does't work

**Comment by uwetews** [comment]
3.1.30-dev/59 does pass all unit tests for {capture}

Did you delete old compiled and cache files?

**Comment by yourchoice** [comment]
Yes,

I have header.tpl where is defined : {$smarty.capture.includeMeta}

Then another file page.tpl that include header.tpl and here I have:
```
{capture 'includeMeta'}
 <meta name="aaaaa" content="bbbbbbbbbbb" />
{/capture}
```

I removed templates_c, but doesn't work

**Comment by uwetews** [comment]
The fix is now in the master branch
