### ISSUE TITLE
No way to force caching for some value in a nocache tag

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [smarty-php/smarty#211]
There is no way to reenable caching in a nocaching tag. See the following example:

I set a nocache bool and some hard-to-calculate numbers:

    $smarty->caching = true;
    $smarty->assign('decision', false, true);
    $smarty->assign('numberA', hardAlgorithmA());
    $smarty->assign('numberB', hardAlgorithmB());
    $smarty->display('display.tpl');

display.tpl

    {if $decision}
        <p>{$numberA}</p>
    {else}
        <p>{$numberB}</p>
    {/if}

I want to get $numberA and $numberB to be cached in resulting template, the if itself not. This is currently not possible.

I think it could be easier if there would be a {cache} around the numbers to force caching?

**Comment by 0xFEEDC0DE64** [comment]
Any ideas to solve this?

**Comment by uwetews** [comment]
The dev-master version has already addressed this.
See https://github.com/smarty-php/smarty/issues/110
There is a new {make_nocache} tag.
Read the NEW_FEATURES.txt

```php
{make_nocache $numberA}
{make_nocache $numberB}
{if $decision}
    <p>{$numberA}</p>
{else}
    <p>{$numberB}</p>
{/if}
```
Note that {make_nocache} must be called before the {if}
