### ISSUE TITLE
Old compiled template executed even if compile_check = True and .tpl changed.

### ISSUE THREAD

**Issue by JulienPalard** [smarty-php/smarty#212]
We have a situation with `compile_check = True` when we compiled a TPL with a fatal error:

      CRITICAL: Cannot use [] for reading

Which is a bug we introduced manually, we know it, and smarty has probably nothing to do with it, that's not the point, point is, if we fix the bug, smarty won't re-read our `.tpl`, as it executes the old one before re-reading the file, and PHP simply shutdown doing so.

The execution, so, the shutdown happen in `smarty_internal_template.php` around line 248 in the `render` method on a `$content = $this->compiled->render($this);` with a redacted stracktrace looking like:

    ...smarty_internal_template.php:458 Smarty_Internal_Template->render()
    .../84/cb/26/[sha1]_0.file.coms.tpl Smarty_Internal_Template->getSubTemplat...
    ...smarty_internal_template.php:376 content_[hash](Smarty_Internal_Template)
    ...smarty_template_compiled.php:204 Smarty_Internal_Template->getRenderedTemplateCode()
    ...smarty_internal_template.php:249 Smarty_Template_Compiled->render(Smarty_Internal_Template)
    ...smarty_internal_template.php:458 Smarty_Internal_Template->render()
    ...Smarty.class.php:820 Smarty_Internal_Template->render(True, False, True)
    ...Smarty.class.php:834 Smarty->fetch(...

But I'm not able to find where the template should be recompiled. But I assume you moved the recompilation after loading the cached template a first time so you can check the smarty version and recompile if version changed ?

As the developpers are not using the same user than the `php-fpm` service, they can't delete the faulty cached `.tpl.php`, and fixing the `.tpl` does nothing as `php` shutdowns before recompiling the file: they're locked out.

**Comment by uwetews** [comment]
Which Smarty version did you use?

If compile_check is true Smarty normally does not read old compiled files when the source template file has a newer time stamp as the compiled file.
But if you use template inheritance or merge_compiled_includes = true Smarty needs to read the compiled file to get the source file names of all included templates. 
The major problem is that you can't catch fatal errors of compiled or cached template files.
In such case the only solution would be to delete the compiled files or call the failing template once with $smarty->force_compile = true.

**Comment by JulienPalard** [comment]
I'm using 3.1.27, BC mode, don't use template inheritance, nor merge_compiled_include.

Can you point me to the place in the code where the decision is made to recompile the file before reading the compiled one ?

**Comment by uwetews** [comment]
Smarty versions <= 3.1.27 did indeed read old compiled templates before before checking time stamps.

If you do not want upgrade to a higher version you can modify smarty_template_compiled.php line 151 from


```php
       if ($_template->source->recompiled || !$_template->compiled->exists || $_template->smarty->force_compile) {
```
to
```php
        if ($_template->source->handler->recompiled || !$_template->compiled->exists ||
            $_template->smarty->force_compile || ($_template->smarty->compile_check &&
                $_template->source->timestamp > $_template->compiled->timestamp)
        ) {
```

**Comment by manish730725** [comment]
When i updated any code on the file not any changes in my website  please help me it urgent

**Comment by wisskid** [comment]
@manish730725 can you tell us what Smarty version you are using and provide a reproduction scenario? The issue you are commenting on has been closed 6 years ago.

**Comment by manish730725** [comment]
> @manish730725 can you tell us what Smarty version you are using and provide a reproduction scenario? The issue you are commenting on has been closed 6 years ago.

Hi wisskid Thanks for my reply, I am using smarty 2 version.

When I am saved the code but not showing  any changes on website

Please help me its urgent

**Comment by scottchiefbaker** [comment]
@manish730725 Smarty 2 is **extremely** old at this point and not really supported anymore. Have you tried upgrading to a supported version?

**Comment by manish730725** [comment]
if i upgrade it what I have to change.

**Comment by manish730725** [comment]
> @manish730725 Smarty 2 is **extremely** old at this point and not really supported anymore. Have you tried upgrading to a supported version?

Will the work I've done be in vain? After upgrade
