### ISSUE TITLE
{strip}{/strip} not stripping all spaces

### ISSUE THREAD

**Issue by lfelizari** [smarty-php/smarty#213]
PHP 7.0.5
Smarty 3.1.29
Apache 2.4.6

Testing the example code in Smarty strip tag page should make this:

`{* the following will be all run into one line upon output *}
{strip}
<table border='0'>
 <tr>
  <td>
   <a href="{$url}">
    <font color="red">This is a test</font>
   </a>
  </td>
 </tr>
</table>
{/strip}`

Become this:
`<table border='0'><tr><td><a href="http://. snipped...</a></td></tr></table>`

Butt this is what I get:
`<table border='0'> <tr> <td> <a href=""> <font color="red">This is a test</font> </a> </td> </tr> </table>`

The bug is that has spaces between the html tags.

**Comment by uwetews** [comment]
This bug is now fixed in the master branch
