### ISSUE TITLE
Smarty property 'sub_template' does not exist

### ISSUE THREAD

**Issue by masimao** [smarty-php/smarty#216]
Hi,

After upgrade from Smarty 3.1.27 to 3.1.29 i am receiving this error:

`Smarty property 'sub_template' does not exist`

It is throwred by the file `smarty_internal_extension_handler.php` at the line 92.

Someone knows how can i solve this?

Thanks!

**Comment by uwetews** [comment]
It does look like that you did extend the Smarty class and accessed a none Smarty property sub_template which was not declared. Errors like this are detected by Smarty's new extension handler which tries to resolve dynamic loading of seldom used methods.

**Comment by masimao** [comment]
Hi,

I am not extending the Smarty class, as well i am not declaring a property
called 'sub_template'.

Seems that Smaty is doing a confusion when it tries to mount dinamically an
internal method called getSubTemplate. Does it make any sense?

Thanks!

**Comment by uwetews** [comment]
Good point. Because of some internal changes Smarty might not have seen the version change for all cases.

Delete all existing compiled and cache files after the upgrade. Looks like that some old files got loaded.

**Comment by masimao** [comment]
I deleted the files of 'view_c' and 'cache' folders but the error persists. An additional information is that for some templates Smarty is working, but for others not.

Do you have any other idea about what can be happening? Thanks for your help!

**Comment by uwetews** [comment]
The {include} tag in Smarty 3.1.27 did compile a call to getSubTemplate() but all of that code was removed in 3.1.29. So it's really strange.

Do you get a call stack with the exception that it could be traced further down?

**Comment by masimao** [comment]
Here is my call stack


```
/usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_internal_data.php line 238 function _callExternalMethod()
/usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_internal_template.php line 307 function __call()
/home/imobevodev/views_c/153d2837d046e1fd7f57cdd234e92826381df399_0.file.montador.tpl.php line 150 function __call()
/home/imobevodev/views_c/153d2837d046e1fd7f57cdd234e92826381df399_0.file.montador.tpl.php line 150 function getSubTemplate()
/usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_template_resource_base.php line 122 function content_57102911d4d471_23575747()
/usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_template_compiled.php line 199 function getRenderedTemplateCode()
/usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_internal_template.php line 159 function render()
/usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_internal_templatebase.php line 191 function render()
/usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_internal_templatebase.php line 109 function _execute()
/usr/share/evodevelopment/evoimob/application/modulos/padrao/controllers/Principal.php line 23 function display()
/usr/share/evodevelopment/evokernel/resources/frontcontroller-app.php line 86 function index()
/home/imobevodev/public_html/index.php line 9 function require_once()
```

I will try to get more details.

**Comment by fulopattila122** [comment]
Hello, I'm the author of this tiny plugin: https://github.com/fulopattila122/smarty3-include-if-exists which is having issues calling `getSubTemplate`. [See here](https://github.com/fulopattila122/smarty3-include-if-exists/blob/master/compiler.include_if_exists.php#L93). What method should be used instead of `getSubTemplate()` ?

**Comment by fulopattila122** [comment]
Is it maybe [_subTemplateRender()](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_compile_include.php#L245) ?

**Comment by masimao** [comment]
@uwetews Could you help us please?

**Comment by uwetews** [comment]
Yes the new function is _subTemplateRender()

**Comment by masimao** [comment]
Hi Attila,

Thanks for your feedback!

I updated the file, but i am receiving this error:

`
Fatal error: Uncaught --> Smarty: Smarty_Internal_Template->subTemplateRender() undefined method <-- thrown in /usr/share/evodevelopment/evolib/library/smarty/sysplugins/smarty_internal_undefined.php on line 46`

Could you please help me with this issue?

**Comment by fulopattila122** [comment]
@masimao I think the issue belongs to my plugin, so I [reopened the issue, let's continue the discussion over there](https://github.com/fulopattila122/smarty3-include-if-exists/issues/2).

**Comment by uwetews** [comment]
@masimao You updated the file with the wrong method name. It must be '_subTemplateRender()'.
You missed the leading underscore.
