### ISSUE TITLE
Included template can't be find in the scenario of template inheritance

### ISSUE THREAD

**Issue by lubobill1990** [smarty-php/smarty#218]
In the following scenario:
1. a.tpl is parent template
2. b.tpl is child template
3. c.tpl is included by b.tpl with relative path
4. d.tpl is included by b.tpl with relative path

then, smarty 3.1.30@dev will occur the following error:

Unable to load template file '../d.tpl' in 'file:./c.tpl'

**Comment by uwetews** [comment]
Can you provide your folder structure and some sample template please

**Comment by hauke725** [comment]
Files:
https://gist.github.com/hauke725/850c993de206dae6f83c439f6fe86114

This won't work if both the included templates are in a subdirectory. When the second include's path is described from the dir of the parent template it works, even if the parent template is not in a resource root.

**Comment by uwetews** [comment]
The fix is now in the master branch
