### ISSUE TITLE
Properly Registering Smarty Plugin With Composer

### ISSUE THREAD

**Issue by fulopattila122** [smarty-php/smarty#219]
Hello, I'm authoring a simple [smarty plugin](https://github.com/fulopattila122/smarty3-include-if-exists) and would like to streamline it to be a first class composer citizen. Meaning that I'd like to register it as a smarty plugin via composer's autoload functionality.

I saw another [smarty plugin](https://github.com/smarty-gettext/smarty-gettext/blob/master/composer.json) that uses a similar approach, but I think the method is not exactly what should be used in my case.

My plugin is now being registered with `$smarty->addPluginsDir("your/path/to/the/files");` but the registration is left to the user. I doubt I can assume that a global `$smarty` object exists (I think it should not). I'm also having doubts that any instantiated Smarty object exists at autoload time. Is there another way I could use for registering a smarty plugin "globally"?

**Comment by uwetews** [comment]
I can currently see no solution to use it as plugin without using $smarty->addPluginsDir("your/path/to/the/files");

But for applications which use the composer autoloader it should work with just a few additions.

Put the following lines at the end of your plugin which will wrap a corresponding internal class name
to your plugin.
```php
Smarty_Internal_Compile_Include_If_Exists  extends Smarty_Compiler_Include_If_Exists 
{
}
``` 

Add the following to your composer.json file
```php
    "autoload": {
        "classmap": ["compiler.include_if_exists.php"]
    }
``` 
That should work.
