### ISSUE TITLE
Smarty_Resource::parseResourceName incompatible with Google AppEngine

### ISSUE THREAD

**Issue by brandomeniconi** [smarty-php/smarty#22]
Google AppEngine PHP Environment uses paths like:

``` /base/data/home/apps/s~[project-name]/[module]:[version]/[path]/template.tpl ```

example:

``` /base/data/home/apps/s~myproject/default:1.316876871687/templates/template.tpl ```

The function Smarty_Resource::parseResourceName in libs\sysplugins\smarty_resource.php uses this code to determine resource type: 

```php

   public static function parseResourceName($resource_name, $default_resource)
    {        
        $parts = explode(':', $resource_name, 2);
        if (!isset($parts[1]) || !isset($parts[0][1])) {
            // no resource given, use default
            //...

```
 and when we have this type of path, the __explode(':'__ splits the $resource_name incorrectly.

It's possible to change the delimiter or escape the path?
Thanks

**Comment by uwetews** [comment]
The fix is now in dev-master and will later be included in version 3.1.22
