### ISSUE TITLE
Allow constructor options, one being follow_symlinks

### ISSUE THREAD

**Issue by cmanley** [smarty-php/smarty#224]
Please add constructor options as an associative array, one being follow_symlinks that adds the option RecursiveDirectoryIterator::FOLLOW_SYMLINKS to all RecursiveDirectoryIterator() calls in
smarty_internal_utility.php
Obviously also check for the existence of that constant for older PHP versions.
See http://www.smarty.net/forums/viewtopic.php?p=66927

**Comment by uwetews** [comment]
The update is now in the master branch
