### ISSUE TITLE
{strip} removes spaces between element and variable

### ISSUE THREAD

**Issue by honzahana** [smarty-php/smarty#225]
{strip} function removes space between TAG element and Smarty variable.

Example:
`{strip}<p><strong>Length:</strong> {$r.head.title.length} character(s)</p>{/strip}`

Will output:
`<p><strong>Length:</strong>21 character(s)</p>`

There is no space between a strong ending and a number (space in source code was removed).

Tested on Smarty v3.1.29 (installed by Composer).

**Comment by uwetews** [comment]
This bugfix is already in the master branch and will be included in 3..1.30
