### ISSUE TITLE
function plugin return an array, modifier plugin is not falling.

### ISSUE THREAD

**Issue by rmasco** [smarty-php/smarty#228]
Always thank you , everyone .

One of the failure has occurred.
If example_function returns an array , the array is not falling into example_modifier.
smarty2, the array is falling into example_modifier.

template:
```
{{example_function name="list[0]"|example_modifier}
```

smarty3:
```php
        ob_start();
        echo $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['example_function'][0][0]->function_wrapper(array('name' => 'list[0]'), $_smarty_tpl);
        echo smarty_modifier_example_modifier(ob_get_clean(), 'test');
```

smarty2:
```php
        echo smarty_modifier_example(smarty_example_function(array('name' => 'list[0]'), $_smarty_tpl);
```

example_modifier:
```php
<?php

function smarty_modifier_example($text, $name) {
    var_dump($text);
}
```

example_modifier is return 'String[5] 'Array'.
How can I fix it ?

**Comment by uwetews** [comment]
All tags including plugins should always return a string or nothing.
If it does return an array like in your case it could never work without a modifier allowing array as parameter. This requirement is not clear by the syntax.
Plugins with array or object results should assign it to a variable and then you can go from there.

I agree that the compiled code of Smarty 2 does create in your sense an expected result.  I will look into it.

**Comment by rmasco** [comment]
@uwetews 
thanks!

I do assign to template variable be able to receive array in modifier.
This is the best way?

**Comment by uwetews** [comment]
Even that I think that normally plugins should return always strings I did fix the code to Smarty 2 behavior.
The fix is now in the master branch
