### ISSUE TITLE
Smarty compiler doesn't put quotes in array keys in some cases.

### ISSUE THREAD

**Issue by d-asensio** [smarty-php/smarty#233]
We found an issue with Smarty 3.1.29, in a nutshell what happens is that in some cases when you try to access to an array via key using the dot notation (`{$motivo_baja.MOTIVO_BAJA}`) the smarty compiler translates it apparently randomly switching between `$_smarty_tpl->tpl_vars['motivo_baja']->value[MOTIVO_BAJA]` without quotes (what isn't correct) and `$_smarty_tpl->tpl_vars['motivo_baja']->value['MOTIVO_BAJA']` with quotes .

**Comment by uwetews** [comment]
I think in your script MOTIVO_BAJA is a defined constant,
Smarty does support the usage of constants within templates. If you have array index names which are similar you must not use the dot notation on arrays. because of this ambiguity.
