### ISSUE TITLE
Let different parts of a template inherit from different parent files

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#234]
Why is Template inheritance limited so that every file can only directly extend one other file. I would really find it useful if a file could contain several `{extends}` blocks, and hence inherit from several different files.

Consider the following example just to illustrate what I mean:

**[index.tpl]**

    <html>
    {extends file="head.tpl"}
        {block name="css" append}
            <style>
               p { color: red; }
            </style>
        {/block}
        {block name="js"}
            <script src="bar.js" type="text/javascript"></script>
        {/block}
    {/extends}
        <body>
            <p>This is a message</p>
    {extends file="buttons.tpl"}
        {block name="buttons"}
            <a href="test.html">Click me!</a>
        {/block}
    {/extends}
        </body>
    </html>

**[head.tpl]**

    <head>
        <title>Lorem ipsum</title>
    {block name="css"}
        <link href="foo.css" rel="stylesheet" type="text/css">
    {/block}
    {block name="js"}{/block}
    </head>

**[buttons.tpl]**

    <div class="button-container">
    {block name="buttons"}
        <a href="default.html">A standard button</a>
    {/block}
    </div>

So the idea is that everything between a pair of `{extends}` and `{/extends}` extends some other file, instead of the whole file extending some other file by having `{extends}` on the first line. This differs from just using `{include}`, since the `{block}`s are sent to the parent template file, giving template inheritance, but instead of the whole template inheriting from a single file, different parts of the template inherits from different files.

For backwards compatibility, support for having an `{extends}` on the first line with no closing `{/extends}` should of course be kept.

**Comment by uwetews** [comment]
You have some wrong understanding how template inheritance works.
Templates can be extended by any number of levels like

[child0.tpl]
```php
{extends file="child1.tpl"}
{block name="foo"}
    child0  foo
{/block}
Any output like this text will be ignored in child templates
{block name="bar"}
    child0  bar
{/block}
{block name="noop"}
    child0 not used
{/block}......
```
[child1.tpl]
```php
{extends file="parent.tpl"}
Any output like this text will be ignored in child templates

{block name="foo"}
    child1  foo
{/block}
{block name="buh"}
    child1 buh
{/block}
......
```
[parent.tpl]
```php
The parent template does generate output
{block name="foo"}
    parent  foo
{/block}
{block name="buh"}
    parent buh
{/block}
{block name="bar"}
    parent bar
{/block}
{block name="blar"}
    parent blar
{/block}
......
```

Child templates register only {block} code which may but must not be referenced by the parent template.  Any text or output of tags outside {block}{/block} of child templates is ignored.
It's the parent template which will be parsed at the end like a normal template.

The generated output will be
```php
The parent template does generate output
child0  foo
child1 buh
child0  bar
parent blar
```
You turned inheritance upside down which was not the idea.
 
Please see:
http://www.smarty.net/inheritance
http://www.smarty.net/docs/en/advanced.features.template.inheritance.tpl
