### ISSUE TITLE
Empty array in foreach generate Warning: Creating default object from empty value in ...

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#239]
Smarty version: 3.1.30 dev 72

```
{$tmp=array()}
{foreach $tmp as $key=>$item}
	...			
{/foreach}
```

This generate:
Warning: Creating default object from empty value in E:\...\templates_c\9ee9361c63d7594e378b9c908467864eedc353a1_0.file.feed_data_details.tpl.php on line 224

Obs: vers. dev 66 worked well without this warning.

**Comment by uwetews** [comment]
The fix is now in the master branch
