### ISSUE TITLE
fail to find template function when extends in 3.1.29

### ISSUE THREAD

**Issue by hkuclion** [smarty-php/smarty#240]
## what I did

testExtendsFunctionBase.html
```
{function name=hkuc}{/function}
{block name=layout}{/block}
```

testExtendsFunction.html
```
{extends file="./testExtendsFunctionBase.html"}

{block name=layout}
{function name=lion}hkuclion{/function}

{call lion}
{/block}
```

## what I expected
`hkuclion`

## what I got
`Fatal error: Uncaught --> Smarty: Unable to find template function 'lion' <-- thrown in \Smarty\smarty-3.1.29\libs\sysplugins\smarty_internal_runtime_tplfunction.php on line 45`

## further test
It's OK when use
`{include file="./testExtendsFunctionBase.html"}`
or remove
`{function name=hkuc}{/function}`
or use Smarty version below 3.1.29 (ie 3.1.27)

**Comment by uwetews** [comment]
This is fixed now in the master branch
