### ISSUE TITLE
in version 3.1.29 bug for PHP 7

### ISSUE THREAD

**Issue by great-handsome** [smarty-php/smarty#241]
i think it bug in PHP 7.
in dev-master 
file  sysplugins/smarty_internal_templatecompilerbase.php
line 735
return $this->smarty->registered_plugins[ Smarty::PLUGIN_COMPILER ][ $tag ][ 0 ][ 0 ]->$function[ 1 ]($args,

line 676
return $this->default_handler_plugins[ $plugin_type ][ $tag ][ 0 ][ 0 ]->$function[ 1 ]($new_args, 

php.net/manual/en/migration70.incompatible.php

```
Expression $foo->$bar['baz']()
PHP 5 interpretation $foo->{$bar['baz']}()
PHP 7 interpretation ($foo->$bar)['baz']() 
```

**Comment by uwetews** [comment]
You are wrong as there is no variable class variable like $bar

**Comment by great-handsome** [comment]
I don't understand how is it will be work in PHP 7 without a changes.
Code for PHP 5:
line 735
return $this->smarty->registered_plugins[ Smarty::PLUGIN_COMPILER ][ $tag ][ 0 ][ 0 ]->$function[ 1 ]($args,
line 676
return $this->default_handler_plugins[ $plugin_type ][ $tag ][ 0 ][ 0 ]->$function[ 1 ]($new_args, 

I think for PHP 7 needs code ( added { , } )
return $this->smarty->registered_plugins[ Smarty::PLUGIN_COMPILER ][ $tag ][ 0 ][ 0 ]->{$function[ 1 ]}($args,
line 676
return $this->default_handler_plugins[ $plugin_type ][ $tag ][ 0 ][ 0 ]->{$function[ 1 ]}($new_args,

**Comment by uwetews** [comment]
Sorry, yes you have been absolutely right.
The fix is in the master branch
