### ISSUE TITLE
Including a file with relative path changes the cwd of the including file

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#246]
In some cases with complex inheritance, including one file ruins for other file inclusions, resulting in unsuccessful template compilation. Consider the following example:

    {* /index.php *}
    <?php
    require_once 'Smarty/Autoloader.php';
    $Smarty = new Smarty();
    $Smarty->setTemplateDir(__DIR__.'/Tpl');
    $Tpl = $Smarty->createTemplate(__DIR__.'/Edit.tpl');
    $Tpl->display();

    {* /Edit.tpl *}
    <form method="post" enctype="multipart/form-data">
       <fieldset>
    {include 'Collection/Edit.tpl'}
       </fieldset>
    </form>

    {* /Tpl/Collection/Edit.tpl *}
    {extends '../Container.tpl'}
    {block Buttons}
       {include '../General.tpl' Button=[Link => '/admin', Title => _('Cancel')]}
       {include '../Primary.tpl' Button=[Name => 'edit', Type => 'submit', Title => _('Save')]}
    {/block}

    {* /Tpl/Container.tpl *}
    <div class="buttons">
    {block Buttons}{/block}
    </div>

    {* /Tpl/General.tpl *}
    {extends './Abstract.tpl'}
    {block Class}_button transparent{/block}

    {* /Tpl/Primary.tpl *}
    {extends './Abstract.tpl'}
    {block Class}_button{/block}
    {block Icon}<i class="_icon-internal-white"></i>{/block}

    {* /Tpl/Abstract.tpl *}
    {if isset($Button.Link)}
    <a class="{block Class}{/block}" role="button" href="{$Button.Link}"><span>{$Button.Title}</span>{block Icon}{/block}</a>
    {else}
    <button type="{$Button.Type}" class="{block Class}{/block}" name="{$Button.Name}"><span>{$Button.Title}</span>{block Icon}{/block}</button>
    {/if}

This will result in a `Fatal error: Uncaught --> Smarty: Unable to load template file '../Primary.tpl' in 'file:../Container.tpl'`.

If you change the order of the buttons in `/Tpl/Collection/Edit.tpl`:

    {* /Tpl/Collection/Edit.tpl *}
    {extends '../Container.tpl'}
    {block Buttons}
       {include '../Primary.tpl' Button=[Name => 'edit', Type => 'submit', Title => _('Save')]}
       {include '../General.tpl' Button=[Link => '/admin', Title => _('Cancel')]}
    {/block}

You get `Fatal error: Uncaught --> Smarty: Unable to load template file '../General.tpl' in 'file:../Container.tpl'`.

So it seems that the first include is always successful, while the second include fails. In other words, both includes are fine, but the first one ruins for the second one. Indeed, if you remove one of the buttons, (either the line `{include '../Primary.tpl' Button=[Name => 'edit', Type => 'submit', Title => _('Save')]}`or the line `{include '../General.tpl' Button=[Link => '/admin', Title => _('Cancel')]}`, the template compiles successfully.

I suspect that this has to do with the relative paths. After including one of the files, the working directory is changed, so that the second file is not found. A simple test more or less confirms this, as the template compiles successfully when the second include's path is changed from `../Primary.tpl` to `./Primary.tpl`.

I am using the latest development build 3.1.30-dev of Smarty.

**Comment by Stadly** [comment]
Have no one else experienced this?

It would be really nice if someone could try my code and confirm whether they get the same error or not.

If anything is unclear in my bug description, please let me know so I can clarify.

**Comment by uwetews** [comment]
I'm working an a fix.

**Comment by Stadly** [comment]
Great! Thanks! :)

**Comment by uwetews** [comment]
The fix is now in the master branch

**Comment by uwetews** [comment]
Sorry, not completely solved

**Comment by uwetews** [comment]
Now it's done
