### ISSUE TITLE
Smarty Security isTrustedResourceDir() does not work properly when using multiple Security objects

### ISSUE THREAD

**Issue by blaaat** [smarty-php/smarty#247]
In commit aee07f7bbacdd6599fd0377707f74e3f8f94cafe a full rewrite of this method is implemented.

When enabling en disabling security multiple times with different security objects; only the first object adds the template_dirs to it's _resource_dir variable.

This code will fail: 

> $smarty->enableSecurity('UserInput_Smarty_Security');
> $smarty->display('a'); 
> $smarty->disableSecurity(); 
> 
> $smarty->display('safe_template');
> 
> $smarty->enableSecurity('UserInput_Smarty_Security');
> $smarty->display('a'); 
> $smarty->disableSecurity(); 

Maybe add a bool to Smarty_security and check if the object has the template/config directories?

**Comment by uwetews** [comment]
The bugfix is now in the master branch
