### ISSUE TITLE
FAILED: files missing

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#248]
Smarty version 3.1.30-dev/72
$smarty->testInstall(); gives everything OK, but claims files missing, which were removed as far as I remember. Weren't they? see https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_testinstall.php#L396 etc
`FAILED: files missing from libs/sysplugins: smarty_internal_compile_private_compiler_plugin.php, smarty_internal_compile_private_modifiercompiler_plugin.php, smarty_internal_compile_private_modifier_plugin.php, smarty_internal_compile_private_object.php, smarty_internal_compile_private_registered_compiler.php, smarty_internal_compile_private_registered_modifier.php, smarty_internal_runtime_assignindexed.php.
`
@uwetews

**Comment by uwetews** [comment]
The fix is now in the master branch
