### ISSUE TITLE
Compiler issue concerning array keys and constants

### ISSUE THREAD

**Issue by bananascript** [smarty-php/smarty#253]
In Smarty 2
`$constants.COUNTRY`
compiles to
`$_smarty_tpl->tpl_vars['constants']->value['COUNTRY']`

But in Smarty 3 it compiles to
`$_smarty_tpl->tpl_vars['constants']->value[COUNTRY]`

The reason is that I also have a constant named `COUNTRY` and for some reason Smarty takes _the_ _value_ of the _constant_ and use it as the array key instead of literal `'COUNTRY'`.

Is this a bug or an intended change from Smarty 2 to Smarty 3? If intended, why, and can the old behaviour be enabled again somehow?

**Comment by artcs** [comment]
This is already fixed in the master branch (see #149).
In 3.1.29 you can use `$constants['COUNTRY']` instead of the dot syntax as a workaround.

**Comment by bananascript** [comment]
Thanks. I found the same workaround. It will do for now.
