### ISSUE TITLE
Smarty->register_resource error in 2.6.30 works with 2.6.29

### ISSUE THREAD

**Issue by stasiukaitis-saulius** [smarty-php/smarty#256]
Hello,

We use smarty register_resource() https://github.com/OXID-eSales/oxideshop_ce/blob/master/source/Core/UtilsView.php#L356

During night time Smarty was updated from 2.6.29 to 2.6.30 by our continue integration build. 
Because of this change project crashed with error message:
2016-07-20 10:36:05 --> Smarty: Smarty->register_resource() undefined method <-- ---------------------------------------------

**Comment by uwetews** [comment]
By mistake v2.6.30 did tag Smarty 3.1.  This has been fixed now
