### ISSUE TITLE
Version 3.1.30 Errors in loading template

### ISSUE THREAD

**Issue by delakanda** [smarty-php/smarty#259]
this update causes 'unrecognized tag' on my php variables i pass to the template.
the version 3.1.29 works fine.

**Comment by madfriend** [comment]
Same thing here. Apparently installing 3.1.30 via composer (or ~3.1, or @stable) leads to v2.6 which does not have template inheritance. Using "smarty/smarty": "3.1.29" in composer.json helped me for now.

**Comment by delakanda** [comment]
I think i will stick to the "3.1.29" until this is resolved

**Comment by uwetews** [comment]
The tag 3.1.30 was added by mistake
It's now removed.
3.1.30 will be released in a couple of days
