### ISSUE TITLE
Use of undefined constant st - assumed 'st' in 

### ISSUE THREAD

**Issue by Artistan** [smarty-php/smarty#26]
i see this issue in 3.1.21
[Thu Apr 30 06:37:41.557259 2015] [:error] [pid 8687] [client 10.128.1.1:34038] PHP Notice: Use of undefined constant st - assumed 'st' in /usr/local/lib/php/Smarty/sysplugins/smarty_internal_templateparser.php on line 3456,

Server version: Apache/2.4.6 (CentOS)
PHP 5.4.16 (cli) (built: Oct 31 2014 12:59:36)
short tags enabled

anything else???

**Comment by uwetews** [comment]
This bug was already fixed in the dev-master version.
The next stable version 3.1.22 including this fix will be released in a few days.
