### ISSUE TITLE
Regression: additional plugins not recognized

### ISSUE THREAD

**Issue by artcs** [smarty-php/smarty#260]
in dev/87 my additional Plugins are no longer recognized, worked fine until dev/86.
I set it up in the constructor with `this->addPluginsDir( '/abs/path/to/dir' );`
It now throws `PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/path/to/template.tpl"  on line 64  ... unknown tag "mypluginname" <-- thrown in /path/to/sysplugins/smarty_internal_templatecompilerbase.php on line 64`.
The indicated linenumber in smarty_internal_templatecompilerbase.php is always the linenumber from the template, where the tag was used.
Double checked installation and cleared all templates.

**Comment by uwetews** [comment]
Sorry,  the fix is now committed

**Comment by artcs** [comment]
Thanks for the fast fix.
