### ISSUE TITLE
Smarty - Precompilling all templates before deployment

### ISSUE THREAD

**Issue by vavrecan** [smarty-php/smarty#261]
Hello,
I was solving the issue with deploying Smarty to Google App Engine. I came up with the idea about compiling all templates before doing deployment - so that external data storage does not have to be used at all.

Here is what I came up with - https://stackoverflow.com/questions/17787266/smarty-and-php-google-application-engine-compatibility/38636020#38636020

Maybe it will be useful for someone else too.

**Comment by uwetews** [comment]
Smarty has the method compileAllTemplates() to precompile all templates.

```php
   /**
     * Compile all template files
     *
     * @api  Smarty::compileAllTemplates()
     *
     * @param \Smarty $smarty        passed smarty object
     * @param  string $extension     file extension
     * @param  bool   $force_compile force all to recompile
     * @param  int    $time_limit
     * @param  int    $max_errors
     *
     * @return integer number of template files recompiled
     */
```
Example
```php
$smarty->compileAllTemplates($smarty, '.tpl', true, 0, null);
```
