### ISSUE TITLE
(3.1.30) @show property not working after a foreach

### ISSUE THREAD

**Issue by jsmad** [smarty-php/smarty#267]
I just tried to upgrade from 3.1.27 to 3.1.30 and every place I use the @show property is broken with the following error: 

```
Notice: Undefined property: Smarty_Variable::$show in ...
```

I then copy/pasted the example shown in the documentation (http://www.smarty.net/docs/en/language.function.foreach.tpl#foreach.property.show) and that worked fine, no error.

I've reverted back to 3.1.27.

**Comment by jsmad** [comment]
I investigated a bit more. Simple arrays iterate and work with the @show property without a problem, but when I try an object within $smarty.session, then @show returns the error I mentioned above.

**Comment by uwetews** [comment]
Can you provide an example?

**Comment by uwetews** [comment]
This is fixed in the master branch
