### ISSUE TITLE
Missing file/class Smarty_Internal_Runtime_ValidateCompiled  since 3.1.30 

### ISSUE THREAD

**Issue by meesha81** [smarty-php/smarty#269]
force_compile = TRUE   is working

force_compile = FALSE   is not working with this error message:

PHP Fatal error:  Uncaught Error: Class 'Smarty_Internal_Runtime_ValidateCompiled' not found in /usr/share/php/Smarty/sysplugins/smarty_internal_extension_handler.php:130

**Comment by uwetews** [comment]
When upgrading to 3.1.30 please delete manually all existing compiled and cached template files.
