### ISSUE TITLE
update to 3.2.13, compiled template defect

### ISSUE THREAD

**Issue by stekida** [smarty-php/smarty#27]
<div id="sid" class="dn">{$p.sid}</div>

will be compiled to 

<div id="sid" class="dn"><?php echo $_smarty_tpl->tpl_vars['p']->value[sid];?>

but ->value[sid] is missing a " ' ", it should be ->value['sid']

**Comment by stekida** [comment]
must have been 3.1.23 not 3.2.13 :-)

**Comment by uwetews** [comment]
I can't reproduce your problem.

it does compile to 
<?php echo $_smarty_tpl->tpl_vars['p']->value['sid'];?>

**Comment by stekida** [comment]
the example ist part of a longer template. Is there any reason where smarty can forget to escape the variable name? eg. [sid] instead of ['sid']

**Comment by uwetews** [comment]
It looks like that sid is a defined constant.
A couple of versions ago the use of costanstants by their name was introduced.
However it did not work in all places. 
It  was fixed that a constant can now be used also as array index.
Maybe this is now the problem in your application.

**Comment by michal-grabowski** [comment]
I've that same problem in 3.1.24.
Something is wrong with this "sid"

When i try to use $smarty.get.params.sid, variable is null, but $smarty.get.params['sid'] is ok

**Comment by uwetews** [comment]
Once again. I you have somewhere in your application sid defined as a constant. Support of constants was added to Smarty a couple of versions ago. In $smarty.get.params.sid will then not be interpreted as string array index, but the value of the constant will betaken. It' a naming conflict you must either rename the constant or  use an other array index, So it's not a bug.

**Comment by uwetews** [comment]
It turned out that SID is a constant created by session_start()

**Comment by HHGAG** [comment]
Hi Uwe,

it's quite awkward to prohibit an usecase that's supported by php. Is there any configuration option to disable this "feature"? Why was it introduced? There was already the possibility to use constants by $smarty.const.foo

Sincerely yours

Hasan
