### ISSUE TITLE
Is smarty "lint" possible?

### ISSUE THREAD

**Issue by chilek** [smarty-php/smarty#270]
Is there any way to imitate lint for smarty templates? I would like to run something like the following command in shell:
```sh
smartylint template.html
```
and seen only error messages (of course if they are). That would allow to automate template syntax checks for example.

**Comment by chilek** [comment]
I answer for myself with code snippet given below:
```php
#!/usr/bin/env php
<?php
...

$SMARTY = new Smarty;

...

if ($argc != 2)
	die('smartylint: syntax error - template file name is required!' . PHP_EOL);

if (!is_readable($argv[1]))
	die('smartylint: template file ' . $argv[1] . ' does not exist or is not readable!' . PHP_EOL);

try {
	$SMARTY->clearCache('file:' . $argv[1]);
	$SMARTY->fetch('file:' . $argv[1]);
} catch (Exception $e) {
	echo $e->getMessage() . PHP_EOL;
}
```

**Comment by marclaporte** [comment]
Related: https://github.com/smarty-php/smarty/discussions/951
