### ISSUE TITLE
Using variables inside nocache block

### ISSUE THREAD

**Issue by blaaat** [smarty-php/smarty#271]
Having an issue with using variables inside {nocache} blocks

`{include file='something.html' abc=1}
`

== something.html ==

```
{$abc}
{nocache}
{$abc} <!-- won't work -->
{/nocache}
```

**Comment by uwetews** [comment]
You assign $abc within the {include} tag.  This tag is executed when rendering the compiled page. When rendering the cached page it's gone and no variable will be assigned.

In 3.1.30 I implemented a new  tag {make_nocache $foo} which does make such variables available in nocache sections.
See NEW_FEATURES.txt
