### ISSUE TITLE
Breaking changes in 3.1.30

### ISSUE THREAD

**Issue by jarkt** [smarty-php/smarty#272]
Since the update from 3.1.29 to 3.1.30 we only get a white page and no error message.
The update usually should not change the interfaces. Temporary we will keep the old version.

**Comment by uwetews** [comment]
Please delete the existing old compiled and cached template files after the upgrade manually. 
the auto detection did not work with some of  the older versions.

See also https://github.com/smarty-php/smarty/issues/269

It's fixed in the master branch
