### ISSUE TITLE
3.1.30 config_load scope global

### ISSUE THREAD

**Issue by blaaat** [smarty-php/smarty#274]
I'm getting the following error; 

> {config_load file='mailtemplate.conf' scope="global"}" illegal value ''global'' for "scope" attribute

Even though scope global is still documented as valid.

**Comment by dimadeush** [comment]
+1, the same problem )

**Comment by uwetews** [comment]
Config variables do  not have a real global storage area like template variables,
Smarty was now checking for real available scopes which caused the error.

Correct would be
```
{config_load file='mailtemplate.conf' scope="smarty"}
```
Use that.

So the documentation needs to be corrected.

Anyway I patched the master branch that scope="global" will fallback to scope="smarty"
