### ISSUE TITLE
Class 'Smarty_Internal_Runtime_Make_nocache' not found (Composer autoloader)

### ISSUE THREAD

**Issue by blaaat** [smarty-php/smarty#275]
The autoloader appears to be case-sensitve; and the correct class name is with an uppercase Nocache ( Smarty_Internal_Runtime_Make_Nocache).

**Comment by uwetews** [comment]
This bug is now fixed in the master branch.

Workaround if you don't want to install it now is to install also the Smarty autoloader.

```
class_exists('Smarty_Autoloader');
Smarty_Autoloader::register();
```
