### ISSUE TITLE
{strip} breaks <script> when it contains comments

### ISSUE THREAD

**Issue by ghost** [smarty-php/smarty#276]
Hello,

When I enclose a template that contains a < script > tag with {strip}, it causes the javascript to stop with errors. Upon further investigation I found the following issue:

```
{strip}
<script>
    $("#myitem").attr({
        // disable autocomplete?
        autocomplete: "off"
    });
</script>
{/strip}
```

The above compiles to something like:

```
<script> $("#myitem").attr({  // disable autocomplete?  autocomplete: "off" });</script>
```

Because the comment is not removed, it remains and causes part of the javascript to be commented out, so the actual javascript execution runs with...

```
<script> $("#myitem").attr({
```

It would be nice if smarty removed comments before parsing.

Thank you.

**Comment by grintor** [comment]
using // to comment is not valid in html. it's acceptable in a .js file, but if you have javascript in an html file, you should be commenting  just like any other html.

It's not a bug in smarty, but a bug in your html file

**Comment by scorninpc** [comment]
is the HTML comment.  The bug occur on javascript language, who accept // inside ou outsite .js file. Need to remove inline comment before strip

**Comment by wisskid** [comment]
This behaviour seems totally consistent with the [documentation](https://www.smarty.net/docs/en/language.function.strip.tpl):
> Anything within {strip}{/strip} tags are stripped of the extra spaces or carriage returns at the beginnings and ends of the lines before they are displayed. This way you can keep your templates readable, and not worry about extra white space causing problems.
