### ISSUE TITLE
{strip} leaves a space

### ISSUE THREAD

**Issue by grintor** [smarty-php/smarty#278]
This:

```
{strip}
	<table border='0'>
		<tr>
		<td>
			<a href="{$url}">
				<font color="red">This is a test</font>
			</a>
		</td>
		</tr>
	</table>
{/strip}
```

should render as:
`<table border='0'><tr><td><a href="http://. snipped...</a></td></tr></table>`

which is what the [documentation says it does](http://www.smarty.net/docsv2/en/language.function.strip.tpl)

but it actually incorrectly renders as:
`<table border='0'> <tr> <td> <a href="http://. snipped...</a> </td> </tr> </table>`

**Comment by uwetews** [comment]
Which Smarty version?
This was already fixed here https://github.com/smarty-php/smarty/issues/213

The fix is included in the 3.1.30 release
