### ISSUE TITLE
constants not working v3.1.23

### ISSUE THREAD

**Issue by Gemorroj** [smarty-php/smarty#28]
```php
{if $smarty.const.SEA_IS_P_NAME === true && $f.p_id}
    //...
{/if}
```
compiled to
```php
<?php if (@constant(''SEA_IS_P_NAME'')===true&&$_smarty_tpl->tpl_vars['f']->value['p_id']) {?>
   //...
<?php }?>
```

error: PHP Parse error:  syntax error, unexpected 'SEA_IS_P_NAME' (T_STRING)

`''` - is two single quotes.

**Comment by Stricted** [comment]
no problem here
{if !$smarty.const.ENABLE_DEBUG}.min{/if}

<?php if (!@constant('ENABLE_DEBUG')) {?>.min<?php }?>

**Comment by Gemorroj** [comment]
The problem appears if the constant is not defined.

index.php
```php
<?php

require __DIR__ . '/smarty-3.1.23/libs/Smarty.class.php';

// !!!
//define('TEST_CONST', false);

class Template extends Smarty
{
    public function __construct()
    {
        parent::__construct();

        $this->setTemplateDir(__DIR__ . '/templates/')
            ->setCompileDir(__DIR__ . '/templates_c/')
            ->setConfigDir(__DIR__ . '/configs/')
            ->setCacheDir(__DIR__ . '/cache/');

        $this->compile_check = true;
        //$this->default_modifiers = array('escape:"htmlall"');
    }

}


$obj = new Template();
$obj->display('test.tpl');
```

templates/test.tpl
```smarty
{if $smarty.const.TEST_CONST === true}
    success
{/if}

render ok
```

**Comment by Stricted** [comment]
ok now i can confirm that
{if $smarty.const.TEST_CONST === true}success{/if}
 compiled to 
<?php if (@constant(''TEST_CONST'')===true) {?>success<?php }?>

Parse error: syntax error, unexpected 'TEST_CONST' (T_STRING) in

i think its better to check with defined() previously if the constant is exist
