### ISSUE TITLE
How to Get the number of item in an object array

### ISSUE THREAD

**Issue by papakay** [smarty-php/smarty#281]
Hello,

Please i have issue finding the number of item in an object returned. I have a object data as below

`public 'tags' => 

    object(stdClass)[74]
      public '1' => 
        object(stdClass)[75]
          public 'id' => string '1' (length=1)
          public 'slug' => string 'fashion' (length=7)
          public 'name' => string 'Fashion' (length=7)
          public 'user_id' => string '1' (length=1)
          public 'published' => string '1' (length=1)
          public 'created_at' => null
          public 'modified_at' => null
          public 'uploads_count' => int 0
      public '3' => 
        object(stdClass)[76]
          public 'id' => string '3' (length=1)
          public 'slug' => string 'photographer' (length=12)
          public 'name' => string 'Photographer' (length=12)
          public 'user_id' => string '1' (length=1)
          public 'published' => string '1' (length=1)
          public 'created_at' => null
          public 'modified_at' => null
          public 'uploads_count' => int 0`

And in my smarty template, i have the code below

`{foreach from=$talent->tags item=tag}

                                {if $tag@total eq 1}
                                    {*//do something*}
                                {else}
                                    {if $tag@index lt 2}
                                        <a href="{base_url('talents/'|cat:$tag->slug)}" class="skill">{$tag->name}</a>
                                    {/if}
                                    {if $tag@index eq 2}
                                        &
                                        {break}
                                    {/if}
                                {/if}
                            {/foreach}`

`{$tag@total}` returns 1 when items are more than 1. Please what i'm i doing wrong?

How can i resolve this?

Thank you.

**Comment by papakay** [comment]
I have tried this

`$data['uploads'] = $this->Upload->with_tags([

            'where' => '`tags`.`id`=\'4\''
        ])->with_user([
            'fields' => 'id,last_name,first_name,username',
            'with' => [
                'relation'=>'tags',
                'fields'=>'name,slug'
            ]
        ])->where($condition)->order_by('id', 'DESC')->get_all();`

but got this error:

`**Error Number: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IS NULL AND `users`.`id` IN('1')' at line 3
SELECT *, `id` FROM `users` WHERE IS NULL AND `users`.`id` IN('1')
Filename: core/MY_Model.php
Line Number: 950**`

however if i use remove the arguments inside `with_users`, it works fine.

In my db, table users and tags has `**has_many_pivot**` relationship, also table uploads and tags  has `**has_many_pivot**` relationship. Table user has `**has_many**` relationship with Uploads while uploads has `**has_one**` relationship with users

**Comment by uwetews** [comment]
It was a bug which is now fixed in the master branch
