### ISSUE TITLE
getConfigVariable() error

### ISSUE THREAD

**Issue by nunomendes** [smarty-php/smarty#286]
From version 3.1.28 to 3.1.30 I get this error:

File:
\sysplugins\smarty_internal_extension_handler.php

Line:
85

Message:
property 'config_variable' does not exist.

Example code (that have been running ok for ages):

$site->view->configLoad('language.conf', $site->language->active);
$int_phrase001 = $site->view->getConfigVariable('phrase001');

**Comment by uwetews** [comment]
Please note that the official documented api method is getConfigVars(). 
see http://www.smarty.net/docs/en/api.get.config.vars.tpl

however I implemented a wrapper for the removed method getConfigVariable().
This is fixed in the master branch

**Comment by nunomendes** [comment]
I missed that I was not using the official api method even after having consulting the docs and not noticing it. With getConfigVars() everything is working as expected again. Thanks!
