### ISSUE TITLE
math: function call x not allowed

### ISSUE THREAD

**Issue by interduo** [smarty-php/smarty#288]
Version: 3.1.30
File: smarty/libs/plugins/function.math.php
Line:66

Message:
Warning: math: function call x not allowed in /var/www/html/lms/vendor/smarty/smarty/libs/plugins/function.math.php on line 66

Example code:
{math equation="floor(x/100)" x=$event.begintime format="%02d"}:{math equation="x % 100" x=$event.begintime format="%02d"}

**Comment by uwetews** [comment]
The was caused by undefined variable $event or undefined array index 'begintime'.
Parameter checking order is now changed to avoid misleading E_USER_WARNING
