### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by interduo** [smarty-php/smarty#289]
Version: 3.1.30
File: function.fileupload.php
Line: 48

Example code:
if (!empty($fileupload))
foreach ($fileupload[$id] as $fileidx => $file)

Is this similar situation like https://github.com/smarty-php/smarty/issues/288 ?

**Comment by uwetews** [comment]
function.fileupload.php is not a plugin of the Smarty distribution.
I assume similar problem that $fileupload[$id] is not set.
