### ISSUE TITLE
plugins can't have a parameter called 'assign' in 3.1.30

### ISSUE THREAD

**Issue by mossadal** [smarty-php/smarty#292]
I stumbled over something that took me quite some time to track down.

In 3.1.30, creating a plugin like

```
function smarty_function_dummy(array $params, Smarty_Internal_Template $template)
{
    return "test";
}
```

and calling it via `{dummy assign=x}` results in no output in the resulting html file. 

This worked fine in 3.1.29. (I have a bunch of plugins where I'm actually using a parameter named `assign` to do something useful.)

**Comment by uwetews** [comment]
function plugins called with assign attribute like {foo assign='bar'} did not output returned content   because assumption was made that it was assigned to a variable

This is now fixed in the master branch
