### ISSUE TITLE
Getting a warning when cache dir is not existing

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [smarty-php/smarty#294]
My smarty is setup like this:

    $smarty = new Smarty;
    $smarty->setTemplateDir('./views')
           ->setCompileDir('./views_c');
    $smarty->setCacheLifetime(-1);
    $smarty->setCaching(Smarty::CACHING_LIFETIME_CURRENT);

And my template is shown like this:

    if(!$smarty->isCached('series.tpl')) {
        $series = [];
        // [...]
        $smarty->assign('series', $series);
    }

    $smarty->display('series.tpl');

On my first request, i get a warning:

Warning: file_put_contents(/path/to/app/cache/version.txt): failed to open stream: No such file or directory in /path/to/app/smarty/libs/Smarty.class.php on line 1264

smarty was checked out using git and is [Revision ec3a00e](https://github.com/smarty-php/smarty/commit/efa18457f2ef4c1e34429070ca876ffec9958558)

**Comment by uwetews** [comment]
This is caused by poor configuration.
You did enable caching but not define an individual cache folder with setCacheDir().
So Smarty did use it's default './cache/' but that folder did not exists.

**Comment by 0xFEEDC0DE64** [comment]
Shouldn't Smarty create that folder BEFORE writing the version.txt file?

It does create the folder after the warning.

A simple fix would be moving the code creating the folder just above the code creating the .txt file.

**Comment by uwetews** [comment]
There is no special code to create the folder. It's created implicit be writing that file which would also happen when the first cache file is written. you should create upfront the the needed compile and cache folders with the right ownership and access rights.
If  you run Smarty::testinstall() This will be reported as rerror
