### ISSUE TITLE
Modifier date_format does not handle future dates correctly

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#298]
Running the following code

    $Smarty = new Smarty();
    $Tpl = $Smarty->createTemplate('string:{$Date->format("Y-m-d")} {date_format($Date, "Y-m-d")} {$Date|date_format:"Y-m-d"}');
    $Tpl->assign('Date', new DateTime('2179-06-06'));
    $Tpl->display();

Will produce this:

    2179-06-06 2179-06-06 2038-01-19

As you can see, the modifier `date_format` does not handle future dates correctly.

**Comment by uwetews** [comment]
This is known as the Unix Millennium Bug Y2K38. All software (like PHP) which does store the Unix timestamp in 4 byte integer will be affected.
See https://en.wikipedia.org/wiki/Year_2038_problem

All PHP date functions like date(), mktime(), strtotime(), strftime() and may be others can not handle dates beyond 2038-01-19. 

As it looks like that limitation does not exists in the DateTime class.

The Smarty date_format modifier was designed to handle all sorts of different input value types and does normalize it  to a Unix time stamp before formatting the output.

I must see how we can solve this problem in a general way for all the format parameter values which can not be handled by the format function of the DateTime class.

**Comment by artcs** [comment]
The above example works correctly here on 64-Bit-PHP 5.5 and 5.6 on MacOS and Debian however (Smarty 3.1.30). So probably the problem only occurs on 32-Bit-Systems?

**Comment by uwetews** [comment]
@artcs You are right. It looks like that on Windows it depends if the Visual C++ Redistributable for Visual Studio x86 or x64 got installed.
So it's not a Smarty problem
