### ISSUE TITLE
Extending templates with full paths needs escaping

### ISSUE THREAD

**Issue by ScuzzyAyanami** [smarty-php/smarty#299]
Developing under Windows, when I use a full path in `{extends}` the compiled template looks like this:

    $_smarty_tpl->inheritance->instanceBlock($_smarty_tpl, 'Block_453857eb068671c206_23663404', "searchCanvas");
    $_smarty_tpl->inheritance->endChild();
    $_smarty_tpl->_subTemplateRender("file:C:\WebRoot\app\templates\theme_responsive\search.tpl",             $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 2, false);

the problem is the `\t` in `\templates` is being treated as a tab character

> Unable to load template 'file:C:\WebRoot\app emplates heme_responsive\search.tpl' in 'search.tpl'

now, above in the compiled template I can see slash being escaped properly

    'includes' => 
    array (
      'file:C:\\WebRoot\\InventoryV4\\app\\templates\\theme_responsive\\search.tpl' => 1,
    ),

Can this same escaping please be applied to this `_subTemplateRender()` syntax

**Comment by ScuzzyAyanami** [comment]
Redacted, going to try something first.

**Comment by ScuzzyAyanami** [comment]
Yes, it was my fault

`{extends file='C:\WebRoot\scratch\extends\theme_source_a\template.tpl'}`

vs

`{extends file='C:\\WebRoot\\scratch\\extends\\theme_source_a\\template.tpl'}`

vs

`{extends file='C:/WebRoot/scratch/extends/theme_source_a/template.tpl'}`

**Comment by uwetews** [comment]
No it was not your fault.  It was a bug that the parameter was passed to _subTemplateRender() in double quotes.
This is now fixedd in the master branch

**Comment by ScuzzyAyanami** [comment]
Perfect, I've implemented a pre-filter that lets me define a {extends} block with the same name. Then, given the `$smarty->_current_file` it locates the next appropriate template in the `$smarty->template_dir` array and replaces the `{extends file=""}` tag with the full path.

**Comment by uwetews** [comment]
See the extendsall resource in the demo folder. It does walk trough the template_dir array and loads  all templates with same name.
