### ISSUE TITLE
Smarty const is broken

### ISSUE THREAD

**Issue by machavity** [smarty-php/smarty#302]
Upgraded my dev environment to work on #301 and came across a new error in doing so

Here's the Smarty code
```
{if $smarty.const.SITE_ID == 1}
	Do stuff
{/if}
```

And the rendered output in Smarty cache (this works in `-dev/32`)

**Smarty version 3.1.31-dev/33, created on 2016-10-10 12:15:40**
```php
$_smarty_tpl->_subTemplateRender('file:layout/".((string)@constant('SITE_ID'))."-index.tpl', $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0, true);
```

With the error
> Parse error: syntax error, unexpected 'SITE_ID' (T_STRING), expecting ',' or ')' in /path/to/cache.tpl.php on line 27

I am using PHP 7.0.11

**Comment by uwetews** [comment]
This is now fixed in the master branch
