### ISSUE TITLE
extends, block append and include mess

### ISSUE THREAD

**Issue by glensc** [smarty-php/smarty#303]
problem appeared first when i tried to use include and block append (Feb 8 2016), and tested recently with 3.1.29 and 3.1.30.

created reproducer gist: https://gist.github.com/glensc/59d329718118dc4ef6bedacbe22406a8

showing two bugs. first is output from includes being reversed. second one manages to even duplicate the output.

given the `test.tpl`:

``` smarty
{extends "manage.tpl"}
{block "javascripts" append}
{/block}
{include file="form.tpl"}
{include file="list.tpl"}
```
# includes in wrong order

```
$ git clone https://gist.github.com/59d329718118dc4ef6bedacbe22406a8.git -b test-2 test-2
$ cd test-2
$ composer install
$ php test.php 
    list.tpl
    form.tpl
$
```
# includes in wrong order and output twice

```
$ git clone https://gist.github.com/59d329718118dc4ef6bedacbe22406a8.git -b test-3 test-3
$ cd test-3
$ composer install
$ php test.php 

    list.tpl
    form.tpl

    list.tpl
    form.tpl
$
```

**Comment by uwetews** [comment]
Per definition child templates in template inheritance should only contain {block}{/block} tags.
See
http://www.smarty.net/docs/en/advanced.features.template.inheritance.tpl

Before Smarty 3.1.28 Inheritance was a compile time process and every thing outside {block}{/block}  was ignored.
Since 3.1.28 inheritance is a run time process and code outside {block}{/block} is execute for example to conditionally enable block definitions by {if}{/if} tags.

The use of {include} outside {block}{/block} was not intended or thought of.
So your result is just random by accident and it should generate an error in future.

The right way is to use the extends resource.

```php
{extends "extends:manage.tpl|form.tpl|list.tpl"}
{block "javascripts" append}
{/block}
```

**Comment by glensc** [comment]
well. the example was simplified form showing data that got misplaced. the real template contains html between the include blocks:

- [templates/manage/users.tpl.html](https://github.com/eventum/eventum/blob/v3.1.3/templates/manage/users.tpl.html)
```smarty
{extends "manage/manage.tpl.html"}

{block "javascripts" append}
  <script type="text/javascript">
  </script>
{/block}

{include file="manage/users_form.tpl.html"}
{if isset($list)}
  {include file="manage/users_list.tpl.html"}
{/if}
```

**Comment by uwetews** [comment]
The append/prepend attributes of {block} tags define if the current {block} shall be appended or prepended to the inheritance  template {block} tag. The parent template is what was defined in the {extends} tag. The {include} templates are not inheritance parent or child templates.
Before 3.1.28 all code outside {block}{/block] was ignored. so the include tags have never been executed.
The {include} templates have not been loaded in wrong order . The {block  append} tags the {include} have not been expected and did create wrong inheritance  parent child relations.

I think what you did expect users.tpl is some think like that the {block} tags in user_form.tpl user_list.tlp. append their code to the {block} in users.tpl, but the append of the {block] tag users.tpl still points to the inheritance parent block in manage.tpl.

I that right?

**Comment by AnrDaemon** [comment]
I think this deserves a "working as intended" resolution.

**Comment by wisskid** [comment]
Working as intended.

**Comment by glensc** [comment]
Yeah, sadly "expected" and "intended" do not match here.

But as I do not plan to re-visit this topic (workaround kind of works), so it's fair to close the ticket.

**Comment by AnrDaemon** [comment]
@glensc with all due respect, you've been pointed twice that {include} tags outside {block} tags were not expected.

**Comment by AnrDaemon** [comment]
@glensc with all due respect, you've been pointed out twice that appearance of `{include}` tag [was not expected](https://www.smarty.net/docs/en/language.function.extends.tpl).

Even if documentation is not strictly accurate now, potential output outside `{block}` tags is not supported.

**Comment by glensc** [comment]
Tried the extends example:
- https://github.com/smarty-php/smarty/issues/303#issuecomment-253061268

but the output is empty now (outputs nothing at all).

```diff
diff --git a/test.tpl b/test.tpl
index 3958c2f..10d6905 100644
--- a/test.tpl
+++ b/test.tpl
@@ -1,5 +1,3 @@
-{extends "manage.tpl"}
+{extends "extends:manage.tpl|form.tpl|list.tpl"}
 {block "javascripts" append}
 {/block}
-{include file="form.tpl"}
-{include file="list.tpl"}
```

ps: the whole templates and scripts are in gist mentioned in issue body

**Comment by glensc** [comment]
@AnrDaemon so, the doc forbids anything else in child templates:
- https://www.smarty.net/docs/en/language.function.extends.tpl

I'm wondering how to solve templating in eventum project:
- template rendering starts from <page_name>.tpl, for example: https://github.com/eventum/eventum/blob/v3.9.4/templates/view.tpl.html
- which extends base_full: https://github.com/eventum/eventum/blob/v3.9.4/templates/base_full.tpl.html
- which extends base: https://github.com/eventum/eventum/blob/v3.9.4/templates/base.tpl.html
- which calls {include}: https://github.com/eventum/eventum/blob/v3.9.4/templates/base.tpl.html#L66-L68

it has worked fine over a decade, but breaks when base.tpl {include} a template that has {blocks} in it.

and having the include in base.tpl makes content in (for example) view.tpl rendered multiple times.

I've updated the example gist with such inheritance (tagged as `test-4`), and the output is printed four times:

```
[~/scm/smarty/bug-303 (master)↑] ➔ cat test.tpl
{extends "manage.tpl"}
{block "javascripts" append}
	javascript from test.tpl
{/block}
[~/scm/smarty/bug-303 (master)↑] ➔ cat base.tpl
{block "javascripts"}{/block}
{include file="extra_header.tpl"}
{include file="form.tpl"}
{include file="list.tpl"}
[~/scm/smarty/bug-303 (master)↑] ➔ php test.php

	javascript from test.tpl



	javascript from test.tpl


    form.tpl

	javascript from test.tpl


    list.tpl

	javascript from test.tpl

[~/scm/smarty/bug-303 (master)↑] ➔
```

so, how to handle such dynamic templates, i.e multiple includes that can add content to blocks?

what's definition of child template? a template that contains {extends} or template that is loaded via {extends}? in this example chain, is view.tpl child template or is base.tpl child template? and in gist example

example for checkout:
```
$ git clone https://gist.github.com/59d329718118dc4ef6bedacbe22406a8.git -b test-4 test-4
```

**Comment by glensc** [comment]
So far I've (again) workaround the problem. This time with using different block name:
- https://github.com/eventum/eventum/pull/930

If curious, then the previous workaround was similar, avoiding {include}:
- https://github.com/eventum/eventum/pull/264
