### ISSUE TITLE
{make_nocache $var} escapes string wrong

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [smarty-php/smarty#305]
I think that this issue is a different one from the other one I just created (#304).

Apostrophes are encoded wrong. I looked in the generated sources in a cache file and found this in an array definition:

    =>array('ID'=>258,'Name'=>'ChrisO\\'Dowd',)

The backslashes only should occur 1 time.

It leads to the PHP error:

    Parse error: syntax error, unexpected 'Dowd' (T_STRING), expecting ')' in /somewhere/cache/dd31c5288f02ce832e61aba7d2505c6d67d5a21e.series_add.tpl.php on line 126

My PHP source and template are both on GitHub:
https://github.com/0xFEEDC0DE64/1000serien.com/blob/master/models/series/series_add.php
https://github.com/0xFEEDC0DE64/1000serien.com/blob/master/views/series/series_add.tpl

**Comment by uwetews** [comment]
This bug is fixed now in the master branch
