### ISSUE TITLE
Variable by-reference DEPRECATED

### ISSUE THREAD

**Issue by elvispdosreis** [smarty-php/smarty#306]
File: libs\sysplugins\smarty_internal_method_appendbyref.php
Line 39: Possible array element creation during by-reference assignment
$data->tpl_vars[$tpl_var]->value[$_key] =& $value[$_key];

**Comment by mreiche** [comment]
Who is telling you that? Reference assigning is not deprecated in PHP and I dont see anything smelly here.

**Comment by AnrDaemon** [comment]
The error message is not about deprecation, it warns you that the results of operation might be not what you expect in return.

**Comment by uwetews** [comment]
As said this is not deprecated just a warning
