### ISSUE TITLE
Need a way to use multiple templates

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [smarty-php/smarty#309]
Heyo! I don't know much about smarty, but i could not find any info on this in the docs. SO for example, when you display a file(index.tpl) for example, it auto reads from the templates folder. But it does not give you the option to get the file under a directory. For example, take this file structure:

- templates
- templates/default
- templates/default/index.tpl
- templates/custom
- templates/custom/index.tpl

The only was i could find a way to make this work. Is to set the template directory based on the template. So lets say i had a var called template. Template is equal to 1. Which means default. So i would have to test of template is one. THEN set the template directory. That's the only work around i could think of. It works, but could their be a more efficient manner?

**Comment by uwetews** [comment]
$smarty->setTemplateDir(array('./templates', './templates/custom','./templates/default');

The parameter of setTemplateDir() can be an array of folders. The folders are search in the order off the array. 
In your example if you call $smarty->display('index.tpl') will load templates/custom/index.tpl
