### ISSUE TITLE
How to unify config settings from two or more files?

### ISSUE THREAD

**Issue by auge8472** [smarty-php/smarty#310]
I load the strings for specific languages from config files (with [sections]), one per language. If a string is not translated to a language, the placeholder will be replaced with nothing. I wish to be able to set a default language, to overwrite the translated elements with their translation and to keep the untranslated strings from the default language.

Example:

english.conf (default)

```
hello = hello
bye = good bye
```

german.conf (selected)

```
hello = Hallo
# no string for the key "bye"!
```

Should result in …

```
hello = Hallo
bye = good bye
```

… but it results in:

```
hello = Hallo
```

I load the selected language (section 'default') with `$smarty->configLoad($language_file, 'default');`.

My first attempt to load both config files one after each other fails. Only the strings from the last file relṕlaces their placeholders. How to do this the right way?

**Comment by uwetews** [comment]
Which Smarty version

```php
$smarty->setConfigOverwrite(true);  // is default 
$smarty->configLoad('default.conf',....');
$smarty->configLoad('selected.conf', '.....');
$smarty->display(...);
```
The above does work. The config variables in 'selected.conf' will replace the variable from 'defaultf.conf'.

**Comment by auge8472** [comment]
> Which Smarty version

It's version 3.1.30.

> The above does work. The config variables in 'selected.conf' will replace the variable from 'defaultf.conf'.

Hmm, my tests ended in a loss of all elements from the first file, that doesn't exist in the second one. I will pass further tests. Thank you.

**Comment by auge8472** [comment]
Sorry, I forgot the issue. It's solved for me, thank you.
