### ISSUE TITLE
array_filter with strlen overhead

### ISSUE THREAD

**Issue by martijnotto** [smarty-php/smarty#311]
After profiling our code I noticed that smarty spends quite some time in array_filter and strlen. Since the objective seems to be to eliminate empty entries from the array the second parameter is not necessary. If no second parameter is given all entries evaluating to false are eliminated - which has the same net effect - at a much lower performance cost.

I could not find any differences in the output. Could we remove the unnecessary strlen here?

**Comment by uwetews** [comment]
Thanks for bringing this up.
The master branch is now updated with the optimized lexer.
Besides array_filter() some additional optimizations have been made.
