### ISSUE TITLE
Not possible to use object operator on function call?

### ISSUE THREAD

**Issue by GC-Mark** [smarty-php/smarty#313]
Is there a reason it is not possible to have syntax like this?

```smarty
{if device()->isMobile()}
    <p>Mobile device detected</p>
{/if}
```

The error returned is
```
Syntax error in template "file:/website/index.tpl" on line 8 "{if device()->isMobile()}" - Unexpected "->", expected one of: "}"
```

Thanks

**Comment by uwetews** [comment]
Please note that Smarty is not PHP. For security reason you should keep PHP out of the template whenever possible. If we use template variable which are an object there is at least a basic level of security that the object must have been assigned to a template variable. By default functions are not restricted to be able to use them as modifier. So it's a difficult boarder line ...

**Comment by aVadim483** [comment]
@GC-Mark I think this code will help you
```
{$device=device()}
{if $device->isMobile()}
    <p>Mobile device detected</p>
{/if}
```

**Comment by GC-Mark** [comment]
Okay, thanks for the clarification
