### ISSUE TITLE
Every registerFilter call leads to IO operations even the registered filter is not used

### ISSUE THREAD

**Issue by ildar-aim** [smarty-php/smarty#314]
1)Apply this patch to master 
```
diff --git a/demo/index.php b/demo/index.php
index b67c217..bbe7e0e 100644
--- a/demo/index.php
+++ b/demo/index.php
@@ -27,4 +27,12 @@ $smarty->assign("option_values", array("NY", "NE", "KS", "IA", "OK", "TX"));
 $smarty->assign("option_output", array("New York", "Nebraska", "Kansas", "Iowa", "Oklahoma", "Texas"));
 $smarty->assign("option_selected", "NE");
 
+
+ini_set('display_errors', 1);
+ini_set('display_startup_errors', 1);
+
+$smarty->registerFilter('pre', 'mainPreFilter');
+
+
+
 $smarty->display('index.tpl');

```

CURRENT OUTPUT
```
( ! ) Fatal error: Uncaught --> Smarty: prefilter "mainPreFilter" not callable <-- thrown in /home/aim/public_html/smarty/libs/sysplugins/smarty_internal_method_registerfilter.php on line 49
( ! ) SmartyException: prefilter "mainPreFilter" not callable in /home/aim/public_html/smarty/libs/sysplugins/smarty_internal_method_registerfilter.php on line 49
```

EXPECTED OUTPUT
No error

TEST PATCH
[test_patch.txt](https://github.com/smarty-php/smarty/files/583848/test_patch.txt)

As you can see the **mainPreFilter filter is not used** in the 'index.tpl' template, in this case it should not be loaded.

These calls 
$smarty->registerFilter('pre', 'mainPreFilter_from_file1');
$smarty->registerFilter('pre', 'mainPreFilter_from_file2');
$smarty->registerFilter('pre', 'mainPreFilter_from_file3');
...
$smarty->registerFilter('pre', 'mainPreFilter_from_file10');
will produce 

10*N IO operations (depends on OS and PHP version)

**Comment by uwetews** [comment]
If you register a filter it must be callable. Smarty does check this on the registerFilter() call.

This is not a bug !!!!

**Comment by ildar-aim** [comment]
Dear Uwe,

I agree this is not a bug, but it might be a performance issue.

In my system modules register filters on **an early stage** in their config.php files.
On this stage there are no $cart_info $user_info $order_info information etc...

The basic template condition looks like 
```
{if $cart_info}
   {include file="cart.tpl" cart=$cart_info} {* module filter is used here *}
{/if}
```

Some module's filters is needed only for the cart.tpl template.
Some module's filters is needed only for an user.tpl template.
Some module's filters is needed only for an order.tpl template.

**I do not want the 'cart'/'user'/'order' filters to be loaded when these variables are empty $cart_info $user_info $order_info.**

How can I avoid the current 'is_callable' behavior ? 

Thank you.

**Comment by uwetews** [comment]
Note;
'pre' Filters do run only over the template source code before a template gets compiled. Which should happen only when you modify your template source code. Once your template 'cart.tpl' is compiled
The filters will no longer run independent if 'cart.tpl. gets called or not.

**Comment by ildar-aim** [comment]
An module does not known if the cart.tpl template is compiled.
$smarty->registerFilter('pre', 'mainPreFilter');  will be called anyway from the module config.php file
