### ISSUE TITLE
PHP Fatal error:  Call to undefined function content_582a6ace305781_26092487() in

### ISSUE THREAD

**Issue by crazelee** [smarty-php/smarty#315]
I get this error when upload tpl，how to solve it~~

**Comment by uwetews** [comment]
What exactly do you mean by "when upload tpl"?
When you modify template sources on a development system. you should upload just the updated template sources not the compiled or cached  template files to the WEB Server..

**Comment by crazelee** [comment]
Hmm，
After I upload new tpl files to the server and I visit the changed pages in the browser I get an error like this:
_PHP Fatal error: Call to undefined function content_582a6ace305781_26092487() in_

Of course, content_582a6ace305781_26092487() is now content_4ff3e2899a21e1_01321222 because smarty recompiled the template. 

In first request when cache is created, where cache was just created on that previous ID I get PHP Fatal error. 

After I reload the page everything is working fine.

**Comment by wUFr** [comment]
i think i noticed similar behaviour few times, cleaning up tpl cache folder fixed it

**Comment by uwetews** [comment]
Since Smarty version 3.1.30 ACP or OPCACHE get cleared by Smarty on template or cache updates.

If you use ACP and Smarty version < 3.1.30 set php.ini  acp.stat =  1
If you use OPCACHE and Smarty  version < 3.1.28 set php.ini
opcache.validate_timestamps=1
opcache.revalidate_freq=0
