### ISSUE TITLE
Extending Smarty_Internal_Resource_File populate method

### ISSUE THREAD

**Issue by genyslt** [smarty-php/smarty#318]
Hi,

i write dynamic module loading and i need to overwrite a class Smarty_Internal_Resource_File -> populate method. 

- {include file=module/ppp/template.tpl} doeas not exists
- if folder "ppp" does not exists on module DIR, i need to load module/dynamic/template.tpl
- Is there a better way from editing SMARTY_INTERNAL_RESOURCE_FILE method?

Now i'm doing this:

```
public function populate(Smarty_Template_Source $source, Smarty_Internal_Template $_template = null)
    {
		/* START DYNAMIC */
		$resource = $source->resource;
		if (
			!file_exists($_SERVER['DOCUMENT_ROOT'] . str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace('file:','', $resource)))
			&&
			file_exists($_SERVER['DOCUMENT_ROOT'] . 'modules/dynamic')
		){
			$test = str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace('file:','', $resource));
			$construct = explode('/', $test);
			$construct[1] = 'dynamic';
			$resource = ((strpos($resource, 'file:') === false) ? '' : 'file:') . implode('/', $construct);
			$name = ((strpos($resource, 'file:') === false) ? '' : 'file:') . implode('/', $construct);
			
			$source->resource = $resource;
			$source->name = $name;
		}
		/* DYNAMIC END */
        /* START SMARTY ORIGINAL CODE  */
	$source->filepath = $this->buildFilepath($source, $_template);
		
        if ($source->filepath !== false) {
            if (isset($source->smarty->security_policy) && is_object($source->smarty->security_policy)) {
                $source->smarty->security_policy->isTrustedResourceDir($source->filepath, $source->isConfig);
            }
            $source->exists = true;
            $source->uid = sha1($source->filepath . ($source->isConfig ? $source->smarty->_joined_config_dir :
                                    $source->smarty->_joined_template_dir));
            $source->timestamp = filemtime($source->filepath);
        } else {
            $source->timestamp = $source->exists = false;
        }
    }
```

Thank you for any answers

**Comment by artcs** [comment]
There's always a better way than editing the internal files!
You could correctly setup the template dirs
```
$Smarty->setTemplateDir( array('/some/dir/', '/some/fallback/dir'));
```
and simply `{include file='template.tpl'}` without path.

If this dosen't work for your setting, you could add a custom function plugin `function.myinclude.php` like this:
```
<?php

function smarty_function_myinclude($params, &$smarty)
{
    $file = '';
    $rootdir = $_SERVER['DOCUMENT_ROOT'];
    $fallbackdir = 'modules/dynamic/';

    if (empty($params['file'])) {
        $smarty->trigger_error("myinclude: missing 'file' parameter");
        return;
    }

    foreach ($params as $var=>$value) {
        switch ($var) {
		case 'rootdir':
		case 'fallbackdir':
			if( mb_substr($value, 1, 1) != '/' ) {
				$value .= '/';
			}
			$$var = $value;
			break;
		case 'file':
			$$var = $value;
			break;
		default:
			$smarty->trigger_error("myinclude: unknown parameter '${var}'");
        }
    }
    
    if( file_exists($rootdir . $file) ) {
    	return $smarty->fetch($rootdir . $file);
    }
    
    if( file_exists($rootdir . $fallbackdir . $file) ) {
    	return $smarty->fetch($rootdir . $fallbackdir . $file);
    }
	
   $smarty->trigger_error("myinclude: file not found '${file}'");
}
```
and call it with {myinclude file='some/file'}.

**Comment by genyslt** [comment]
Thank you artcs for your comment.

With $Smarty->setTemplateDir( array('/some/dir/', '/some/fallback/dir')); works fine, for overwrite files with existing templates, but if i use

$smarty->display('dir/file.tpl') <-- the directory 'DIR' doe's not exists, i want to redirect to 'dynamic/file.tpl',

Is beter example if template didn't found i want include 404.tpl file.

Be nice, if smarty for not found file call specific function with filepath param and you can implement some logic and return some $output to smarty

**Comment by artcs** [comment]
Then simply check the existence before calling display():
```
if( $Smarty->templateExists($sometpl) ) {
   $Smarty->display($sometpl);
}
else {
   $Smarty->display($error404tpl);
}
```
Or make some custom PHP function (e.g. display_template()) where you check the paths however you want and call `$Smarty->display()` from there with the file.tpl or 404.tpl.
The point is: Don't mess with the internal files, because they can change anytime and you would have to reapply your changes on every update. Very errorprone...

**Comment by genyslt** [comment]
It's not so easy to do, because smarty subtemplate loading is called on smarty.

I do $smarty->display ('/dir/File.tpl');

File.tpl content:

```
{include file="dir/head.tpl"}
<div id="main" style="z-index:999">
{include file="dir/menu.tpl"}
<section id="content_wrapper">
  <section id="content" class="table-layout" style="width:100%">
	  {include file="aaa/file.tpl"} <-----# this file doe's not exits
  </section>
</section>
</div>
{include file="dir/foot.tpl"}
```

So i must parse content (REGEXP ?)  on prefilter function, $output of File.tpl, to check every file exists.

There are large amount of tpl files, it's not so easy to detect where i need write own include function.

**Comment by artcs** [comment]
Then you can use a try/catch block. Smarty throws a SmartyException if a resource cannot be loaded.
```
try {
   $Smarty->display($file);
}
catch( SmartyException $e ) {
   $Smarty->display($errorfile);
}

**Comment by genyslt** [comment]
Your solution give me to display ALL File.tpl $content OR display different tpl. I need to overwrite just 

```
<section id="content" class="table-layout" style="width:100%">
	  {include file="aaa/file.tpl"} <-----# this file doe's not exists
  </section>
```

this block, every other blocks must be displayed too.

Thank you very much for help, now i can make some workarounds.

P.S. Anyway, it will be nice to have native function, when tpl file not found you can pass $output to that place, aka:

```
smarty_function_notfound($file, &$smarty){
return 'file not found ' . $file;
}
```

Now you get smarty error and scares simple users :)

**Comment by artcs** [comment]
If you want to overwrite just the `{include}` inside your section, use the above mentioned `{myinclude}` approach. Adjust it to your needs. If the included file imports more tpl's, use a try/catch block around the fetch() function. In the catch block you are free to return a 404.tpl or return notfound errortext, e.g. `return $e->getMessage();`, that's up to you.

**Comment by uwetews** [comment]
There is no need of modifying the SMARTY_INTERNAL_RESOURCE_FILE class . You can extend it to create your  custom class.

Into the plugins folder  resource.myfile.php
```php

Smarty_Resource_Myfile extends SMARTY_INTERNAL_RESOURCE_FILE
{
public function populate(Smarty_Template_Source $source, Smarty_Internal_Template $_template = null)
    {
		/* START DYNAMIC */
		$resource = $source->resource;
		if (
			!file_exists($_SERVER['DOCUMENT_ROOT'] . str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace('file:','', $resource)))
			&&
			file_exists($_SERVER['DOCUMENT_ROOT'] . 'modules/dynamic')
		){
			$test = str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace('file:','', $resource));
			$construct = explode('/', $test);
			$construct[1] = 'dynamic';
			$resource = ((strpos($resource, 'file:') === false) ? '' : 'file:') . implode('/', $construct);
			$name = ((strpos($resource, 'file:') === false) ? '' : 'file:') . implode('/', $construct);
			
			$source->resource = $resource;
			$source->name = $name;
		}
		/* DYNAMIC END */
        /* START SMARTY ORIGINAL CODE  */
populate(Smarty_Template_Source $source, Smarty_Internal_Template $_template = null)
	$source->filepath = $this->buildFilepath($source, $_template);
		
        if ($source->filepath !== false) {
            if (isset($source->smarty->security_policy) && is_object($source->smarty->security_policy)) {
                $source->smarty->security_policy->isTrustedResourceDir($source->filepath, $source->isConfig);
            }
            $source->exists = true;
            $source->uid = sha1($source->filepath . ($source->isConfig ? $source->smarty->_joined_config_dir :
                                    $source->smarty->_joined_template_dir));
            $source->timestamp = filemtime($source->filepath);
        } else {
            $source->timestamp = $source->exists = false;
        }
    }
}

**Comment by genyslt** [comment]
Thanks, uwetews & artcs for your answers.

Now i have several choises to get  necessary functionality.

Good luck!
