### ISSUE TITLE
3.1.31 - touch() warning on compile file creation with use_sub_dirs enabled

### ISSUE THREAD

**Issue by sofl88** [smarty-php/smarty#321]
After upgrading to 3.1.31 I get a warning like

> Warning: touch(): Unable to create file C:\inetpub\wwwroot\x\y\Data\Compiles\40\64\5d\40645d3421547b8e53d9f7051e19f465daaf66e4_2.file.Overview.tpl.cache.php because No such file or directory in C:\inetpub\wwwroot\weblibraries\smarty\latest\sysplugins\smarty_template_compiled.php on line 198

This only appears if the option _use_sub_dirs_ is set to **true**

**Comment by PBeckerr** [comment]
+1

**Comment by uwetews** [comment]
This is meanwhile fixed in the dev-master version and will be included in the upcomming 3.1.32 release
