### ISSUE TITLE
broken tarball export for 3.1.31

### ISSUE THREAD

**Issue by sunweaver** [smarty-php/smarty#325]
I just wanted to upload smarty 3.1.31-1 to Debian unstable, but the tarball as exported by Github is defect:

In commit https://github.com/smarty-php/smarty/commit/beeec36bb844835dfa6a58e4981704b97e3e18f5#diff-fc723d30b02a4cca7a534518111c1a66. the lexer/ subfolder is marked as 

```
/lexer/ export-ignore
```

However, this folder is essential for building smarty. Do you see a chance to get this fixed on Github and tag a 3.1.32 (or 3.1.31a) release? If not, I have to import those files manually into the Debian package which I'd like to avoid.

Feedback within the next 2 weeks is necessary to get the 3.1.31 upstream version into Debian 9 (we are in freeze already).

Thanks and Greets,
Mike

**Comment by sunweaver** [comment]
I just saw that composer.json gets also excluded from the tarball export. For the Debian packaging, I actually need that file. Please revert that change in .gitattributes and include composer.json. Thanks!

**Comment by wisskid** [comment]
`composer.json` is now in the Github download. The `lexer` subfolder stil isn't, but why would you need this?

**Comment by sunweaver** [comment]
@wisskid: in the Debian smarty3 package, I rebuild the lexer stuff using smarty-lexer. For that, I need the content of the lexer/ subfolder. The pre-build lexer (and parser) .php files are considered machine-built in Debian and must not be part of some source code.

**Comment by wisskid** [comment]
I see! I'll re-add them, add `smarty/smarty-lexer` as a composer dev dependency and add rebuilding instructions. I'm waiting for some input from @uwetews on smarty-lexer, since the latest parser/lexer seem to have been built by a newer version of smarty-lexer than availble in the public repo.
