### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by JimiC** [smarty-php/smarty#326]
Been looking for an SVG version of the logo to use in [vscode-icons](https://github.com/robertohuertasm/vscode-icons).

Thanks in advance.

**Comment by wisskid** [comment]
We don't have one. Could you piece one together from the [trademark notice](https://www.smarty.net/files/SmartyTrademark.pdf)?

**Comment by PrestaConnect** [comment]
> Been looking for an SVG version of the logo to use in [vscode-icons](https://github.com/robertohuertasm/vscode-icons).
> 
> Thanks in advance.

I drawed a svg logo from [trademark notice](https://www.smarty.net/files/SmartyTrademark.pdf)

You can use here 
![smarty](https://github.com/smarty-php/smarty/assets/66181288/8e6faf6c-4d57-43d0-9a4e-284b5af9bd8b)

**Comment by scottchiefbaker** [comment]
@PrestaConnect wow that's a pretty decent logo!

Can you post the actual SVG file somewhere?

**Comment by PrestaConnect** [comment]
> @PrestaConnect wow that's a pretty decent logo!
> 
> Can you post the actual SVG file somewhere?

https://www.prestaconnect.net/img/cms/smarty.svg
