### ISSUE TITLE
Chained modifiers, unexpected results.

### ISSUE THREAD

**Issue by padraigdoran** [smarty-php/smarty#327]
The first case below comes from a Smarty2 script which works fine, but once applied to Smarty3.1.x and up it breaks giving an unexpected value.

The issue stems from the -4 being used in substr and the cat after it. If the - sign is removed, the functions works as expected, albeit the other way around.

Is this a Smarty bug?

The following is a simple test script with expected and actual results.

`{assign var="aFile" value="somefile.xyz"|substr:0:-4|cat:".ext"}`
`<!-- Result expected: somefile.ext -->`
`<!-- Actual result:   somefile -->`
`{$aFile}`

`{assign var="aFile" value="somefile.xyz"|substr:0:4|cat:".ext"}`
`<!-- Result expected: some.ext -->`
`<!-- Actual result:   some.ext -->`
`{$aFile}`

`{assign var="aFile" value=("somefile.xyz"|substr:0:-4)|cat:".ext"}`
`<!-- Result expected: somefile.ext -->`
`<!-- Actual result:   somefile.ext -->`
`{$aFile}`

`{assign var="aFile" value="somefile.xyz"|substr:0:-4}`
`{assign var="aFile" value=$aFile|cat:".ext"}`
`<!-- Result expected: somefile.ext -->`
`<!-- Actual result:   somefile.ext -->`
`{$aFile}`

`{assign var="aFile" value="somefile.xyz"|substr:0:-(4)|cat:".ext"}`
`<!-- Result expected: somefile.ext -->`
`<!-- Actual result:   somefile -->`
`{$aFile}`

`{assign var="aFile" value="somefile.xyz"|substr:0:(-4)|cat:".ext"}`
`<!-- Result expected: somefile.ext -->`
`<!-- Actual result:   somefile.ext -->`
`{$aFile}`

`{assign var="aFile" value=-4|cat:".ext"}`
`<!-- Result expected: -4.ext -->`
`<!-- Actual result:   -4.ext -->`
`{$aFile}`

`{assign var="aFile" value=-4-4|cat:".ext"}`
`<!-- Result expected: -8.ext -->`
`<!-- Actual result:   -8.ext -->`
`{$aFile}`

Above code contained here:
[test.tpl.txt](https://github.com/smarty-php/smarty/files/696144/test.tpl.txt)

**Comment by padraigdoran** [comment]
In the compiled tpl, the first case is compiled as:

`$_smarty_tpl->_assignInScope('aFile', substr("somefile.xyz",0,-(4).(".ext")));`

We can see from this that `-(4).(".ext")` is trying to be used as the 3rd parameter of substr which is not what is expected and used to work fine with Smarty2.

**Comment by padraigdoran** [comment]
I've attached the whole compiled tpl of the test script above for reference

[compiled.file.test.tpl.php.txt](https://github.com/smarty-php/smarty/files/698492/compiled.file.test.tpl.php.txt)

**Comment by AnrDaemon** [comment]
Any results of modifying an assignment is an undefined behavior.
Please do not do that. Better yet, do not use assignments in templates if at all possible.

**Comment by AnrDaemon** [comment]
If you absolutely want to do it, please try the v3 syntax `{$name=value}`.

**Comment by uwetews** [comment]
This is a bug on chained modifier when last modifier parameter is a signed value. I will fix that asap

**Comment by uwetews** [comment]
AnrDaemon
It has nothing to do with the assign tag

**Comment by uwetews** [comment]
The bugfix is now in the master branch and will later be included in 3.1.22
