### ISSUE TITLE
3.1.23 - Foreach in foreach issue

### ISSUE THREAD

**Issue by Naki** [smarty-php/smarty#33]
Example template data:

    $data = [
        'rows' => [[], ['children' => ['bug appears here']], []]
    ];

Example template file:

    {foreach $rows as $row}
        {$row@index}, 
        {if !empty($row.children)}
            {foreach $row.children as $children}
                {* anything *}
            {/foreach}
        {/if}
    {/foreach}

Output:
`0, 1, 1,`

Should be:
`0, 1, 2,`

**Comment by uwetews** [comment]
This is now fixed in dev-master
