### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by flik** [smarty-php/smarty#330]
Parse error: syntax error, unexpected '/', expecting ',' 

I have install smarty with composer and now loading in php file but getting above error
use smarty\smarty ; 
Parse error: syntax error, unexpected '/', expecting ',' 

if i use
use \smarty\smarty ; 
Fatal error: Uncaught Error: Class 'smarty\smarty' not found

**Comment by areebmajeed** [comment]
Doesn't look like an issue with Smarty. It's more likely an error with your code :)

**Comment by uwetews** [comment]
Smarty does not use namespaces.

To instance Smarty just

$smarty  = new  Smarty;
