### ISSUE TITLE
Iterating class implementing ArrayAccess with {foreach}

### ISSUE THREAD

**Issue by chmeldax** [smarty-php/smarty#332]
Hello,

it seems to me that the change introduced in https://github.com/smarty-php/smarty/commit/21aa211ddbc0be879d0ce7a7090114b2792d9c72 prevents some certain classes implementing `ArrayAccess` from being iterated with `foreach` macro.

The condition in https://github.com/smarty-php/smarty/commit/21aa211ddbc0be879d0ce7a7090114b2792d9c72#diff-6b401ee81e7ad91e8e4fb5f199bc6a3eR129 does not take into account classes that implement `ArrayAccess` but do not use numerical offsets.

Consequently, the`init()` method then returns `NULL` and the iteration is not performed at all.

**Comment by uwetews** [comment]
Please note that a class implements ArrayAccess does not necessary mean that it can be iterated by foreach.
