### ISSUE TITLE
The method $smarty->setStrip(2);  can be useful, but not working

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#333]
I found this method $smarty->setStrip(int stripLevel);,  but seems not works. Can be useful, instead to add in each template {strip}...{/strip}

stripLevel: 
0: default value - don't change any template 
1: auto strip all variables with |strip modifier 
2: auto strip templates - no need to add in the template {strip}{/strip} tags 
3: auto strip templates and variables - no need to add in template {strip}{/strip} and use modifier strip on all variables 
4: debug mode - skip all {strip}{/strip} and |strip tags 

I have error:

> <br />
> <b>Fatal error</b>:  Uncaught  --&gt; Smarty: property 'strip' does not exist. &lt;-- 
>   thrown in <b>...\smarty\sysplugins\smarty_internal_extension_handler.php</b> on line <b>92</b><br />

**Comment by wisskid** [comment]
Auto stripping could cause all sorts of problems and I don't see why it would be very useful.
