### ISSUE TITLE
modifier default not working with @ suppression 

### ISSUE THREAD

**Issue by alabama** [smarty-php/smarty#336]
The default modifier just access the tpl_vars array with the non existing key and tries to suppress the error outcome with '@' like:
`$tmp = @$_smarty_tpl->tpl_vars['bShowInfo']->value`

This won't work in PHP >= 5.4 (5.3 as well?)
There should be at least an "array_key_exist | isset" check to get the functionality right

**Comment by Miksser** [comment]
Is it possible to get rid of suppression in 'default'? 
This behavior is very disturbing during debugging through xDebug =(

**Comment by Miksser** [comment]
Is it possible to get rid of suppression in 'default'? 
This behavior is very disturbing during debugging through xDebug =(

**Comment by wisskid** [comment]
@Miksser @antman3351 I've added an empty check for variables for `|default` modifier in #650 . It does not appear to break anything. Can you confirm this fixes your problem?

**Comment by antman3351** [comment]
I just had a quick look at the change, so I might have missed something, but doesn't this change the behaviour of the default modifier?
before default was used for unset variable, null or an empty string. Using empty() default would also be applied to false, 0 , '0' and [ ].

**Comment by wisskid** [comment]
Well spotted, @antman3351 ! Not sure how that got past me. I thought I ran the new unit tests against the old code (seeing no change in behavior) but I must have somehow messed that up. 
Added the 0, '0' and [] cases to the unit tests and fixed the implementation.
Is this better?

**Comment by wisskid** [comment]
The default modifier has already been changed to longer use the @ modifier in https://github.com/smarty-php/smarty/pull/629
