### ISSUE TITLE
Problem with nested blocks and {$smarty.block.parent}

### ISSUE THREAD

**Issue by alejosky** [smarty-php/smarty#339]
Got **Fatal error**: Uncaught --> Smarty: inheritance: illegal {$smarty.block.parent} or {block append/prepend} used in parent template 'C:\...\parent.tpl' block 'block1.1' <-- thrown in C:\...\smarty\smarty\libs\sysplugins\smarty_internal_runtime_inheritance.php on line 226

when using {$smarty.block.parent} in a child nested block. When the block is **not** nested, it works well as expected. Example outputs the error:

**parent.tpl**
```
{block name="block1"}
	{block name="block1.1"}
		Content
	{/block}
{/block}
```

**child.tpl**
```
{extends file="parent.tpl"}

{block name="block1"}
	{block name="block1.1"}
		{$smarty.block.parent}
	{/block}
{/block}
```

We want to nest the blocks to change their display sequence, something like 1.1, 1.2, 1.3 -> 1.3, 1.1, 1.2, which works great without any {$smarty.block.parent}.

**$smarty.version 3.1.31.**

Also, with  $smarty.version 3.1.27 the output was recursive (all sub-blocks were displayed for each {$smarty.block.parent}) which was also undesired.

**Comment by maxprihodko8** [comment]
How could it be fixed?

**Comment by wisskid** [comment]
The [docs state](https://www.smarty.net/docs/en/language.function.block.tpl) that blocks 'can be nested' but this should be probably be understood to mean that they can be nested in the parent's context. Once inside a block in a child template, you are redefining the content of that block, and the parent's sub-blocks disappear.

A workaround for your problem would be to change `child.tpl` to:
```
{extends file="parent.tpl"}

{block name="block1.1"}
	{$smarty.block.parent}
{/block}
```
But I'm sure you've thought of this. Is there a reason I'm not seeing why this would not work?

**Comment by wisskid** [comment]
Closed because of inactivity.
