### ISSUE TITLE
PHP Warning:  filemtime(): stat failed for missing file

### ISSUE THREAD

**Issue by stephanlueckl** [smarty-php/smarty#341]
It seems not to have a big effect - but the error logs are full of this messages:
`
PHP Warning:  filemtime(): stat failed for /var/www/^773307d3849ef0eee2c6c9cc5512e49c169fe1c8_0.somefile.tpl.php in /var/www/smarty/libs/sysplugins/smarty_template_resource_base.php on line 154
`

It happens on a server with heavy load while cleaning the cache.
We have turned off the compile check  (Smarty Version 3.1.31)

**Comment by uwetews** [comment]
You can mute expected errors by calling 

`
Smarty::muteExpectedErrors();
`
However I added some additional is_file() checks which should also solve the problem.
The fix is now in the master branch and will later be included in version 3.1.32

**Comment by blaaat** [comment]
I'm seeing this warning occur a lot recently (I assume after PHP or kernel updates). Happens both after emptying the templates compile directory and on regular cache hits. 

> filemtime(): stat failed for 
> smarty/smarty/libs/sysplugins/smarty_internal_cacheresource_file.php:69
> Smarty_Internal_CacheResource_File::populate
> 

Appears that there is a race condition between the `is_file` and `filemtime`?
