### ISSUE TITLE
Default compiler plugin handler error when have shorthand attribute

### ISSUE THREAD

**Issue by vuongminh** [smarty-php/smarty#342]
Demo default compiler plugin with shorthand attribute:

```
{mycompiler test}
```

A problem in [templatecompilerbase L667](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatecompilerbase.php#L667) when compiler making a `args` for compiler handler, it not check a type of element is array or not => php error exception when do merge.

**Comment by uwetews** [comment]
This is also fixed in the master branch and will later be included in 3.1.32
