### ISSUE TITLE
Call to undefined function smarty_modifier_truncate()

### ISSUE THREAD

**Issue by jsmad** [smarty-php/smarty#346]
I'm stuck with version 3.1.27 because every time I try to upgrade, I hit some kind of bug. I've already reported several that I've found and I have also hit bugs that others have reported. No matter what, I always end up going back to 3.1.27.

Today I tried 3.1.31 and immediately it came up with this error:
```
PHP Fatal error:  Uncaught Error: Call to undefined function smarty_modifier_truncate()
```

The offending lines all use 'truncate' like:
```
{$barcode|truncate:5:""}
```

What is interesting, is that the error goes away and everything works when I disable caching. But that is not a solution and the site can't work without cache, so back to 3.1.27.... again for the fourth time :(

**Comment by carpii** [comment]
Have you tried clearing out your $cache_dir?   Defaults to ./cache

**Comment by uwetews** [comment]
I was not able to reproduce this problem.
Did you clear the templates_c and cache folders?
Was the code in a {nocache}{/nocache} section?
Was it in a sub template?

**Comment by scottchiefbaker** [comment]
I agree with @uwetews and @carpii this really sounds like a cache issue to me.

**Comment by tahonaPL** [comment]
I had same problem in 3.1.32


```
            {nocache}
            {foreach $someList  as $advertisement}
                <div >
                    <div>
                        <a href="/xxx/{$advertisement->getId()}/{$advertisement->getSeoUrl()}">{$advertisement->getTitle()}</a>
                        <span >{call date value=$advertisement->getPublicDate()}</span>
                    </div>
                    <div>
                        <span>{$advertisement->getContent()|truncate:130:"..."}</span>
                    </div>
                </div>
            {/foreach}
            {/nocache}
```
