### ISSUE TITLE
3.1.31 potentially breaks if statement order

### ISSUE THREAD

**Issue by eth8505** [smarty-php/smarty#347]
As described on the forums here: http://www.smarty.net/forums/viewtopic.php?p=92056#92056 the bugfix applied here https://github.com/smarty-php/smarty/commit/b8acd7ea176bee219f65eed15721dbd23b3c24ed potentially breaks the processing order of if statements.

Let me re-describe:

Assuming I have a class with a has($key) and a get($key) method, where the get() method throws an exception if $key does not exist in the internal stack. If I then build the following if statement with smarty, the get() exception will be triggered with 3.1.31, but not with 3.1.30 or 3.1.29.

```
{if !$stack->has('mykey') || empty($stack->get('mykey')}
{/if}
```

The variable prefixing done by the php function parser for empty() function calls will convert the statement into
```
<?php $_prefixVariable1=$_smarty_tpl->tpl_vars['stack']->value->get('mykey');
if ($_smarty_tpl->tpl_vars['element_current']->value->has('mykey') && !empty($_prefixVariable1)) {?>
```

Which totally breaks the original handling of if statements, as the empty() call would never have to be executed if the key does not exist.

**Comment by uwetews** [comment]
now fixed in master branch

**Comment by uwetews** [comment]
The  fix is now in the master branch
