### ISSUE TITLE
After upgrade to 3.1.23 function in template doesn't work

### ISSUE THREAD

**Issue by Michael-Gusev** [smarty-php/smarty#35]
```smarty
{function name='select'}
    {foreach from=$options item='label' key='key'}
        {if is_array($label)}
            {if !empty($label)}
                {select options=$label}
            {/if}
        {elseif $key == $value}
            {$label|escape}
        {/if}
    {/foreach}
{/function}
{select options=$options}
```

When I don't have compiled template I get `unknown tag "select"` error

**Comment by uwetews** [comment]
I confirm this bug. 
Recursive calling the function just by its name is broken.

{call name=select options=$label}

would work.

I will get that fixed.  Also because of some other problems I think I will roll out 3.1.24  later today

**Comment by uwetews** [comment]
The patch is now in dev-master.I may release 3.1.24 later today

**Comment by Michael-Gusev** [comment]
Great, thank you.

**Comment by gufei** [comment]
> The patch is now in dev-master.I may release 3.1.24 later today

The bug still exists in release 3.1.33
