### ISSUE TITLE
Question: Smarty 3.2

### ISSUE THREAD

**Issue by ghost** [smarty-php/smarty#353]
Hello,

Almost 4 years ago you posted something about smarty 3.2 being created, do you have any idea when this new version of smarty will be published? Or do you perhaps already have a dev version for this which simply hasn't been posted yet?

Sincerely yours,

**Comment by flexjoly** [comment]
Hi, 
I have the same question
Maybe we can start a fork to develop a follow-up, since smarty -development seems to be death and uwetews is not responding (much).

Smarty needs to be updated for php 7 and must start using namespaces and the errorhandling must be updated. 

Any volunteers?

Greetz, flexjoly

**Comment by pinkminds** [comment]
We run smarty on PHP 7, so no problem with that. But it would indeed be good to know if the development of smarty is still active and by when next releases are scheduled...

**Comment by uwetews** [comment]
Hallo
Smarty does run without Problems on php 7.
I myself are recovering from a longer illness and should be active very
soon again.

Regards Uwe


pinkminds <notifications@github.com> schrieb am Mo. 19. Juni 2017 um 13:12:

**Comment by Gemorroj** [comment]
@uwetews, wish you good health 💊

**Comment by pinkminds** [comment]
@uwetews, get better soon!

**Comment by PoppedWeb** [comment]
@uwetews, I hope you will be better soon! I know I am asking a lot, but could you give us like some sort of update on the progress of smarty 3.2? Because we all are very curious as to what you are planning to do with smarty 3.2!!!

**Comment by uwetews** [comment]
Smarty 2 version 2.6.28 is the latest version which does support PHP 4.
However if you want to use composer it does require as minimum PHP 5.3.

PHP 4 support has been dropped in Smarty 2 version 2.6.29 and higher.

Smarty 2 version 2.6.29 and higher is compatible with PHP versions:
5.2 and higher
7.0
7.1
and even the upcomming 7.2

Corresponding PHPUnit tests will be published i the next couple of days.

For Smarty 3.1 I have tested PHP 7.2 compatibility back to version 3.1.24, but I think earlier version should also run.

PHPUnit tests for PHP 7.2 have already been added to the 3.1.32-dev version of Smarty 3.1.

I have dropped the development of Smarty 3.2, but working now on Smarty 4.

I will release a feature list in the near future.

**Comment by flexjoly** [comment]
I am very happy to read this!! Thanks @uwetews ! 
Can we help we development?

**Comment by jcfalcone** [comment]
Where can I check the feature list for Smarty 4 or a release date? I'm deciding if I should change the template engine in some projects...

**Comment by AnrDaemon** [comment]
I have a suggestion. Start 3.2 branch to support PHP7+ only.
In PHP7, there's a number of changed which can't be addressed in a backward-compatible manner without a lot of ugly code.
The most prominent is a change in exception handling (i.e. [`\Throwable`](https://github.com/smarty-php/smarty/issues/514))

**Comment by wisskid** [comment]
Smarty 3.1 is compatible with php versions up to 7.4.
Creating a new version (which would have to be a version 4) just to drop support for php5 doesn't seem to provide any value to anyone. (Though you really should not be using PHP5 anymore!)

**Comment by AnrDaemon** [comment]
I suggested to start a new branch, that would aim for PHP 7+. It would prove valuable for you as a developer first, the reasoning should be quite obvious.
