### ISSUE TITLE
HEAD request causes empty cache files

### ISSUE THREAD

**Issue by rob-z** [smarty-php/smarty#355]
Hi, I was asked to raise a ticket over here. I found some problems in Smarty when a page is requested with an HEAD request. Sometimes this results in the caching of empty pages (with no html-output). This happens when multiple templates are cached separately in one php script. When one of the template files to be displayed / cached is sufficiently large, the caching of the next template fails. I use some template-includes, so maybe this is a factor. I found that this problem is caused by a (too) small output buffer in PHP. The default size is 4kb. When I raised this value to 128kb my problem disappeared. Output buffers are used by Smarty to store the parsed templates to be written as cache files. 

N.B. this bug only happens when the templates were not already cached, the php script is requested by an HEAD request and the php script tries to display/cache multiple templates.

I am using Smarty version 3.1.30 on Nginx with php-fpm 5.6.30, but this problem also existed in earlier Smarty versions. An extensive description of this problem (and how I found it can be found on the  Smarty forums: http://www.smarty.net/forums/viewtopic.php?p=92262 ). 

I found these people with similar issues with HEAD requests and PHP output buffers: 
https://bugs.php.net/bug.php?id=64152 
https://www.reddit.com/r/PHPhelp/comments/5chuus/does_php_disable_or_shrink_usage_of_output/ 

I hope this can be resolved so Smarty gets a little better. This bug was quite difficult to find/resolve and caused a lot of frustration (my site only sometimes displayed empty pages). If necessary I am willing to provide my template files in which the problem manifests.

**Comment by wisskid** [comment]
This appears to be a PHP-bug, which has been [fixed](https://bugs.php.net/bug.php?id=64152) in [PHP7](https://wiki.php.net/rfc/continue_ob)
Not much we could or should do about it here.
