### ISSUE TITLE
Support: looking a way to get smarty parse tree

### ISSUE THREAD

**Issue by glensc** [smarty-php/smarty#364]
I'm looking a way to get tokens from smarty, something similar to 
[getTags()](http://www.smarty.net/docs/en/api.get.tags.tpl), but with other tokens as well like text nodes.

The intention is  to write external parser to extract `{t attrib="123" attr2='foo bar'}text here{/t}` as tokens by smarty own parser, instead of using regexps on source template file.

Here's example how `getTags` is being used good way externally:
https://github.com/geekwright/Po/blob/v1.0.4/src/PoInitSmarty.php#L189-L218

however that solution does not apply to me because i need the TEXT element from between `t` and `tclose` notes.

**Comment by AnrDaemon** [comment]
I don't quite understand, why YOU want to parse Smarty template?
Why don't you just write a Smarty plugin and Smarty will send everytihing you you ready and parsed?

**Comment by glensc** [comment]
see related links in this issue. i need `{t opts=111}...{/t}` not render actual template.

can you provide example how to get same result with plugin? what is plugin anyway? any docs?

**Comment by AnrDaemon** [comment]
Please read http://xyproblem.info/ before answering my question.
Now, the question: WHY do you want to do this?
What would be the end result for you?

**Comment by glensc** [comment]
looks like you never visited any links given. sad.

[smarty-gettext](https://github.com/smarty-gettext/smarty-gettext) has tool named [tsmarty2c](https://github.com/smarty-gettext/smarty-gettext/blob/1.5.1/tsmarty2c.php) (manual: [tsmarty2c.1](https://github.com/smarty-gettext/smarty-gettext/blob/1.5.1/tsmarty2c.1)), which uses regexps to scan templates for the translations. there are several bugs and features requested ([#1](https://github.com/smarty-gettext/smarty-gettext/issues/1), [#15](https://github.com/smarty-gettext/smarty-gettext/issues/15), [#20](https://github.com/smarty-gettext/smarty-gettext/issues/20)) which i [tried to solve](https://github.com/smarty-gettext/smarty-gettext/pull/16#issuecomment-300573040) with [some code refactoring](https://github.com/glensc/smarty-gettext/commit/9f759cb96ac4bf774655f5d7da5e5d46338f96d0) but decided that that i'll be doing it wrong inventing all moving parts myself and rather use existing components.

so a new project was porn: [smarty-gettext/tsmarty2c](https://github.com/smarty-gettext/tsmarty2c), which attempts to do this properly, using parser not regexp. initial 0.1.0 release target can be seen from the ticket: [#1](https://github.com/smarty-gettext/tsmarty2c/issues/1)

**Comment by AnrDaemon** [comment]
Why should I visit any links? I asked YOU, what YOU want to do with this information.

**Comment by glensc** [comment]
indeed, you shouldn't do anything, you're just trolling me, not helping anybody. the links provide extra information what you may be searching for. for the implementation i provided enough information in initial issue description.

**Comment by AnrDaemon** [comment]
I'm searching for information I asked you to provide.
If you are unable to state clearly, what you want to get done, you most likely don't need it and just wishful thinking.

**Comment by glensc** [comment]
what i want is described in initial description: https://github.com/smarty-php/smarty/issues/364#issue-228272665

if you're unable to help (you are not maintainer!), just stop posting there. thank you.

**Comment by AnrDaemon** [comment]
That answers "how" not "what". See http://xyproblem.info/

**Comment by wisskid** [comment]
Hi @glensc, I see what you were trying to do here and it seems you've already been able to do so on your own. Good job. I don't see a clear use case here for Smarty other than what you have been doing, so closing this issue now.

**Comment by glensc** [comment]
@wisskid, it's a hackish one, mostly works, but unfortunately, it doesn't solve all scenarios needed, i.e when template uses variable assignments and that result inside `{t}{/t}` tags:
- https://github.com/smarty-gettext/tsmarty2c/pull/10

**Comment by glensc** [comment]
@wisskid sadly using internals like that caused breakage since 3.1.35:
- https://github.com/smarty-gettext/tsmarty2c/pull/16

The bisected commit to the breakage is smarty-php/smarty@19ef834

belonging to smarty-php/smarty#582
