### ISSUE TITLE
version 1.3.31 not compatible with PHP 5.2

### ISSUE THREAD

**Issue by aschleifer** [smarty-php/smarty#365]
Hi,

the composer.json for version 1.3.31 states that it is compatible with `php >= 5.2` but it uses the `__DIR__` constant which was introduced in PHP 5.3 (https://github.com/smarty-php/smarty/blob/v3.1.31/libs/Smarty.class.php#L38)

Either the version should be marked as only 5.3 compatible or should not use PHP 5.3 features.

Best regards

**Comment by scottchiefbaker** [comment]
Looks like this will be fixed in the next official release. Good work.

**Comment by uwetews** [comment]
The fix is in the master branch and will later be included in the 3.1.32 release
