### ISSUE TITLE
Capture append as item in associative array

### ISSUE THREAD

**Issue by vbezruchkin** [smarty-php/smarty#366]
Hi guys,

We use Smarty in our opensource CMS and happy with it. If possible, please consider this request to be added to the default version.

make capture append work with associative arrays

So I could pass capture content to a new array element with name as key, for example. 

Thanks in advance.

**Comment by vbezruchkin** [comment]
Or could you please advise how to achieve this? @uwetews 

Thanks in advance.

**Comment by uwetews** [comment]
The named capture buffers can now be accessed as array()by special Smarty variable $smarty.capture.
This extension is now in the master branch and will later be included in 3.1.32

   {capture name='foo'}
        bah
     {\capture}
     {capture name='buh'}
       blar
     {\capture}
     {foreach $smarty.capture as $name => $buffer}
        ....
      {/foreach}
