### ISSUE TITLE
Security Policy problem when create template

### ISSUE THREAD

**Issue by vuongminh** [smarty-php/smarty#367]
When call create template with smarty CLONE:

```php
$smarty->setTemplateDir(['a/b/c']);
$template1 = $smarty->createTemplate($file1, null, null, null, true);
$smarty->setTemplateDir(['d/f/e']);
$template2 = $smarty->createTemplate($file2, null, null, null, true);
```
A security will be have a problem because `smarty` instance in `security` is old => templateDir can not be sync with to `d/f/e` => Exception will be throw because security reason.

Suggestion to add `__clone` method to `Smarty.Class`

```php
public function __clone() {

if ($this->security_policy) {
    $this->security_policy->smarty = $this;
}

}

```

**Comment by vuongminh** [comment]
This issue is custom business because in my custom Smarty class auto enable security in constructor.

**Comment by uwetews** [comment]
This is a tricky use case. Please note the Security does also not allow that you change the $template_dir setting. The following would also fail on the second fetch() when security was enabled.

`
$smarty->fetch('foo.tpl');
$smarty->setTemplateDir(['d/f/e']);
$smarty->fetch('bar.tpl');     // this will fail
`

The following would work:

`
$smarty->fetch('foo.tpl');
$smarty->disableSecurity();
$smarty->setTemplateDir(['d/f/e']);
$smarty->enableSecurity();
$smarty->fetch('bar.tpl');     `

**Comment by vuongminh** [comment]
Thanks for letting me know.
