### ISSUE TITLE
{make_nocache} outputs (un?)compiled code in final HTML output when using multiple includes

### ISSUE THREAD

**Issue by strikernl** [smarty-php/smarty#369]
When using `{make_nocache}` in a template with a parent that was included from another parent, I get unexpected uncompiled Smarty code in the final HTML output.

This is using Smarty **3.1.31**.

Simple test case:

PHP
==
```php
<?php

require('vendor/smarty/smarty/libs/Smarty.class.php');

$tpl = new Smarty();
$tpl->setCaching(Smarty::CACHING_LIFETIME_CURRENT);
$tpl->assign('dir', __DIR__);
$tpl->display(__DIR__ . '/page1.tpl');
```

page1.tpl
==
```smarty
{$var='test'}
{include file="{$dir}/layout.tpl" myvar=$var}
```

layout.tpl
==
```smarty
{include file="{$dir}/layout_base.tpl" myvar2=$myvar}
```

layout_base.tpl
==
```smarty
Hello world
{make_nocache $myvar2}
Bye world
```

Expected output
==
I expect the following output:

```html
Hello world

Bye world
```

Actual output
==
Instead I get:

```html
Hello world
/*%%SmartyNocache:1884390456592e9210e147c0_85763675%%*/<?php $_smarty_tpl->smarty->ext->_make_nocache->store($_smarty_tpl, 'myvar2', array(
   'value' => 'test',
   'nocache' => false,
));?>
/*/%%SmartyNocache:1884390456592e9210e147c0_85763675%%*/
Bye world
```
Misc
==
Interestingly enough, if I put the code from **layout_base.tpl** into **layout.tpl** instead, it does work as expected.

Also, if I insert `<?>` into **layout_base.tpl**, the undesired code also seems to disappear.

I.e.
```smarty
Hello world
{make_nocache $myvar2}
Bye world
<?>
```

Outputs

```html
Hello world

Bye world
<?>
```

**Comment by uwetews** [comment]
The fix is now in the master branch
