### ISSUE TITLE
bug with bugfix "called as callable to allow closures..."

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#370]
Hi @uwetews 
https://github.com/smarty-php/smarty/commit/ef889c79e0b41e780eaa8dc0ab4508f59171abc1
now (3.1.32-dev-11) throws a 
`Uncaught ErrorException: Warning: Parameter 1 to serendipity_smarty_refhookPlugin() expected to be a reference, value given ...`
which has been working ever before.
We have a 
```Smarty
    {capture name="advanced_options"}{$entry_vars.entry|serendipity_refhookPlugin:'backend_display'}{/capture}
```
(_This is not about the capture wrap. We have other places without it too._)
which calls a 
```php
function serendipity_smarty_refhookPlugin(&$eventData, $hook, $addData = null) { ... }
```
with a referenced Parameter.
Is there a way to allow referenced parameters again?

Ian

**Comment by ophian** [comment]
Compiled it looks like such
```php
echo call_user_func_array($_smarty_tpl->registered_plugins[ 'modifier' ][ 'serendipity_refhookPlugin' ][ 0 ], array( $_smarty_tpl->tpl_vars['entry_vars']->value['entry'],'backend_display' ));
```
Adding a reference here will make it work again
```php
echo call_user_func_array($_smarty_tpl->registered_plugins[ 'modifier' ][ 'serendipity_refhookPlugin' ][ 0 ], array( &$_smarty_tpl->tpl_vars['entry_vars']->value['entry'],'backend_display' ));
```
It is an issue of `call_user_func` (and all other calling interpreters used here) since call_user_func passes everything by value.

But I can not see how I could change https://github.com/smarty-php/smarty/blob/ef889c79e0b41e780eaa8dc0ab4508f59171abc1/libs/sysplugins/smarty_internal_compile_private_modifier.php#L52 ff
to follow this, since I already tried the obvious.

**Comment by ophian** [comment]
ping @uwetews Any thoughts? Since I really don't want to check in my workaround every time...

**Comment by AnrDaemon** [comment]
I have an urge to call it your design flaw.
Using pass-by-reference arguments is really not a good idea to return values.

**Comment by uwetews** [comment]
Ian this is a design flaw of your modifier. Note that the Input value of a modifier may not be a variable. It can be any value like function result, literal etc

**Comment by ophian** [comment]
Well, it is what it is and has been working with Smarty for so many years, until you lately switched to use call_user_func(), which is too strict by passing full copy values only, if  not adding the reference sign `array( & %s )`. That is all I said and why I asked to keep it. It is a hook and needs to be referenced to carry on changes.

**Comment by AnrDaemon** [comment]
Remove business logic from templates, save yourself a headache.

**Comment by uwetews** [comment]
As i said before your patch would work only with simple variables. It does break for example modifiers on expressions like

($foo + $bar)|modifier

So using a reference did work before also only in your special use case but not as general solution

**Comment by uwetews** [comment]
As i said before your patch would work only with simple variables. It does break for example modifiers on expressions like

($foo + $bar)|modifier

So using a reference did work before also only in your special use case but not as general solution

See also the documentation about Plugins like
https://www.smarty.net/docs/en/plugins.modifiers.tpl
And others where it is specified that the $value has to be passed by value
