### ISSUE TITLE
HELP upgraded to composer and smarty 3 but cant load smarty

### ISSUE THREAD

**Issue by redimongo** [smarty-php/smarty#373]
This is how I use to start smartyphp

index.php

```
<?php
session_start();
date_default_timezone_set("Australia/Melbourne");
define('SMARTY_DIR',"./");
require('configs/setup.php');
$smarty = new Smarty_Steal();
$smarty->enableSecurity();

?>

```
and in setup.php

```

<?php
define('POWERBY','Mogo');
define('SITEURL',$_SERVER['SERVER_NAME']);

require_once(SMARTY_DIR . 'Smarty.class.php');

class Smarty_Steal extends Smarty {

  function __construct()
  {

    // Class Constructor.
    // These automatically get set with each new instance.

    parent::__construct();

    $this->setTemplateDir('templates/main');
    $this->setCompileDir('templates_c/');
    $this->setConfigDir('configs/');
    $this->setCacheDir('cache/');

    $this->caching = Smarty::CACHING_LIFETIME_CURRENT;
    $this->assign('app_name', 'iPet');
  }

}
?>
```

However this no longer works with smarty3 can someone please tell me the correct composer index.php and setup.php plz

**Comment by jasonlam604** [comment]
What do your logs say? are sure SMARTY_DIR is still set correctly?  What do you mean no longer works, did you upgrade?

**Comment by AnrDaemon** [comment]
Please read https://getcomposer.org/doc/
This is not a Smarty question.

**Comment by uwetews** [comment]
SMARTY_DIR must point to Smarty's libs folder. 
When unsing composer it will be
vendor/smarty/smarty/libs

**Comment by AnrDaemon** [comment]
More specifically, it WILL point to Smarty's `libs` directory, once you initialize your Smarty instance.

**Comment by uwetews** [comment]
Remove
    define('SMARTY_DIR',"./");
in index.php.
Instead include the composer generated autoloader.php which is located in the vendor folder.
    include 'path to/vendor/autoloader.php';

Remove the 
   require_once(SMARTY_DIR . 'Smarty.class.php');
in setup.php.
