### ISSUE TITLE
Composer not downloading composer.json file

### ISSUE THREAD

**Issue by lifewcody** [smarty-php/smarty#378]
Hello,

I just installed composer and installed Smarty 3.1.31 and the composer.json files does not show up.
It it mentioned it pulls from /libs but my directory structure is /vendor/smarty/smarty/[libs]

When I download a ZIP, composer.json isn't in there either

**Comment by JayBizzle** [comment]
It is exclude from export here https://github.com/smarty-php/smarty/blob/master/.gitattributes#L26

**Comment by uwetews** [comment]
Composer installs all packages in under subfolder vendor/vendor name/package name.
For Smarty it is vendor/smarty/smarty. This is how composer works.
The composer.json file needs not to be downloaded for composer installation and is also not needed if you install via a ZIP file. 
That is why it is excluded.
