### ISSUE TITLE
Dead links on Smarty.net website (Resources section)

### ISSUE THREAD

**Issue by dfranco** [smarty-php/smarty#381]
Hello,
Looking for information on how to upgrade from version 2.x to 3.x, I found out that ther's few dead links in Smarty.net website (Resources sections).

**Smarty 2 -> 3 upgrade notes**
http://smarty-php.googlecode.com/svn/trunk/distribution/SMARTY_2_BC_NOTES.txt (404)
**README (from distro)**
http://smarty-php.googlecode.com/svn/trunk/distribution/README
and maybe some others but I haven't checked yet.

Thanks for fixing theses links

Best regards

**Comment by dfranco** [comment]
ping ;)

**Comment by dfranco** [comment]
First link should point to ...
https://github.com/smarty-php/smarty/blob/master/SMARTY_2_BC_NOTES.txt
and obviously, README should point to ...
https://raw.githubusercontent.com/smarty-php/smarty/master/README

I'm pretty you all are on vacations :)

Enjoy !

**Comment by uwetews** [comment]
Monte was out off town.
He will fix the links after he returns ASAP.

**Comment by dfranco** [comment]
Thank you
