### ISSUE TITLE
Deprecated PHP 7.2 functions in Smarty 2.x

### ISSUE THREAD

**Issue by mambax7** [smarty-php/smarty#383]
The each() function is deprecated.
Function create_function() is deprecated

Any chances, it will be fixed in Smarty 2.x ?

**Comment by HMAZonderland** [comment]
A good starting point would be adding PHP7.2 to the Travis testing service.

**Comment by ildar-aim** [comment]
The other point 
  . gettype() will now return "resource (closed)" instead of "unknown type" for
```
aim-server[~/tmp/smarty]$ grep -rl 'unknown type'                
.git/hooks/update.sample
libs/plugins/modifier.debug_print_var.php
aim-server[~/tmp/smarty]$ 
```
https://github.com/php/php-src/blob/php-7.2.0RC1/UPGRADING

**Comment by mambax7** [comment]
Any updates?

**Comment by uwetews** [comment]
I will look into it in the near future

**Comment by uwetews** [comment]
Smarty 2 version 2.6.29 and higher is compatible with PHP versions:
    5.2 and higher
    7.0
    7.1 
    and even the upcomming 7.2
Corresponding PHPUnit tests will be published i the next couple of days.

For Smarty 3.1 I have tested PHP 7.2 compatibility back to version 3.1.24, but I think earlier version should also run.

PHPUnit tests for PHP 7.2 have already been added to the 3.1.32-dev version of Smarty 3.1.

**Comment by mambax7** [comment]
Thank you!

**Comment by mambax7** [comment]
Wait, 2.6.29  is not compatible with PHP 7.2:

> The each() function is deprecated.
> Function create_function() is deprecated

**Comment by uwetews** [comment]
deprecated means that that the functions are still supported but are subject to be removed in a later release. (I think in PHP 7.3)
So 2.6,29 is still compatible with PHP 7.2

**Comment by uwetews** [comment]
Smarty 2   version 2.6.30 without deprecated function is released on github.

Smarty 3.1 is not affected by the changes of 7.2
