### ISSUE TITLE
Default classes for {html_select_date} function

### ISSUE THREAD

**Issue by Chealer** [smarty-php/smarty#384]
Our project has forked version 1.3.4 of html_select_date: https://www.smarty.net/docs/en/language.function.html.select.date.tpl
I would like to return to the upstream version, but our version has changes which I can't achieve with the vanilla version 2. In particular, it adds classes form-control and date to the select elements.

The plugin supports all_extra, day_extra, month_extra and year_extra parameters which allow adding these classes. Unfortunately I see no way to do that by default, so please either:
1. Add classes date and form-control by default
1. Allow setting classes always added to html_select_date

**Comment by wisskid** [comment]
@Chealer why don't you write a [plugin](https://www.smarty.net/docs/en/plugins.functions.tpl) that does what you want? You could even call `smarty_function_html_select_date` with your default parameters so you wouldn't have to duplicate any code.
