### ISSUE TITLE
This sequence doesn't work on last dev 3.1.32-dev (v22), but working on dev 3.1.32-dev (v1)

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#389]
This sequence doesn't work on last dev 3.1.32-dev (v22), but working on dev 3.1.32-dev (v1)

`{{'recipe_status_'|cat:$form_act.recipe_status}|get_trans}`

Result on last dev "3.1.32-dev-22" is 

> {{'recipe_status_'|cat:$form_act.recipe_status}|get_trans}

instead call of function get_trans().

**Comment by uwetews** [comment]
This issue is now solved.

However you have used some recursive Smarty tag call. 
This does create ugly and code with bad performance.

{('recipe_status_'|cat:$form_act.recipe_status)|get_trans}

Use ( ) in the inner
