### ISSUE TITLE
PHP smarty create custom block like if else

### ISSUE THREAD

**Issue by tzookb** [smarty-php/smarty#390]
I would like to create a new smart block like this doc:

https://www.smarty.net/docsv2/en/plugins.block.functions.tpl

But I want my block will ‘else’ like the smarty built in if/else

    {if bool}
         //code
     {else}
          //code
      {/if}

I want to have :

    {secured}
         //code
     {notSecured}
         //code
      {/secured

Any ideas?

**Comment by AnrDaemon** [comment]
```
{if $smarty.server.HTTPS}
…
{else}
…
{/if}
```

**Comment by tzookb** [comment]
thanks @AnrDaemon 

but doing if/else is simple :)

my check is much more complex, and I want to hide it from the template

thats why I want to create my own component

**Comment by AnrDaemon** [comment]
Create a function doing the check and returning a boolean. It will be MUCH simpler than implementing an override for template parser.

**Comment by wisskid** [comment]
Closed because of inactivity.
