### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#391]
Consider the following smarty template.

    {"{if false}"|cat:{'foo'}|cat:"{/if}"}

It is compiled into the following php template.

    ob_start();
    if (false) {
    $_prefixVariable1=ob_get_clean();
    ob_start();
    echo 'foo';
    $_prefixVariable2=ob_get_clean();
    ob_start();
    }
    $_prefixVariable3=ob_get_clean();
    echo (($_prefixVariable1).($_prefixVariable2)).($_prefixVariable3);
    }

When the compiled template is run, it generates two errors: `Notice: Undefined variable: _prefixVariable1` and `Notice: Undefined variable: _prefixVariable2`.

Note: Obviously, the template is not very useful, since I've tried to make a minimal example to show the issue. But I ran into the issue when using some similar logic in a template that was actually useful.

**Comment by uwetews** [comment]
The master branch has been updated to throw a compiler exception for this condition.
