### ISSUE TITLE
Output from false condition

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#392]
Consider the following smarty template.

    {"{if false}"|cat:'foo'|cat:"{/if}"}

It is compiled into the following php template.

    ob_start();
    if (false) {
    $_prefixVariable1=ob_get_clean();
    ob_start();
    }
    $_prefixVariable2=ob_get_clean();
    echo (($_prefixVariable1).('foo')).($_prefixVariable2);
    }

When the compiled template is run, `foo` is output, even though it should only be output when the condition is true (which it isn't).

Note: running this template also generates an error: `Notice: Undefined variable: _prefixVariable1`, but that issue is already reported here: https://github.com/smarty-php/smarty/issues/391

**Comment by uwetews** [comment]
Why don't you use the {eval} tag which has been designed for such use case.

`{eval '{if true}'|cat:'foo'|cat:'{/if}'}`

**Comment by Stadly** [comment]
Thanks. There are probably lots of other ways to do it, but I just wanted to make you aware that this doesn't work. In my opinion, it should either produce a compilation error, or give the expected result of no output.

**Comment by uwetews** [comment]
Yes, I will look into it ASAP

**Comment by AnrDaemon** [comment]
May I ask, what was the original intention of such code?

**Comment by Stadly** [comment]
@AnrDaemon Actually, I just discovered this issue when trying to make a minimal example for issue https://github.com/smarty-php/smarty/issues/391. So there was no intention behind this code other than that.

**Comment by AnrDaemon** [comment]
I've seen both reports, but to me, the interpretation of the given template is far from intuitive.
From my naive PoV, the result should've been literal `{if false}foo{/if}`.

**Comment by Stadly** [comment]
@AnrDaemon Sure, `{if false}foo{/if}` would give the expected result and be much easier to understand.

As I said, I did not actually use this template for anything. Just discovered the issue when making a minimal example.

In order to not mix the issue conversations, please ask on the other issue if you're wondering about the intention of that template.

**Comment by AnrDaemon** [comment]
No, I mean that I expect the OUTPUT of a provided sample to be LITERAL `{if false}foo{/if}`. Not a result of its evaluation as a smarty template.

**Comment by Stadly** [comment]
@AnrDaemon Sorry, then I misunderstood you.

The literal `{if false}foo{/if}` would actually be the output of `{'{if false}'|cat:'foo'|cat:'{/if}'}`. Note the use of `'` instead of `"`, which makes all the difference. It's kind of similar to the difference between `'` and `"` in php.

**Comment by AnrDaemon** [comment]
Makes a little bit more sense, thanks for explanation.

**Comment by uwetews** [comment]
Smarty does allow to embed tags in double quoted strings like
 "something {foo}"
"{if true}foo{/if}"   does work also

In case of block tags opening and closing tags must stay in the same double quoted string otherwise it does break the generated PHP code structure and does not make sense anyway.
So your example should result in a syntax error.

**Comment by uwetews** [comment]
The master branch has been updated to throw a compiler exception for this condition.
