### ISSUE TITLE
"Unexpected "$smarty.block.parent"" in default modifier.

### ISSUE THREAD

**Issue by AnrDaemon** [smarty-php/smarty#393]
```
{block "content"}{$content|default:$smarty.block.parent}{/block}
```
emits
```
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:legacy-page.tpl"  on line 10
"{block "content"}{$content|default:$smarty.block.parent}{/block}"  - Unexpected "$smarty.block.parent" <-- 
  thrown in …/sysplugins/smarty_internal_templatecompilerbase.php on line 10
```

There's a simple workaround, however
```
{block "content"}{$content|default:{$smarty.block.parent}}{/block}
```
but I'm not sure the original behavior is desired.

**Comment by uwetews** [comment]
Never considered that $smarty.block.parent could be used as |default: value.
I will change hat ASAP

**Comment by AnrDaemon** [comment]
Shouldn't any variable reference be acceptable as parameter value?
I've seen similar behavior with cache_id parameters of '{include}' blocks.

**Comment by AnrDaemon** [comment]
And to clarify the original use case, I have the following structure:
#### parent.tpl
```tpl
{block "content"}<div>error message</div>{/block}
```

#### child.tpl
```tpl
{block "content"}{$content|default:$smarty.block.parent}{/block}
```

**Comment by uwetews** [comment]
This is now fixed in the master branch.

Can you explain the behavior with cache_id parameters of '{include}' blocks you have mentioned.

**Comment by AnrDaemon** [comment]
First time I started to port my current project forward, I've tried to dynamically assign cache ids to various includes (mainly various menu blocks), but failed because it would crash on anything but a plain variable.
I'm unable to reproduce it now, and it was so long ago that it may have been fixed already.
If it would resurface anywhere, I will file a new issue.
