### ISSUE TITLE
Unclosed "{if}", when it is actually closed

### ISSUE THREAD

**Issue by Stadly** [smarty-php/smarty#396]
The latest version of the master branch causes the template

    {"{if true}foo{/if}"}

to throw a compiler exception: `"{"{if true}foo{/if}"}" unclosed "{if}" in doubled quoted string`.

This is probably due to the changes concerning https://github.com/smarty-php/smarty/issues/391 and https://github.com/smarty-php/smarty/issues/392, but in my opinion `{"{if true}foo{/if}"}` should be a valid template, even though `{"{if true}"|cat:"foo{/if}"}` should not.

**Comment by uwetews** [comment]
This is now fixed.
