### ISSUE TITLE
new forced unclosed block compiler exception

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#397]
in latest dev 3.1.32-25 version brought in some issues with elder working code.

Hi Uwe

I don't say its an issue or bug, and do only want to make this noticable for your further work,

We had to 2 occurences of exceptions using code like
```smarty
{$link="{if $file.hotlink}{$file.path}{else}{$file.full_file}{/if}"}
```
throwing an `unclosed "{else}" in doubled quoted string <-- ` and now easy to solve by using brackets

and a special one in a modifier

```smarty
{$smarty.const.UNMET_REQUIREMENTS|sprintf:"{if $requirements_failures.{$plug.class_name}.s9y}s9y $plug.requirements.serendipity,{/if} {if $requirements_failures.{$plug.class_name}.php}PHP $plug.requirements.php,{/if} {if $requirements_failures.{$plug.class_name}.smarty}Smarty $plug.requirements.smarty{/if}"}
```
throwing `unclosed "{if}" in doubled quoted string <-- ` which also is avoidable using brackets, 
```smarty
{$smarty.const.UNMET_REQUIREMENTS|sprintf:"({if ($requirements_failures.{$plug.class_name}.s9y)}s9y {$plug.requirements.serendipity},{/if}{if ($requirements_failures.{$plug.class_name}.php)} PHP {$plug.requirements.php},{/if}{if ($requirements_failures.{$plug.class_name}.smarty)} Smarty {$plug.requirements.smarty}{/if})"}
```
but outputs the brackets. (That is ok for me this special case, but might be an unwanted behaviour in other cases.)

Feel free to close,

**Comment by uwetews** [comment]
This is fixed now.

**Comment by ophian** [comment]
👍 works, thanks!
