### ISSUE TITLE
tag {$smarty.block.parent} used outside {block}

### ISSUE THREAD

**Issue by soft4net** [smarty-php/smarty#403]
Smarty version 3.1.31

I have changed default configuration to:
$smarty->left_delimiter  = '[{';
$smarty->right_delimiter = '}]';

I have defined 2 templates dirs:
```
array(2) {
  [0]=> "/var/www/Instances/pozidev/out/Custom/tpl/"
  [1]=> "/var/www/Instances/pozidev/out/Responsive/tpl/"
}
```

Parent template:
/var/www/Instances/pozidev/out/Responsive/tpl/layout/header.tpl
```
[{block name="Layout_Header_HeaderLogo_Wrapper"}]
	<div class="header-logo">
		[{block name="Layout_Header_HeaderLogo"}]
			<a class="navbar-brand" href="[{$oViewConf->getHomeLink()}]">
				<img src="[{$oViewConf->getLogoImageUrl()}]" alt="" />
			</a>
		[{/block}]
	</div>
[{/block}]
```

Child template:
/var/www/Instances/pozidev/out/Custom/tpl/layout/header.tpl
```
[{extends file="file:[1]layout/header.tpl"}]

[{block name='Layout_Header_HeaderLogo'}]
    [{$smarty.block.parent}]
[{/block}]
```

I get an error:

demo_logger.ERROR: Page Process Error:  >> Syntax error in template "file:/var/www/Instances/pozidev/out/Custom/tpl/layout/header.tpl"  on line 5 "[{$smarty.block.parent}]"  tag {$smarty.block.parent} used outside {block} tags  #0 /var/www/Instances/pozidev/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_block_parent.php(65): Smarty_Internal_TemplateCompilerBase->trigger_template_error(' tag {$smarty.b...', 5) #1...

Anyone has any suggestions?

**Comment by uwetews** [comment]
I have tested your code under Smarty versions 3.1.29, 3.1.30 and 3.1.31 and was not able to reproduce your problem.

Are you sure that your template /var/www/Instances/pozidev/out/Custom/tpl/layout/header.tpl is identical to the source provided here?

**Comment by wisskid** [comment]
Closed because of inactivity.
