### ISSUE TITLE
Feature Request: Slots

### ISSUE THREAD

**Issue by pYr0x** [smarty-php/smarty#405]
Is there a way in smarty that is similar to https://laravel.com/docs/5.5/blade#components-and-slots ?
otherwise it would be a nice feature for reuseable components

**Comment by uwetews** [comment]
See block plugin.  https://www.smarty.net/docs/en/plugins.block.functions.tpl


```
// file :  File:     block.alert.php
function smarty_block_alert($params, $content, Smarty_Internal_Template $template, &$repeat)
{
    // only output on the closing tag
    if(!$repeat){
         echo "<div class=\"alert alert-danger\">
                          {$content}
                  </div>";  
    }
}
```

{alert}<strong>Whoops!</strong> Something went wrong!{/alert}

**Comment by pYr0x** [comment]
@uwetews thanks for the feedback
but how can i handle the  `slot`?

in blade where is:
```
<div class="alert-title">{{ $title }}</div>
```
with
 ``
@slot('title')
        Forbidden
    @endslot
```

**Comment by uwetews** [comment]
See  my example and documentation of block plugin.

{block} This text is passed to PHP variable $content in the plugin {/block}

**Comment by pYr0x** [comment]
yes that's clear.
but in the blade example the code looks like
```
<div class="alert alert-danger">
    <div class="alert-title">{{ $title }}</div>

    {{ $slot }}
</div>
```
there is a slot variable called `title`.

if i use your code `{alert}Whoops! Something went wrong!{/alert}`
the result would be:
```
<div class="alert alert-danger">
    <div class="alert-title">{{ $title }}</div>
    Whoops! Something went wrong!
</div>
```
what about the `$title` ?

**Comment by uwetews** [comment]
You can pass the title as parameter to the block plugin. 


{alert title='This is my title'}Whoops! Something went wrong!{/alert}

In the PHP code of the plugin the parameter are passed by the $params array. $params['title']
If you need the value of a template variable in the plugin you must pass it as parameter as well.

{alert title='This is my title' value=$foo}Whoops! Something went wrong!{/alert}

In PHP $params['value']
