### ISSUE TITLE
Smarty 3.1.31 doesn't cache output filters if template contains {nocache}

### ISSUE THREAD

**Issue by mreiche** [smarty-php/smarty#407]
I think there is a bug in  ``smarty_internal_runtime_updatecache.php``
on
```php
if (!$no_output_filter && !$_template->compiled->has_nocache_code &&
            (isset($_template->smarty->autoload_filters['output']) ||
                isset($_template->smarty->registered_filters['output']))
        ) {
            $content = $_template->smarty->ext->_filterHandler->runFilter('output', $content, $_template);
}
```

If the template contains {nocache} code, the results of the output filters are not going to be cached and that is IMHO useless because it leads to loss of the result of probably expensive output filters.

It's fixed by removing the condition
```php
if (!$no_output_filter &&
            (isset($_template->smarty->autoload_filters['output']) ||
                isset($_template->smarty->registered_filters['output']))
        ) {
            $content = $_template->smarty->ext->_filterHandler->runFilter('output', $content, $_template);
}
```

**Comment by uwetews** [comment]
Note that this is intended. 
The definition for output filter is that they run when the page is complete rendered. If a cached page does contain. nocache code the filter will run when the page gets displaye.

**Comment by mreiche** [comment]
Does it make sense then, that the output filters is beeing applied when the cache doesn't contain any nocache code?

**Comment by uwetews** [comment]
This is how it works. The output filter does run before writing the cache file to disk if there is no nocache code.

**Comment by mreiche** [comment]
I made a PR for this feature

**Comment by uwetews** [comment]
I will not include this feature in the standard package.
You can not predigt the results as the input to the filter at that time will be some more or less random mixture of text and code. It's much likely the filters can srew up the look of the page or result in fatal errors as the PHP code will be screwed up. I can forsee tons of support cases.

Also the filter will still run at display time.
you need ($this->cached->has_nocache_code && ! $this->smarty->allow_caching_output_filters)
in line 216  and 247 in Smarty_Internal_Template

**Comment by mreiche** [comment]
Is it possible to introduce another filter type, which is cacheable?

**Comment by uwetews** [comment]
There is no solution as the content for pages with  nocache code is not complete rendered.
So the input  to the filters is at that time not what you expect. The nocache parts of the page can only be rendered at display time.

**Comment by mreiche** [comment]
> The nocache parts of the page can only be rendered at display time.

Thats not the point. I fully unterstand the render pipeline. But the expected result differs from templates that contains nocache code and them they don't.

I'm going to build up an example and get back to you.

**Comment by mreiche** [comment]
[smarty-cache-test.zip](https://github.com/smarty-php/smarty/files/1450660/smarty-cache-test.zip)

Short explanation:
* It includes 2 plugins, {collect} and {output}
* {collect} collects its content during runtime
* {output} outputs a replacement mark and registeres an output filter
* the output filter replaces the mark with the captured content.
* The behaviour differs from {capture}

Tests:
* Run ``php test-fine.php`` or ``php test-fine-without-cache.php`` for the positive results.
* Run ``php test-bad.php`` at least twice, to get the negative result.

**Comment by mreiche** [comment]
Can you give any feedback to the example, please?

**Comment by uwetews** [comment]
The use of an output filter was the wrong aproach. As said befor output filter will run on the final content of a page as it gets displayed.

Use another block plugin to output your collections.

block.output.php
```php
function smarty_block_output(array $params, $content, Smarty_Internal_Template $template, &$repeat) {
    if ($content) {
        return str_replace('%%output%%', join('',$template->tpl_vars['collected']->value),$content);
    }
}
```

base.tpl
```
{output}
Im the base
{block name="body"}

{/block}

{collect}
Affe
{/collect}
{/output}
```

nocache.tpl
```
{extends "./base.tpl"}
{block name="body"}

{collect}
Kuh
{/collect}

Nocache: {$smarty.now nocache}

Animals:
%%output%%

{collect}
Katze
{/collect}

{/block}
```

block.collect.php  can be made simpler
```php
function smarty_block_collect(array $params, $content, Smarty_Internal_Template $template, &$repeat) {
    if ($content) {
        $template->append('collected', $content);
    }
}
```

or you can use {capture} like
```
{capture append='collected'}
Kuh
{/capture}
```

**Comment by mreiche** [comment]
I know that, and that is mostly exactly what I'm doing. But using blocks and {capture} has two disadvantages.

- You can't output before {capture}. Obviously this doesn't work
```smarty
{$smarty.capture.animals}
{capture name="animals"}
Kuh
{/capture}
```

- Another requirement is, that I need to know about the dynamic content beeing displayed. I use the feature of output filters to accomplish that.

```smarty
{load_text_for id=33} {* outputs <!-- text-id-33 --> *}
{load_text_for id=45} {* outputs <!-- text-id-45 --> *}
{load_text_for id=$randomTextId} {* outputs <!-- text-id-99 --> *}
```

The plugin:
```php
$template->append('text_ids', $params['id']);
$template->register_filter('output', $filterCallback);
return '<!-- text-id-'.$params['id'].'-->');
```

The output filter:
```php
$stmt = query('SELECT id,text FROM texts WHERE id IN (:ids)');
$stmt->bind('ids', $template-> tpl_vars['text_ids']);
foreach ($stmt->fetchAll() as $row) {
    $content = str_replace('<!--text-id-'.$row['id'].' -->', $row['text']);
}
return $content;
```
That works well, except for templates including no-cache-code.

**Comment by uwetews** [comment]
Once again output filters are intended and implemented to run on 100% completed rendered pages not just on cached code of pages containing nocache code. This is not a bug. You are trying to use the wrong feature. 
The correct solution is a block plugin which spans the complete template like {output}{/output} in my example.

My example of {capture **append='collected'**}{/capture} is a general solution to collect content in a variable like collected. NOT a named one for use with {$smarty.capture.name}. See [https://www.smarty.net/docs/en/language.function.capture.tpl](url)
