### ISSUE TITLE
Smarty2 $smarty.foreach.<name>.index comparison breaks in smarty 3.1

### ISSUE THREAD

**Issue by jeffreydevreede** [smarty-php/smarty#41]
I am having a problem with upgrading from 3.0 to 3.1, some of our code uses smarty 2 style foreach loops. The comparison of the indexes is breaking.

This works in smarty 3.0 but breaks in 3.1:
```php
{foreach from=['foo', 'bar', 'baz'] key="key" item="value" name="foobar"}
	{$smarty.foreach.foobar.index|var_dump}
	{if $smarty.foreach.foobar.index > 1}
		{$smarty.foreach.foobar.index|var_dump}
	{/if}
{/foreach}

Output in 3.0: int(0) int(1) int(2) int(2)
Output in 3.1: int(0) int(1) int(1) int(2) int(2)
```

I've also noticed that adding brackets around the index is a workaround for the problem.
```php
{if ($smarty.foreach.foobar.index) > 1}
```

This is probably due to the fact that it compiles to the following code (`null > 1`).
Without brackets:
```php
<?php if ((isset($_smarty_tpl->tpl_vars['__foreach_foobar']->value['index']) ? $_smarty_tpl->tpl_vars['__foreach_foobar']->value['index'] : null > 1)) {?>
```
With brackets:
```php
<?php if ((isset($_smarty_tpl->tpl_vars['__foreach_foobar']->value['index']) ? $_smarty_tpl->tpl_vars['__foreach_foobar']->value['index'] : null) > 1) {?>```

**Comment by uwetews** [comment]
The patch is now in dev-master. It will be included in 3.1.24 which will be released very soon.
