### ISSUE TITLE
smarty compiler changed?

### ISSUE THREAD

**Issue by s4l1h** [smarty-php/smarty#411]
I have legacy code https://gist.github.com/s4l1h/3e6ac443e2c65d16e52f3fbc99ac52fa
Work under Smarty Version 3.0.9.
But not work 3.1.*

I wanna upgrade smarty version for php7.
But this code not working.

**3.1.32-dev-35**
![Smarty 3.1.32-dev-35](https://i.gyazo.com/e18a4015d04387e9c2a9371ae7262a80.png)

**3.0.9**
![Smarty 3.0.9](https://i.gyazo.com/d021f4f0ad039335aab6f268ebf16169.png)

[Smarty 3.0.9](https://www.smarty.net/files/Smarty-3.0.9.zip) 
[Smarty 3.1.31](https://github.com/smarty-php/smarty/archive/v3.1.31.zip)

**Comment by uwetews** [comment]
Internals have changed between Smarty 3.0 and 3.1
Plugins must assign variables at the template object, not smarty object.

function.run.php
```php
function smarty_function_run($params, $template)
{
   // pass template object
    call_user_func($params['method'],$template);
}
```

```php
function addVariable($template)
{
    $template->assign("variable", "from run");
}
```
