### ISSUE TITLE
Clean up www.smarty.net or move to Github pages

### ISSUE THREAD

**Issue by DanielRuf** [smarty-php/smarty#413]
In the right side there are links to some weird russian websites.

And everyone can edit the FAQ and other parts.

I guess the website isn't really maintained anymore.
I highly recommend switching to GitHub pages for the documentation and move the forums to GitHub issues and so on.

No one should be able to edit the website without any ok from project owners.

**Comment by gpsbabel** [comment]
Several of the blocks on https://www.smarty.net/ are pretty clearly hacked even beyond the vandalism of the Wiki style pages.  It sends a bad message to Smarty users when the Smarty site gets hacked. Is there a vulnerability in Smarty itself? Is the version of Smarty being distributed trustable or has it been replaced, too?

**Comment by mohrt** [comment]
The Smarty WIKI has been (temporarily) unlinked. I do not own that site and it appears to no longer be maintained. As for the links on smarty.net, they are known sponsored links that use Smarty in their own capacities. I agree some look questionable, I allow a small level of control of the text, but I assure you the site is not hacked. If you have a specific link in question you can PM me.

**Comment by uwetews** [comment]
I get McAfee risk warnings for

 <http://www.weddingdresstrend.com/> Weddingdresstrend.com

 <http://www.weddingdresstrend.com/> discount wedding dresses 

 

 

 

Von: Monte Ohrt [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. November 2017 03:31
An: smarty-php/smarty <smarty@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [smarty-php/smarty] website hacked? (#413)

 

The Smarty WIKI has been (temporarily) unlinked. I do not own that site and it appears to no longer be maintained. As for the links on smarty.net, they are known sponsored links that use Smarty in their own capacities. I agree some look questionable, I allow a small level of control of the text, but I assure you the site is not hacked. If you have a specific link in question you can PM me.

**Comment by DanielRuf** [comment]
Imho the website should be hosted with GitHub pages to also use the docs pages.

So far it seems like other people can have some control on the links and contents which is not directly monitored.

This does not produce a high trust in the whole project.

**Comment by DanielRuf** [comment]
Bump.

**Comment by wisskid** [comment]
Try searching for https://duckduckgo.com/?q=smarty+gettags

**Comment by DanielRuf** [comment]
> Try searching for [duckduckgo.com/?q=smarty+gettags](https://duckduckgo.com/?q=smarty+gettags)

Hi, my initial issue is about the website with spam and other suspicious URLs. It seems this project is dead.

**Comment by wisskid** [comment]
@DanielRuf I know, the suspicious URLs don't look good. That was my point with adding the duckduckgo link. The suspicious URLs even show up in the search results. Smarty is not dead, however.

**Comment by mohrt** [comment]
I have isolated the links to the home page, those browsing docs won't have to see them. I am contemplating shutting down forums and just use github issues, it has been more of a hassle than help as of late. Over time I'll be cleaning up links, but they are paid ads even though they are not pretty looking.
