### ISSUE TITLE
load multiple files (config load)

### ISSUE THREAD

**Issue by gtraxx** [smarty-php/smarty#415]
Hi , if I load multiple files with the same name (my.conf) they are ignored
Yet they are not in the same folder

Best Regards

**Comment by uwetews** [comment]
Please provide some example code.
Which Smarty version?

**Comment by gtraxx** [comment]
Hi, With last version :)
example : 
$smarty->addConfigDir(component_core_system::basePath().'/plugins/test/i18n/');
$smarty->configLoad('public_local_fr.conf');
This works fine but if I use it twice the second is ignored

Best Regards

**Comment by uwetews** [comment]
Note that Smarty::addConfigDir() does append the new directory to the array of folders to be searched.
If 'public_local_fr.conf' is present in more than one folder your Smarty::configLoad() will load it from the first folder containing the file.

I your case I assume that you had loaded 'public_local_fr.conf' already from the default folder, but it will now find same file first again. 

You have two options:
```php
$smarty->setConfigDir(component_core_system::basePath().'/plugins/test/i18n/');
$smarty->configLoad('public_local_fr.conf');
```
in which the new folder will be the only one to be searched

or
```php
$smarty->addConfigDir(component_core_system::basePath().'/plugins/test/i18n/');
$smarty->configLoad('[1]public_local_fr.conf');
```
In the later case the index [1] does force the loading from the second folder of the internal config_dirs array.
