### ISSUE TITLE
when content too big preg_replace 

### ISSUE THREAD

**Issue by anassrakibi** [smarty-php/smarty#417]
I get a white page when the content is too big. After Debugging I found that the problem is:

`$content .= preg_replace('/(<%|%>|<\?php|<\?|\?>|<script\s+language\s*=\s*[\"\']?\s*php\s*[\"\']?\s*>)/',"<?php echo '\$1'; ?>\n", $curr_split);` in smarty_internal_runtime_updatecache.php.A quick fix for this would be to add `{nocache} `in the template. But for the other preg_replace in smarty_internal_runtime_codeframe.php couldn't find any quick fix. The $output should be split , preg_replaced and finally merged again

**Comment by uwetews** [comment]
The fix is now in the master branch and will later be included in 3.1.32
