### ISSUE TITLE
v3.1.31 AND short-circuiting error

### ISSUE THREAD

**Issue by olmunkaido** [smarty-php/smarty#418]
`
{if !empty($foo) && !empty($foo->bar())}{/if}
`

Provides an error: "Fatal error: Uncaught Error: Call to a member function bar() on null"

This works fine in v3.1.30.

**Comment by uwetews** [comment]
This is a duplicate see https://github.com/smarty-php/smarty/issues/347
The fix is already in the master branch and will be included in the 3.1.32 release
