### ISSUE TITLE
3.1.24 raise "too many shorthand attributes"

### ISSUE THREAD

**Issue by remicollet** [smarty-php/smarty#42]
While 3.1.23 was ok, since update to 3.1.24 some template are borken 

     Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "smarty/templates/rpmphp/zoom.tpl"
     on line 71 "<td>{if $p->repo_main neq $prev}<strong>{$p->repo_main}</strong>{/if}</td>"
     too many shorthand attributes <-- thrown in /usr/share/php/Smarty/sysplugins smarty_internal_templatecompilerbase.php on line 71

Looks like a regression.

**Comment by remicollet** [comment]
Notice, switching to {if $p->repo_main != $prev} seems to workaround this issue.

**Comment by uwetews** [comment]
Grr, I had a typo  neg instead of neq And just this was missing in the Unit test.

The patch is in dev-master

**Comment by mkrauser** [comment]
I have the same error after upgrading to 3.1.24, but without any typo: 

```
Syntax error in template "ist.tpl" on line 95 "{if $keyword neq ''}" too many shorthand attributes
```

The exact same template worked without any problems in prior smarty versions. With != it also works.
