### ISSUE TITLE
the problem of update smarty compile file of v3.1.31

### ISSUE THREAD

**Issue by spierman** [smarty-php/smarty#421]
I got a problem of smarty,when I update the php code from svn,the smarty does not check compile and recompile the source file,I have check the source code of smarty,I found a function filemtime,this fuction will cache the result,you should use function clearstatcache to get the latest reesult.wish you response.

**Comment by uwetews** [comment]
The file status cache is not the problem,as the cache is valid only within the current running script. So clearstatcache is not needed.
From which version did you update Smarty to 3.1.31?
Or did you update other PHP code?
