### ISSUE TITLE
Please create a 3.1.32 or 3.2 interim/bugfix release

### ISSUE THREAD

**Issue by tom2tom** [smarty-php/smarty#425]
I've read the comments below about work on smarty 4, in reply to a similar request for a fresh release.
A new major version may be in the works, but some of us would prefer to get the benefits of the last year or so into production systems, nowish. Project admins tend to be a bit conservative, often prohibit using smarty from git. Without an interim 3.x release, we may be waiting a year or so to see fixes get into production systems.

**Comment by kristian-b** [comment]
Same wish here :)

**Comment by nadorator** [comment]
Same needs here it is becoming urgent as Smarty 3.1.31 is not compatible with php 7.0 example: 
preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead on line 77 in /vagrant/src/libs/Smarty/sysplugins/smarty_internal_resource_file.php

**Comment by eth8505** [comment]
@nadorator we've been using Smarty 3.1.29 with PHP 7.1 for about a year now, no problems there. Looking at the current codebase on github, there isn't even a preg_replace IN smarty_internal_resource_file, could you check if you're using an up2date smarty version please?

**Comment by uwetews** [comment]
Smarty 3.1.32 is now released
