### ISSUE TITLE
smarty.block.parent without nested parents

### ISSUE THREAD

**Issue by hlb-schmidt** [smarty-php/smarty#427]
i'm really lost with `{$smarty.block.parent}`. first i thought (as your examples only show one block) that `{$smarty.block.parent}` will only copy that single parent block, but it seems it copies also all the parents parents...

for example, this `index.tpl`:
```
{block name="foo"}
	Foo
	{block name="bar"}
		Bar
	{/block}
{/block}
```

outputs:
```
Foo Bar
```

and extending it with `index-new.tpl`:
```
{extends "index.tpl"}
{block name="foo"}
	Zap
	{block name="bar"}
		{$smarty.block.parent}
		Nib
	{/block}
{/block}
```

outputs:
```
Zap Foo Bar Nib
```

but what i thought/expected it to output:
```
Zap Bar Nib
```

the above example was produced with smarty `3.1.11`.

and with latest (at the time of writing) smarty `3.1.31` i get an error:
```
Fatal error: Uncaught --> Smarty: inheritance: illegal {$smarty.block.parent} or {block append/prepend} used in parent template '/home/vagrant/play/parentsmarty/template/index-new.tpl' block 'bar' <-- thrown in /home/vagrant/play/parentsmarty/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php on line 226
```

so now i'm even more confused.

- is it a bug or feature that `{$smarty.block.parent}` returns also nested parents?
- is `{$smarty.block.parent}` not supported with nested blocks anymore (with `3.1.31`)?
- and most importantly, is there any way to get the content of only the parent block? (and only that block, not parents of that block)

ps. got my test case here https://github.com/hlb-schmidt/parentsmarty

**Comment by uwetews** [comment]
Please note that child templates should not contain nested blocks, but the replacements of single {block} tags in the parent template.

index.tpl
```php
{block name="foo"}
    {block name="buh"}
        Foo
    {/block}
    {block name="bar"}
        Bar
    {/block}
{/block}
```
index-new.tpl:
```php
{extends file="index.tpl"}
{block name="buh"}
    Zap
{/block}

{block name="bar"}
    {$smarty.block.parent}
    Nib
{/block}
```
