### ISSUE TITLE
section properties only available when using $smarty.section-syntax

### ISSUE THREAD

**Issue by eposjk** [smarty-php/smarty#428]
When you take the [example 7.71](https://www.smarty.net/docs/en/language.function.section.tpl#idp36316128) from the documentation and reduce it to
```smarty
{section name=row loop=$rows}
{$rows[row.index_next]}
{/section}
```
`row.index_next` is undefined for current Smarty versions - so you get no output.
If you use `$smarty.section.row.index_next` instead it works:
```smarty
{section name=row loop=$rows}
{$rows[$smarty.section.row.index_next]}
{/section}
```
Its also possible to use the short syntax and add the $smarty.section-syntax as comment - `row.index_next` is defined in this case:
```smarty
{section name=row loop=$rows}{*$smarty.section.row.index_next*}
{$rows[row.index_next]}
{/section}
```

Tested and reproduced with Smarty 3.1.29, Smarty 3.1.31 and current Smarty 3.1.32-dev.
Also tested with Smarty 3.1.21 - that version does not have this problem.

**Comment by uwetews** [comment]
The fix is now in the master branch and will later be included in 3.1.32
