### ISSUE TITLE
include template issue

### ISSUE THREAD

**Issue by greevex** [smarty-php/smarty#43]
Last version of the Smarty has broken our logic. It renders only last "included template" inside "foreach" cycle. In the example you can see, that template files may be different, but it renders all items as last item.

TEMPLATE

    {foreach from=$mapper->getMap() key="fieldKey" item="field"}
        <tr>
            <td>{$field.name}</td>
            <td>{include file="forms/type_{$field.formType}.tpl" fieldName=$fieldKey field=$field}</td>
        </tr>
    {/foreach}
    
RESULT ON version 3.2.21 (and it's expected result)

    <tr>
        <td>name1</td>
        <td>    
            <select id="name1" name="item[name1][]" class="form-control" required="">
                <option value="1">Yes</option>
                <option value="0">Don't know</option>
                <option value="-1">No</option>
            </select>
        </td>
    </tr>
    <tr>
        <td>name2</td>
        <td><input type="text" class="form-control" id="name2" name="item[name2]" value=""></td>
    </tr>
    <tr>
        <td>name3</td>
        <td><input type="text" class="form-control" id="name3" name="item[name3]" value=""></td>
    </tr>

RESULT ON version 3.2.24 (actual and wrong result)

    <tr>
        <td>name1</td>
        <td><input type="text" class="form-control" id="name3" name="item[name3]" value=""></td>
    </tr>
    <tr>
        <td>name2</td>
        <td><input type="text" class="form-control" id="name3" name="item[name3]" value=""></td>
    </tr>
    <tr>
        <td>name3</td>
        <td><input type="text" class="form-control" id="name3" name="item[name3]" value=""></td>
    </tr>

**Comment by uwetews** [comment]
The fix is now in dev-master

**Comment by greevex** [comment]
Thank you very much!
