### ISSUE TITLE
Problem with setPluginsDir for Smarty Debug tag

### ISSUE THREAD

**Issue by juangacovas** [smarty-php/smarty#430]
File: smarty_internal_debug.php at Line 214

In order to use the debug tag properly with mixed directory separators under windows, I had to change:
```
$debObj->setPluginsDir(is_dir(__DIR__` . '/../plugins') ? __DIR__ . '/../plugins' : $smarty->getPluginsDir());
```

to
```
$debObj->setPluginsDir($smarty->getPluginsDir());
```

Anyway, isn't better to just use the getPluginsDir method to resolve the plugins dir?

**Comment by uwetews** [comment]
What problem did you get? Mixed separators should not create a problem.
getPluginsDir() should be the last resort as user may have changed the plugins dir setting not to use the distribution folder at all. Debug needs special modifier from it.

**Comment by wisskid** [comment]
Closed because of inactivity.
