### ISSUE TITLE
Call to undefined function smarty_modifier_truncate 3.1.32-dev

### ISSUE THREAD

**Issue by robo2bobo** [smarty-php/smarty#431]
My problems continue with version 3.1.32-dev. Since the problem with the "caching" tag persists, I found a work-around by using "inline" as I mentioned in bug issue #429 but immediately I came upon another bug.

I have a template that looks like this:
```smarty
{block name=info}
{strip}

	{nocache}
		{foreach ...}
			{$data|truncate:11:""}
		{/foreach}
	{/nocache}

{/strip}
{/block}
```

The above template runs fine the FIRST time only. It generates the proper compiled template_c file and the proper cache file. But any subsequent view of the page that loads the cached file, generates the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function smarty_modifier_truncate() in /www/smarty/cache/info^1^aafa239c033db78d9c02f360d2b63bd1749f804a.info.html.php:195
Stack trace:
#0 /www/smarty/libs/sysplugins/smarty_template_resource_base.php(130): content_5ac1d6e58b8ad8_71671140(Object(Smarty_Internal_Template))
#1 /www/smarty/libs/sysplugins/smarty_template_cached.php(137): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /www/smarty/libs/sysplugins/smarty_internal_template.php(201): Smarty_Template_Cached->render(Object(Smarty_Internal_Template), false)
#3 /www/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#4 /www/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), 'info|1', NULL, NULL, 1)
#5 /www/index.html(130): Smarty_Internal_TemplateBase->display('extends:templat...', 'info|1')
#6 {main}
  thrown in /www/smarty/cache/info^1^aafa239c033db78d9c02f360d2b63bd1749f804a.info.html.php on line 195, referer: https://...
```

I tried to do some tests, I copied the smarty/libs/plugins/modifier.truncate.php file into my own smarty/plugins directory but that didn't make a difference. I also renamed the function to "truncateTest" and modified my template to call it accordingly, but that also made no difference.

Interestingly, other modifiers that I call seem to work fine, like "escape".

This bug looks similar to bug issue #346 which reports the same error, but there is no solution to the problem, someone mentions that it is a cache problem but no further information is provided about why the cache is causing undefined function errors.

Thank you.

**Comment by uwetews** [comment]
Please use the latest update of 3.1.32-dev from the master branch which was modified on 26.03.2018
and did address possible problems with plugin loading from within {block} and {function} tags.
