### ISSUE TITLE
[3.1.32] Smarty::compileAllTemplates ignores `$extension` parameter

### ISSUE THREAD

**Issue by caugner** [smarty-php/smarty#437]
We run the following in a CI job:

```php
<?php
$smarty = new Smarty();
$smarty->setCompileDir(...);
$smarty->setTemplateDir(...);


$smarty->compileAllTemplates('.tpl', true);
```

This has always worked fine.

However, after upgrading from 3.1.31 to 3.1.32, `compileAllTemplates` reports several errors in files without the `.tpl` extension.

**Comment by caugner** [comment]
cc @uwetews

**Comment by uwetews** [comment]
The fix is  now in the master branch
