### ISSUE TITLE
version number contains DEV

### ISSUE THREAD

**Issue by spaceone** [smarty-php/smarty#44]
You are providing a tar.gz which has the string DEV in it's version number instead of 3.1-24.
in Smarty.class.php:
 * @version   3.1-DEV

Another typo:
* Try loading the Smmarty_Internal_Data class
→ s/Smmarty/Smarty/

**Comment by uwetews** [comment]
Please note that by default the Download Zip button on github is linked to the dev-master version. 
To get a zip file of a stable version select the tag like 3.1.24 at the branch button on the left hand side.  or get it here https://github.com/smarty-php/smarty/tags.

I just see you referenced not not the SMARTY_VERSION constant but a version reference in the comment which was auto generated by SVN while Smarty was on google code before. We will fix that.
