### ISSUE TITLE
Smarty creates new compile files every request in 3.1.31+

### ISSUE THREAD

**Issue by mattatobin** [smarty-php/smarty#440]
I have been experiencing an issue where Smarty 3.1.31+ seems to create compile files out of control when `$smarty->display` is fed a string.

In 3.1.30 smarty wouldn't generate a new compile file unless the string fed to display was materially different. This regression may not be limited to a string but I have not tested this.

**Comment by uwetews** [comment]
What did you mean exactly? The string resource type?

```php
$smarty->display('string:foo');
```
Will only recompile on each call if $smarty->force_compile was set to true.

**Comment by mattatobin** [comment]
Then there is a regression. What is the default for force comple? Reverting back to 3.1.30 with no code changes on how I use smarty gives the correct behavior as described. 3.1.31 and 3.1.32 recomple every request.

**Comment by uwetews** [comment]
Nothing has changed. The default of force_compile is false. And I can not reproduce your problem.
Can you give an example of the string/display call? Which OS, which PHP version?

**Comment by mattatobin** [comment]
PHP 7.0-remi
CentOS 7
Nginix

https://github.com/Pale-Moon-Addons-Team/phoebus/blob/TRUNK/components/site/addonSite.php#L36

**Comment by uwetews** [comment]
Question: why do you need a compile_id in your display('string:') call?
How does $GLOBALS['strRequestPath'] and the compile_dir path typically look like?
If the string gets recompiled it does overwrite exacly same compiled file?
Does 3.1.31 and 3.1.32 create identical compiled file path? Does it recompile just the string template or maybe also other subtemplates if the problem shows up?
Does the PHP script and the file system run on same server? Identical system clock?

**Comment by wisskid** [comment]
Closed because of inactivity.
