### ISSUE TITLE
Annotation for addDefaultModifiers is incorrect

### ISSUE THREAD

**Issue by Synchro** [smarty-php/smarty#441]
A very minor thing, but it gets flagged by my IDE.

[This line](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatebase.php#L23) in the `Smarty_Internal_TemplateBase` class declares a method called `addDefaultModifier` in an annotation, when it's actually called `addDefaultModifiers`, and the implementation is in [here](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_method_adddefaultmodifiers.php).

**Comment by uwetews** [comment]
It's now fixed in the master branch
