### ISSUE TITLE
smarty uses iterator_count() on un-rewindable iterator, even if it isn;t needed

### ISSUE THREAD

**Issue by quamis** [smarty-php/smarty#443]
In Smarty_Internal_Runtime_Foreach

, the $total variable is computed even when not needed. This might be slow (I use iterators for very large resultsets) and it will also break one-way iterators (iterators that can only be iterated over once, not having a way of implementing the rewind() method).

I have attached a testcase. The rewind function should only get called once in this case
[smarty bug testcase.zip](https://github.com/smarty-php/smarty/files/1999519/smarty.bug.testcase.zip)

To fix this, please take a look at the attached patch:
[Smarty_Internal_Runtime_Foreach.zip](https://github.com/smarty-php/smarty/files/1999534/Smarty_Internal_Runtime_Foreach.zip)

Expected output: 
![expected](https://user-images.githubusercontent.com/2966084/39981208-3a61494a-5758-11e8-8b97-568a200cfe44.png)

Real output:
![real](https://user-images.githubusercontent.com/2966084/39981221-48ab96ae-5758-11e8-8c63-214939997f93.png)

**Comment by uwetews** [comment]
This is now fixed in the master branch and will later be included in 3.1.33
Please note that the total property is required and will be computed also when you are using some other propteries like last and show

**Comment by quamis** [comment]
Any ideea when 3.1.33 will be released?

**Comment by uwetews** [comment]
Within the next 14 days


quamis <notifications@github.com> schrieb am Do. 17. Mai 2018 um 15:36:
