### ISSUE TITLE
Question/issue $smarty->escape_html

### ISSUE THREAD

**Issue by peon501** [smarty-php/smarty#444]
ok if I have $smarty->escape_html = true;
,but I dont want escape specific $smarty->assign('my_array_without_escape',$my_array); what should I do?
because I dont want to write nofilter for specific array elements

**Comment by uwetews** [comment]
It's currently only possible to use the nofilter option flags. 
It's on my TODO list for some future release to assign() variables with a corresponding flag.

**Comment by peon501** [comment]
I hope :)

**Comment by peon501** [comment]
Any news?
