### ISSUE TITLE
We should support using dot inside name custom plugins

### ISSUE THREAD

**Issue by vuongxuongminh** [smarty-php/smarty#446]
Currently we can register plugin name having dot `.` but when using it an exception will be thow.

Ex:

```php

$smarty->registerPlugin('block', 'product.cart', [new class {
	
	public function handler(){
		return 123;
	}
	
}, 'handler']);

```

In tpl

```php

{product.cart}

     An exception will be thow

{/product.cart}

```

We should support using dot `.` inside name of custom plugins for create a struct of large plugins have multi level, like a modular.

**Comment by vuongxuongminh** [comment]
Should i make a PR update lexer?

**Comment by wisskid** [comment]
The [docs](https://www.smarty.net/docs/en/plugins.naming.conventions.tpl) say plugins cannot have dots: 
> name should be a valid identifier; letters, numbers, and underscores only

I don't see a benefit of allowing dots that justifies the cost of doing so.
