### ISSUE TITLE
$smarty->configLoad($file); doesn't work in version 3.1.33-dev-5

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#451]
$smarty->configLoad($file); doesn't work in version 3.1.33-dev-5

> Fatal error: Uncaught --> Smarty: Unable to load config 'file:trans_fr.conf' <-- thrown in ....\lib\smarty\sysplugins\smarty_template_compiled.php on line 96

Before I had version 3.1.32-dev-31. Afte rupdate I get this error

Config folder is defined: 
$smarty->setConfigDir(TEMPLATES_DIR . 'configs');

**Comment by yourchoice** [comment]
I see that the problem is just on my local windows, where path start with E:/sitename/.

If I remove the "E:/" and let just "/sitename/" then working. Version 3.1.32 worked in this way.

Can be updated to work in both ways?

**Comment by ophian** [comment]
see https://github.com/smarty-php/smarty/commit/115e178884f511d436d0952f16b3b905c78878fa#comments

**Comment by ophian** [comment]
Fix confirmed OK! In the meantime for dev-6/7, I did the following, which also worked well
```php
    public function _realpath($path, $realpath = null)
    {
        $nds = array('/' => '\\', '\\' => '/');
        // WinOS prep
        $path = str_replace(array($nds[DIRECTORY_SEPARATOR], DIRECTORY_SEPARATOR . '.' . DIRECTORY_SEPARATOR), DIRECTORY_SEPARATOR, $path);
```
