### ISSUE TITLE
{strip} doesn't remove white-spaces when built-in functions are used

### ISSUE THREAD

**Issue by asaveljev** [smarty-php/smarty#455]
**A white-space in {foreach}:** 
```
{strip}
	<span>1</span>
	{foreach [1] as $i} {/foreach}
	<span>2</span>
{/strip}
```

The result with a not stripped white-space:
```
<span>1</span> <span>2</span>
```

**A white-space in {if}:**
```
{strip}
	<span>3</span>
	{if 1} {/if}
	<span>4</span>
{/strip}
```

The result with a not stripped white-space:
```
<span>3</span> <span>4</span>
```

**White-spaces between tags:**
```
{strip}
	<span>5</span>


	<span>6</span>
{/strip}
```

The result with correctly stripped white-spaces:
```
<span>5</span><span>6</span>
```

**Comment by AnrDaemon** [comment]
`{strip}` is a compile-time instruction.

**Comment by wisskid** [comment]
This behaviour seems totally consistent with the [documentation](https://www.smarty.net/docs/en/language.function.strip.tpl):
> Anything within {strip}{/strip} tags are stripped of the extra spaces or carriage returns at the beginnings and ends of the lines before they are displayed. This way you can keep your templates readable, and not worry about extra white space causing problems.
