### ISSUE TITLE
Custom plugin invocation compiles into garbage

### ISSUE THREAD

**Issue by AnrDaemon** [smarty-php/smarty#457]
```
[01-Jul-2018 00:17:42 Europe/Moscow] PHP Parse error:  syntax error, unexpected '^' in …/tmp/smarty/templates/b06b264876f1056e83fb1c88d2b34b1f696d52d2_0.file.menu-sectionTree.smarty.cache.php on line 38
```

The relevant code is
```
    $tpl->registerPlugin('function', 'svgImage', [new SvgImage('/img/cat/icon'), 'render'], true, [
      'name', 'id', 'class', 'style', 'fallback'
    ]);
```
invoked as `{svgImage name=$item.icon}`, which somehow compiles into

```
echo call_user_func_array( $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['svgImage'][0], array( array('name'=>^#^.var_export($_smarty_tpl->tpl_vars[^#^item^#^]->value[^#^icon^#^],true).^#^),$_smarty_tpl ) );
```

**Comment by wisskid** [comment]
Can't reproduce this, is this already fixed?

**Comment by AnrDaemon** [comment]
I can reproduce it with 3.1.34. Will try to create a testcase.

**Comment by wisskid** [comment]
Thanks! Could it be locale related, then?

Simon

**Comment by AnrDaemon** [comment]
I wonder. how's that possible.
This is run under default system locale, which is configured as "en_US.UTF-8".

**Comment by AnrDaemon** [comment]
https://github.com/AnrDaemon/test-001/tree/smarty-457

**Comment by wisskid** [comment]
The difference between my test and yours causing this bug is `$smarty->setCaching(\Smarty::CACHING_LIFETIME_SAVED);` (so not locale, indeed...)
I'll see if  I can figure out what's going on here.

**Comment by wisskid** [comment]
playground/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_registered_function.php:60

**Comment by wisskid** [comment]
Okay, I figured this one out. You somehow found an impossible combination of parameters to `$smarty->registerPlugin($type, $name, $callback, $cacheable = true, $cache_attr = null)`.

If you leave `$cacheable` true, as you did, then `$cache_attr` should be meaningless. `$cache_attr` is only interesting if `$cacheable` is false. So this should be easy to fix.
