### ISSUE TITLE
count generate waring in PHP 7 if there array is null

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#459]
Warning: count(): Parameter must be an array or an object that implements Countable in ....

`{$c = $var|count}`

**Comment by tchalvak** [comment]
This is related to the php 7.x updates where count() can no longer be passed nulls.  Unfortunately the only workaround that I am aware of is to also add a `!empty($var)` as well, or ensure the var is always countable, even if it is an empty array.  Not sure if that will work for your situation.

**Comment by uwetews** [comment]
count() has been changed with PHP 7.2. See http://php.net/manual/en/migration72.incompatible.php
It does only accept arrays or objects that implement Countable.
For that reason the |count modifier fails if the variable is unassigned or has a value of NULL.

The workaround is

```php
{$c = $var|default:array()|count}
```
