### ISSUE TITLE
Fatal error: Cannot unset string offsets in vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_block.php on line 337

### ISSUE THREAD

**Issue by Gamesh** [smarty-php/smarty#46]
smarty v.3.1.24

Stack trace:
```
10	87.0320	22877960	Smarty->fetch( string(17), null, null, null, bool, bool, bool )	.../ViewRenderer.php:84
11	87.0320	22882448	Smarty_Internal_Template->render( bool, bool, bool )	.../Smarty.class.php:824
12	87.0380	22909816	Smarty_Template_Compiled->render( object(Smarty_Internal_Template)[1804] )	.../smarty_internal_template.php:246
13	87.0380	22910424	Smarty_Template_Compiled->process( object(Smarty_Internal_Template)[1804] )	.../smarty_template_compiled.php:199
14	87.0380	22910768	Smarty_Template_Compiled->compileTemplateSource( object(Smarty_Internal_Template)[1804] )	.../smarty_template_compiled.php:152
15	87.0415	22958584	Smarty_Internal_TemplateCompilerBase->compileTemplate( object(Smarty_Internal_Template)[1804], ???, ??? )	.../smarty_template_compiled.php:226
16	87.0434	22966104	Smarty_Internal_SmartyTemplateCompiler->doCompile( string(4272), bool )	.../smarty_internal_templatecompilerbase.php:396
17	87.0689	24537000	Smarty_Internal_Templateparser->doParse( long, string(1) )	.../smarty_internal_smartytemplatecompiler.php:114
18	87.0689	24537584	Smarty_Internal_Templateparser->yy_reduce( long )	.../smarty_internal_templateparser.php:2398
19	87.0689	24537792	Smarty_Internal_Templateparser->yy_r57( )	.../smarty_internal_templateparser.php:2303
20	87.0689	24538008	Smarty_Internal_TemplateCompilerBase->compileTag( string(10), array(0), ??? )	.../smarty_internal_templateparser.php:1585
21	87.0690	24538368	Smarty_Internal_TemplateCompilerBase->compileTag2( string(10), array(0), array(0) )	.../smarty_internal_templatecompilerbase.php:462
22	87.0690	24538416	Smarty_Internal_TemplateCompilerBase->callTagCompiler( string(10), array(0), array(0), ???, ??? )	.../smarty_internal_templatecompilerbase.php:495
23	87.0690	24541352	Smarty_Internal_Compile_Blockclose->compile( array(0), object(Smarty_Internal_SmartyTemplateCompiler)[1814], array(0), null, null )	.../smarty_internal_templatecompilerbase.php:761
```

**Comment by Gamesh** [comment]
v3.1.21 does not have this bug, works fine.

**Comment by SvenRtbg** [comment]
You should probably add the (template or other) code that triggers this error.

**Comment by uwetews** [comment]
Please provide example code

**Comment by uwetews** [comment]
I can't reproduce the problem. Do you get it on all templates?

**Comment by Gamesh** [comment]
for the time being just in one, i'll provide the templates tomorrow

**Comment by Gamesh** [comment]
i can't seem to isolate this issue, it's produced by mail tamplate that is rendered using fetch() and before each render clearAllAssign() is issued. tried to reproduce it but currently i can't, it appears to happen only some times. I will try to find how to reproduce it all of the time.
Template:
https://gist.github.com/Gamesh/3cd1a0926227fdceee0e

**Comment by uwetews** [comment]
The provided template does not contain any {bock}{/block}  tags.
The compiler failed while compiling an inheritance template on {bock}{/block} tags.
Did you modify template files which caused a recompilation?

**Comment by Gamesh** [comment]
the provided template has one block tag
```
                                {block "mail_body"}
                                    {$message}
                                {/block}
```
or am i missing something ?

no, i didn't modify any files, i might have cleared the cached versions ant templates_c folder

**Comment by uwetews** [comment]
Sorry I did not see the {block} tag. Clearing the templates_c folder does explain the recompile. Can you show your template structure? Where did you include the failing template? Inside other block tags?

**Comment by uwetews** [comment]
Even if the root cause of the error message is still unknown I added some extra check to avoid it. 
The fix is now in dev-master

**Comment by Gamesh** [comment]
that just is the weird thing this template is not included as parent template anywhere. It is just used as standalone template and the block tags were there for future template extending. So even if some other templates change they should not cause this template to recompile as it remains the same and is not being extended or included anywhere, and has not changed for a long time.

**Comment by uwetews** [comment]
It did recompile because you cleared templates_c .
Also now the error is clear to me. Caused by a standalone template with {block} tags.
For now either remove the {block} tags until next release or install dev-master.

**Comment by Gamesh** [comment]
ok, thanks for the fix. i've downgraded to smarty 3.1.21 for now, that was the last version that worked without errors with this template, i'll just wait for the next stable release
