### ISSUE TITLE
!empty not working on PHP 5.3.28/29 | Compatible?

### ISSUE THREAD

**Issue by richardeth** [smarty-php/smarty#460]
Compiler create a !empty($variable) to if (!($variable === false) which is true on an "" empty string.

I'm not sure if this is the best way but fixed it for me. Composer says it's PHP 5.2+ but it isn't?

file: smarty_internal_templatecompilerbase.ph

line 589:
```
if ($parHasFuction && version_compare(PHP_VERSION, '5.5.0', '<')) {
```
I added 
```
if ($parHasFuction && version_compare(PHP_VERSION, '5.4.0', '<')) { //custom
    return $func_name . '(' . $parameter[ 0 ] . ')';  //custom
} else 
```
So it looks like this
```
if ($parHasFuction && version_compare(PHP_VERSION, '5.4.0', '<')) { //custom
    return $func_name . '(' . $parameter[ 0 ] . ')';  //custom
} else if ($parHasFuction && version_compare(PHP_VERSION, '5.5.0', '<')) {
```

**Comment by wisskid** [comment]
This is very much related to #453 and will be fixed in https://github.com/smarty-php/smarty/pull/567
