### ISSUE TITLE
Nofilter is executed on sub tags (string concatenation)

### ISSUE THREAD

**Issue by fbett** [smarty-php/smarty#464]
Configuration:
$smarty->addDefaultModifiers('escape');

`$test = '<strong>test</strong>';`

Examples:
1. {$test}
2. {$test nofilter}
3. {nl2br("{$test}") nofilter}

Results:
1. `&lt;strong&gt;test&lt;/strong&gt;` (Expected)
2. `<strong>test</strong>` (Expected)
3. `nl2br("<strong>test</strong>");` (Unexpected)

Problem:
Nofilter is executed on sub tag {$test} within {nl2br("{$test}") nofilter}, but that's unexpected.
It would be expected, that nofilter is not executed on the sub tag.

This allows XSS-attacks!

From what i have seen, the problem occurs, because the full tag "{nl2br("{$test}") nofilter}" is compiled at once. I would suggest to split sub tags and to compile them first.

**Comment by wisskid** [comment]
No, that would not be the expected behavior. You cannot escape all intermediate results, because you wouldn't know what you'd end up with. Only the outermost result is escaped (or it is not, if `nofilter` is present).
