### ISSUE TITLE
assign - Function has standard value for second parameter

### ISSUE THREAD

**Issue by Sironheart** [smarty-php/smarty#466]
The assign function is using the following declaration

`function assign($tpl_var, $value = null) { ... }`

I believe that there is no reason why there should be the possibility to not a assign a specified value! also there would be a clear Linting Error at PHPStorm, Sublime, etc if you do not give it a second parameter.

**Comment by AnrDaemon** [comment]
Your wording making it unclear, what are you complaining about.
The documentation clearly states that if first parameter is an array, the second parameter is not used.
