### ISSUE TITLE
getTags clarification

### ISSUE THREAD

**Issue by gbrault** [smarty-php/smarty#468]
I have a vast collection of .tpl files not written by me and would like to create some documentation about it.
So I tried the getTags function, which is of great help, but for simple print variable, I don't get the variable name i.e: all entries with private_print_expression are followed by an empty array.

Any idea?

**Comment by wisskid** [comment]
getTags does indeed not provide any information on the variable being printed in a simple `{$var}` field. Might be useful.

test.tpl
```
            {foreach $categories as $category}
				<li>
                    {$category->name}
				</li>
            {/foreach}
```

test.php
```
<?php
require_once './vendor/autoload.php';
$smarty = new Smarty();
$smarty->assign('categories', array());

// create template object
$tpl = $smarty->createTemplate('test.tpl');

// get tags
$tags = $smarty->getTags($tpl);

print_r($tags);
```

**Comment by wisskid** [comment]
Support for `getTags` has been dropped since v5.
