### ISSUE TITLE
{strip}{/strip} Is almost useless as no meaniful impact

### ISSUE THREAD

**Issue by henryejemuta** [smarty-php/smarty#470]
I still have all new line after strip and a lot of white spaces... I need a possible workaround

**Comment by JercSi** [comment]
My solution to remove {strip}{/strip} from templates few years ago - not sure if it is still working:

```php
// autoload filters
$smarty = new Smarty();
$smarty->autoload_filters = array('pre' => array('stripFilter'));
```

plugins/prefilter.stripFilter.php:
```php
function smarty_prefilter_stripFilter($source, $template)
{
    // copied from smarty_internal_templateparser.php :: yy_r13()
    return preg_replace('![\t ]*[\r\n]+[\t ]*!', '', $source);
}
```

**Comment by henryejemuta** [comment]
Thanks for the prompt response @JercSi  just confirmed it on Smarty 3 Doc now:

`$this->registerFilter('output','minifyOutput');//Within my custom Smarty object`

`function minifyOutput($source, Smarty_Internal_Template $template)
{`
    `   return preg_replace('![\t ]*[\r\n]+[\t ]*!', '', preg_replace("/<!--#.*-->/U",'',$source));`
`}`

actually was looking to minify output... and type output works great

**Comment by uwetews** [comment]
Please note that {strip}{/strip} and a pre filter do process the template source before compiling. They don't affect the output of any Smarty tags like variables, plugins etc.

An output filter does run on the complete rendered page. However it does add some extra CPU time on each page call if caching is not enabled or the page does contain nocache sections or tags.
