### ISSUE TITLE
Compiled templates all error after upgrading to v3.1.32 from v3.1.31 in php 7.2

### ISSUE THREAD

**Issue by tchalvak** [smarty-php/smarty#471]
I have a suite of tests that compiles smarty templates.  When I run the tests in smarty v3.1.31, the tests return errors that I expect, based on the phpunit tests.  When I upgrade to the latest version of smarty, version v3.1.32, the code appears to stop recognizing the smarty templates as correct php code, spewing back a lot of errors like:

```
<br>        ------>Error: Syntax error in template "file:/srv/ninjawars/deploy/templates/compiled/b667a14250d4584904c36430a869fcd4c42c0106_0.file.email.assistance.account.tpl.php"  on line 41 "<?php if (!$_smarty_tpl->tpl_vars['confirmed']->value) {?>"  - Unexpected "?"<br><br>
<br>        ------>Error: Syntax error in template "file:/srv/nw/deploy/templates/compiled/16a9746f61d4a4e80ae1e71a28b04e4df28f0cd4_0.file.messages.nav.tpl.php"  on line 25 "if ($_smarty_tpl->tpl_vars['pages']->value > 1) {?>"  - Unexpected "?"<br><br>
```
(and 40-50 more Unexpected "?" errors. )

I have just recently upgraded to php 7.2, and found that smarty was using each() which was deprecated, and was throwing deprecated warnings, so I upgraded my smarty version from v3.1.29 to latest v3.1.32, but found that the very latest minor version fails rather catastrophically.  Somehow the templates compiled by that version seem to no longer be recognized as valid php, or no longer recognize valid php end tags.

I will attach the compiled template that errors on a syntax error.  It looks like otherwise correct php code to me, if someone messily nested, so it's hard to tell.  Almost invariably it is the `{?>` character combination that shows errors.
[b667a14250d4584904c36430a869fcd4c42c0106_0.file.email.assistance.account.tpl.php.txt](https://github.com/smarty-php/smarty/files/2280515/b667a14250d4584904c36430a869fcd4c42c0106_0.file.email.assistance.account.tpl.php.txt)

Is smarty being tested in php 7.2 at this time?

**Comment by uwetews** [comment]
This is really strange. Smarty v3.1.32 does pass all its PHPUnit tests using PHP 7.2.8.
Also your provided compiled template file does run at my place without any problems.
Which PHP version have you installed?

**Comment by tchalvak** [comment]
As I said above, it is with PHP 7.2 , php-fpm with Nginx. This issue can be closed as I have worked around it, if I experience the problem again when I upgrade in the future I will reopen.

**Comment by rgjoyce** [comment]
can you please advise what the fix is?
I have several web apps using smarty templates and they all show this each deprecated error.
and now with php 7.3 each is completely gone I think.
so, for all new clients, my templates will all fail?
