### ISSUE TITLE
empty variable in IF block  3.1.29

### ISSUE THREAD

**Issue by tahonaPL** [smarty-php/smarty#474]
In smarty there is a bug. When i assign variable to display it in **if** block then variable is missing. 

CODE:

```
{$blockCls="col-lg-12 window mar-bottom-20"}
 <div class="{$blockCls} ">
  SHOW A
 </div>

{if count($var) > 0}
 <div class="{$blockCls} ">
  SHOW B
 </div>
{/if}
```

Resolve to cache with: 

 NOTE:  {$blockCls="col-lg-12 window mar-bottom-20"} - this is missing

```
<div class="col-lg-12 window mar-bottom-20 ">
  SHOW A
</div>

   <?php if (count($_smarty_tpl->tpl_vars['var']->value]) > 0) {?>
            <div class="**<?php echo $_smarty_tpl->tpl_vars['blockCls']->value;**?> "> //WAT WAT 
  SHOW B
 </div>

```

Output from cache:

```
 <div class="col-lg-12 window mar-bottom-20 ">
  SHOW A
 </div>
 <div class="">
  SHOW B
 </div>
```

Missing class value. 

Newest smarty version is notworking for me so did not test it.

**Comment by uwetews** [comment]
Your variable $var is assigned as nocache variable and this is causing that the whole {if} ... {/if} section is executed in nocache mode. As your local assigned variable $blockCls is not as nocache it's not available when the cached template is rendered.

Solution:
```php
{$blockCls="col-lg-12 window mar-bottom-20" nocache}
```
But why did you assign $blockCls at all and don't use "col-lg-12 window mar-bottom-20" in both cases?

**Comment by tahonaPL** [comment]
well if You have 20 divs of "col-lg-12 window mar-bottom-20"  and in one moment You want to ad one more class or remove "window" You do it in one place.   Yeah of course I can use find/replace IDE function but at some point it always something goes wrong with this method :D .

Anyway. I think that all execution of my {$blockCls} var which is a cached variable, should behave as cached variable. Am I right?

**Comment by uwetews** [comment]
All variable variable which are not assigned in your script with $smarty->assign() or in your template in cached sections by ($foo=... } without the nocache attribute will not exists when the cached page is called
