### ISSUE TITLE
inheritance: illegal '{$smarty.block.parent}' used in child template 'template_name' block 'input'

### ISSUE THREAD

**Issue by maxprihodko8** [smarty-php/smarty#479]
Nested blocks are not working now and there is no workaround for the legacy code. 
```
{block name='field'}
    {block name="input"}
        {$smarty.block.parent}
    {/block}
{/block}
```

**Comment by wisskid** [comment]
Please refer to the [docs](https://www.smarty.net/docs/en/language.function.block.tpl) to see how smarty.block.parent is supposed to be used.
