### ISSUE TITLE
INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

### ISSUE THREAD

**Issue by oasfuyou** [smarty-php/smarty#480]
INI directive 'mbstring.func_overload' is deprecated since PHP 7.2,pelase add a new release

**Comment by AnrDaemon** [comment]
I'd like to raise a question [against calling `mb_internal_encoding()` in constructor](https://github.com/smarty-php/smarty/blob/master/libs/Smarty.class.php#L678) at all to begin with.

In all cases of using `mb_**` functions I've found they are used with explicit specification of `Smarty::$_CHARSET`, and I can see clear disadvantage of such hidden behavior change for an entire application.
