### ISSUE TITLE
Smarty_Security check can be bypassed

### ISSUE THREAD

**Issue by xqc2000** [smarty-php/smarty#485]
you have untrusted parties editing the templates eg via ftp。Even if you Enable security，the attacker can disable it in the templates content.  just like this {$name=$smarty.template_object->disableSecurity()} {include "file://etc/passwd"}

**Comment by uwetews** [comment]
You can disable access to the special variable $smarty.template_object in security by

```public $disabled_special_smarty_vars = array('template_object');```
