### ISSUE TITLE
Master Branch contains security fixes since months and no release was issued

### ISSUE THREAD

**Issue by Hibbelharry** [smarty-php/smarty#487]
While researching another bug I stumbled across commits made the current release 3.1.32, which is tagged already some month ago. Days after release security related bugfixes were committed, but no follow up release was made, so that all people using smarty happily require a not-fixed version of Smarty, at least if your application runs on any linux webserver (which is the majority of webservers out there!).

I think this is a severe misconception.

Please issue a new release of Smarty. I think release strategy should also be discussed between Smarty devs, at least how to handle security related stuff.

**Comment by uwetews** [comment]
I agree and will change strategy in future.
Because of some personal reasons things got delayed.
3.1.33 has now been released
