### ISSUE TITLE
Large template parsing error in smarty 3.1.33  

### ISSUE THREAD

**Issue by Visualq** [smarty-php/smarty#488]
Wrapping the svg template file in the attachment [svg.tpl.txt](https://github.com/smarty-php/smarty/files/2378185/svg.tpl.txt) with `{literal}{/literal}` throws the following exception:

```
Fatal Error
Unexpected input at line 1:
in file: /var/www/smarty/sysplugins/smarty_internal_templatelexer.php at line: 912
```

It appears that it has trouble handling the amount of content inside the {literal}{/literal}. Without the literal it throws a similar error:

```
Fatal Error
Unexpected input at line1:
in file: /var/www/smarty/sysplugins/smarty_internal_templatelexer.php at line: 368
```
It works fine if you remove a line or 2 or use a previous version of Smarty. (Note: I upgraded from 3.1.31 -> 3.1.33 so I haven't tested 3.1.32)

**Comment by uwetews** [comment]
This fix is now in the master branch.

In 3.1.32 and 3.1.33 you could as workaround split the large plain text section somewhere in the middle with
```php
... {/literal}{literal}...
```
