### ISSUE TITLE
The older version 3.1.21 allowed {$var.{$arr.index}}. The v. 3.1.24 seems generate error 

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#49]
The older version 3.1.21 allowed {$var.{$index}}. The v. 3.1.24 seems generate error.

Maybe see that not sense to use {$var.{$index}}, because can be just {$var.$index}. I saw that {$var.{$arr.index}} working...

Also, seems to be a problem with "@" used for array functions. I know that not necessary use of # in smarty > 3.1 , but just in vers 3.1.24

**Comment by uwetews** [comment]
The  {$var.{$index}} problem is now fixed in dev-master.

But what kind of problem did you see with "@"?  please provide an example.
