### ISSUE TITLE
Modifier is applied on whole expression (3.1.32)

### ISSUE THREAD

**Issue by getdatakick** [smarty-php/smarty#491]
Since smarty 3.1.32 the modifier is applied on whole expression:

```php
{1 + array(1, 2, 3)|count}
```
The result of this expression used to be 4. Now it tries to apply `count` function on the result of `1+array(1,2,3)`, which throws Fatal error: Unsupported operand types on php 7.2.

**Comment by doclucas** [comment]
Seems to be still the case on 3.1.33

**Comment by uwetews** [comment]
The fix is now in the master branch and will later be included in 3.1.34
