### ISSUE TITLE
Release note of v2.6.31 is sooner than PHP7.2.0

### ISSUE THREAD

**Issue by vuongmn** [smarty-php/smarty#493]
In change log of Smarty v2.6.31( https://github.com/smarty-php/smarty/blob/Smarty2/ChangeLog). It wrote:
2017-11-03
* replace functions deprecated in PHP 7.2

But official release of PHP 7.2.0 is 2017-11-30( http://php.net/ChangeLog-7.php#7.2.0). 
It's very strange. So do we have any reason here ?
**Is Smarty v2.6.31 being tested completely  in PHP 7.2?**

**Comment by uwetews** [comment]
Please note that the list of deprecated functions was known long time before the official 7.2.0 release.
The required changes have been tested with older PHP versions and some 7.2 pre-releases.
The support of Smarty 2 is limited to bug fixes. There is no guarantee that we can update Smarty for upcoming PHP 8. We will test against PHP 7.3 which will be released in the nearer future.
