### ISSUE TITLE
wordwrap do not work if sentence contains an accent (or special char)

### ISSUE THREAD

**Issue by rodolamule** [smarty-php/smarty#495]
Exemple : 
`{assign var="ss" value="Mise à disposition rgerug iugheirgh ierg furrrrei ze zef ezf zef"}
<b>{$ss|wordwrap:20:"<br />\n":true}</b>
`

Due to "à", wordwrap function will have no effect.

**Comment by uwetews** [comment]
I can not reproduce your problem. I assume that your template was not stored in UTF-8 encoding
