### ISSUE TITLE
{insert} not works when caching is enabled and included template is present

### ISSUE THREAD

**Issue by wyssman** [smarty-php/smarty#496]
If {insert name="test"} is in main template and other template is included into main template (while caching is enabled) - I see in browser part of php code like:
"/*%%SmartyNocache:8801992865bb72d3e5b40d0_75775836%%*/smarty; if (!is_callable('smarty_insert_test')) require_once ..."
instead of output of {insert}.

But {insert} works well when no templates is included or when caching is disabled.

This bug appeared in version 3.1.28 (3.1.27 is ok) and is still in master.

I've attached a test case - needs to be unpacked in distro folder.
[bug.zip](https://github.com/smarty-php/smarty/files/2449775/bug.zip)

Hope my test files will be useful to fix this problem :)

**Comment by uwetews** [comment]
This is now fixed in the master branch and will later be included in 3.1.34
