### ISSUE TITLE
setCacheLifetime after isCached is ignored

### ISSUE THREAD

**Issue by m-hume** [smarty-php/smarty#497]
Consider the following
`test.tpl`
```
{$smarty.now}
```

`test.php`
```
$smarty = new Smarty();
$smarty->setCaching(Smarty::CACHING_LIFETIME_SAVED);

if( $smarty->isCached('./test.tpl') ){
	die('test.tpl is cached');
}
else{
	$smarty->setCacheLifetime(1);
	$smarty->display('./test.tpl');
}
```

Expected behaviour: refreshing the page every second should show the current unix timestamp
Actual behaviour: first page load shows unix timestamp, further refreshes show "test.tpl is cached" (at least for the next hour)

It seems that the call to `isCached` affects the `'cache_lifetime'` stored in the cache file (3600 rather than the expected 1).
Calling `setCacheLifetime` before `isCached` stops the issue, although its not what i would call expected behaviour.

**Comment by AnrDaemon** [comment]
```php
$template = $smarty->createTemplate('./test.tpl')->setCacheLifetime(1);

if($template->isCached() ){
	die('test.tpl is cached');
} else {
	$template->display();
}
```

**Comment by AnrDaemon** [comment]
Sorry, my code wasn't exactly correct in writing. Please see the abovementioned testcase for details.
