### ISSUE TITLE
Template rendering unexpected result since Smarty 3.1.31

### ISSUE THREAD

**Issue by noam-k** [smarty-php/smarty#500]
I have some PHP code that is being tested with PHPUnit. One test in particular fails once I use Smarty version of 3.1.31 (or higher). The failing part is attached.

[smarty-version-test.zip](https://github.com/smarty-php/smarty/files/2495322/smarty-version-test.zip)

When 'Smarty/Smarty.class.php' (in the PHP require statement) points to a smarty of version 3.1.30, the (expected) result is as follows:
`nkritenberg@d-2-174:~$ php smarty-version-test.php`
`begin-a#b#c#d#end`

But when 'Smarty/Smarty.class.php' points to a smarty of version 3.1.31 or higher, the separator is being ignored:
`nkritenberg@d-2-174:~$ php smarty-version-test.php`
`begin-abcdend`.

I tried with PHP 5 and PHP 7.

**Comment by uwetews** [comment]
This bug is now fixed in the master branch and will later be included in 3.1.34
