### ISSUE TITLE
registerPlugin("function",..) stop working on version 3.1.32 using PHP 5.6.37 - reference parameter

### ISSUE THREAD

**Issue by fmancardi** [smarty-php/smarty#504]
I've registered
 **$this->registerPlugin("function","lang_get", "lang_get_smarty");**

**Function definition** 
function lang_get_smarty($params, &$smarty)
Important second parameter is a **REFERENCE**

This has been tested with Smarty version Smarty-3.1.13 using PHP 5.6.37 and PHP 7.2.8

When trying to upgrade to 3.1.33, the registered functions seems not to be called.
After reading several posts on your forum, my choice was to give a look to generated code.

then ( compiled template excerpt)
/* Smarty version 3.1.31
...
<?php echo lang_get_smarty(array('var'=>'labels','s'=>'login_name,password,btn_login,new_user_q,login,demo_usage,lost_password_q,oauth_login'),$_smarty_tpl);?>

**While on 3.1.32**
<?php echo **call_user_func_array(** $_smarty_tpl->smarty->registered_plugins[Smarty::PLUGIN_FUNCTION]['lang_get'][0], array( array('var'=>'labels','s'=>'login_name,password,btn_login,new_user_q,login,demo_usage,lost_password_q,oauth_login'),$_smarty_tpl ) );?>

After a lot of tests and confusion, it seems that on 5.6.37 when using call_user_func_array() if one of the parameters is a reference the call does not work.

It will be great if you can confirm this issue.

regards

**Comment by fmancardi** [comment]
There is a similar issue, that's why my choice is not to open a new one.
I've registered an 'output' filter to deal with Cross-Site Request Forgery (CSRF), but again the function definition has a reference
**function smarty_csrf_filter($source, &$smarty) {** 

in this case the implementation does use the smarty object, then changing function prototype to
**function smarty_csrf_filter($source, $smarty) {** 

solved the issue.

**Comment by fmancardi** [comment]
Hi, I've done new tests changing from**&$smarty** to **_$smarty_** in all my filters definition, and things seem to work ok.
Probably the approach I've used was wrong but worked anyway under certain PHP versions and conditions.

**Comment by uwetews** [comment]
With Smarty 3.1 Plugins, Filters etc should no longer use references for the Smarty object. However the register.... functions did still allow this by mistake in earlier 3.1. versions.

So changing from**&$smarty** to $smarty is the right way to deal with it.

**Comment by halmai** [comment]
I agree, updating your old code is the appropriate way to fix it. 

However, with php 7.3.14, the old version also works well so be careful when you deploy the code to php 7.0 and tested on newer php. This misalignment is always risky but in this case it can bite you.
