### ISSUE TITLE
Some numeric error on PHP 7.2

### ISSUE THREAD

**Issue by blue-eyed-devil** [smarty-php/smarty#511]
Error: [2] A non-numeric value encountered
in /var/www/test/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 589

**Comment by blue-eyed-devil** [comment]
its "dev-master": "3.1.x-dev" from 18th of November. I tried to update to the latest when seen it first time. It's related to PHPO 7.2 stricter rules. More classes have it. The easiest solution is to convert to integer by adding (int) if value is a string containing number. or change to 0 if string is empty.

**Comment by blue-eyed-devil** [comment]
Ok I sorted it, was my mistake.
I changed :
`$smarty->assign('Pictures', $pictures, 'true');`

to:
`$smarty->assign('Pictures', $pictures, true);`

**Comment by wisskid** [comment]
Closed because of inactivity.
