### ISSUE TITLE
Uncaught exception 'Exception' with fetch()

### ISSUE THREAD

**Issue by robo2bobo** [smarty-php/smarty#513]
I am still using smarty 3.1.29 because every time I try to upgrade to 3.1.33 or the latest code in github, I receive the following error:

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Unexpected input at line1: <' in /home/user/public_html/smarty/libs/sysplugins/smarty_internal_templatelexer.php:368

Stack trace:
#0 /home/user/public_html/smarty/libs/sysplugins/smarty_internal_templatelexer.php(279): Smarty_Internal_Templatelexer->yylex1()
#1 /home/user/public_html/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php(123): Smarty_Internal_Templatelexer->yylex()
#2 /home/user/public_html/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(481): Smarty_Internal_SmartyTemplateCompiler->doCompile('{block name=con...', true)
#3 /home/user/public_html/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(405): Smarty_Internal_TemplateCompilerBase->compileTemplateSource(Object(Smarty_Internal_Template), NULL, NULL)
#4 /home/user/public_html/smarty/libs/sysplugins/smarty_template_compiled.php(184): Smarty_Internal_Templ in /home/user/public_html/smarty/libs/sysplugins/smarty_internal_templatelexer.php on line 368

```

Here is how I use fetch, which loads an html template with a block:

```php
$smarty->fetch('extends:template.html|string:base64:'.$id)
```

I am not sure if its a bug in smarty or if something changed in the fetch command, but everything works fine in smarty 3.1.29.

**Comment by juangacovas** [comment]
Same here but upgrading PHP version helped. Can't provide exact version
bump right now

**Comment by robo2bobo** [comment]
Unfortunately, upgrading is not an option. I'm using CentOS 7, which uses php 5.4, supported by RedHat (via RHEL) with regular patches and backports. Long-term support is for 10 years, so there is little change to upgrade to a newer version for various stability reasons.

I guess newer versions of smarty use some kind of feature that doesn't exist in php 5.4, I will try to compare the templatelexer.php file and see if I can figure out what is broken.

**Comment by ophian** [comment]
> Unfortunately, upgrading is not an option. I'm using CentOS 7, which uses php 5.4

Ridiculous! :grinning: Sticking to 5.4 is **not** a good idea since it EOL support for security fixes was about mid 2015.
https://www.linuxtechi.com/install-php-7-centos-7-rhel-7-server/
http://php.net/supported-versions.php
