### ISSUE TITLE
Output buffer not cleaned on Throwable error

### ISSUE THREAD

**Issue by ErwinSteffens** [smarty-php/smarty#514]
We have an Error in one of our views like this:

`Call to a member function getSettings() on null`

This is thrown as an `Error` which extends `Throwable`. The error handling in Smarty only catches `Exception` for cleaning the output buffer:
https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatebase.php#L249

This messes up our error template output. I think you should catch `Throwable` on this point.

**Comment by wisskid** [comment]
By now, the approriate link would be https://github.com/smarty-php/smarty/blob/support/3.1/libs/sysplugins/smarty_internal_templatebase.php#L249
