### ISSUE TITLE
Strip {strip} not stripping well if there have a function 

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#519]
{strip} not stripping well if there have a function 

php 7, smarty 3.1.34-dev-7

```
{function name='test'}
	...
	{$p_url}
{/function}
```

**Comment by AnrDaemon** [comment]
`{strip}` done **at compile time**!

**Comment by wisskid** [comment]
Closed because of inactivity. Also, there doesn't seem to be a question here.
