### ISSUE TITLE
Smarty fails with any plugin that ends in 'close'

### ISSUE THREAD

**Issue by calguy1000** [smarty-php/smarty#52]
##Sample code:
<?php
require_once('smarty-3.1.24/libs/Smarty.class.php');
function test_plugin($params,$template) {
    return 'Test Plugin Called';
}

$smarty = new Smarty;
$smarty->registerPlugin('function','testclose','test_plugin',false);
$tpl = '{testclose}';
$smarty->display('string:'.$tpl);
?>

##Error:
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "4f51b386251639c28dd52ffe53b55c127b1faa69"  on line 1 "{testclose}" unknown tag "testclose" <-- 
  thrown in /nfs/u1404/smarty_test/smarty-3.1.24/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 1

##Note:
Changing the plugin name to 'testfoo'  and the call in the template to {testfoo} provides the expected output.

**Comment by Stricted** [comment]
looks like https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatecompilerbase.php#L521 is the problem

echo substr($tag, - 5); above this line says 'close'
if you look at line https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatecompilerbase.php#L638 you see that the 'close' will be removed and then it will trigger the error becouse your plugin has the name 'testclose' and not 'test'

i think @uwetews need to check this

**Comment by uwetews** [comment]
Smarty does use tag names ending with close internally to  handle closing tags. Like {/foo} => fooclose.
You should not use it as a standalone plugin name.

It allows for example to write compiler plugins for block tags usage. One compiler plugin 'foo' and one for 'fooclose'  to use {foo} .... {/foo}.

**Comment by calguy1000** [comment]
Well, the problem is that older versions of smarty (2.x) didn't do that...
and there are valid cases where people have written smarty plugins for
various third party packages using smarty with the name 'close' in them,
and those plugins are years old...... maybe they could have used a block
tag, but they didn't.   i.e: tags like {form_open} or {form_close} or
{togglearea_open} and {togglearea_close}

And now those plugins cause an error in smarty 3.

Is it possible to change smarty in the next version to use a delimiter
like:  "_smartyclose" or something that is less likely to conflict with
valid tag names.

**Comment by uwetews** [comment]
If  I do that Smarty 3 users which have written compiler  plugins for closing tags will get errors.
What I can do is to handle tags ending with "_close" like normal plugins tag.

**Comment by uwetews** [comment]
This problem is now resolved.
Function plugins can now have names ending with 'close'.
The fix is in dev-master and will later be included in the 3.1.28 release.
