### ISSUE TITLE
502 Bad Gateway on huge {assign}

### ISSUE THREAD

**Issue by dertin** [smarty-php/smarty#520]
Hello, I think I have this problem when sending a large amount of data to the View.
https://www.smarty.net/forums/viewtopic.php?p=88947&sid=6410edf26a62086219c6bfda3c5206fe

How can I see if I really have this problem? And what should I configure to change the limit on my Nginx server?

Smarty version 3.1.33.

**Comment by wisskid** [comment]
You could try `ini_set('memory_limit', '2048M');` or higher in your php-code. For nginx, please see the [nginx docs](https://nginx.org/en/docs/).
