### ISSUE TITLE
Function with array return

### ISSUE THREAD

**Issue by laudaicat92** [smarty-php/smarty#521]
> `    <img class="py-0 my-0" src="/assets/img/flags/{ht::config('lang')[ht::user()->getLanguage()][1]}">`

This function **ht::config('lang')** return an array. It show error:

> 
`Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:index.tpl" on line 48 "<img class="py-0 my-0" src="/assets/img/flags/{ht::config('lang')[ht::user()->getLanguage()][1]}">" - Unexpected "[", expected one of: "}" <-- thrown in smarty\libs\sysplugins\smarty_internal_templatecompilerbase.php on line 48`

It work fine if i pass array var instead
> `    <img class="py-0 my-0" src="/assets/img/flags/{$g_config['lang'][ht::user()->getLanguage()][1]}">`

**Comment by AnrDaemon** [comment]
Assign the result of function call to a variable.
Smarty does not support that level of AST parsing.
