### ISSUE TITLE
Error locating custom modifier plugin

### ISSUE THREAD

**Issue by benkeen** [smarty-php/smarty#523]
I've used Smarty on a project of mine for years (formtools.org) and found it consistently solid. But I've run into a curious problem on a user's server which I've been unable to solve, or even figure out how to continue debugging. Smarty doesn't recognize a custom plugins directory - I get a generic `Fatal error: Call to undefined function smarty_modifier_custom_format_date() in ...` error (that's the name of my modifier plugin. I've triple-checked the folder is correct, and getPluginsDir() is returning the right info. 

This ring any bells? I'm on Smarty 3.1.31.

I do have multiple instances of Smarty running simultaneously, so thought maybe something like this had reared its head again. https://github.com/smarty-php/smarty/issues/146 - but this is only occuring on this one person's server. I can't reproduce locally. 

Even debugging tips would be helpful, I'm out of ideas...!

**Comment by AnrDaemon** [comment]
This could be permissions issue. Make sure the user your PHP is running from has read access to the files and directories of the project.

**Comment by wisskid** [comment]
Closed due to inactivity. AnrDaemons answer seems plausible.
