### ISSUE TITLE
Warning: touch(): Utime failed: Permission denied

### ISSUE THREAD

**Issue by dertin** [smarty-php/smarty#524]
Hi,

I need the group (www-data) to have read and write permission in the files.
Since there are two different users that can generate compiled files within the group (www-data).

This did not work for me:
```php
final class View extends \Smarty
{
$this->_file_perms = 0664;
$this->_dir_perms = 2775;
...
```

Smarty: 3.1.33

Error:
`Warning: touch(): Utime failed: Permission denied in /var/www/webdisk/tufiesta.com.uy/htdocs/Particle/Core/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php on line 178`

https://github.com/smarty-php/smarty/blob/4f7cd8f1b3e29b108d6eee28e912149f8d8ad893/libs/sysplugins/smarty_template_compiled.php#L178

**Comment by artcs** [comment]
file_perms and dir_perms are obsolete and not used by Smarty 3.1.33. Besides that, permission values shoud start with a zero to indicate an octal number, while 2775 is decimal. Try setting directory permissions for your compiled templates directory manually to 0771.

**Comment by dertin** [comment]
"2775" is an octal number that defines the file permissions. The leftmost digit (the "2") is optional and defaults to zero if not specified.

> SGID
> 2770 on a directory named 'music' owned by the user 'root' and the group 'engineers'
> A user named 'torvalds' who belongs primarily to the group 'torvalds' but secondarily to the group 'engineers' makes a directory named 'electronic' under the directory named 'music'. The group ownership of the new directory named 'electronic' inherits 'engineers.' This is the same when making a new file named 'imagine.txt'
> 
> Without SGID the group ownership of the new directory/file would have been 'torvalds' as that is the primary group of user 'torvalds'.
https://en.wikipedia.org/wiki/Setuid#setgid_on_directories

I do not understand the reason why these properties are obsolete. For me they would be very useful.

What do you think ?

**Comment by artcs** [comment]
Not sure, just saw them in the `$obsoleteProperties` array in Smarty.class.php. They are however honored in the `writeFile()` function. 2775 definitely is not an octal number for php, it must have a leading zero AFAIK. Try checking the actual permissions with your ftp-program. The decimal value 2775 is octal number 05327, which is not what you want. Read chmod in the php-docs.

**Comment by dertin** [comment]
Hi @artcs 
Should I use chmod 02775 in php ?
I'll find a way to make obsolete properties work.

**Comment by artcs** [comment]
If you need the SGID-Bit, that's the correct value (works only if safe mode isn't enabled in php). But check the actual permissions in case you already messed something up.

**Comment by AnrDaemon** [comment]
> Should I use chmod 02775 in php ?

Wrong answer is "Yes, because you want to tell PHP it as an octal number."

Right answer most of the time would be "fix your filesystem permissions already, you are not writing a file manager, you should not concern yourself with filesystem access control".
Ownership and permissions should be set by the OS. Use setfacl to craft desired ACL layout.

**Comment by wisskid** [comment]
Closed due to inactivity.
