### ISSUE TITLE
Smarty 3.1.33 block plugins issue

### ISSUE THREAD

**Issue by Mr-Tenglin** [smarty-php/smarty#525]
Smarty 3.1.33 basic configuration.
`include_once LIBS_PATH . "smarty" . DIRS . "Smarty.class.php";
$smarty = new \Smarty();
$smarty->force_compile = false;
$smarty->debugging = \__CFG::SMARTY_DEBUG;
$smarty->caching = \__CFG::SMARTY_CACHE_IS;
$smarty->cache_lifetime = _format_second(\__CFG::SMARTY_CACHE_TIME);
$smarty->template_dir = EJCMS_PATH;
$smarty->compile_dir = SMARTY_COMPILE;
$smarty->cache_dir = SMARTY_CACHE;
$smarty->config_dir = SMARTY_CONFIGS;
$smarty->left_delimiter = "<{";
$smarty->right_delimiter = "}>";
$smarty->addPluginsDir(PLUG_PATH . "smarty");`

Block Plugins script source.
![block](https://user-images.githubusercontent.com/31702375/49988144-b329fb00-ffb0-11e8-86d9-892f0037f582.png)

Template file write block.
![Tpl](https://user-images.githubusercontent.com/31702375/49988235-f4baa600-ffb0-11e8-898f-353ce3079586.png)

The website shows that the content cannot be loaded, PHP can print out the data.
![Source](https://user-images.githubusercontent.com/31702375/49988317-3ea38c00-ffb1-11e8-978e-1363c31434c7.png)

**What configuration do I need to load?**

**Comment by wisskid** [comment]
Maybe the problem here is `$assign` in `$smarty->assign($assign, $item);`. Try changing it to `$smarty->assign("item", $item);` 
But it's really hard to tell with (images of) partial sources. If this doesn't help, please provide a reproduction scenario.
