### ISSUE TITLE
throwing some sort of compile error if using a modifier where it won't work

### ISSUE THREAD

**Issue by eth8505** [smarty-php/smarty#526]
We've been running smarty 3.1.29 for a while, since we were having problems with anything newer. Due to the CVE found in smarty we have to give upgrading another go. However, it appears that modifiers no longer work in includes.

```php
{include|dot:"x-template-id" file="included.dot.tpl"}
```

The plugin is used to wrap the include result in a script tag.
With 3.1.29 the resulting html was:
```php
<?php ob_start();
$_smarty_tpl->smarty->ext->_subtemplate->render($_smarty_tpl, "file:includes/notifications/layer_notifications.dot.tpl", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0, false);
echo smarty_modifier_dot(ob_get_clean(),"x-tpl-notification-layer");?>
```

with newer versions we only get:
```php
<?php $_smarty_tpl->_subTemplateRender("file:includes/notifications/layer_notifications.dot.tpl", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0, false);
?>
```

Is this anything we can fix ourself with some new config I missed or is it broken?

**Comment by wisskid** [comment]
[Modifiers](https://www.smarty.net/docs/en/language.modifiers.tpl) were not intended to be used on built in functions (as stated in the docs). It seems that applying modifiers to include did in fact work, however in 3.1.29 and prior.
In 3.1.30 compilation of templates changed quite a bit, and now it no longer works. I'm not sure what you've been trying to do here, but I'm afraid you'll have to find some other way.

**Comment by eth8505** [comment]
@wisskid Oh, I never understood the docs that way actually, as it didn't explicitly exclude built in functions, thanks for clarifying that. What we're trying to do here is wrap a script-Tag around an include result with a modifier. It's more of a convenience function really, but we do use it a lot. We did find a workaround for that, but speaking from experience with smarty in the past it'll most likely break eventually ;-)

What I'd like to see with this is smarty throwing some sort of compile error if using a modifier where I shouldn't. Simply swallowing it seems wrong, is that something that could be done?

**Comment by wisskid** [comment]
> What I'd like to see with this is smarty throwing some sort of compile error if using a modifier where I shouldn't. Simply swallowing it seems wrong, is that something that could be done?

That seems very reasonable. I'll see if we can get that in. It would have to go into Smarty 4 as it might break existing code. Hopefully it won't break your workaround :)

**Comment by eth8505** [comment]
@wisskid great, thanks. We're working on getting rid of most of the inline-templates anyway, it's a massive app though, so you know how that goes ;-)
