### ISSUE TITLE
(3.1.32 and 3.1.33) @last property not working inside foreach on an object

### ISSUE THREAD

**Issue by sveldhuisen** [smarty-php/smarty#529]
I just tried to upgrade from 3.1.31 to 3.1.33 and every place I use the @last property inside a foreach iteration on an object is broken with the following error:

`Undefined property: Smarty_Variable::$last`

After downgrading to 3.1.31 everything works fine.

**Comment by wisskid** [comment]
Cannot reproduce this in any recent version (including 3.1.31) with:
```
<?php
require_once './vendor/autoload.php';
$smarty = new Smarty();

class B {
	public $a = 1;
	public $b = 2;
}

$smarty->assign('test', new B());

$smarty->display('string:
{foreach $test as $key => $val}
 {$key}: {$val}
 {if $val@last}last{/if}
{/foreach}
');
```

Do you have a reproduction scenario?

**Comment by wisskid** [comment]
Closed because of inactivity.

**Comment by ecourtial** [comment]
I have the same issue with 3.1.31, 3.1.43 and the 4.x version.
The warning appeared after a migration from PHP 7.4 to 8.1.
