### ISSUE TITLE
Trailing comma in arrays not supported

### ISSUE THREAD

**Issue by putnik** [smarty-php/smarty#533]
Code like
```php
{$a = [
    'value',
    'value2',
    'value3',
]}
```
returns syntax error: `Unexpected "]"`.

But code
```php
{$a = [
    'value',
    'value2',
    'value3'
]}
```
works fine.

**Comment by AnrDaemon** [comment]
Why it should?
Smarty is not PHP, it is not obliged to support everything PHP does.

**Comment by Lerie82** [comment]
I believe this is a syntax error in your code as this is not functionality supported Smarty, therefore not an issue.
