### ISSUE TITLE
Fatal errors when debugging

### ISSUE THREAD

**Issue by tom2tom** [smarty-php/smarty#536]
Data structures incompatible with the code trigger errors, in  sysplugins/smarty_internal_debug.php V.3.1.33.

A workable solution is attached, though probably not the most elegant you could come up with ...

[smarty-3.1.33-debugfix.diff.zip](https://github.com/smarty-php/smarty/files/2922999/smarty-3.1.33-debugfix.diff.zip)

**Comment by wisskid** [comment]
I'm not quite sure what you mean. Could you provide a reproduction scenario?

**Comment by wisskid** [comment]
Closed because of inactivity.
