### ISSUE TITLE
Umlaut Error with date_format modifier

### ISSUE THREAD

**Issue by alexander-pick** [smarty-php/smarty#537]
I have my locale set to de_DE, if I try to dateformat a March date (german März) it will cause a compile error.

I use:
`<![CDATA[{$xxxxx.CREATED|date_format:"%a %b %Y %H:%M:%S"} GMT]]>
`
This will cut the string after the %b and cause some hick up in the code generation:

```
<date>
<![CDATA[Sa M445]]>
</url>
```
Which should be (with locale en_US it works like that):

```
<date>
<![CDATA[Sat Mar 2019 11:49:53 GMT]]>
</date>
<referencenumber>
<![CDATA[3974523]]>
</referencenumber>
<url>
<![CDATA[URL REMOVED]]>
</url>
```

**Comment by wisskid** [comment]
Could you provide a reproduction scenario? I tried, but got no errors.

```
locale = setlocale(LC_ALL, 'de_DE');

echo "Locale: $locale\n";

$smarty->assign('xxxxx', ['CREATED' => strtotime('2021-01-01')]);
$smarty->display(__FILE__);

__HALT_COMPILER();
?><![CDATA[{$xxxxx.CREATED|date_format:"%a %b %Y %H:%M:%S"} GMT]]>
```

returns

```
$ php testcase.php 
Locale: de_DE
<![CDATA[Fr Jan 2021 00:00:00 GMT]]>
``` 

as expected.

**Comment by wisskid** [comment]
Closed because of inactivity.
