### ISSUE TITLE
Capture append as item in associative array

### ISSUE THREAD

**Issue by vbezruchkin** [smarty-php/smarty#538]
Hello,

This task is very close to #366. But the previous solution does not fit the idea.

Let me explain in details.

I have one array and it's available in Smarty:
`$arr = array('first' => 'One', 'second' => 'Two');`

I want to extend this array with more items using capture:
```
{capture name='third' append='arr'}
Three
{/capture}

{capture name='fourth' append='arr'}
Four
{/capture}
```

As a result I would like to have array like this:
`$arr = array('first' => 'One', 'second' => 'Two', 'third' => 'Three', 'fourth' => 'Four');`

At the moment, capture does not allow to do this, as it does not pass any keys to the array during append. I know I can use $smarty.capture.third, etc. anyhow it's not the option for me right now. 

Let me know if we can hack somehow the system, to get the results we expect. 

Thanks

**Comment by vbezruchkin** [comment]
I managed to achieve this, I modified Smarty_Internal_Runtime_Capture class.

and changed append in close to this one:

`$_template->append($append, array($buffer => ob_get_contents()), true);`

Not sure if this might be needed by anyone else :) I guess no. Please close the ticket if you find this irrelevant and useless.

Thanks

**Comment by wisskid** [comment]
Hi @vbezruchkin. I'm closing this, no one else seems to find this useful. Sorry!
