### ISSUE TITLE
Custom delimiters <{ }> not working after v3.x

### ISSUE THREAD

**Issue by Benjaminhu** [smarty-php/smarty#539]
Hi,

UPDATE: Sorry, I updated the issue, checked all available releases (30 releases).

I'm using custom tags <{ }> and they work unless I use version v3.x and later.
My settings:
```
<?php
...
$smarty->left_delimiter = '<{';
$smarty->right_delimiter = '}>';
...
```
I've tried the all previous releases (smarty-2.6.24, smarty-2.6.25, smarty-2.6.26, smarty-2.6.27, smarty-2.6.28) and has no problem.

Thanks!

**Comment by AnrDaemon** [comment]
Unable to reproduce (see https://github.com/AnrDaemon/test-001/tree/smarty-539 )

**Comment by wisskid** [comment]
Closed because of inactivity.
