### ISSUE TITLE
section with negative step don´t work

### ISSUE THREAD

**Issue by stupsi0815** [smarty-php/smarty#541]
{section name=yearValue start=$smarty.now|date_format:'%Y' + 1 loop=2015 step=-1}
    ....
{/section}

Should 2019,2018, .... 2015.
You get 2014 .... 0

**Comment by wisskid** [comment]
This works as intended, please see the [docs](https://www.smarty.net/docs/en/language.function.section.tpl) and this example:
```
{section name=bar loop=21 max=6 step=-2}
  {$smarty.section.bar.index}
{/section}
```
resulting in
```
  20
  18
  16
  14
  12
  10
```
