### ISSUE TITLE
Is there some schedule for release smarty v3.1.34 ?

### ISSUE THREAD

**Issue by matks** [smarty-php/smarty#545]
Hello !
Last smarty release was v3.1.33 which was released on the 12th of September 2018. So it will be almost 9 months now.

Some very nice work has been done since then and is waiting in `master` branch to be released. Is there any chance you guys perform a new release soon (meaning: in the summer) so we can use v3.1.34 (instead of our own fork now) ? 🙏 Or if non do you have a release calendar or a release schedule ?

Thank you for the hard work, have a nice day 😄

**Comment by simplexx** [comment]
would like to know this as well, I really hope that smarty does not die, it is a great project.

**Comment by matks** [comment]
> would like to know this as well, I really hope that smarty does not die, it is a great project.

I'm starting to get worried 😅

**Comment by kuntal112** [comment]
hey i m having this error...what to do?

Warning: require_once(/usr/share/php/smarty3/Smarty.class.php): failed to open stream: No such file or directory in C:\xampp\htdocs\whitepages\htdocs\index.php on line 35

Fatal error: require_once(): Failed opening required '/usr/share/php/smarty3/Smarty.class.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\whitepages\htdocs\index.php on line 35

**Comment by matks** [comment]
I asked on the forum if there are more informations
https://www.smarty.net/forums/viewtopic.php?p=94653#94653

**Comment by DavidGoodwin** [comment]
I saw 3.1.34 come through in a 'composer update' this morning.

**Comment by caugner** [comment]
@matks It has been released: https://github.com/smarty-php/smarty/releases/tag/v3.1.34

Could you close the issue?

> Or if non do you have a release calendar or a release schedule ?

There is no release calendar and the maintainer is currently not available for personal reasons.

**Comment by matks** [comment]
> @matks It has been released: https://github.com/smarty-php/smarty/releases/tag/v3.1.34
> 
> Could you close the issue?

Yes indeed, the topic has been fully solved 😊
