### ISSUE TITLE
Impossible to change _dir_perms so 0771 is used

### ISSUE THREAD

**Issue by pixmin** [smarty-php/smarty#548]
Hi,

We are using prestashop, but I don't think it matters.

The Smarty_Internal_Runtime_WriteFile::writeFile sets $_dir_perms to 0771 which is a problem since we can't list files in the folder.

Could you either set it to 0775, or use the default umask, or let us set $_dir_perms to whatever we want?

Thanks.

**Comment by AnrDaemon** [comment]
0750 should be more than enough. If it is not, then fix your server setup.
Not a Smarty problem.

**Comment by Designburo** [comment]
It's Smarty.. 
Every time I change it to 0755, smarty puts it back..

**Comment by wisskid** [comment]
!507 might fix this
