### ISSUE TITLE
Version 3.1.25 produce error on nocache function

### ISSUE THREAD

**Issue by sofl88** [smarty-php/smarty#55]
After updating from 3.1.23 to 3.1.25, I get a fatal error like

Fatal error: Call to undefined function smarty_function_testfunc() in C:\path\to\Cache\62\b1\ff\62b1ff3d740b834c8454b925562791706a82261a.view.tpl.php on line 749

This seem to appear when I use a function in my template with the nocache flag like {testfunc nocache}
When I look into the cache file, It isn't even a part of the require / include list. I expected "if (!is_callable('smarty_function_testfunc')) require_once ..."

I use addPluginsDir multiple times (absolute paths only) and use_sub_dirs = true...if that may help

**Comment by uwetews** [comment]
The fix is now in 3.1.27
