### ISSUE TITLE
section "name" prop does not accept variable

### ISSUE THREAD

**Issue by klmedia** [smarty-php/smarty#550]
Hi!
First of all, Smarty project is the best and we rely on it for 10+ years now. I have upgraded from 3.1.25 to 3.1.33. I got a few errors. One of them which I can't get pass through is: I have a section where the "name" property is a variable which is like an iterator, when using the template multiple times, especially if it embeds itself, so the section name does not get mixed up.
It gives the following error:
"'name' attribute/variable has illegal value"
code:

    {if !isset($subIndex)}{$subIndex=0}{else}{$subIndex=$subIndex+1}{/if}
    {$scData="cData{$subIndex}"}
    {section name=$scData loop=$d->mData}
      {*here I may include the parent tpl again, eventually and I get the $subIndex iterated*}
    {/section}

Is this possible somehow?
Thanks in advance! Keep up the good work!

**Comment by AnrDaemon** [comment]
Try `name="$scData"`

**Comment by klmedia** [comment]
@AnrDaemon I will try it, thank you!
