### ISSUE TITLE
Problematic {foreach} compilation

### ISSUE THREAD

**Issue by AnrDaemon** [smarty-php/smarty#552]
The Smarty code
```
{foreach [1] as $i}$i => {$i}{/foreach}
```

compiles into

```php
<?php
$_from = $_smarty_tpl->smarty->ext->_foreach->init($_smarty_tpl, array(1), 'i');
if ($_from !== null) {
foreach ($_from as $_smarty_tpl->tpl_vars['i']->value) {
?>$i => <?php echo $_smarty_tpl->tpl_vars['i']->value;
ob_start();
}
}
$_smarty_tpl->smarty->ext->_foreach->restore($_smarty_tpl, 1);
$_prefixVariable1 = ob_get_clean();
echo $_prefixVariable1;?>
```

Which has a very obvious issue of creating uncontrollable amount of output buffers.

**Comment by wisskid** [comment]
I cannot reproduce this right now. Compiled template does not contain either `ob_start` or `ob_get_clean`. Are you still getting this and if so, could you provide us with reproduction steps?

**Comment by wisskid** [comment]
Is this maybe linked to https://github.com/smarty-php/smarty/issues/530 ?

**Comment by AnrDaemon** [comment]
For some reason I can't install exactly the version of Smarty I've used in tests.
Unable to reproduce on current master.
