### ISSUE TITLE
Smarty 3.1.-x dev dateformat

### ISSUE THREAD

**Issue by Florian-Sobotka** [smarty-php/smarty#556]
Hey there dear Smarty team.

by accident i found out that your in your current dev version date format sets the varriable and not just format it. So if you would dateformat it a second time you will get an error. Is it a bugg or a feature?

best regards F.S

**Comment by wisskid** [comment]
Not sure what you mean here. `date_format` does not "set" the variable you pass it. Could you provide an example?

**Comment by wisskid** [comment]
Closed because of inactivity.
