### ISSUE TITLE
_smarty_include method

### ISSUE THREAD

**Issue by TuxBoy** [smarty-php/smarty#557]
Hello,

I would like to know the equivalent of the `Smarty::_smarty_include` method, which is present in version 2, but no more in version 3, maybe` Smarty_Internal_Resource_File`?

Thank you

**Comment by timd35b** [comment]
Not sure how you are using it but I think you just use include. A lot of the functions in v3 are simplified to standard PHP...i.e.
{* absolute filepath *}
{include file='/usr/local/include/templates/header.tpl'}

{include file='index.tpl'}
{include file='file:index.tpl'} {* same as above *}

**Comment by TuxBoy** [comment]
Thank you for your answer

The method has been overloaded to make sure that the file path is implicit, all we need to do is make an {include file = 'file: index.tpl'} without having to specify the path.
I'm getting around the problem for the moment by adding all possible paths in the `include_path` array which is no longer a simple string.

Maybe there is another better solution?

**Comment by wisskid** [comment]
This is indeed completely different in Smarty3. Maybe you can use https://www.smarty.net/docs/en/variable.default.template.handler.func.tpl ?

**Comment by AnrDaemon** [comment]
Indeed, you should have used custom resource handler.
Relying on include_path is just plain wrong.

**Comment by wisskid** [comment]
Closed because of inactivity.
