### ISSUE TITLE
implode(): Passing glue string after array is deprecated. Swap the parameters

### ISSUE THREAD

**Issue by zhaokeli** [smarty-php/smarty#559]
php7.4: 
implode(): Passing glue string after array is deprecated. Swap the parameters

**Comment by blaaat** [comment]
I've added this modifier to keep the syntax the same in my templates. 

```
<?php
function smarty_modifier_implode($array, $glue = '')
{
	return implode($glue, $array);
}
```

**Comment by Stadly** [comment]
This issue should be reopened, and that modifier added to the Smarty core.
