### ISSUE TITLE
PHP 7.4 / join() deprecated warning

### ISSUE THREAD

**Issue by hscheffknecht** [smarty-php/smarty#561]
php7.4:
join(): Passing glue string after array is deprecated. Swap the parameters.

**Comment by caugner** [comment]
Can you provide the code location where this warning comes from?

**Comment by hscheffknecht** [comment]
Thanks for your response. This is the exact PHP warning:

DEPRECATED: [8192] join(): Passing glue string after array is deprecated. Swap the parameters in file .../a8/61/57/a861573a07f1fa9315f36e5a9c73bb3beac831ec_0.file.html.html.php (line 50)

This is line 50 of ... file.html.html (compiled Smarty template):

" <?php if (!empty($_smarty_tpl->tpl_vars['requirejs_custom_modules']->value)) {?>data-eboxx-init="<?php echo call_user_func_array($_smarty_tpl->registered_plugins[ 'modifier' ][ 'html' ][ 0 ], array( join($_smarty_tpl->tpl_vars['requirejs_custom_modules']->value,"|") ));?>

Unfortunately, I don't know where this code is generated.

**Comment by caugner** [comment]
> This is the orginal template line in "html.html":

I don't see it, can you put your code in Markdown code blocks:
https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by hscheffknecht** [comment]
I updated the previous comment. The problematic code is `join($_smarty_tpl->tpl_vars['var']->value,"|")`.

**Comment by Visualq** [comment]
'`join()`' is not part of the Smarty template language but directly relayed to the the PHP `join()` function. So the first parameter will be the variable.

You could however fix it with either: `{join("|", $var)|html}` or the ugly: `{"|"|join:$var|html}`
Or you could register the following plugin to your Smarty instance:
```
$smarty->registerPlugin(Smarty::PLUGIN_MODIFIER, 'join', function($array, $glue) {
     return join($glue, $array);
});
```

**Comment by hscheffknecht** [comment]
Thanks you very much for the clarification. The plugin seems the cleanest solution for me, I'll try it.

**Comment by hscheffknecht** [comment]
The solution is working well. I'm closing the issue.
