### ISSUE TITLE
{foreachelse} not showing with Iterator 0 elements

### ISSUE THREAD

**Issue by tom-2015** [smarty-php/smarty#562]
Recently updated to PHP7.3 and Smarty 3.1.34 and noticed that {foreachelse} is not executed when the data count is 0.

I think this is because $needTotal parameter in smarty_internal_runtime_foreach.php:44 is false and $total will always be 1 so function will not return null if total items in array/Iterator is 0.

smarty_internal_runtime_foreach.php

 if (!isset($total)) {
            $total = empty($from) ? 0 : ($needTotal ? count($from) : 1);
        }
   ......
        if ($total === 0) {
            $from = null; //should return 0 if {foreachelse} is used
        } else {

To fix this smarty_internal_compile_foreach.php:190 should check if total is needed and/or foreachelse tag is present. I have added "|| true" so it will always do a count() on the supplied array. Not best fix but I don't know how to check if a {foreachelse} tag is present.

smarty_internal_compile_foreach.php:190
`        $needTotal = isset($itemAttr[ 'total' ]) || true; //check if {foreachelse} tag is present instead of || true ...
`

**Comment by caugner** [comment]
What Smarty version did you use before?

**Comment by tom-2015** [comment]
It was working with 3.1.14

**Comment by caugner** [comment]
Could you try with 3.1.30 and 3.1.31 please? If it works in 3.1.30, but not in 3.1.31, it's probably due to this change:

https://github.com/smarty-php/smarty/blob/b2ecd98ae08204616f3215133b9749b153f8bc20/change_log.txt#L302-L303

**Comment by tom-2015** [comment]
I've tested and it works correctly with 3.1.31, 3.1.32
does not with: 3.1.30, 3.1.33, 3.1.34

Problem only occurs when using objects like class that implements iterator.

**Comment by wisskid** [comment]
this was fixeed in https://github.com/smarty-php/smarty/pull/566
