### ISSUE TITLE
json_decode in template always return NULL (syntax error)

### ISSUE THREAD

**Issue by gibigate** [smarty-php/smarty#575]
We have correct json variable assigned to smarty template. For example:
`{"title":"Test title","avgColor":"#D38C75","frameRate":33.4897,"numFrames":1642,"hasAudio":true}`
But `{{$json|json_decode:true}}` always return nulled result. We tried decode it in php, and no error there.

We used smarty version 2.6.31-dev. 

Also we tried `{{$json|smarty:nodefaults|json_decode:true}}`, it doesn't help too

**Comment by wisskid** [comment]
works fine here:
```

$smarty->assign(
	'json',
	'{"title":"Test title","avgColor":"#D38C75","frameRate":33.4897,"numFrames":1642,"hasAudio":true}');

echo $smarty->fetch('string:
{$json|json_decode:true}
');
```
Results in 
```
Array
```
as expected.

Could you provide a reproduction scenario?

**Comment by AnrDaemon** [comment]
Second that emotion, my templates are making heavy use of the JSON control blocks, and I've never had a problem printing them for debugging purposes

If you can reproduce it using https://github.com/AnrDaemon/test-001 (clone, create a new branch off the `master` and write a reproduction script, then publish your changes and link them here), that would be highly appreciated.

**Comment by wisskid** [comment]
Closed because of inactivity.
