### ISSUE TITLE
call function defined in template from within body of another custom function?

### ISSUE THREAD

**Issue by chilek** [smarty-php/smarty#576]
Hello,

I've defined the following function in template:
```smarty
{function ticket_item_content assign="item_content_result"}
  {sprintf("#%06d", $item[id])} <a href="?m=rtticketview&id={$item[id]}">{$item[name]}</a>';
{/function}
```

I'd like to call the above function from my own function plugin looking like this:
```php
function smarty_function_list(array $params, Smarty_Internal_Template $template)
{
  call_user_func_array($template->tplFunctions[$params['item_function']]['call_name'], array('item' => $params['item_args']))
}
```

I try to use {list} function as is:
```smarty
{list item_function="ticket_item_content" item_args=$item}
```

Is there a way to use Smarty in such (or like) scenario?

**Comment by chilek** [comment]
I've found the solution:
```php
  $template->smarty->ext->_tplFunction->callTemplateFunction($template, $item_content, array('item' => $item), true);
  $content = $template->smarty->ext->_capture->getBuffer($template, 'item_content_result');
```
Is it correct way of handling capture blocks from PHP?

**Comment by wisskid** [comment]
Why not use a foreach loop in your template? It seems you are tying a lot of smary internals into your project here. If anything changes in the future, that'll surely break.

**Comment by chilek** [comment]
> Why not use a foreach loop in your template?

Because smarty does NOT allow to define callable in template and pass these callables to smarty function.

**Comment by wisskid** [comment]
Ok, but why insist on defining the callable in your template? You could just define it in PHP?

**Comment by chilek** [comment]
Because my smarty function wants to execute some external (related to it) code. I want this code to make callable.
Btw. most of class methods are public. Is it for hacker convenience or is it intentional? :)

**Comment by chilek** [comment]
> You could just define it in PHP?

But it wouln't separate visualisation completely from logic - this callable has to generate some html code.

**Comment by wisskid** [comment]
Well, if you insist to keep your html in .tpl files, you can always use Smarty from in php function and render a template again. Closing this now, as there doesn't seem to be an issue left to fix here!
