### ISSUE TITLE
{$smarty.template} with "_" characters and custom resource

### ISSUE THREAD

**Issue by EDCScott** [smarty-php/smarty#578]
This is a followup to issue #490

The original report was that the {$smarty.template} variable reports incorrectly for template names that contain an underscore.  After some further testing, I was able to isolate that the issue only happens when using a custom resource.

I've attached a sample which recreates the issue.  To reduce the size of my upload, I didn't include the smarty installation, which is expected to be in a "smarty" sub directory.

[example.zip](https://github.com/smarty-php/smarty/files/4448043/example.zip)

**Comment by EDCScott** [comment]
I've been able to isolate the issue to the following commit:

https://github.com/smarty-php/smarty/commit/614ad1f8b9b00086efc123e49b7bb8efbfa81b61

**Comment by EDCScott** [comment]
I have the issue resolved locally, but it appears as though I don't have permissions to push to this repository.  Is there a different procedure, other than requesting permissions to push branches and open pull requests?

**Comment by wisskid** [comment]
Hi @EDCScott! At github it is customary for you to fork this project in your own namespace, create a branch that fixes the issue there and than create a pull request (PR) from your repo to this one.

**Comment by EDCScott** [comment]
Done.  Thank you for the insight.

**Comment by wisskid** [comment]
NIce! I'll review the PR asap.

**Comment by wisskid** [comment]
Fix was already merged last year.
