### ISSUE TITLE
Upgrate to any above v3.1.31 gets unknown error

### ISSUE THREAD

**Issue by khurshid290** [smarty-php/smarty#587]
Hi, when using anything higher than 3.1.31 I keep getting message shown below, and all pages get messed up, when using 3.1.31 or below pages are rendered fine. So please let me know what I am doing wrong.
--Warning: Parameter 2 to smarty_function_assign_adv() expected to be a reference, value given in C:\wamp64\www\vhost\atds.home\htdocs\templates_c\3320b82ac623830fd4863720a701136fc2bf1fd4_0.file.genericDataView.tpl.php on line 101

**Comment by khurshid290** [comment]
![изображение](https://user-images.githubusercontent.com/63809206/79489053-2b388300-8034-11ea-9ff5-f665de7d3545.png)

**Comment by khurshid290** [comment]
![изображение](https://user-images.githubusercontent.com/63809206/79489211-6470f300-8034-11ea-9518-20113b0d9ff5.png)

**Comment by khurshid290** [comment]
snapshot above version 3.1.32, second one is version 3.1.31

**Comment by AnrDaemon** [comment]
Not a Smarty issue.
You have a bunch of badly written plugins you have to fix yourself.

**Comment by AnrDaemon** [comment]
Also, I hope that is not your production server on that screenshot.
