### ISSUE TITLE
Status of Smarty 3.1.36 ?

### ISSUE THREAD

**Issue by matks** [smarty-php/smarty#588]
Hi guys,

I see there is a release tag 3.1.36 and [we can see why it was created](https://github.com/smarty-php/smarty/issues/584). However it has been pending for a few days now and no official release is done ... Is there something blocking ?

Basically I plan to update from 3.1.34 to 3.1.36 when it's ready so I'm wondering if I'll wait for a long time 😄.

If there is no schedule / plan / issue, but you guys just need time, it's OK 👍I'm just wondering whether there are issues we should be aware of

**Comment by AnrDaemon** [comment]
https://packagist.org/packages/smarty/smarty

**Comment by matks** [comment]
Indeed packagist now delivers Smarty v3.1.36 but GitHub release is not created
<img width="954" alt="Capture d’écran 2020-04-20 à 10 01 39" src="https://user-images.githubusercontent.com/3830050/79728304-ffe0bd00-82ed-11ea-910f-f324b639b1f9.png">

**Comment by AnrDaemon** [comment]
Open your eyes, the release is right at your screenshot.

**Comment by matks** [comment]
My bad, I did use the wrong word. "It's not marked as latest"

**Comment by AnrDaemon** [comment]
Because it's a "technical release". Otherwise identical to 3.1.35, with fixed branding.

See https://github.com/smarty-php/smarty/commits/v3.1.36 for details.

**Comment by matks** [comment]
Thanks !

**Comment by glensc** [comment]
Note, the "latest" link also points to latest "latest":
- https://github.com/smarty-php/smarty/releases/latest

to fix this, maintainer needs to hit "edit" for v3.1.36 and save it at least once
- https://github.com/smarty-php/smarty/releases/tag/v3.1.36
