### ISSUE TITLE
registerFilter does not allow to use Anonymous functions(closures)

### ISSUE THREAD

**Issue by ildar-aim** [smarty-php/smarty#59]
The sample code is
```
    $tpl->registerFilter('output', function($source, $smarty){
        if ($smarty->smarty->isEvalTemplate($smarty->template_resource)) {
            return 'Test is passed.';
        } else {
            return 'Test is failed. Fix strpos in isEvalTemplate() method related to "eval:" string';
        }
    });
```

the possible fix is
```
-        if (!empty($template->smarty->registered_filters[$type])) {
+        if (isset($template->smarty->registered_filters[$type])) {
```

The function _get_filter_name returns wrong name for a closure
It results to
Warning: Illegal offset type to /lib/smarty3/sysplugins/smarty_internal_templatebase.php on line 699

![callable1](https://cloud.githubusercontent.com/assets/1235868/8228856/c300396a-15ba-11e5-896f-bd736df80f9a.png)

![callable2](https://cloud.githubusercontent.com/assets/1235868/8228903/1ec22038-15bb-11e5-9f34-b92defd1d15d.png)

PHP 5.3.29

**Comment by uwetews** [comment]
Closure support is new added in the dev-master version.
It will be included in 3.1.28

Read also NEW_FEATURES.txt

**Comment by ildar-aim** [comment]
Thank you.

**Comment by ildar-aim** [comment]
May be an issue with two or more closure's filters.

1)first call to registerFilter returns
registered_filters[$type]['closure'] = closure_obj1

2)second call to registerFilter overwrites the first filter
registered_filters[$type]['closure'] = closure_obj2

The problem code is not uniq index in the  _getFilterName function
```
return 'closure';
```

**Comment by ildar-aim** [comment]
Should I open a new ticket related to non-unique filter names ?

**Comment by uwetews** [comment]
Read  NEW_FEATURES.txt.

If you register multiple closures use the new filter name parameter to assign unique filter names.

$smarty->registerFilter('pre', function($content) {return $content;}, 'name1');
$smarty->registerFilter('pre', function($content) {return $content;}, 'name2');
