### ISSUE TITLE
forgot to bump version number in 3.1.35 release?

### ISSUE THREAD

**Issue by joebordes** [smarty-php/smarty#597]
https://github.com/smarty-php/smarty/blob/master/libs/Smarty.class.php#L30

https://github.com/smarty-php/smarty/blob/v3.1.35/libs/Smarty.class.php#L115

**Comment by AnrDaemon** [comment]
Fixed with https://github.com/smarty-php/smarty/releases/tag/v3.1.36

**Comment by Bigbear7** [comment]
Shouldcthe smarty homepage be updated since it announces Smarty 3.1.35?

**Comment by scottchiefbaker** [comment]
This is a duplicate of #588 

In other words... it's a known issue :)
