### ISSUE TITLE
Dowloading the latest release

### ISSUE THREAD

**Issue by hollymcr** [smarty-php/smarty#602]
It used to be possible to script a download of the latest release by using [this link](http://www.smarty.net/files/Smarty-stable.tar.gz)

But at time of writing it is downloading 3.1.21

Is there a better way to link directly to the latest released tar.gz file, or is this a bug?

**Comment by AnrDaemon** [comment]
You can use Composer. Already.

**Comment by hollymcr** [comment]
Composer is fine on a development or typical production machine but on a device with limited capacity it's an unnecessary overhead ~ 5MB of tools to install 2M of Smarty, and that's my use case.

There are other (less convenient) ways to get the latest code, e.g. parsing the github page, but really my goal was to find out if the "latest" download is still supposed to work. If it's now officially defunct then I'll work around it, if it's a "bug" I'm reporting it!

Mark

**Comment by AnrDaemon** [comment]
You don't have to use Composer on a target host.
Assemble locally, then rsync the assembled project.

**Comment by hollymcr** [comment]
What I have at the moment is a script which configures a new host the way I want it, including (as necessary) installing Smarty. It has always used the smarty-stable.targ.gz to obtain the latest version but that stopped working without me realising it some time ago (it didn't fail to download, it just got stuck at 3.1.21). The script is modular and the code it installs depends on the application, many of which use Smarty.

There are lots of ways I can work around it (I am now parsing github). 

But http://www.smarty.net/files/Smarty-stable.tar.gz linking to 3.1.21 is clearly a bug; either it should return a 404 or it should download the current stable verson. Ideally the latter, but linking to an old version ought to be a definite "no".

A look at the server logs should indicate whether anyone (apart from me!) still uses it.

**Comment by AnrDaemon** [comment]
https://github.com/smarty-php/smarty/releases/latest

**Comment by hollymcr** [comment]
Sure, that's the page I'm parsing to find the latest URL to download:
```
        smartyver=$(wget -O/dev/null https://github.com/smarty-php/smarty/releases/latest 2>&1 | grep following|tail -n1|grep -Po 'tag/v\K[\.0-9]+')
        wget -N "https://github.com/smarty-php/smarty/archive/v$smartyver.tar.gz" -O ~/Downloads/smarty-v$smartyver.tar.gz
```

But it doesn't change that http://www.smarty.net/files/Smarty-stable.tar.gz should either direct to the current stable version or it should give a 404.

**Comment by wisskid** [comment]
Yes, I agree. There are multiple issues regarding www.smarty.net. One of them being the out-of-date impression the website gives. As I see it, documentation should be moved to a different location.

**Comment by mohrt** [comment]
The Smarty-stable links are now removed. Also there is a link to the Smarty 4 documentation on the documentation page, which is the latest github location.
