### ISSUE TITLE
Messed up cache file names

### ISSUE THREAD

**Issue by lsces** [smarty-php/smarty#603]
The latest update seems to have made changes to the file name element of the cached tpl files. The loss of the '_' in the names makes finding a file difficult, and the loss of the .tpl depending where the new name is cropped exacerbated the problem. Now if I did not have to manually adjust these files to kill warning error such as caused by the 'count' crap introduced in recent PHP builds then it would be less of a problem, but is there ANY reason to make this change when the established mechanism was working fine? I can see the addition of package name helps, but that should simply prefix the template file name ...

**Comment by scottchiefbaker** [comment]
I've not run in to any issues with the latest release. Can you elaborate on what you mean "messed up cache file names"? What were they before, and what are they now?

**Comment by lsces** [comment]
97a96cf6ec454d8995a60bda7de800ee8f46953d_0.bitpackage.list_xref_generic.tpl.php is still on the list but has been replaced by 97a96cf6ec454d8995a60bda7de800ee8f46953d_0.bitpackage.contactlistxrefgeneric.tp.php ... obviously I now need to wipe the cache and rebuild everything, but I've got fixes in to stop warnings such as where 'count(x)' has an empty x value :(

**Comment by scottchiefbaker** [comment]
I've never run in to this syntax. Of course, I've never worried about the compiled PHP output either. You probably shouldn't be mucking around with the compiled output, as it's designed to be machine readable, not human readable. The side effects are, when the devs change things your stuff breaks.

**Comment by wisskid** [comment]
Yes @scottchiefbaker is right here. Even in patch release, internal stuff like this may change without prior notice.

**Comment by lsces** [comment]
Time to fork something that has worked perfectly for 20 years and kill off unnecesary changes that do nothing other than being an undocumented requirement to wipe and rebuild long time stable caches!!!
