### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by 09eric09** [smarty-php/smarty#607]
Hello, I understand there have been similar issues, I've tried following, however this line of my code:

`if(!count( $_SESSION['err'] ) > 0)](url)`

Is giving me the error, can someone please assist me?

**Comment by scottchiefbaker** [comment]
This is most likely related to:

https://somecrazy.com/using-php-count-without-warnings-php-7-2/

You probably want something like:

    if (!empty($_SESSION['err'])) { ... }

**Comment by 09eric09** [comment]
This seems to have worked, thank you sir, I appreciate your help.
