### ISSUE TITLE
Homepage has casino spam

### ISSUE THREAD

**Issue by danielcompton** [smarty-php/smarty#610]
I noticed there is casino spam at https://www.smarty.net.

<img width="1044" alt="Screenshot of Safari (6-10-20, 7-49-50 AM)" src="https://user-images.githubusercontent.com/811954/95119514-91fb5580-07a8-11eb-952d-f9b654e2da83.png">

**Comment by mohrt** [comment]
Not spam, paid links. It's only on the home page, documentation has none.

**Comment by tyronx** [comment]
That looks quite credibility degrading, just sayin'

**Comment by RobThree** [comment]
> That looks quite credibility degrading, just sayin'

I literally assumed smarty.net was hacked and panicked because I thought Smarty itself might've been compromised too then.

I mean, I get the income is needed but this is a sad, but apparently necessary, new low. Jeesh.

**Comment by wisskid** [comment]
@RobThree I am considering. It's just that there are bunch of doc-pages to rewrite. But it's definitely on my whishlist.
