### ISSUE TITLE
smarty css and js file inclusions

### ISSUE THREAD

**Issue by chilek** [smarty-php/smarty#615]
I'd like to implement smarty function like below:
```
{js}
{css}
```
which translates to some dedicated subdirectories which contain (respectively) js and css files
with the same name as calling template/subtemplate file.
Is there is simple way to achieve this?
Does Smarty class have some method or property to determine full path of calling template directory?
If doesn't then how difficult would it be to implement such feature?
I appreciate any feedback in advance!

**Comment by wisskid** [comment]
@chilek please see https://www.smarty.net/docs/en/plugins.functions.tpl
You may be able to use `$template->source` but you have to check if it is a `Smarty_Template_Source` first.
