### ISSUE TITLE
Custom function attributes causing errors

### ISSUE THREAD

**Issue by mjgw** [smarty-php/smarty#619]
**Description:**

I have a function called {link}, because I am using Smarty as part of a CMS. The tag works like this: {link to="page:home” with=“Home”}.

In some templates, the tag is compiled perfectly, and when I look at the cached output, I see:
< ? php echo smarty_function_link(array('to'=>"page:home",'with'=>”Home")),$_smarty_tpl);?>

However, in other cases, I encounter the error:
Syntax error in template "file:/path/to/templates/index.tpl" on line 43 "" unexpected 'to’ attribute.

Strangely, this error only seems to arise if the plugin is called “link”. When I make an identical function called “linkd” and insert it into the same template at the exact same position, the template compiles as it should. As soon as I rename it back to “link”, the error message reappears.

From the digging that I have done, it seems as though Smarty is _sometimes_ misrecognising the “link” tag as an internal compiler function and validating its attributes - a validation process that it of course fails.

So there seems to be a bug with this classification happening (i.e. is this an internal function or a user plugin?), which of course may affect other custom tag names not hitherto discovered in my setup.

Happy to fix this and submit a pull request if others can advise me where this problem may be occurring?

Smarty version 3.1.34
PHP version 7.3

**Comment by wisskid** [comment]
That is strange. `link` is not an internal function. It would have to be a compilation error. Do you have a reproduction scenario?

**Comment by wisskid** [comment]
Closed because of inactivity.

**Comment by mjgw** [comment]
@wisskid Can I request that this be reopened? I didn't realise there was a set time limit on this, but I was planning to come back to it once my actual day job (which has been extremely intense) quieted down a bit.
