### ISSUE TITLE
PHP Fatal error:  Cannot use [] for reading

### ISSUE THREAD

**Issue by masimao** [smarty-php/smarty#62]
Hi,

I made an upgrade from Smarty 3.1.21 to 3.1.27, after this i am getting this error in some templates:

`PHP Fatal error:  Cannot use [] for reading in /home/conquist/views_c/83c15fae7d6abe30de328afde91cc87c27947c90_0.file.Imovel.view.tpl.php on line 387`

The line 387 starts with:

```php
<?php if ((isset($_smarty_tpl->tpl_vars['__foreach_info']->value[]) ? $_smarty_tpl->tpl_vars['__foreach_info']->value[] : null) < 4) {?>
    <li><h4><?php echo ('- ').($_smarty_tpl->tpl_vars['info']->value);?>
</h4></li>
<?php }?>`
```

I am not seeing how to solve this issue. Anybody can help me please?

**Edit 1**

The original code is:
```php
{foreach $dadosImovel.nomes_diferenciais as $info}
    {if $smarty.foreach.info < 4}
        <li><h4>{'- '|cat:$info}</h4></li>
    {/if}
{/foreach}
```

**Comment by uwetews** [comment]
$smarty.foreach is a special Smarty variable for named Smarty 2 style {foreach} tags to access special properties.
See http://www.smarty.net/docsv2/en/language.function.foreach.tpl and example 7.10.

$smarty.foreach.info in your case is not valid.

I think you did mean {if $info < 4}.

<li><h4>{'- '|cat:$info}</h4></li>  could be simplified like

<li><h4>- {$info}</h4></li>
