### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 2 passed to Smarty_Internal_ParseTree_Template::append_subtree() must be an instance of Smarty_Internal_ParseTree, string given

### ISSUE THREAD

**Issue by sunweaver** [smarty-php/smarty#621]
Hi,

Smarty3's Debian package maintainer here. I just uploaded Smarty3 3.1.36 to Debian unstable (I must admit, without runtime testing, shame on me). With a smarty web applicaiton I am using (GOsa²), I know see the below error message in the browser tab: 

```
Fatal error: Uncaught TypeError: Argument 2 passed to Smarty_Internal_ParseTree_Template::append_subtree() must be an instance of Smarty_Internal_ParseTree, string given, called in /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php on line 2065 and defined in /usr/share/php/smarty3/sysplugins/smarty_internal_parsetree_template.php:41 Stack trace: #0 /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php(2065): Smarty_Internal_ParseTree_Template->append_subtree() #1 /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php(2799): Smarty_Internal_Templateparser->yy_r2() #2 /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php(2894): Smarty_Internal_Templateparser->yy_reduce() #3 /usr/share/php/smarty3/sysplugins/smarty_internal_smartytemplatecompiler.php(128): Smarty_Internal_Templateparser->doParse() #4 /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php(481): Smarty_Internal_SmartyTemplateCompiler->doCompile() #5 /usr/share/php/smarty3/sysplu in /usr/share/php/smarty3/sysplugins/smarty_internal_parsetree_template.php on line 41
```

Downgrading to Debian's previous smarty3 version in unstable (some 3.1.34 version + patches) fixes the issue, but that should not be the option to take.

Debian's smarty3 is special as it does not use the lexer and parser files as provided by upstream, but generates the at "build" time (when the installable packages are created on Debian's build infrastructure). For this, we build-require smarty-lexer (also packaged in Debian. The smarty-lexert version I use for that is 3.1.32.

Locally, I updated the smarty-lexer package being used during smarty3 build to the latest Git version, but that does not fix the above error, either.

Unfortunately, I need help from upstream to get smarty3 fixed in Debian unstable (and upcoming Debian 11). Any feedback / ideas you can share on this?

Thanks so much,
MIke

**Comment by schweer-guest** [comment]
Hi,
similar error while trying to use slbackup-php (only white screen w/o any feedback).
From Apache2 error log:
[Sun Dec 27 18:04:00.174009 2020] [php7:error] [pid 6390] [client 10.0.2.2:33922]

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Smarty_Internal_ParseTree_Template::append_subtree() must be an instance of Smarty_Internal_ParseTree, string given, called in /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php on line 2065 and defined in /usr/share/php/smarty3/sysplugins/smarty_internal_parsetree_template.php:41\nStack trace:\n#0 /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php(2065): Smarty_Internal_ParseTree_Template->append_subtree()\n#1 /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php(2799): Smarty_Internal_Templateparser->yy_r2()\n#2 /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php(2894): Smarty_Internal_Templateparser->yy_reduce()\n#3 /usr/share/php/smarty3/sysplugins/smarty_internal_smartytemplatecompiler.php(128): Smarty_Internal_Templateparser->doParse()\n#4 /usr/share/php/smarty3/sysplugins/smarty_internal_templatecompilerbase.php(481): Smarty_Internal_SmartyTemplateCompiler->doCompile()\n#5 **/usr/share/php/smarty3/sysplu** in /usr/share/php/smarty3/sysplugins/smarty_internal_parsetree_template.php on line 41, referer: https://www/

Please notice the highlighted string (boldface setting from me, definitly no copy/paste error).
Same (truncated?) thing like above (GOsa).

Wolfgang

**Comment by schweer-guest** [comment]
**Is it a smarty_internal_templatecompilerbase issue?**

As far as I was able to find out, the mentioned error seems to be caused by the last two commits concerning smarty_internal_templatecompilerbase.php, see [here](https://github.com/smarty-php/smarty/commits/v3.1.36/libs/sysplugins/smarty_internal_templatecompilerbase.php).
Using the templatecompilerbase version before,  compiling succeeds and the issue is gone.

Tested with slbackup-php, see [related source](https://salsa.debian.org/debian-edu-pkg-team/slbackup-php/-/tree/master/src).

**Or is  the cited slbackup-php code outdated?**

Wolfgang
(who has no real clue about PHP and Smarty)

**Comment by wisskid** [comment]
Hi @sunweaver 
This is a bit of a mess, sorry. At some point in the history of the smarty project, someone started working on the compiled php sources directly. Now they have diverged. We'll have to clean this up, but for now, I made a quick fix in the source .y file that should produce a compiled version that is functionally equivalent to the one normally used in the project.
Please let me know if #625 fixes your problem.
Cheers,
Simon

**Comment by sunweaver** [comment]
@wisskid: awesome. Thanks for the patch. After a quick smoketest based on pre-upload versions of Debian packages (smarty-lexer with all latest upstream commits and smarty3 with the proposed-here patch), GOsa² seems to work again. I assume slbackup-php will also work. I think, your patch closes this issue once merged.

Thanks a lot!

**Comment by wisskid** [comment]
@sunweaver cool! Merged and released it.

**Comment by schweer-guest** [comment]
Confirmed that both GOsa² and slbackup-php work on Debian Bullseye with smarty3 3.1.36-2 from Debian Sid.
