### ISSUE TITLE
Error smarty

### ISSUE THREAD

**Issue by srn87** [smarty-php/smarty#622]
Hello, I have problems for a long time and I have not been able to solve it in any site that I have commented, someone could help me please
`[Wed Dec 23 15:56:06.148166 2020] [proxy_fcgi:error] [pid 9684] [client 194.65.37.73:11438] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /var/www/vhosts/myweb.es/myweb/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177\n', referer: https://myweb.es/moviles....

*I put myweb instead of my original website

**Comment by wisskid** [comment]
Hi @srn87 . I cannot reproduce the problem you are seeing. The problem is likely in the way you call Smarty from your php files. Please post a reproduction scenario and I'll be happy to help.
