### ISSUE TITLE
Chain @return types

### ISSUE THREAD

**Issue by blaaat** [smarty-php/smarty#623]
For Chaining `->assign('x',1)->displa('x');` and IDE/static analysis purposes can I suggest having the proper @return docblock?

so for example: 
`     * @return static current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for
     *                              chaining`
  
instead of: 

`    * @return Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for
 chaining`

**Comment by wisskid** [comment]
@blaaat could you provide a PR?
