### ISSUE TITLE
Wrong version number in 3.1.37?

### ISSUE THREAD

**Issue by Chrissyx** [smarty-php/smarty#628]
- https://github.com/smarty-php/smarty/blob/v3.1.37.1/libs/Smarty.class.php#L30
- https://github.com/smarty-php/smarty/blob/v3.1.37.1/libs/Smarty.class.php#L115
- https://github.com/smarty-php/smarty/blob/master/libs/Smarty.class.php#L30
- https://github.com/smarty-php/smarty/blob/master/libs/Smarty.class.php#L115

Both, doc and const, are set to 3.1.36 instead of 3.1.37(.1), looks like same issue as #597 and #588.

**Comment by wisskid** [comment]
Ugh. Yes. Hardcoded version numbers in source files. We need a build step. Or I need to start remembering this.

**Comment by Chrissyx** [comment]
> We need a build step.

There is already a [make-release.sh](https://github.com/smarty-php/smarty/blob/master/make-release.sh) build tool. ;)

**Comment by wisskid** [comment]
Lol. I wrote that last april, after forgetting to bump the version number... I have no memory

**Comment by wisskid** [comment]
Fixed in 3.1.38
