### ISSUE TITLE
3.1.24 update breaks any possible pre-compiled function support

### ISSUE THREAD

**Issue by Demodian** [smarty-php/smarty#63]
I know this is probably not really a feature, but older versions allowed pre-compiled functions to be used as long as they were in the format:

function smarty_template_function_NAME($_tpl, $params) { ... }

We were able to leverage this prior behavior to hand-optimize template functions and provide standard libraries to work with our multiple projects utilizing Smarty.  Below is the patch to I had to add to restore that functionality to sysplugins/smarty_internal_template.php in callTemplateFunction()..

<pre>
diff smarty_internal_template.php-orig-3.1.24 smarty_internal_template.php
580a581,586
>  // HACK - Need to allow pre-compiled functions to be called
>         if (function_exists($function = 'smarty_template_function_' . $name)) {
>             $function ($_smarty_tpl, $params);
>             return;
>         }
>  // END HACK
</pre>

**Comment by uwetews** [comment]
Because of some problems under hhvm we had to add a unique compilation hash to the internal function names. There may be other changes in future. 
Sorry we can't add code for user hacks in the distribution.
