### ISSUE TITLE
There is posible to strip all with a smarty variable instead of using {strip} ?

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#634]
Hi

I would like to know if exists and I think will be nice to have something to strip all on template display .

Something that do the same with {strip} ... {/strip} used as wrapper in each template?

I appreciate every idea!

Thank You!

**Comment by bhsmither** [comment]
For an application I work with, there is this that we use:
https://github.com/markhughes/HTMLMinify-Smarty

**Comment by chriswheeler** [comment]
Have you see the trimwhitespace output filter? 

https://github.com/smarty-php/smarty/blob/master/libs/plugins/outputfilter.trimwhitespace.php

**Comment by toxicroadkill** [comment]
I personally use this for a working commercial site, it works very well, found it online, and made some minor mods

<?php

function smarty_outputfilter_minify_html( $html, Smarty_Internal_Template $smarty )
{
		$doc												= new DOMDocument();
		$doc->preserveWhiteSpace							= false;
		$errors_value										= libxml_use_internal_errors(TRUE);
		$doc->loadHTML((string)$html);
		libxml_clear_errors();
		libxml_use_internal_errors($errors_value);
		$xpath												= new DOMXPath($doc);
		//
		foreach ($xpath->query('//comment()') as $comment)
			{
				$val = $comment->nodeValue;
				if (strpos($val,'[') !== 0)
					{
						$comment->parentNode->removeChild($comment);
					}
			}
		//
		$doc->normalizeDocument();
		$textnodes											= $xpath->query('//text()');
		$skip												= array('style','pre','code','script','textarea');
		//
		foreach ($textnodes as $t)
			{
				$xp											= $t->getNodePath();
				$doskip										= false;
				foreach ($skip as $pattern)
					{
						if (strpos($xp,"/{$pattern}") !== false)
							{
								$doskip						= true;
								break;
							}
					}
				if ($doskip === true)
					{
						continue;
					}
				//
				$t->nodeValue								= preg_replace('/\s{2,}/',' ',$t->nodeValue);
			}
		//
		$doc->normalizeDocument();
		$divnodes											= $xpath->query('//div|//p|//nav|//footer|//article|//script|//hr|//br');
		//
		foreach ($divnodes as $d)
			{
				$candidates									= array();
				if ( count($d->childNodes))
					{
						$candidates[]						= $d->firstChild;
						$candidates[]						= $d->lastChild;
						$candidates[]						= $d->previousSibling;
						$candidates[]						= $d->nextSibling;
					}
				//
				foreach ($candidates as $c)
					{
						if ($c == null)
							{
								continue;
							}
						if ($c->nodeType == 3)
							{
								$c->nodeValue				= trim($c->nodeValue);
							}
					}
			}
		//
		$doc->normalizeDocument();
		return $doc->saveHTML();
		exit( 0 );}
?>

**Comment by toxicroadkill** [comment]
here is the CSS minifier, in case you have any inline style's
[Uploading outputfilter.minify_css.txt…]()
[Uploading outputfilter.minify_css.txt…]()

**Comment by toxicroadkill** [comment]
and last but not least, a javascript minifier (inline script only)
be absolutely sure lines end with a semicolon, or this module will fail

the above are gathered online, and modified to fix errors and enhancements.

hope everyone finds them useful
[outputfilter.minify_java.txt](https://github.com/smarty-php/smarty/files/5902959/outputfilter.minify_java.txt)

**Comment by toxicroadkill** [comment]
quick and dirty "better select" wrap this around the <select> statement, and it takes care of the work for you.
[modifier.gp_html_select.txt](https://github.com/smarty-php/smarty/files/5902978/modifier.gp_html_select.txt)

**Comment by toxicroadkill** [comment]
yes, I have a whole bunch of plugins...here is one that displays the time remaining in human readable form...

if there is a negative time given, it will email you with the smarty template name that caused the error

simple, works good, no frills

[modifier.gp_time_difference.txt](https://github.com/smarty-php/smarty/files/5902988/modifier.gp_time_difference.txt)

**Comment by yourchoice** [comment]
Yes, but nice is to have directly in smarty that 

In config to can write:
```
define('DEBUG', true);
$smarty->outputMinify(DEBUG ? true : false);
```

**Comment by yourchoice** [comment]
> Have you seen the trimwhitespace output filter?
> 
> https://github.com/smarty-php/smarty/blob/master/libs/plugins/outputfilter.trimwhitespace.php

HI,

Thank You,
I'm trying trimwhitespace. At a first view seems ok. I' will see after many tests

**Comment by yourchoice** [comment]
> > Have you seen the trimwhitespace output filter?
> > https://github.com/smarty-php/smarty/blob/master/libs/plugins/outputfilter.trimwhitespace.php
> 
> HI,
> 
> Thank You,
> I'm trying trimwhitespace. At a first view seems ok. I' will see after many tests

What I see for the moment is that code under <script> tags is not minified ... 

Maybe the same for inline css, even I don't tried because I not use inline css...

I will try and what recommended toxicroadkill

**Comment by chriswheeler** [comment]
Yes I think it will just strip whitespace from the HTML, but not within a SCRIPT tag, as that can affect the execution of the script in some cases I believe. What I tend to do is use mod_pagespeed with Apache to do automatic post-processing of website output, this will do lots of things including inlineing and minifying CSS/JS and even images. Worth looking at HTTP2 as well if performance is your goal.

**Comment by toxicroadkill** [comment]
i gave up using trimwhitespace, it was just not reliable the code i posted rebuilds the dom tree, and re-constructs it

the java minifier, also works great, but only for the java side
