### ISSUE TITLE
{assign} in template is not cached

### ISSUE THREAD

**Issue by m-hume** [smarty-php/smarty#635]
Consider the following
`test.tpl`
```
{assign var="page_title" value="my test page"}

{nocache}
{$page_title|default:"unknown page"}
{/nocache}
```

`test.php`
```
$smarty = new Smarty();
$smarty->setCaching(Smarty::CACHING_LIFETIME_CURRENT);
$smarty->display('./test.tpl');
```

Expected behavior: refreshing the page should show the text "my test page"
Actual behavior: first page load shows "my test page" subsequent loads show "unknown page"

Is this an expected quirk? or just expected?
PS changing the scope of the assignment makes no difference

**Comment by wisskid** [comment]
This is expected. The cached part of the template isn't executed (because it's output is cached).
