### ISSUE TITLE
Do we officially support PHP 8 yet?

### ISSUE THREAD

**Issue by scottchiefbaker** [smarty-php/smarty#642]
I see the version 3.1.39 release and no mention of PHP 8. The README says:

>Smarty can be run with PHP 5.2 to PHP 7.4.

How close are we to officially supporting PHP 8?

**Comment by sapics** [comment]
I guess that it would be near future ;) #629

**Comment by wisskid** [comment]
Correct, work is underway. Expect to release soon. See #629 and the discussion in #593
