### ISSUE TITLE
Smarty 3+ much slower than Smarty 2 (most likely due to config loading)

### ISSUE THREAD

**Issue by CySlider** [smarty-php/smarty#654]
For me the speed difference is extremely severe:

Smarty 2 needs 0.01s while Smarty 3 needs 0.30 seconds.

I tracked down where the time is lost, and one big chunk is when I load my **multiple** config files.

I am using config files for the translation backend and load a lot of different ones for different sections and main/fallback language.

I tracked down the time loss to the repeated render call for each config file I load.

    public function _loadConfigFile(Smarty_Internal_Data $data, $config_file, $sections = null, $scope = 0)
    {
        /* @var \Smarty $smarty */
        $smarty = $data->_getSmartyObj();
        /* @var \Smarty_Internal_Template $confObj */
        $confObj = new Smarty_Internal_Template($config_file, $smarty, $data, null, null, null, null, true);
        $confObj->caching = Smarty::CACHING_OFF;
        $confObj->source->config_sections = $sections;
        $confObj->source->scope = $scope;
        $confObj->compiled = Smarty_Template_Compiled::load($confObj);

        $confObj->compiled->render($confObj);

        if ($data->_isTplObj()) {
            $data->compiled->file_dependency[ $confObj->source->uid ] =
                array($confObj->source->filepath, $confObj->source->getTimeStamp(), $confObj->source->type);
        }
    }

I wonder why it is rendered while still loading config files. If I'm not wrong, Smarty 2 only rendered it once at the end when calling `$smarty->display($template)`

**Comment by CySlider** [comment]
I have to reevaluate the situation as it turns out with deeper digging, that my benchmark script is not working anymore as expected with Smarty 3 as it does with Smarty 2, so the numbers I got are unreliable.

Specifically, i use this line in my outer template file :


    <span id="speed" class="ib">
        Generated in {php}echo  number_format(microtime(true) - Globals::$startTime,5){/php} seconds
    </span>

			
to output the total execution time. Seems like Smarty 3 is outputting the result of this into the cached template instead of the code itself. So the time shown is the time of the first template generation, not the one of using the cached template. I'm a bit scared of this behavioral change and will check the documentation if I missed this.

Anyway. Until I have found out more, It might well be, that this speed drop is just an illusion (hopefully)

**Comment by wisskid** [comment]
Alright, feel free to re-open if you have new info.

**Comment by CySlider** [comment]
Will do. Any way to introduce hot code with Smarty 3, like it was with {php} tag with smarty 2? I fail to do so. Even wring a plugin function did end up with a "run once" result.

**Comment by CySlider** [comment]
NVM. caching was on and it seems it was not on in my smarty 2 config (or not available?)

Sorry for wasting time. Once I have a full picture, I'll leave something on the forum, as I seem to not have been the only one hitting this imaginary issue in the past.
