### ISSUE TITLE
Bitwise operations give incorrect results

### ISSUE THREAD

**Issue by ymTm7KuhCnIjkZAl2x2m2** [smarty-php/smarty#656]
It appears bitwise operations when both numbers aren't in the same format fail. 2&2 and 0x2&0x2 seem to work while 2&0x2 returns 0.

Code:
1: {2&0x2}

Results:
Version 3.1.15:
1:0

Version 3.1.14:
1:2

**Comment by wisskid** [comment]
Interesting. You are obviously right, start at 3.1.15, `0x2` is compiled as a string: `'0x2'`. However since the v3.1.15 is 9 years old and the documentation never mentions support for hex numbers, I propose letting this be.
