### ISSUE TITLE
how to bypass filter on modifiter?

### ISSUE THREAD

**Issue by peon501** [smarty-php/smarty#658]
how to bypass filter on modifier?

Example code:

```
$smarty->registerPlugin("modifier", 'span', 'init_span');

function init_span($content)
{
    $template = <<<HTML
    <span>
        $content
    </span>
HTML;
  return $template;
}

```
now I need to use {$variable|span nofilter}
and I cant just use {$variable|span}

Any ideas on how could I work around it? Without modifying the source code of the smarty lib?

**Comment by wisskid** [comment]
@peon501 I don't think it can be done. The docs state: "Everything except the individual modifier can be disabled with the nofilter flag."

**Comment by wisskid** [comment]
@peon501 hmmm maybe you can use a modfiercompiler plugin?
```
function smarty_modifiercompiler_span($params, $compiler) {
	return "<span>${params[0]}</span>";
}
```
