### ISSUE TITLE
Smarty attribute noscope is recognized in all included tempaltes

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#661]
Smarty attribute noscope is recognized in all included tempaltes.
Smarty version: 3.1.39

//file tpl1.tpl
```
{$foo='bar' noscope}
{include 'tpl2.tpl'}
```

//file tpl2.tpl
`{$foo}`

File tpl2.tpl show value of $foo

Can I set a scope value for $foo var (in tpl1.tpl), to be recognized just in file tpl1.tpl?

**Comment by wisskid** [comment]
@yourchoice I didn't know about this `noscope` flag, it seems undocumented, but it was explained in NEW_FEATURES.txt. As I understand it, it serves to override a scope attribute for the calling (parent) include. So it's not intended to do what you want it to do.

https://www.smarty.net/docs/en/language.function.include.tpl suggests it is not possible to hide variables from tpl2.tpl, although you could unset it by passing it as an attribute as follows:

```
{$foo='bar'}
{include 'tpl2.tpl' foo=null}
```
