### ISSUE TITLE
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls

### ISSUE THREAD

**Issue by toplisek** [smarty-php/smarty#663]
How to fix this issue and an error:
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls
smarty_internal_compilebase.php
Line 75
                $kv = each($mixed);

**Comment by wisskid** [comment]
@toplisek for now, lower your error_reporting level. It will be removed in Smarty4, to be compatible with PHP8.
