### ISSUE TITLE
Unknown encoding when upgrade to the latest version

### ISSUE THREAD

**Issue by toplisek** [smarty-php/smarty#670]
I'm new to this but why are unknown character from a contact form when we upgrade to the latest version

Can be validated inside source code Smarty why is not seen an example character?
đpđpđpđ

Nothing was modified at server except Smarty version and its connection to the web app.
When files are validated, it is also UTF-8 as encoding and Unix format. So, it is related to the settings inside Smarty source code or even some files should be verified as UNIX, UTF-8 inside Smarty source code.

**Comment by wisskid** [comment]
Could you provide an example and the Smarty version you were using before?
