### ISSUE TITLE
Smarty is not compatible with PHP 8.1

### ISSUE THREAD

**Issue by ildar-aim** [smarty-php/smarty#671]
https://github.com/php/php-src/blob/php-8.1.0/UPGRADING

https://www.php.net/index.php#id2021-07-22-1

For example, this patch causes a fatal error

```
aim-server[~/www/smarty/demo]$ gitdiff .
diff --git a/demo/templates/index.tpl b/demo/templates/index.tpl
index 1fbb6d37..1e125e15 100644
--- a/demo/templates/index.tpl
+++ b/demo/templates/index.tpl
@@ -1,6 +1,6 @@
 {config_load file="test.conf" section="setup"}
 {include file="header.tpl" title=foo}
-
+{php}{/php}
 <PRE>
 
 {* bold and title are read from the config file *}
```

```
Fatal error: Type of SmartyCompilerException::$line must be int (as in class Exception) in public_html/smarty/libs/sysplugins/smartycompilerexception.php on line 8
```

The expected error is 
```
Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:public_html/smarty/demo/templates/index.tpl" on line 3 "{php}{/php}" {php}{/php} tags not allowed. Use SmartyBC to enable them <-- thrown in public_html/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 3
```

**Comment by pilif** [comment]
what's really nasty is that fixing the class to work with 8.1 makes it break for < 8.1.

the only fix I see is to either conditionally define the class depending on PHP version or alternatively renaming the property and using the changed name instead.

Which one would you prefer? I can do a PR for both.

**Comment by wisskid** [comment]
See https://github.com/smarty-php/smarty/pull/678

**Comment by genyslt** [comment]
Any news?

**Comment by glensc** [comment]
if the problem being `$line` being re-declared as `public` from inherited `Exception` class, can it be declared as private if used only in that class?

**Comment by wisskid** [comment]
@glensc yes, see #678
