### ISSUE TITLE
Authorization to use a Monochrome Smarty SVG logo

### ISSUE THREAD

**Issue by estebangarviso** [smarty-php/smarty#680]
I need an authorization to use your smarty logo to be uploaded to [https://github.com/simple-icons/simple-icons](https://github.com/simple-icons/simple-icons). Issue: [https://github.com/simple-icons/simple-icons/issues/6671](https://github.com/simple-icons/simple-icons/issues/6671). They are requiring a logo that can be resized and used as monochrome, such an SVG image format.

If you could send a link or file of a monochrome logo where is only the Smarty lamp symbol, I would appreciate it.

My email is e.garvisovenegas@gmail.com

Thank you in advance.

**Comment by wisskid** [comment]
Please see https://www.smarty.net/copyright
