### ISSUE TITLE
unknown tag 'php'

### ISSUE THREAD

**Issue by shashistack** [smarty-php/smarty#683]
I am using Smarty 4 with PHP 8 in my application, and I came across the error like: unknown tag 'php'.
I have enabled PHP tag using: $smarty->allow_php_tag=true; But still I get that error.
I could not find any class variable like: **$php_handling** either.
Is that something related to backward compatibility of Smarty, or the PHP tags are no longer supported?

**Comment by wisskid** [comment]
@shashistack support for the {php} tag has been removed, please see https://github.com/smarty-php/smarty/blob/master/CHANGELOG.md
