### ISSUE TITLE
{foreach} properties are not available in included templates

### ISSUE THREAD

**Issue by ohreally** [smarty-php/smarty#685]
Hi,

{foreach} properties are not available in files that are included inside the {foreach} loop.

A simple example:

Main template:
```
{* thebeatles.tpl *}
{foreach ['john', 'paul', 'george', 'ringo'] as $beatle}
{include 'abeatle.tpl'}
{/foreach}
```

Included template that works:
```
{* abeatle.tpl *}
{$beatle}
```

Result:

> john paul george ringo

Included template that errors:
```
{* abeatle.tpl *}
{$beatle@iteration}
```

Result:

> Warning: Undefined property: Smarty_Variable::$iteration in /path/to/templates/compiled/1776ef426e7316da9a83f348156978ac2e5f6467_0.file.abeatle.tpl.php on line 24

The error message is repeated for each iteration.

A similar message is given for the other properties.

I'm using Smarty 4.0.0, BTW.

Cheers,
  Rob

**Comment by joelmiguelvalente** [comment]
Hola, pruébalo de esta manera!
```
{foreach ['john', 'paul', 'george', 'ringo'] as $beatle}
{include "$beatle.tpl"}
{/foreach}
```
Las comillas simples solo es válido para `{include file='$beatles.tpl'}`

La manera corta es con comillas doble `{include "$beatle.tpl"}`

**Comment by wisskid** [comment]
You could pass these along as follows:
```
{include 'abeatle.tpl' iteration=$beatle@iteration}
```
