### ISSUE TITLE
Support policy of Smarty 3.x vs 4.x

### ISSUE THREAD

**Issue by marclaporte** [smarty-php/smarty#686]
I am thrilled [Smarty 4.x has been released](https://packagist.org/packages/smarty/smarty#v4.0.0) and is now supporting PHP 8.0 [and soon PHP 8.1](https://github.com/smarty-php/smarty/pull/678)

[We](http://tiki.org) will soon upgrade to Smarty 4 for an upcoming major version. I am wondering what are the plans for supporting 3.x for security patches, while in parallel continuing innovation in Smarty 4. As a reference, [here is our lifecycle](https://tiki.org/Versions).

Thank you!

**Comment by WinterSilence** [comment]
@marclaporte if you look [chengelog](https://github.com/smarty-php/smarty/blob/v4.0.0/CHANGELOG.md), you will see that new in v4 is only PHP 8 support, v4 less functional than v3 )))

**Comment by wisskid** [comment]
I intend to maintain security support for 3.x at least for as long as PHP7.x is supported.
