### ISSUE TITLE
Smarty tries to map a custom error handler to an internal method name

### ISSUE THREAD

**Issue by Synchro** [smarty-php/smarty#696]
I'm using Smarty templates in a user-facing situation, so I need to do syntax checks in my UI. To help with this I define an error handler method on my Smarty child class:

    protected function errorHandler(int $errno, string $errstr, string $errfile, int $errline, ?array $errcontext = null): bool

and I wrap my Smarty calls like this:

    set_error_handler([$this, 'errorHandler']);
    try {
        $this->fetch(...);
    } catch (SmartyCompilerException $e) {
        ...
    } catch (SmartyException $e) {
        ...
    }
    restore_error_handler();

Since updating to Smarty 4, I've started getting this error:

    undefined extension class 'Smarty_Internal_Method_ErrorHandler'

I have confirmed (by renaming the error handler) that this is being mapped automatically from the errorHandler method. If I don't install the error handler, the error does not occur.

What's going on here? Do I need to install an error handler, or trap errors in some other way?

**Comment by wisskid** [comment]
Could you provide a complete example that reproduces this error? And include your PHP version? I'll have a look at it.

**Comment by Synchro** [comment]
Here you go:

```php
<?php

require '../vendor/autoload.php';

class TestSmarty extends Smarty {
    protected function errorHandler(int $errno, string $errstr, string $errfile, int $errline, ?array $errcontext = null): bool
    {
        return true;
    }
    public function test($template): string
    {
        set_error_handler([$this, 'errorHandler']);
        $out = $this->fetch($template);
        restore_error_handler();
        return $out;
    }
}

$s = new TestSmarty();
$s->test('test.tpl');
```
The template file doesn't actually have to exist as the error seems to occur before it tries to load it. Running that gives me this error:

```
Fatal error: Uncaught  --> Smarty: undefined extension class 'Smarty_Internal_Method_Bananas' <-- 
  thrown in /Users/marcus/test/vendor/smarty/smarty/libs/sysplugins/smarty_internal_undefined.php on line 62

SmartyException: undefined extension class 'Smarty_Internal_Method_Bananas' in /Users/marcus/test/vendor/smarty/smarty/libs/sysplugins/smarty_internal_undefined.php on line 62
```

I'm running PHP 8.1, but this doesn't look like an 8.1 issue to me.

**Comment by wisskid** [comment]
When specifying a callback in array notation (ie. `[$this, 'bananas'])`) the method must be public, because it might be triggered from outside the class. It does here. This then causes Smarty to go look for a magic method, which it cannot find.
Change `protected function bananas` to `public function bananas` and you will be fine.

**Comment by Synchro** [comment]
Ah, that explains it. I didn't want to have it triggerable from outside, hence the protected signature. I've tried this and it's much happier now, thanks.
