### ISSUE TITLE
With PHP 8.1.0 : Deprecated: Implicit conversion from float 14.5 to int loses precision in Smarty/libs/plugins/modifier.truncate.php on line 45 and 46 and 59

### ISSUE THREAD

**Issue by 5cms** [smarty-php/smarty#699]
For example try {$long_text|truncate:30:'…':true:true}

To fix - replace all:

$length / 2 

with:

intval($length / 2)

in Smarty/libs/plugins/modifier.truncate.php

**Comment by pH-7** [comment]
With what version are you having that issue @5cms? Is it with [v4.0.0](https://github.com/smarty-php/smarty/releases/tag/v4.0.0)?

**Comment by 5cms** [comment]
> With what version are you having that issue @5cms? Is it with [v4.0.0](https://github.com/smarty-php/smarty/releases/tag/v4.0.0)?

Yes v.4.0.0

Just try for example {$long_text|truncate:30:'…':true:true}

**Comment by marclaporte** [comment]
Related: https://github.com/smarty-php/smarty/pull/678

**Comment by pH-7** [comment]
> > With what version are you having that issue @5cms? Is it with [v4.0.0](https://github.com/smarty-php/smarty/releases/tag/v4.0.0)?
> 
> Yes v.4.0.0
> 
> PHP 8.1.0
> 
> Just try for example {$long_text|truncate:30:'…':true:true}

Thanks! This needs a fix indeed 👍
