### ISSUE TITLE
 Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/vhosts/secretdomainname/subdomains/secretsubdomain/httpdocs/vendor/smarty/smarty/libs/Smarty.class.php on line 1385

### ISSUE THREAD

**Issue by MarvinMatherson** [smarty-php/smarty#700]
When running 'echo $smarty->testInstall();' when setting up project I am recieving this error.

I have added a screenshot of the lines that the error has highlighted.
        
<img width="1118" alt="Screenshot 2022-01-03 at 20 27 03" src="https://user-images.githubusercontent.com/55834622/147976896-cca9d7d9-4e5d-48d1-939c-4a4cd7eac2d9.png">
}

**Comment by wisskid** [comment]
You screenshot highlights line 1358, not 1385. Considering the actual line 1385, I suppose you are not using a PHP version between 7.1 and 8.0.
