### ISSUE TITLE
PHP8.1 Deprecated Funtion strftime()

### ISSUE THREAD

**Issue by rexop** [smarty-php/smarty#707]
Hi.

I'm getting this deprecated-error with Smarty 4.0.0 on PHP 8.1:

Deprecated: Function strftime() is deprecated in /smarty/sysplugins/smarty_internal_runtime_codeframe.php on line 48

**Comment by viamuli** [comment]
Duplicate: https://github.com/smarty-php/smarty/issues/672
Please check issues before opening a new one.
