### ISSUE TITLE
PHP 8.1 PHP Deprecated:  mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/smarty/smarty/libs/plugins/modifier.truncate.php on line 33

### ISSUE THREAD

**Issue by hkargv** [smarty-php/smarty#710]
PHP 8.1 PHP Deprecated:  mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/smarty/smarty/libs/plugins/modifier.truncate.php on line 33

**Comment by avatec** [comment]
before
`if (Smarty::$_MBSTRING) {`

add this:

       ```
 if(empty( $string )) {
            return;
        }
```
