### ISSUE TITLE
New Smarty Variable or asset

### ISSUE THREAD

**Issue by jondavis0787** [smarty-php/smarty#712]
in smarty_internal_compile_private_special_variable.php version 4.04 could you add something like this.

` case 'template_path':
                   
                    return 'str_ireplace($_SERVER["DOCUMENT_ROOT"], "", str_ireplace($_smarty_tpl->source->name, "", $_smarty_tpl->source->filepath))';`

This will help to return something like /templates/default main case will be to include like css files or something of that nature or could we get a function called asset with path and if multiple templates are selected the one that has it will win and return /templates/default2/media/css/test.css if not in default2 it will return something like /templates/default/media/css/test.css usage would be asset('/media/css/test.css').

**Comment by wisskid** [comment]
Sorry, I can't follow you. Is there a problem you are trying to fix?

**Comment by wisskid** [comment]
Closed because of inactivity.
