### ISSUE TITLE
math equation return warning: math: illegal character for : {math equation="x > 0 ? x : 1" x=$start assign=start}

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#719]
math equation return warning: math: illegal character for : 

`{math equation="x > 0 ? x : 1" x=$start assign=start}`

Problem here is Ternary Operator .... On previous version worked well!

**Comment by wisskid** [comment]
Please consider switching to `min(1, x)` here. We've tried to make the `{math}` function safer, and re-introducing control flow logic seems to wrong way to do so.
