### ISSUE TITLE
error smarty 4.0 and 4.1 PHP 8.1.2

### ISSUE THREAD

**Issue by lmramaya** [smarty-php/smarty#728]
hi,

I get this error smarty/libs/plugins/modifier.truncate.php:45] Implicit conversion from float 20.5 to int loses precision

{$val.my_name|upper|truncate:43:'..':true:true}

in PHP 7.4.27 it works fine

ubuntu 20.4.3, nginx 1.18 php8.1-fpm and php7.4-fpm

tks

**Comment by wisskid** [comment]
Has already been fixed in https://github.com/smarty-php/smarty/issues/699
