### ISSUE TITLE
Any way to get old version @ PHP8.1 or new versions supporting old templates?

### ISSUE THREAD

**Issue by garbus** [smarty-php/smarty#729]
Hello.

I am trying to upgrade my old app to PHP8.1. I stuck on such a problem:

Old version of Smarty (say 2.6.33) does not run at PHP8.1 correctly (example - problem with strftime() function). 
I fixed it quickly by changing this to date() function, but there is no official release so composer could not be automated in this case with the official release.

Second try was to get 4.1.0 but in this case I have a problem with old templates. For example {php} tag is not supported and I guess not only this problem. Found solution to use SmartyBC class - which probably is not included any more with the newest releases.

Is there any way to run this with any official release?

Is it possible to make commit to old source changing this strftime() function (say to v.2.6.33 or to create new v.2.6.34) and release old version running @ PHP8 (Yes, it seems to be that easy!) or not really?

Cheers!

**Comment by wisskid** [comment]
Yes it would be possible to change v2, but there seems to be little reason to do so. The strftime "error" is really a deprecation notice. strftime will be in PHP as long as you do not upgrade to PHP9.

Smarty v2 is a legacy version, it  is officially not getting security support. We'll try to keep Smarty 3 usable and secure for the time being. New features (such as support for newer PHP-versions) are for Smarty 4+.

**Comment by garbus** [comment]
Oh, @wisskid you are right.
Actually I don't know why I stuck on this firstly. Probably something else crashed my app and I got this notice as a cause.
Installed package smarty/smarty (composer, packagist) in version 2.6.33 and it seems to work fine with PHP Version 8.1.2!
Amazing. Thank you!
