### ISSUE TITLE
Can the method "getVariableValue" be added to "Smarty_Internal_Data" (smarty_internal_data.php)

### ISSUE THREAD

**Issue by killrawr** [smarty-php/smarty#739]
Can you please add this method "getVariableValue" to "Smarty_Internal_Data"

    /**
     * Get the Variable Value
     * @param string variable_name
     * @return mixed
     */
    public function getVariableValue($variable_name)
    {
        
        $variable_item = $this->getVariable($variable_name);
        
        if (is_object($variable_item) && property_exists(get_class($variable_item), 'value')) {
            $variable_result = $variable_item->value;
        } else {
            $variable_result = null;
        }
        
        return $variable_result;
    }

It is lazy way of grabbing value from Variable instead of `$myValue = $smarty_tpl->getVariable('myvalue')->value;`

**Comment by wisskid** [comment]
Wouldn't that be [getTemplateVars](https://smarty-php.github.io/smarty/programmers/api-functions/api-get-template-vars.html)?
