### ISSUE TITLE
<? tag causes infinite loop

### ISSUE THREAD

**Issue by Visualq** [smarty-php/smarty#74]
Using <? In a tpl file crashes causes an infinite loop. It happens with a clean install of smarty 3.1.27. 

This tag is used in XML files which are rendered using a Smarty template.
Even though I have public $php_handling set to self::PHP_PASSTHRU;. A working solution for now is to wrap the tag in {literal}{/literal} or let Smarty print the tag for me {"<?"}

**Comment by uwetews** [comment]
Do you have some example code showing this problem?

Could you try the dev-master version? There have been a couple of bugfixes and parser changes which could be related.

**Comment by Visualq** [comment]
Master branch still causes the problem.

Shortest way to replicate:

<?php
include('Smarty.class.php');
$smarty = new \Smarty();
$smarty->fetch('eval:<??>');

It appears that it requires the ?> tag in order to make it fail .

**Comment by uwetews** [comment]
The fix is now in dev-master
