### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 3 passed to Smarty_Internal_Method_RegisterResource::registerResource()

### ISSUE THREAD

**Issue by sidharthmohanty** [smarty-php/smarty#744]
Fatal error: Uncaught TypeError: Argument 3 passed to Smarty_Internal_Method_RegisterResource::registerResource() must be an instance of Smarty_Resource, array given, called in /app/libs/smarty/sysplugins/smarty_internal_extension_handler.php on line 133 and defined in /app/libs/smarty/sysplugins/smarty_internal_method_registerresource.php:33 Stack trace: #0 /app/libs/smarty/sysplugins/smarty_internal_extension_handler.php(133): Smarty_Internal_Method_RegisterResource->registerResource() #1 /app/libs/smarty/sysplugins/smarty_internal_data.php(270): Smarty_Internal_Extension_Handler->_callExternalMethod() #2 /app/libs/smarty/sysplugins/smarty_resource.php(92): Smarty_Internal_Data->__call() #3 /app/libs/smarty/sysplugins/smarty_template_source.php(140): Smarty_Resource::load() #4 /app/libs/smarty/sysplugins/smarty_template_source.php(181): Smarty_Template_Source->__construct() #5 /app/libs/smarty/sysplugins/smarty_internal_template.php(168): Smarty_Template_Source::load() #6 /app/libs/smarty/Smarty.class.php(987): Smarty_I in /app/libs/smarty/sysplugins/smarty_internal_method_registerresource.php on line 33

I have dowloaded the new smarty version and after upgrading my old one, I got this issue.

**Comment by uu1467** [comment]
Hi,
did you find a solution for it or is a bugfix out there ?
May the reason is that plugin resources can not longer be registered this way ?

**Comment by sidharthmohanty** [comment]
Hi,

I couldn't find a solution for this, I found that whenever I tried to use the htmlmimeemail class, it's throwing the above error.

**Comment by wisskid** [comment]
Could you provide reproduction steps? e.g. what template are you using?
