### ISSUE TITLE
htmlspecialchars() - Deprecation warning in php 8.1

### ISSUE THREAD

**Issue by MaximilianKresse** [smarty-php/smarty#748]
# Code:
```
$smarty = new \Smarty();
$smarty->setEscapeHtml(true);

$smarty->assign('value', null);

var_dump($smarty->fetch('string:{$value}'));
```

# Expected output:
```
string(0) ""
```

# Output in php >= 8.1:
```
string(215) "
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in ...\7f3eb64ac896f10d0f0414cf415a097993be285b_2.string.php on line 18
"
```

I could fix this problem with a "default"-modifier but I think smarty should be robust enough to prevent this kind of errors. I see the problem in [this line here](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_compile_private_print_expression.php#L96).
The ```{$output}``` should be casted to string to prevent this error.

**Comment by wisskid** [comment]
Thanks @MaximilianKresse. Closing this in favor of https://github.com/smarty-php/smarty/issues/750
