### ISSUE TITLE
PHP 8.0.16: Get whitescreen, but works well on PHP 7.4.28

### ISSUE THREAD

**Issue by mySmarty** [smarty-php/smarty#752]
I'm using 3.1.44 SmartyBC because my beginning was with the version 3.09.  
What I have to change or delete (like literal or others) to get it work on PHP 8.0?
And another question: is it planed to make a SmartyBC.class in the latest version 4.1.0?
Thanks and best regards

**Comment by Baffos** [comment]
Got a similar Problem on PHP 8.x with the Whitescreen today.

Error Message:
`PHP Fatal error:  Uncaught TypeError: date_format(): Argument #1 ($object) must be of type DateTimeInterface, int given`

Code:
`{$smarty.now|date_format:'%Y'}`

On PHP 7.4, everything works fine.

**Comment by scottchiefbaker** [comment]
Any updates on this @mySmarty?

**Comment by mySmarty** [comment]
No. For the moment I'm back to PHP 7.4.28.
Before I've tried to find PHP errors step by step. I also deleted sections of php code as a test. Bit by bit parts became visible, but never completely. At some point I gave up.

**Comment by scottchiefbaker** [comment]
It's hard to troubleshoot the issue without some more info. Are you able to get us some logs from the time the error occurs?

**Comment by mySmarty** [comment]
Ok. I'll try that in the near future. Here it is 9 hours later. So I have to say good night.. Thanks.
