### ISSUE TITLE
Debug console not working under Firefox (Version 99, Ubuntu)

### ISSUE THREAD

**Issue by obw** [smarty-php/smarty#753]
I work normally with Firefox (actual: Version 99 under Ubuntu) and wanted to debug a Template and use the "debug console", but it's not working, in the JS-Console of Firefox I see:
```
Uncaught TypeError: _smarty_console is null
    <anonymous> http://localhost:8090/de/Home:21
Home:21:5
```
As work around I use Chromium, where it's works just fine!

Regards

**Comment by wisskid** [comment]
Works fine for me in Firefox 99, Ubuntu. You may have to allow popups.
