### ISSUE TITLE
Whitescreen with PHP 8.0 and Smarty 4.1

### ISSUE THREAD

**Issue by reovero** [smarty-php/smarty#757]
I tried to update my project to PHP 8.0 and Smarty 4.1 version but i have found this error in my template.

Fatal error:
Uncaught TypeError:
Cannot access offset of type string on string in
/templates_c/ita_^23f8b7aa4621fc701b2d03b12af9f4efa4db27f4_0.file.staff_index.tpl.php:85 Stack trace:
#0 /bin/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_3666206546277e8bfc1a7f6_45647236->callBlock(Object(Smarty_Internal_Template))
#1 /bin/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_3666206546277e8bfc1a7f6_45647236), Object(Smarty_Internal_Template))
#2 /bin/libs/sysplugins/smarty_internal_runtime_inheritance.php(186): Smarty_Internal_Runtime_Inheritance->process(Object(Smarty_Internal_Template), Object(Block_3666206546277e8bfc1a7f6_45647236), Object(Block_201776996277e525d02616_86282809))
#3 /bin/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(Smarty_Internal_Template), Object(Block_201776996277e525d02616_86282809))
#4 /templates_c/ita_^46631cd058ba13a5b601d32c3388ec5f3c5597e2_0.file._master.tpl.php(77): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(Smarty_Internal_Template), 'Block_201776996...', 'meta')
#5 /bin/libs/sysplugins/smarty_template_resource_base.php(123): content_6277e525d0ab34_31073089(Object(Smarty_Internal_Template))
#6 /bin/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#7 /bin/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#8 /bin/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#9 /bin/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender('_master.tpl', NULL, 'ita-', 0, 3600, Array, 2, false, NULL, NULL)
#10 /templates_c/ita_^23f8b7aa4621fc701b2d03b12af9f4efa4db27f4_0.file.staff_index.tpl.php(52): Smarty_Internal_Runtime_Inheritance->endChild(Object(Smarty_Internal_Template), '_master.tpl')
#11 /bin/libs/sysplugins/smarty_template_resource_base.php(123): content_6277e8bfc54cf1_49432140(Object(Smarty_Internal_Template))
#12 /bin/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#13 /bin/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#14 /bin/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1)
#15 /bin/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#16 /index.php(111): Smarty_Internal_TemplateBase->display('staff_index.tpl')
#17 {main} thrown in /templates_c/ita_^23f8b7aa4621fc701b2d03b12af9f4efa4db27f4_0.file.staff_index.tpl.php on line 85

I have found the part of the code that is causing this problem.
This is the proble:
{$page.img[0].img}

If my img[0] not contain any element inside (like img) so in this case i have this error.
I can fix this error by add an if condition like:
{if !empty($page.img[0].img)}
{$page.img[0].img}
{/if}

In this mode work but i would like to understand why if i run this project with PHP 7.4 i haven't this problem.

Thank you

**Comment by bhsmither** [comment]
PHP8 has greater restrictions and is less forgiving about this specific problem and several other things.

**Comment by reovero** [comment]
Hi, thank you for your reply.
I can't understand though why i can see this error with php 8 only in smarty template (.tpl files).

For example.

I have this array:
$page = array(
   'img' => array(
       0 => array(...),
       1 => ,
       2 => 
   )
);

So i have 3 elements inside my IMG element but only 0 have an subarray

If i do that in my php file work well.
if($page['img'][1]){
    echo "element exists";
} else {
    echo "element not exists";
}

If i do that in smarty tpl template:
{if $page['img][1]}

This breaks my page and goes into fatal error.
So I can't understand what changes between the two conditions. Could it be something within smarty?

I would like to understand this because, in this way I need to change all the if conditions of my functions in all the pages otherwise the templates are in error.

Thank you

**Comment by scottchiefbaker** [comment]
Try:

    {if !empty($page['img'][1])) { ... }

You probably just need to lower your error handling in PHP/Smarty

**Comment by reovero** [comment]
> ```
> {if !empty($page['img'][1])) { ... }
> ```

Yes, if i add !empty condition work but i have a lot of TPL file to change in various projects.
So i want to understand first if there is another way or if there is a bug of Smarty 4 version.

Because i not understand why if in the same project if i insert this simple php condition in php file work:
if($page['img'][1]){ ... }

but if i write this same condition in TPL file not work (Fatal error: Uncaught TypeError: Cannot access offset of type string on string in...)
{if $page['img'][1]) { ... }

Sorry, what do you means with: error handling in PHP/Smarty

Because i have a Fatal error so i don't know how i can set error to lower. There is a way to do that in Smarty?

Thank you for your support

**Comment by scottchiefbaker** [comment]
This is a PHP error, not a smarty error. PHP changed the classification of certain types of errors in newer versions of PHP.

Look at: https://www.php.net/manual/en/function.error-reporting.php

**Comment by reovero** [comment]
Ok thank you, so there is not way for me :)
I need to insert a lot of !empty condition in my tpl files :)

Thank You

**Comment by bhsmither** [comment]
Is this file:
```
/templates_c/ita_^23f8b7aa4621fc701b2d03b12af9f4efa4db27f4_0.file.staff_index.tpl
```
still available? If so, please let us see line 85.

**Comment by bhsmither** [comment]
You wrote:
```
If i do that in smarty tpl template:
{if $page['img][1]}
```
Is this an accurate? The bracket contents is missing the closing apostrophe.
