### ISSUE TITLE
$smarty->muteUndefinedOrNullWarnings(); doesn´t work

### ISSUE THREAD

**Issue by SebastianGl1** [smarty-php/smarty#759]
Well, I do:

`$this->tmpl = new Smarty();`
`$this->tmpl->setTemplateDir(Config::ROOTPATH);`
`$this->tmpl->setCacheDir(Config::SERVERURL.'/template/_cache');`
`$this->tmpl->setCompileDir(Config::SERVERURL.'/template/_compiled');`
`$this->tmpl->setErrorReporting(E_ALL & ~E_NOTICE);`
`$this->tmpl->muteUndefinedOrNullWarnings();`

My normal PHP error_reporting is: 

`set_error_handler('handleError');`
`set_exception_handler('handleError');`
`error_reporting(E_ALL);`

My personal error_handler:

`function handleError($errno, $errstr = null, $errfile = null, $errline = null, $errcontext = null)`
`{`
    `echo "<pre style='margin:0;padding:0;'>";`
     `echo "(L".$errno.") ".$errfile."(".$errline."): ".$errstr;`
     `echo "</pre>";`
`};`

But I get SMARTY Errors of undefined:

(L8) /var/www/vhosts/arbeitszeitpro.de/dev_session/_lagerpro/template/_compiled/205ac43492441da978e04a6dd485244739e874ac_0.file.manuell.tpl.php(169): Undefined index: lieferantenArt
(L8) /var/www/vhosts/arbeitszeitpro.de/dev_session/_lagerpro/template/_compiled/205ac43492441da978e04a6dd485244739e874ac_0.file.manuell.tpl.php(169): Trying to get property 'value' of non-object
(L8) /var/www/vhosts/arbeitszeitpro.de/dev_session/_lagerpro/template/_compiled/205ac43492441da978e04a6dd485244739e874ac_0.file.manuell.tpl.php(170): Undefined index: lieferant
(L8) /var/www/vhosts/arbeitszeitpro.de/dev_session/_lagerpro/template/_compiled/205ac43492441da978e04a6dd485244739e874ac_0.file.manuell.tpl.php(170): Trying to get property 'value' of non-object
(L8) /var/www/vhosts/arbeitszeitpro.de/dev_session/_lagerpro/template/_compiled/205ac43492441da978e04a6dd485244739e874ac_0.file.manuell.tpl.php(170): Trying to get property 'strName' of non-object

My Smarty Version 4.0.0 but I testet 4.1.1 too

**Comment by brondibur** [comment]
@wisskid Facing the same issue. This is what I've used:
```
$tpl = new Smarty;
$tpl->setErrorReporting(E_ALL & ~E_NOTICE);
$tpl->muteUndefinedOrNullWarnings();
```
But all undefined array key errors are being logged still.

Version: 4.1.1

**Comment by wisskid** [comment]
This is expected behavior. The methods doesn't make the errors go away, it lowers their error level. More specifically, it converts E_WARNINGS for "undefined array key" and "trying to read property of null" errors to E_NOTICE to bring template behavior for PHP8 in line with how it used to be in PHP7.

**Comment by wisskid** [comment]
Reopening this to take another look. I might have been too quick to dismiss it.

**Comment by wisskid** [comment]
Disregard my previous comment. It is not expected behavior. But it's also not something I can reproduce (using PHP8.0).
```
<?php
set_error_handler('handleError');
set_exception_handler('handleError');
error_reporting(E_ALL);

require_once "vendor/autoload.php";

$smarty = new Smarty();
$smarty->assign('definedVar', 13);
$smarty->setErrorReporting(E_ALL & ~E_NOTICE);
$smarty->muteUndefinedOrNullWarnings();

echo $smarty->display('string:This is defined: {$definedVar}. This is undefined: {$undefined}.');


function handleError($errno, $errstr = null, $errfile = null, $errline = null, $errcontext = null)
{
	echo "<pre style='margin:0;padding:0;'>";
	echo "(L".$errno.") ".$errfile."(".$errline."): ".$errstr;
	echo "</pre>";
}
```
no errors

But with
```
<?php
set_error_handler('handleError');
set_exception_handler('handleError');
error_reporting(E_ALL);

require_once "vendor/autoload.php";

$smarty = new Smarty();
$smarty->assign('definedVar', 13);
$smarty->setErrorReporting(E_ALL & ~E_NOTICE);
//$smarty->muteUndefinedOrNullWarnings();

echo $smarty->display('string:This is defined: {$definedVar}. This is undefined: {$undefined}.');


function handleError($errno, $errstr = null, $errfile = null, $errline = null, $errcontext = null)
{
	echo "<pre style='margin:0;padding:0;'>";
	echo "(L".$errno.") ".$errfile."(".$errline."): ".$errstr;
	echo "</pre>";
}
```

I see the errors from your custom error handler. 

If you have additional information, please re-open!
