### ISSUE TITLE
Smarty can not parse html correctly but it is working when we changed code alignment

### ISSUE THREAD

**Issue by shohanjh09** [smarty-php/smarty#761]
Dear concern, 

We are using  **Smarty version: 3.1** and found an issue where smarty can not parse the HTML code correctly without formatted code. 

For example: The following code snap is not formatted where smarty failed to parse correctly.

**Not formatted code snap:**
`<p style="word-wrap: break-word;">{$job.job_desc_less}{if $job.job_desc_more}<span id="prop-read-less">...</span><span id="prop-read-more" style="display: none;">{$job.job_desc_more}</span>
                                    <br><br><a href="javascript:void(0);" id="prop-read-more-less" class="nav-toggle">Read More</a>{/if}</p>`

**Smarty parse the following from the above code:** 
`<p style="word-wrap: break-word;">This is a beautiful song that moved me listening to it. Flooded my mind with all kinds of thoughts, imagery and even some slight memories.<br>
<br>
This is what I see would be needed listening to the demo<br>
<br>
From 00:00 to 00:34 guitar picking<br>
from 00:35 to 01:38 One guitar strumming<br>
From 01:39 to 2:00 guitar picking<br>
from 02:01 to 03:18 One guitar strumming<br>
From 03:18 to 03:30 maybe arpeggios on guitar instead of strumming<br<span id="prop-read-less" style="display: none;">...<span id="prop-read-more" style="display: inline;">/&gt;
from 03:30 to end silence<br>
<br>
I think one guitar would suffice on the strumming parts and it may even be enough on the picking parts. The song speaks very well for itself. We can try it with just the one guitar, and see how it comes along and always add the second if needs it. I also thought you could consider a nylon guitar for one or both of the picking parts if you want to experiment with the sounds.<br>
<br>
Normally I would charge for multiple track recordings, but if we can communicate through the process we can probably knock this out reasonably quickly. Plus I like the song. So I am willing to keep this within your budget.<br>
<br>
I will send you one guitar picking the lead and strumming (as above), plus a second track of guitar doubling the strumming through the song over both parts, and we can auditioning a nylon if you like.<br>
<br>
I also play other instruments like bass and mandolin too if you need me for anything else, so please keep that in mind now and in the future!</span>
                                    <br><br><a href="javascript:void(0);" id="prop-read-more-less" class="nav-toggle">Read Less</a></br<span></p>`

                                    
For example: The following code snap is formatted where smarty can parse correctly.

**Code Snap with formatting:**
`<p style="word-wrap: break-word;">{$job.job_desc_less}
                                        {if $job.job_desc_more}
                                            <span id="prop-read-less">...</span>
                                            <span id="prop-read-more" style="display: none;">{$job.job_desc_more}</span>
                                            <br><br>
                                            <a href="javascript:void(0);" id="prop-read-more-less" class="nav-toggle">Read More</a>
                                        {/if}
                                    </p>`
                                    
**Parsed output with the formatted code:**
`<p style="word-wrap: break-word;">This is a beautiful song that moved me listening to it. Flooded my mind with all kinds of thoughts, imagery and even some slight memories.<br>
<br>
This is what I see would be needed listening to the demo<br>
<br>
From 00:00 to 00:34 guitar picking<br>
from 00:35 to 01:38 One guitar strumming<br>
From 01:39 to 2:00 guitar picking<br>
from 02:01 to 03:18 One guitar strumming<br>
From 03:18 to 03:30 maybe arpeggios on guitar instead of strumming<br <span="" id="prop-read-less" style="display: none;">...
                                            <span id="prop-read-more" style="display: inline;">/&gt;
from 03:30 to end silence<br>
<br>
I think one guitar would suffice on the strumming parts and it may even be enough on the picking parts. The song speaks very well for itself. We can try it with just the one guitar, and see how it comes along and always add the second if needs it. I also thought you could consider a nylon guitar for one or both of the picking parts if you want to experiment with the sounds.<br>
<br>
Normally I would charge for multiple track recordings, but if we can communicate through the process we can probably knock this out reasonably quickly. Plus I like the song. So I am willing to keep this within your budget.<br>
<br>
I will send you one guitar picking the lead and strumming (as above), plus a second track of guitar doubling the strumming through the song over both parts, and we can auditioning a nylon if you like.<br>
<br>
I also play other instruments like bass and mandolin too if you need me for anything else, so please keep that in mind now and in the future!</span>
                                            <br><br>
                                            <a href="javascript:void(0);" id="prop-read-more-less" class="nav-toggle">Read Less</a>
                                                                            </p>`

The issue we faced are recorded in the in the following screencast:
Screencast: https://www.screencast.com/t/6fu0pWnl3yeL 

Note: We have used the following js for read more / read less in the screencast:
    
    var propReadLess = document.getElementById("prop-read-less");
    var propReadMore = document.getElementById("prop-read-more");
    var propReadLessAndMore = document.getElementById("prop-read-more-less");

    if (propReadLess.style.display === "none") {
        propReadLess.style.display = "inline";
        propReadLessAndMore.innerHTML = "Read More";
        propReadMore.style.display = "none";
    } else {
        propReadLess.style.display = "none";
        propReadLessAndMore.innerHTML = "Read Less";
        propReadMore.style.display = "inline";
    }`

Can have a look at the above issue and take an action item to fix the problem asap.

Thanks 
Shohanur Rahman

**Comment by scottchiefbaker** [comment]
This is a complex issue, and you have a lot of data here. I think it would be most helpful if you could break this down into a smaller test case. 

I loaded your sample template on my Smarty 4.x installation and it parses just fine.

PHP
```
$job = ['job' => ['job_desc_less' => "Less body", "job_desc_more" => "More body"]];
$smarty->assign($job);
```

TPL
```
<p style="word-wrap: break-word;">{$job.job_desc_less}{if $job.job_desc_more}<span id="prop-read-less">...</span><span id="prop-read-more" style="display: none;">{$job.job_desc_more}</span> <br><br><a href="javascript:void(0);" id="prop-read-more-less" class="nav-toggle">Read More</a>{/if}</p>
```

The devs aren't going to be able to fix this problem until it's a simpler and repeatable test case. Start slowly removing pieces of code or template elements until it "works" then we can try and come up with a solution.

**Comment by wisskid** [comment]
@shohanjh09  @scottchiefbaker  is right here. Very hard to establish what is going on here. But my guess would be that your value for `$job.job_desc_less` ends in "<br" which causes the rest of the HTML to be invalid.

**Comment by shohanjh09** [comment]
@scottchiefbaker,
I have uploaded the full data below. But the problem here is whether it should work or not but both formatted/not formatted code should behave the same way. But formatted code can parse it but not formatted code failed to parse it. It should be the case. 

Please analyze the issue one more time. 

```
['job_desc_less' => "This is a beautiful song that moved me listening to it. Flooded my mind with all kinds of thoughts, imagery and even some slight memories.<br />
<br />
This is what I see would be needed listening to the demo<br />
<br />
From 00:00 to 00:34 guitar picking<br />
from 00:35 to 01:38 One guitar strumming<br />
From 01:39 to 2:00 guitar picking<br />
from 02:01 to 03:18 One guitar strumming<br />
From 03:18 to 03:30 maybe arpeggios on guitar instead of strumming<be", 

"job_desc_more" => "/>
from 03:30 to end silence<br />
<br />
I think one guitar would suffice on the strumming parts and it may even be enough on the picking parts. The song speaks very well for itself. We can try it with just the one guitar, and see how it comes along and always add the second if needs it. I also thought you could consider a nylon guitar for one or both of the picking parts if you want to experiment with the sounds.<br />
<br />
Normally I would charge for multiple track recordings, but if we can communicate through the process we can probably knock this out reasonably quickly. Plus I like the song. So I am willing to keep this within your budget.<br />
<br />
I will send you one guitar picking the lead and strumming (as above), plus a second track of guitar doubling the strumming through the song over both parts, and we can auditioning a nylon if you like.<br />
<br />
I also play other instruments like bass and mandolin too if you need me for anything else, so please keep that in mind now and in the future!"]
```

**Comment by shohanjh09** [comment]
@scottchiefbaker ,
Can you please also integrate the JS code I provided in the description and try to work read more / less function and check the issue again?

Hope then you can identify the issue.

**Comment by scottchiefbaker** [comment]
You have too many pieces involved here. Smarty and Javascript have nothing to do with each other in this scenario. Smarty renders the text (in this case HTML) and spits that to the browser. It's up to the browser to decide how to display that. I have confirmed with the template and the test data you provided that Smarty is parsing correctly. The text that Smarty is rendering in this scenario is correct on my test.

It's it's not **displaying** correctly in your browse that is 100% a different issue. I am 99% sure this is not a Smarty issue, but instead related to invalid HTML or JavaScript somewhere else on the page causing problems. This is exactly what @wisskid suggested above.

**Comment by wisskid** [comment]
@shohanjh09 smarty is not the issue here, your html is. You cannot break up HTML in the middle of a tag like this:
```
['job_desc_less' => "of strumming<br", 

"job_desc_more" => "/>from 03:30 to end silence<br />"]
```

**Comment by bhsmither** [comment]
It seems to me (having done this myself) that there is a PHP statement in @shohanjh09's code that splits the `job_desc` content at exactly 450 characters (458 if using two-byte line endings for Windows), giving the first chunk to `_less` and the rest to `_more`.

If so, then unfortunately there will be a high probability that the split will happen inside something that really should not be split.

There is probably more processing that is working on the strings such that the closing angle for `<br />` gets converted to `&gt;` - which is not considered part of a tag by the browser's HTML rendering engine.

Note: I wanted have this discussion in the forums, but that is currently not possible.
