### ISSUE TITLE
Smarty escape Modifier: Javascript escape will escape <strong> 

### ISSUE THREAD

**Issue by sHorst** [smarty-php/smarty#762]
https://github.com/smarty-php/smarty/blob/3f97b7352e9c59b4b7460908a709de954e54862e/libs/plugins/modifier.escape.php#L190

For Security reasons smarty will escape `<script>` tags, that is correct, but it also will escape `<strong>` which is not intended.

**Comment by wisskid** [comment]
How are you using the escape modifier? Can you provide an example? Escaping is shouldn't hurt.

**Comment by sHorst** [comment]
Hey,

of course i use it like this:

```
    Info : "{$eintrag.info|nl2br|escape:"javascript"}"
```

For the input:
```
-
<strong>Veranstalter:</strong> Test Organizer
<strong>Zielgruppe:</strong> Test TargetGroup
```

it will result in:
```
Info : "-<br />\n<\strong>Veranstalter:<\/strong> Test Organizer<br />\n<\strong>Zielgruppe:<\/strong> Test TagretGroup"
```

which is clearly not what i want.

**Comment by wisskid** [comment]
Clearly not?
```
console.log("-<br />\n<\strong>Veranstalter:<\/strong> Test Organizer<br />\n<\strong>Zielgruppe:<\/strong> Test TagretGroup");
```
```
-<br />
<strong>Veranstalter:</strong> Test Organizer<br />
<strong>Zielgruppe:</strong> Test TagretGroup
```
Looks fine to me!
