### ISSUE TITLE
Class "SmartyCompilerException" not found

### ISSUE THREAD

**Issue by msrumon** [smarty-php/smarty#769]
I have downloaded a PHP script which uses **Smarty** to render views. After downloading and extracting, I've run `composer install` and `composer update` commands. Then I started the PHP development server to serve the app. When I visited it in the browser, I got the following error:

`
Fatal error: Uncaught Error: Class "SmartyCompilerException" not found in /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php:1137 Stack trace: #0 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(1745): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown tag 'in...', 1, true) #1 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(553): Smarty_Internal_TemplateCompilerBase->compileTag2('include', Array, Array) #2 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2156): Smarty_Internal_TemplateCompilerBase->compileTag('include', Array) #3 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2777): Smarty_Internal_Templateparser->yy_r24() #4 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2872): Smarty_Internal_Templateparser->yy_reduce(24) #5 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php(128): Smarty_Internal_Templateparser->doParse(13, '}') #6 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(469): Smarty_Internal_SmartyTemplateCompiler->doCompile('{include file='...', true) #7 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(395): Smarty_Internal_TemplateCompilerBase->compileTemplateSource(Object(Smarty_Internal_Template), false, NULL) #8 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(184): Smarty_Internal_TemplateCompilerBase->compileTemplate(Object(Smarty_Internal_Template)) #9 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object(Smarty_Internal_Template)) #10 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(105): Smarty_Template_Compiled->process(Object(Smarty_Internal_Template)) #11 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) #12 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1) #13 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1) #14 /var/www/html/includes/functions.php(2399): Smarty_Internal_TemplateBase->display('index.tpl') #15 /var/www/html/index.php(302): page_footer('index') #16 {main} thrown in /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 1137
`

(had to use single backtick instead of triple backticks)

The error was originally bubbled up from `Smarty_Internal_TemplateBase::display` call.

### Versions
- Smarty: 4.1.1
- PHP: 8.1.8

**Comment by wisskid** [comment]
Could you provide (a link to) the script you downloaded? Smarty 4 is PHP8.1 compatible, so this should just work.

**Comment by msrumon** [comment]
> Could you provide (a link to) the script you downloaded? Smarty 4 is PHP8.1 compatible, so this should just work.

<https://codecanyon.net/item/sngine-the-ultimate-social-network-platform/13526001> is the original script. I downloaded it from a 3rd party website, without paying.

**Comment by wisskid** [comment]
I'm afraid I can't help you with that. The error is probably somewhere in this project. The people providing the script might be able to help you. If you provide a simple reproduction scenario (only a couple of lines of code), I'll be happy to help you.

**Comment by msrumon** [comment]
> I'm afraid I can't help you with that. The error is probably somewhere in this project. The people providing the script might be able to help you. If you provide a simple reproduction scenario (only a couple of lines of code), I'll be happy to help you.

<https://github.com/msrumon/smarty>

**Comment by wisskid** [comment]
Excellent reproduction scenario. Albeit that this indeed throws a completely different error: `Smarty: unable to create directory /var/www/html/templates_c` 

This is caused by the `templates_c` dir not existing. Add `$smarty->setCompileDir('/tmp');` to `index.php` and it runs just fine.

**Comment by msrumon** [comment]
> Excellent reproduction scenario. Albeit that this indeed throws a completely different error: `Smarty: unable to create directory /var/www/html/templates_c`
> 
> This is caused by the `templates_c` dir not existing. Add `$smarty->setCompileDir('/tmp');` to `index.php` and it runs just fine.

I'm sorry, but I don't see that error. I indeed made the necessary changes you suggested.

![image](https://user-images.githubusercontent.com/9024015/178130658-90d74308-8932-4d7d-81d3-b79fadba34f6.png)
