### ISSUE TITLE
Global variables $_GET and $_POST not properly parsed

### ISSUE THREAD

**Issue by Visualq** [smarty-php/smarty#77]
In Smarty 3.1.27 {$smarty.get.q} becomes $_GET['q'] as it should, however in the master branch {$smarty.get.q} becomes $_GET instead of $_GET['q']

// test.php
include 'smarty-master/libs/Smarty.class.php';
$smarty = new \Smarty();
$smarty->fetch('global_variables.tpl');

// global_variables.tpl
{$smarty.get.q|print_r}
{$smarty.post.q|print_r}

**Comment by uwetews** [comment]
The fix is now in the master branch
