### ISSUE TITLE
Uncaught Error: Class "Smarty_Internal_Undefined" not found in C:\xampp81\htdocs\cirt\libraries\smarty\sysplugins\smarty_internal_extension_handler.php:168

### ISSUE THREAD

**Issue by jegelstaff** [smarty-php/smarty#774]
Hello, I think this is an installation/configuration error. I'm dropping in 4.1.0 in place of an older version of Smarty, but something is not quite working. Any insights?

**Comment by jegelstaff** [comment]
Looks like the autoloader is not finding the smarty_internal_undefined.php file in the sysplugins folder??

**Comment by wisskid** [comment]
@jegelstaff looks like it indeed, but I can't say why. I'd start with trying to get a stacktrace at the point of the error and then going through the steps. Is an autoloader active? Are paths set correctly?

Alternatively, set up a seperate, clean install of Smarty 4 that works, then add parts of your existing code into this new installation and see when it breaks. That should get you your answer.

If nothing helps, please re-open the issue and provide a minimal example that causes the error.
