### ISSUE TITLE
ERROR: Function strftime() is deprecated

### ISSUE THREAD

**Issue by krisskals** [smarty-php/smarty#780]
I use PHP 8.1 and Smarty 4.2.

I got this error:

ERROR: Function strftime() is deprecated on line 81 in file/vendor/smarty/smarty/libs/plugins/modifier.date_format.php.

**Comment by Bozosoft** [comment]
confirmed also by using cmsmadesimple/branches/2.4/  PHP 8.1.8 and Smarty 4.2
Deprecated: Function strftime() is deprecated in  /plugins/function.html_select_date.php on line 312

**Comment by ophian** [comment]
see PR https://github.com/smarty-php/smarty/pull/781

**Comment by Bozosoft** [comment]
Thanks ophian

**Comment by fmancardi** [comment]
Hi, I've given a look to the two files with strftime() in the PR

modifier.date_format.php
function.html_select_date.php

IMHO solution can not be changing calls to strftime() to @strftime(), but code need to be re-written using date() or another valid function that will be OK for PHP 8.1.x

regards

**Comment by ophian** [comment]
It is total valid to silence deprecation notices up to at least PHP 9, since a valid solution to dateTime does require the intl/icu extension, which isn't the standard nowadays.

**Comment by wisskid** [comment]
Duplicate of #672
