### ISSUE TITLE
Smarty 2.6.x PHP 8 support

### ISSUE THREAD

**Issue by Adz10kvtech** [smarty-php/smarty#783]
Hi all,

Just putting this out there, any plans for 2.6.x to have PHP 8 support? 

I wont hold my breath.

Thanks for all your hard work.

**Comment by wisskid** [comment]
Sorry, no plans for that. Not fixing security issues for Smarty 2 either: https://github.com/smarty-php/smarty/blob/master/SECURITY.md

**Comment by scottchiefbaker** [comment]
@wisskid the link you posted should be updated as it says Smart 4.x hasn't been released yet :)

**Comment by wisskid** [comment]
Doh! Fixed it.

**Comment by duck7000** [comment]
@wisskid 
No plans means not ever? 
In other words there never will be support for php  8 or 8.1?
I'm asking just to be sure as i currently use 2.6 on php 7.4

**Comment by wisskid** [comment]
No, never. Sorry. Upgrading is your best option.

**Comment by duck7000** [comment]
Oke thanks
