### ISSUE TITLE
PHP Parse error:  syntax error, unexpected token "class"

### ISSUE THREAD

**Issue by llcool** [smarty-php/smarty#785]
Error:
PHP Parse error:  syntax error, unexpected token "class" in /usr/share/php/smarty3/sysplugins/smarty_internal_templateparser.php on line 24

Version:
smarty3/jammy,now 3.1.39-2ubuntu1 all [installed]

Problem:
smarty_internal_templateparser.php is missing multiple semicolons.

Solution:
Add missing semicolons.

**Comment by wisskid** [comment]
There surely must be something else going on here. v3.1.39 is 17 months old.

**Comment by wisskid** [comment]
The issue is in the debian package. The smarty_internal_templateparser.php differs from the smarty_internal_templateparser.php in the source. It was probably regenerated from lexer/smarty_internal_templateparser.y

**Comment by wisskid** [comment]
More recent versions seem fine, so I suggest you just update your smarty3 package. Let me know if that doesn't help.

**Comment by Smylers** [comment]
Version 3.1.39-2ubuntu1 is [the latest version provided in Ubuntu 22.04 LTS](https://packages.ubuntu.com/search?keywords=smarty3), the most-recent Ubuntu release. It's an LTS release, so supported by Ubuntu until 2027.

There's an [Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/smarty3/+bug/1986916) for this issue.

**Comment by wisskid** [comment]
This has probably been fixed, see #822
