### ISSUE TITLE
Smarty error on function call

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#79]
I tried : $message = $smarty->fetch('webmail/contact_alert_user.tpl');

The tpl "contact_alert_user.tpl" include a top tpl where is a function defined and a call of it.

With a old version (3.1.13) this working without problems. With last version of smarty  3.1.27, I have this error:

<b>Fatal error</b>:  Uncaught  --&gt; Smarty: Unable to find template function 'autologinParam' &lt;-- 
  thrown in <b>E:\_prjutils\lib3\smarty\sysplugins\smarty_internal_template.php</b> on line <b>581</b><br />

**Comment by uwetews** [comment]
Please provide a small example which shows your template structure.

**Comment by uwetews** [comment]
Closed as I got no more information.
