### ISSUE TITLE
$smarty->assign not passing variable in other template files

### ISSUE THREAD

**Issue by samuel9554** [smarty-php/smarty#791]
I've a bit of a struggle since I've bump my smarty version from 3.1 to 4.2.
It some that the template is not retrieving the variable that have been set

in PHP 
`if(!empty($VAR['alert_msg'])) {
	$smarty->assign('error_msg', $VAR['error_msg']);
}
$smarty->display('core'.SEP.'header.tpl');
`

Then in a other template EX: customer.tpl I have
`
{if $error_msg|escape != ""}
    {include file="core/error.tpl"}
{/if}
`

My core/error.tpl look like this
`
{if !empty($error_msg)}            
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {$type} {$error_msg}
    </div>
{/if}`

The issue is that the variable $error_msg in the template stay empty. I've verified that the $VAR['alert_msg'] have a string in it.
All of that use to work in previous version of smarty. Do I need to change some parameter or does someone have this issue before?

**Comment by mohrt** [comment]
Wouldn't you want `$smarty->assign('error_msg', $VAR['alert_msg']);` since that is the value you are testing?

**Comment by wisskid** [comment]
So you verified that `$VAR['alert_msg']` has a string, but did you verify if `$VAR['error_msg']` has a value?

**Comment by samuel9554** [comment]
Sorry I made some copy paste mistake.
I found my mistake I was overwritten it somewhere else in the code.
We can close that.
