### ISSUE TITLE
Which version is the last compatible one for PHP 7.0.x?

### ISSUE THREAD

**Issue by kosuodhmwa** [smarty-php/smarty#792]
Which version is the last compatible one for PHP 7.0.x?

**Comment by wisskid** [comment]
Smarty 4 requires at least PHP 7.1, so you should stick to Smarty 3.1. Latest release: https://github.com/smarty-php/smarty/releases/tag/v3.1.46

**Comment by kosuodhmwa** [comment]
Thank you very very much for your fast feedback!! :-)
