### ISSUE TITLE
 Smarty PHP error ERRNO: 2 TEXT: Attempt to read property "_codeFrame" on null

### ISSUE THREAD

**Issue by Billjay65** [smarty-php/smarty#793]
I am trying to upgrade my PHP smarty template system from smarty 3 to smarty-4.1.0. I have followed the recommended procedure and setup all of the required directories. However, when I try to run my application I keep getting this error message:

ERRNO: 2
TEXT: Attempt to read property "_codeFrame" on null
LOCATION: C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_internal_templatecompilerbase.php, line 392, at July 14, 2022, 1:22 am
Showing backtrace:
Smarty_Internal_TemplateCompilerBase.compileTemplate(Object: Smarty_Internal_Template) # line  184, file: C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_template_compiled.php
Smarty_Template_Compiled.compileTemplateSource(Object: Smarty_Internal_Template) # line  141, file: C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_template_compiled.php
Smarty_Template_Compiled.process(Object: Smarty_Internal_Template) # line  105, file: C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_template_compiled.php
Smarty_Template_Compiled.render(Object: Smarty_Internal_Template) # line  216, file: C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_internal_template.php
Smarty_Internal_Template.render(false, "1") # line  238, file: C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_internal_templatebase.php
Smarty_Internal_TemplateBase._execute(Object: Smarty_Internal_Template, null, null, null, "1") # line  134, file: C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_internal_templatebase.php
Smarty_Internal_TemplateBase.display("store_front.tpl") # line   80, file: C:\Users\JAY.V\Desktop\campbroot\campb\index.php

When I run the smarty installation test, everything seems to be in place as shown below. I don't know where the error is coming from.

Smarty Installation test...
Testing template directory...
C:\Users\JAY.V\Desktop\campbroot\campb\presentation\templates is OK.
Testing compile directory...
C:\Users\JAY.V\Desktop\campbroot\campb\presentation\templates_c is OK.
Testing plugins directory...
C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\plugins is OK.
C:\Users\JAY.V\Desktop\campbroot\campb\presentation\smarty_plugins is OK.
Testing cache directory...
C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\cache is OK.
Testing configs directory...
C:\Users\JAY.V\Desktop\campbroot\campb\include\configs\ is OK.
Testing sysplugin files...
... OK
Testing plugin files...
... OK
Tests complete.

Here is the code that calls for smarty in index.php. $application is a class which extends Smarty class.

$application->testInstall();
   
  // Display the page
  $application->display('store_front.tpl');

**Comment by wisskid** [comment]
Can you post (an excerpt from) the template source that triggers this error? I've reviewed the source, but there seems to be no path that would set $smarty->ext to null.

**Comment by Billjay65** [comment]
``

**Here is the application.php file code:**

<?php

// Reference Smarty library
require_once SMARTY_DIR . 'Smarty.class.php';

/* Class that extends Smarty, used to process and display 
 smarty files */
class Application extends Smarty
{
  // class contructor
  public function __construct()
  {
    // Call Smarty's constructor
    //Smarty::Smarty();  this line is useless 

    // Change the default template directories
    $this->template_dir = TEMPLATE_DIR;
    $this->compile_dir  = COMPILE_DIR;
    $this->config_dir   = CONFIG_DIR;
    $this->cache_dir    = CACHE_DIR;
    $this->plugins_dir[0] = SMARTY_DIR . 'plugins';
    $this->plugins_dir[1] = PRESENTATION_DIR . 'smarty_plugins';
  }
}

?>

**Here is an excerpt from  the store_front.tpl file:**
{* smarty *}
{config_load file="site.conf"}  
{load_presentation_object filename="store_front" assign="obj"}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
   <head>
   
      <title>{$obj->mPageTitle}</title></title>
      
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      
      <meta charset="UTF-8" /> ...

**`Here is the function.load_presentation_object.php file`**

<?php
// Plug-in functions inside plug-in files must be named: smarty_type_name
function smarty_function_load_presentation_object($params, $smarty)
{
  require_once PRESENTATION_DIR . $params['filename'] . '.php';

  $className = str_replace(' ', '',
                           ucfirst(str_replace('_', ' ',
                                               $params['filename'])));

  // Create presentation object
  $obj = new $className();

  if (method_exists($obj, 'init'))
  {
    $obj->init();
  }

  // Assign template variable
  $smarty->assign($params['assign'], $obj);
}
?>

``

**Comment by Billjay65** [comment]
Do you mean an excerpt from C:\Users\JAY.V\Desktop\campbroot\campb\libs\smarty\sysplugins\smarty_internal_templatebase.php
Smarty_Internal_TemplateBase.display("store_front.tpl") # line 80?

or An excerpt from store_front.tpl  

Here is the excerpt code for  store_front.tpl

{* smarty *}
{config_load file="site.conf"}  
{load_presentation_object filename="store_front" assign="obj"}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
   <head>
   
      <title>{$obj->mPageTitle}</title></title>
      
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      
      <meta charset="UTF-8" />   ...

**Comment by Billjay65** [comment]
Here is the application.php file excerpt:
<?php

// Reference Smarty library
require_once SMARTY_DIR . 'Smarty.class.php';

/* Class that extends Smarty, used to process and display 
 smarty files */
class Application extends Smarty
{
  // class contructor
  public function __construct()
  {
    // Call Smarty's constructor
    //Smarty::Smarty();  this line is useless 

    // Change the default template directories
    $this->template_dir = TEMPLATE_DIR;
    $this->compile_dir  = COMPILE_DIR;
    $this->config_dir   = CONFIG_DIR;
    $this->cache_dir    = CACHE_DIR;
    $this->plugins_dir[0] = SMARTY_DIR . 'plugins';
    $this->plugins_dir[1] = PRESENTATION_DIR . 'smarty_plugins';
  }
}

?>

**Comment by Billjay65** [comment]
Here is the function.load_presentation_object.php file


![function load_presentation_object](https://user-images.githubusercontent.com/95188150/189501676-5a09d80b-bb33-4c89-a7e3-98b750cf941e.PNG)

**Comment by wisskid** [comment]
Try calling parent::__construct() in your Application constructor

**Comment by Billjay65** [comment]
Wow thanks! we are almost there. I added parent::__construct() in Application constructor and got an html response from the web server. However css styles have disappeared and the page looks plain. Why has this happen? I will try to review the code and see why css has disappeared. 
![html-response](https://user-images.githubusercontent.com/95188150/191104270-ea311271-15d8-42e5-bc15-c3c837657365.PNG)
![html-response-source-code](https://user-images.githubusercontent.com/95188150/191104337-752b364e-4e45-4e7d-be9a-877c54ca0642.PNG)
