### ISSUE TITLE
Include docs (and ideally demo, tests) in the releases

### ISSUE THREAD

**Issue by orlitzky** [smarty-php/smarty#799]
I'm packaging smarty for Gentoo, and it would be nice if we could install the documentation and examples when users install the smarty library. In the past we've used the manual from `https://www.smarty.net/files/docs/manual-en.*.zip`, but that's now outdated, and the good stuff is in `docs/`. We can also have our users run the test suite if it's included in the tarball...

**Comment by wisskid** [comment]
I could re-include the `/demo` and `/docs` folders. The docs are in markdown format, and accessible online at https://smarty-php.github.io/smarty/

I don't see the use of adding the `/tests` folder. To run them you also need phpunit, and probably docker and the `/utilities` folder as well. If you want to, it's a lot easier to just clone the repository imho.

**Comment by orlitzky** [comment]
Thanks. For some background, Gentoo users are able to install smarty globally with the command `emerge smarty`. Our package manager allows them to set several configuration flags, called "USE flags", that affect what gets installed. Three very common USE flags are `doc`, `examples`, and `test`.

`USE=doc emerge smarty`, for example, is supposed to install any additional API documentation for the package. So in this case, it would install everything under the `docs/` folder. Likewise, `USE=examples` would install the demo. Both of these are mainly useful for offline development (i.e. you're developing a website on localhost on a plane/train/etc.) which is less common these days, but still nice to have, and the framework is already in place for it -- we just need the files :)

`USE=test` is a bit different in that it runs the test suite before installation and doesn't affect what gets installed. As a source-based distribution, we're pretty unique in having the ability to run the test suite on the end-user's machine. This too is nice for users who want to be sure that (say) an upgrade will not have any regressions. With so many USE flags corresponding to so many configuration options, it's impossible for the maintainers themselves to test every configuration. And if the package's test suite fails, the upgrade bails out. **However**, packaging PHPUnit has become kind of a nightmare recently, so I don't feel as strongly about this as I once did. Feel free to leave them out.

The docs and demo would be nice though if no one else minds too much.

**Comment by wisskid** [comment]
Done!

**Comment by orlitzky** [comment]
Thank you!
