### ISSUE TITLE
Deprecated: preg_replace(): The /e modifier is deprecated ...  modifier.capitalize.php on line 33

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#80]
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in E:\_prjutils\lib3\smarty\plugins\modifier.capitalize.php on line 33

**Comment by mmerian** [comment]
Hi,

@yourchoice, it looks like this issue has been fixed a long time ago. Which version of Smarty are you using ?

Cheers,

**Comment by yourchoice** [comment]
3.1.27

**Comment by uwetews** [comment]
This was already fixed in 3.1.14
