### ISSUE TITLE
Smarty Syntax Error

### ISSUE THREAD

**Issue by ItsAnfield** [smarty-php/smarty#809]
My dev webpage has got some issue with the syntax that I'm not capable of fixing by my own

The error is : **Parse error: syntax error, unexpected '<', expecting function (T_FUNCTION) or const (T_CONST)**

I upload a pic of the codeline that the debug mode says its having an error.

![image](https://user-images.githubusercontent.com/78814210/191685536-ed6755e4-19ff-4163-a827-97c40ddd75e5.png)

**Comment by wisskid** [comment]
Could you show your template source and list the versions of Smarty and PHP you are using?
