### ISSUE TITLE
function.mailto Warning script type="text/javascript"

### ISSUE THREAD

**Issue by Bozosoft** [smarty-php/smarty#815]
in 3.1.x Warning: The type attribute is unnecessary for JavaScript resources. <script type="text/javascript"> 
test on validator.w3.org/nu

**Comment by Bozosoft** [comment]
for information /plugins/function.mailto.php
line 117 and 122
return '<script type="text/javascript"> ... 
is  OK on HTML 4.01  ( <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 ..  )
But 
Warning: The type attribute is unnecessary for JavaScript resources.
on on HTML 5 ( <!DOCTYPE html> ) 
So return '<script>... only is OK

**Comment by wisskid** [comment]
I removed all `type="text/javascript"` and `language="Javascript"`

**Comment by Bozosoft** [comment]
Sorry but on  last  [4.3.2]   on /plugins/function.mailto.php
Line 112 
return '<script type="text/javascript">document.write(unescape(\'' . $js_encode . '\'))</script>';
Line  117
return '<script type="text/javascript">document.write(String.fromCharCode(' . implode(',', $ord) . '))</script>';
so
Warning: The type attribute is unnecessary for JavaScript resources. <script type="text/javascript">

**Comment by wisskid** [comment]
This is planned for release in v5.0
