### ISSUE TITLE
PHP 8 migration - Warning: Undefined array key

### ISSUE THREAD

**Issue by barisyazganc** [smarty-php/smarty#820]
Hi,

i was using php7.4 but i want to switch to php 8, but my codebase is crowded with a lot of smarty template files. and in my templates i use {$error} but in some cases php wont assign this var to template, and since its working in php7.4, it gives warning all over the pages in php8.. i think it will be very painfull to review all the templates and change them.. i need to do it in the smarty core...

any suggestions?

**Comment by scottchiefbaker** [comment]
I think you want `muteExpectedErrors()`

https://www.smarty.net/docs/en/api.mute.expected.errors.tpl

**Comment by barisyazganc** [comment]
actually when i set this var;

   /**
     * PHP7 Compatibility mode
     * @var bool
     */
    private $isMutingUndefinedOrNullWarnings = false;

it mutes the warnings, but i'm not sure if its the correct way, there must be a solution within the Smarty core (i.e while creating the template file isset() automatically added to parameters) ?

**Comment by barisyazganc** [comment]
Yep i'm using it too! :) at the end Smarty is a template engine, its acceptable to mute warnings i guess :)

**Comment by wisskid** [comment]
@scottchiefbaker muteExpectedErrors has been dropped in v4 and did something else. muteUndefinedOrNullWarnings is the API method one would use to mute warning about undefined variables.

**Comment by scottchiefbaker** [comment]
Thanks for the clarification. I have updated my side.

**Comment by scottchiefbaker** [comment]
@wisskid I just checked the [docs](https://smarty-php.github.io/smarty/programmers/api-functions.html) and there is no mention of the new method, or the deprecation on the old one.

**Comment by clops** [comment]
I also did not find any mention of muteUndefinedOrNullWarnings in the docs… I actually started implementing a custom error handler first, but then stumbled upon it in the core source code :) 

would be super awesome to have a reference included in a docs section dedicated to porting templates to PHP 8.*
