### ISSUE TITLE
Stray "0" in sysplugins/smarty_internal_{template,configfile}parser.php when self-generated

### ISSUE THREAD

**Issue by sunweaver** [smarty-php/smarty#822]
In Debian, we have to re-generate lexer-generated files, enforced by Debian policy.

Since recently, the generation process of smarty_internal_configfileparser.php and smarty_internal_templateparser.php generates broken files.

In those files, there is a stray "0" at the end of the files and also one near the top:

```
// line "./lexer/smarty_internal_templateparser.y"
0
// line 11 "./lexer/smarty_internal_templateparser.y"
```

I have attached the self-generated files from release 4.2.1.

Maybe this is a smarty-lexer related issue?
[smarty_internal_configfileparser.php.txt](https://github.com/smarty-php/smarty/files/9854303/smarty_internal_configfileparser.php.txt)
[smarty_internal_templateparser.php.txt](https://github.com/smarty-php/smarty/files/9854304/smarty_internal_templateparser.php.txt)

**Comment by wisskid** [comment]
@sunweaver I added a fix to https://github.com/smarty-php/smarty-lexer that seems to fix this. Could you let me know if this works for you too?

**Comment by sunweaver** [comment]
@wisskid Wow, this was fast. That patch in smarty-lexer seems to fix things here. So, I just updated smarty-lexer, smarty3 and smarty4 in Debian unstable accordingly. Thanks!

For documentation purposes: this issue has been resolved by https://github.com/smarty-php/smarty-lexer/commit/e0ee2739c93c717b18ed703a54073a8f55e9f646
