### ISSUE TITLE
Depricated warning

### ISSUE THREAD

**Issue by AlexPaterson** [smarty-php/smarty#824]
Deprecated: Function strftime() is deprecated in /var/***/Smarty/smarty-4.2.1/libs/plugins/modifier.date_format.php on line 81

**Comment by klaoun** [comment]
`return @strftime($format, $timestamp);`

**Comment by bhsmither** [comment]
If you are able to modify the source template, do not use the %X collection of date/time specifiers, but rather use the equivalent php function `date()` single-character specifiers.

**Comment by TK200KM** [comment]
We should be allowed to use the modifier 'date_format'. There isn't anything more to say.

**Comment by wisskid** [comment]
Fixed in https://github.com/smarty-php/smarty/pull/811
