### ISSUE TITLE
Undefined property: Smarty_Internal_Undefined::$objMap

### ISSUE THREAD

**Issue by fenjen** [smarty-php/smarty#826]
I have to upgrade a web page to make it work with the current version of Smarty. The web page was built with Smarty 2.6.19, and it ran for a long time without problems  (15 years). But now that PHP 7 is reaching EOL, the web page (specifically Smarty) needs to be compatible with PHP 8.

I already found and fixed a couple of incompatible changes between the two versions. Now I am stuck at smarty-4.2.1/libs/sysplugins/smarty_internal_extension_handler.php:132:
I just get:
```
Undefined property: Smarty_Internal_Undefined::$objMap
```
This seems like a bug in Smarty to me:

1. If my Smarty 2.x code called some meanwhile-undefined method, the error should be issued at the time this undefined method was called.
2. An error message like "Undefined property" is in my understanding a bug in the framework code.

The Smarty code is

```php
if (isset($callback) && $callback[ 0 ]->objMap | $data->_objType) {
    return call_user_func_array($callback, $args);
}
```
I'd expect that

1. the framework triggers some error message like "call to undefined method `register_object`" or whatever went wrong here. (Or if the callback needed to provide some method; then registering the callback should verify it implements some interface.)
2. `objMap`  should be there - always - either through a `protected` variable (suboptimal design) or a getter. But a message like "undefined property" stems from bad assumptions and a too vaguely defined class hierarchy.

I haven't read much of the source code though. A small research showed others had suffered the same issues, too.

**Comment by wisskid** [comment]
Can you provide (an example of) the template code that triggers this error?

**Comment by fenjen** [comment]
Thanks for your answer, wisskid. After some digging I found:
```
PHP Fatal error:  Uncaught  --> Smarty: undefined extension class 'Smarty_Internal_Method_ConsumationCheck' <--
```

I was able to fix it:
```php
// $this is a subclass of Smarty
$this->registerFilter('output', array($this, 'consumationCheck'));
```

The `consumationCheck` method was `protected`, and seems it has to be `public` now. This maybe duplicates https://github.com/smarty-php/smarty/issues/137. Now I get:
```
Syntax error in template:
[...] {$smarty.post.login|default:$smarty.cookies.login|default:''|escape:"htmlall"} [...]
unknown modifier 'default'
```

But default [still exists](https://www.smarty.net/docs/en/language.modifier.default.tpl), isn't it?

**Comment by fenjen** [comment]
OK, after comparing the paths of this code with a clean install using `|default`, I found

> As of Smarty 3.1 the attribute $plugins_dir is no longer accessible directly. Use [getPluginsDir()](https://www.smarty.net/docs/en/api.get.plugins.dir.tpl), [setPluginsDir()](https://www.smarty.net/docs/en/api.set.plugins.dir.tpl) and [addPluginsDir()](https://www.smarty.net/docs/en/api.add.plugins.dir.tpl) instead.

https://www.smarty.net/docs/en/variable.plugins.dir.tpl
