### ISSUE TITLE
Smarty comments changed in version 3.1.32 (bug?)

### ISSUE THREAD

**Issue by russellgilbert** [smarty-php/smarty#827]
The behavior of Smarty comments changed in version 3.1.32. The following test template with JavaScript code displayed correctly (on three lines) before this version:

Line 1.
// Line 2. {* comment *}
Line 3.

In versions 3.1.32 to 3.1.47, that same template displays as:

Line 1.
// Line 2. Line 3.

It appears that the line break after the {* comment *} is being removed. The problem only seems to happen when the comment is at the end of the line. It displays the three lines correctly when there's anything on the same line after the comment.

The commit for version 3.1.32 is here: https://github.com/smarty-php/smarty/commit/ac9d4b587e5bf53381e21881820a9830765cb459

I'm using PHP 7.4.11 on CentOS.

**Comment by wisskid** [comment]
Hi @russellgilbert ! You are right, this seems to have changed, but only to fix a previous change that occurred earlier. It was discussed in #555 and I feel it should not be changed back again, as it has been working like it is now since 2017/2018.
