### ISSUE TITLE
{html_options} does not work since at least 3.1.12 (it worked in 3.1.5)

### ISSUE THREAD

**Issue by tribis** [smarty-php/smarty#83]
Example:
//test.php

```php
include 'Smarty3/Smarty.class.php';
$smarty = new \Smarty();
$smarty->caching = 0;
$smarty->force_compile = true;
$smarty->assign('test', array('one', 'two', 'three'));

$smarty->display('test.tpl');
```
//test.tpl
```html
<select name="test">{html_options values="$test" output="$test" selected=""}</select>
```
The output is only 1 option containing: Array

poking inside the code it shows that the argument $params passed to function.html_options.php is simply a string "Array"

I could verify that smarty-3.1.5 works as expected, while already in smarty-3.1.12 we have the described error. I havn't got any version between .5 and .12 to find the exact time of this fault.
The last version where  the error is found is 3.1.27

**Comment by uwetews** [comment]
You passed the value and option attributes as string. Never pass variables in quotes. It's wrong and may create all sorts of failures. It has also bad performance.

```
<select name="test">{html_options values=$test output=$test selected=""}</select>
```

**Comment by tribis** [comment]
Ooops, sorry for this.
Thanks
