### ISSUE TITLE
Deprecation notice should not be a fatal error

### ISSUE THREAD

**Issue by davidsneighbour** [smarty-php/smarty#837]
For some reason, I am receiving Fatal Errors like the following:

```
Fatal error: Uncaught ErrorException: Using php-function "md5" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /home/patrick/github.com/getbooka/booka/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 114
```

While I understand that and why this "feature" is deprecated, I don't understand why it has to be a fatal error. The wording is "will be removed in a future release," which means it is not removed now. So why is it throwing an error/exception? It should be a warning of some kind? Maybe I am doing something wrong that sets notices to fatal errors in my system, but I am not aware of this. 

Can you confirm that it's currently an exception with the wording above?

PS: I know how to add my modifiers and work through this; the issue is about the error level of the deprecation notice, not the change itself.

**Comment by EgorBoyko** [comment]
Hi, by the way, whats the smarty version?

**Comment by wisskid** [comment]
The error triggered is:
'''

trigger_error('Using php-function "' . $modifier . '" as a modifier is deprecated and will be ' .
                                    'removed in a future release. Use Smarty::registerPlugin to explicitly register ' .
                                    'a custom modifier.', E_USER_DEPRECATED);
'''

Shouldn't trigger a fatal error. Might it be a custom error handler that escalates this?

**Comment by gtraxx** [comment]
Hi, I have the same problem :

`Deprecated: Using php-function "ucfirst" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /lib/smarty4/sysplugins/smarty_internal_compile_private_modifier.php on line 114`
How can we avoid deprecated notifications, we can no longer use for example sprintf php in a template ?

**Comment by davidsneighbour** [comment]
My (dirty) workaround is to register each of the functions I am using as plugin like this (in my smarty class extension):

```php
        $callbacks = [
            ['modifier', 'filesize', [\Booka\Frontend\Page\Page::class, 'smartyModifierFilesize']],
            ['modifier', 'format_date', [\Booka\Frontend\Page\Page::class, 'smartyModifierFormatDate']],
            ['modifier', 'trim', 'trim'],
            ['modifier', 'md5', 'md5'],
            ['modifier', 'in_array', 'in_array'],
        ];
        foreach ($callbacks as $callback) {
            try {
                $this->registerPlugin($callback[0], $callback[1], $callback[2]);
            } catch (SmartyException $eException) {
                Tracking::trackException($eException);
            }
        }
```

The last three values in $callbacks are piping the functions through. The other ones are internal functions of my system.

Ans yes, @wisskid, the error is that I am escalating the error with a handler that throws an exception. 

```php
set_error_handler(['\Booka\Core\Errors\ErrorHandler', 'exceptions_error_handler']);
```

It's a great way to clean up coding issues if you remember implementing it ;) Closing this issue for now.
