### ISSUE TITLE
Exception : "Invalid compiled template for"

### ISSUE THREAD

**Issue by begend** [smarty-php/smarty#84]
hi, my env : hhvm 2.2 and  Smarty-3.1.5.

3ks a lot

**Comment by uwetews** [comment]
Smarty 3.1.5 is a very old outdated version from 2011. It's very likely that it is not compatible with HHVM.
In a few days we will officially release Smarty 3.1.28 which does run under HHVM without any restriction. You can download the current master branch version for the time being. I'm just working on some optimizations before the official release.

**Comment by begend** [comment]
hi，did you ever found that the function "uniqid" return in hhvm ?
thanks again

**Comment by uwetews** [comment]
It does work at least with uniqid('', true)
