### ISSUE TITLE
Vscode: Use of unknown class: 'integer' 

### ISSUE THREAD

**Issue by leifnel** [smarty-php/smarty#841]
In doc-comments like 
```
   /**
     * saved cache lifetime in seconds
     *
     * @var integer
     */
    public $cache_lifetime = 0;

```
vscode complains 
Use of unknown class: 'integer' 
I suppose it should be int instead.

I currently have 257 errors in my project; I'd like to only have my  own errors/warnings to worry about. ;-)

**Comment by wisskid** [comment]
PHPDoc officially supports both: https://docs.phpdoc.org/2.9/guides/types.html
But if you want to make a PR, I'd happily merge it for you.

**Comment by wisskid** [comment]
This has been fixed in v5
