### ISSUE TITLE
Undefined index: isChild in smarty_internal_template.php:339

### ISSUE THREAD

**Issue by doopEino** [smarty-php/smarty#85]
Hello, I'm getting Undefined index: isChild

exception

exception 'ErrorException' with message 'Undefined index: isChild' in smarty/smarty/libs/sysplugins/smarty_internal_template.php:339

After upgrading from: Updating smarty/smarty dev-master (31a7162 => bfcffb0)

**Comment by uwetews** [comment]
Sorry i missed to increment the internal dev version index on some internal change. So it did not automatically recompile.  Empty the compiled and cache folder and it should work.
