### ISSUE TITLE
[PHP 8.2] Warning: Undefined array key "foo"

### ISSUE THREAD

**Issue by element-code** [smarty-php/smarty#855]
Using v4.3.0 (ref: c02e9e13)
```smarty
{if $foo}
```
The compiled PHP code is
```php
if ($_smarty_tpl->tpl_vars['foo']->value) {
```
Which fails with an E_WARNING for the undefined array key, when the variable was never assigned.
In my opinion, this should be somewhat safe to call `{if $foo}` and not fail with this error, instead just validate to `false`.
Wrapping all if/elseif calls in a legacy project with `{if !empty($foo)}` seems a little overkill.

---

https://github.com/smarty-php/smarty/blob/c02e9e135ea719b91f457a0072748ded0e852e7d/libs/sysplugins/smarty_internal_templatecompilerbase.php#L562-L578
Dirty hack return for compileVariable():
```php
return '($_smarty_tpl->tpl_vars[' . $variable . '] ?? NULL)?->value';
```

**Comment by element-code** [comment]
Also, in my opinion, dot access should be null-safe (for each element in the chain).
```smarty
{if $foo.bar}
```
```php
<?php if ($_smarty_tpl->tpl_vars['foo']->value['bar']) {?>
```

**Comment by sutrus** [comment]
Why don't you use {if isset($foo)} ?

**Comment by wisskid** [comment]
Tried `$smarty-> muteUndefinedOrNullWarnings()`?

**Comment by element-code** [comment]
> Why don't you use `{if isset($foo)}` ?
Identifying, replacing 500+ matches and testing them just sucks.


> Tried `$smarty->muteUndefinedOrNullWarnings()`?
Works for me

**Comment by nd3w** [comment]
> $smarty-> muteUndefinedOrNullWarnings()
Thank you for inform about this function.

Is this a workaround to be corrected for the future version of Smarty/PHP or had been exist since before?

**Comment by nd3w** [comment]
> $smarty->muteUndefinedOrNullWarnings()

I meant to quote this function. Had this function existed before, or is it just there to suppress the warning error that happened when we used PHP 8 ?

**Comment by wisskid** [comment]
You are correct: it has been introduced in Smarty v4.0 in order to convert warnings about undefined or null template vars to notices when running PHP8. In Smarty v3.x, it doesn't exist.
