### ISSUE TITLE
tag 3.1.29 removed class 'Smarty_Security'?

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#86]
Hi Uwe

with your tagged 3.1.29 version - did you remove the class 'Smarty_Security'?

We have a wrapper class for compat reasons, and would now get a 
`Fatal error: Class 'Smarty_Security' not found`

**Comment by uwetews** [comment]
There is no tagged version 3.1.29.  ???

The latest version is 3.1.27

**Comment by ophian** [comment]
Uh damn, I should have took my glasses. Its 2.x, sorry. :)
