### ISSUE TITLE
Discussion: Ability to inline templates for quick testing?

### ISSUE THREAD

**Issue by scottchiefbaker** [smarty-php/smarty#862]
@wisskid as I was mocking up that ternary test from the other bug something occurred to me: "This should be easier"

To test I had to write PHP that loads Smarty, write a quicky template, and then `fetch()` the template and print it out. In [Sluz](https://github.com/scottchiefbaker/sluz) I used the idea of [inline templates](https://scott.web-ster.com/sluz/docs/read.php?doc=060_inline_mode) for really simple scripts. Is there anything similar in Smarty I'm not aware of?

How do you mock up a quicky test like that? Having everything in **one** file like that makes it really easy to mock up and distribute.

**Comment by wisskid** [comment]
@scottchiefbaker something like this was done by @AnrDaemon 
See https://github.com/AnrDaemon/test-001

**Comment by AnrDaemon** [comment]
Exactly.
You may clone the repo and do your mocking in a branch.

If you want to replicate the behavior, check the https://github.com/AnrDaemon/test-001/blob/master/smarty-config.php#L32-L39
