### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by IG-PhantomX** [smarty-php/smarty#868]
Upon trying to load my index page, I get a white page with this:

Fatal error: Uncaught --> Smarty: Unable to load template 'file:core/header.tpl' <-- thrown in /usr/www/mysite/includes/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 196

**Comment by wisskid** [comment]
You have likely misconfigured your template dir, or the template file is missing.
