### ISSUE TITLE
v. 3.1.27 - $smarty->display error with atom1.0 feed

### ISSUE THREAD

**Issue by ophian** [smarty-php/smarty#87]
Hi Uwe 

We have an issue with v. 3.1.27, when we use `$smarty->display($metadata['template_file']);` for a Atom 1.0 feed. This is something which worked well for years.

I reverted testwise to version 3.1.21, which worked well. 
The Rss2 feed works well on both version, taking the same route.

For the Atom feed we get:
`Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/..../Smarty/libs/sysplugins/smarty_internal_templatelexer.php on line 289`

Do you have any ideas what this could be? I tried to upgrade, but there I got the #86 issue.

**Comment by ophian** [comment]
The strange thing is, that is does not always error in same file and same line, see this three examples:
```log
[this morning] [error] [client 66.249.78.28] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/.../Smarty/libs/sysplugins/smarty_internal_templateparser.php on line 948

[this morning] [error] [client 213.136.78.49] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/.../Smarty/libs/sysplugins/smarty_internal_templatelexer.php on line 290

[this morning] [error] [client 66.249.78.72] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/.../Smarty/libs/sysplugins/smarty_internal_templateparser.php on line 2261
```
which are 2 Googlebots and another tracker

**Comment by uwetews** [comment]
How does your <?xml tag look like?

Can you provide some simplified template code showing this error?

Looks like the lexer/parser is in an endless loop.
Btw: The execution time error shows the line where it was after 60 seconds which will always be random.

**Comment by ophian** [comment]
> Can you provide some simplified template code showing this error?

```xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="{serendipity_getFile file='atom.css'}" type="text/css" ?>

<feed {$namespace_display_dat}
...
```
It had been like this for a long time.

I figured out it must have been the stylesheet line. I now moved it into the feed header as
`<link rel="stylesheet" href="{serendipity_getFile file='atom.css'}" type="text/css" />` which works well with 3.1.27.

At least the Smarty 28-dev told me me about this. But it was/is caused by two issues:
* an unclosed tag before the stylesheet, which could just change position as to be a link tag and
* a Fatal error:  Uncaught exception 'ErrorException' with message 'Warning: Parameter 2 to serendipity_replaceSmartyVars() expected to be a reference, value given in Smarty/libs/sysplugins/smarty_internal_filter_handler.php:63, which is in 
```php
function &serendipity_replaceSmartyVars($tpl_source, &$smarty) {
    $tpl_source = str_replace('$CONST.', '$smarty.const.', $tpl_source);
    return $tpl_source;
}
```
set by
```php
$serendipity['smarty']->registerFilter('pre', 'serendipity_replaceSmartyVars');
```
I can't say why that is though.
If I disable the prefilter register and change the stylesheet it works with 28-dev too.

**Comment by uwetews** [comment]
1.)  Using smarty tags within <?xml  ...  ?>  got broken some versions ago.
This is already fixed in the master branch and will be included in the upcoming 3.1.28 release in a few days.

2.) Since PHP5 it's no longer required to pass objects as reference. References should be removed from Smarty 2 plugins, filter etc.
Starting with 3.1.28 you can register closures as filter. For that reason the filter functions are now called as callback with call_user_func() which does not pass the reference.
See also the examples here http://www.smarty.net/docs/en/plugins.prefilters.postfilters.tpl

```
function serendipity_replaceSmartyVars($tpl_source, $smarty) {
    $tpl_source = str_replace('$CONST.', '$smarty.const.', $tpl_source);
    return $tpl_source;
}
```
Also note that Smarty 3 does pass the template object instead of the Smarty object to plugins and filter.
For BC you can use the properties and methods of the Smarty class also on the template object.
The mapping is done by the magic __get(), __set() and __call() methods.
For better performance you should directly access the Smarty object by $template->smarty.

**Comment by ophian** [comment]
Great, that is what was missing. I should have seen that...! Thanks.
Can you just give me a note why its says `$source, Smarty_Internal_Template $template` as parameters. What does that `Smarty_Internal_Template` do in there?

**Comment by uwetews** [comment]
Filters have so access to the template object $template or Smarty object by $template->smarty.
For example the filter function could be dependent on some property settings.

**Comment by ophian** [comment]
Yeah I do understand that.
I just do not understand why it it isn't `($source, $template)` only and has this `Smarty_Internal_Template` in it. What is that for? And what does it do?

**Comment by uwetews** [comment]
Its the type declaration (type hint).
See http://php.net/manual/en/functions.arguments.php

**Comment by ophian** [comment]
Oh thanks. I have not seen this before and did not know about it. 
So in this case its an instanceof, right?
