### ISSUE TITLE
smarty_internal_compile_private_modifier.php trim deprecated

### ISSUE THREAD

**Issue by lmramaya** [smarty-php/smarty#874]
Php 8.1 Smarty 4.3.1 FATAL [C:\www\smarty\libs\sysplugins\smarty_internal_compile_private_modifier.php:114] Using php-function "trim" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

in Smarty 4.2.1 work fine.

Tks

**Comment by wisskid** [comment]
It's a deprecation notice. Shouldn't be fatal. Do you use a custom error handler?

**Comment by wisskid** [comment]
That is correct

**Comment by interduo** [comment]
ok - so we are waiting politely :)

**Comment by Visualq** [comment]
@interduo as of 4.3 you will need to explicitly register the PHP functions you want to use as a modifier (as the error message states). Check [https://smarty-php.github.io/smarty/4.x/designers/language-modifiers/#examples](https://smarty-php.github.io/smarty/4.x/designers/language-modifiers/#examples) and [https://smarty-php.github.io/smarty/4.x/programmers/advanced-features/advanced-features-security/](https://smarty-php.github.io/smarty/4.x/programmers/advanced-features/advanced-features-security/)
