### ISSUE TITLE
unescape:htmlall and escape:htmlall are failing with an array input

### ISSUE THREAD

**Issue by Alaa-MK** [smarty-php/smarty#876]
It looks like `smarty/smarty:4.3.0` broke the `unescape:htmlall` modifier as well as `escape:htmlall` when used with an array input (breaking change: [here](https://github.com/smarty-php/smarty/commit/c016895166af23aa37468e7556577e3f7772065c#diff-511a9313699fe5fd97810996d2475f742ed637cb98c9af06804609279ae50dbaR42)). This is because `html_entity_decode` doesn’t accept an array as the first argument and throws a type error. This might also apply to other modifiers that I’m not aware of.

**PHP Vesion:** 8.1

**Error Message:**
```
Fatal error: Uncaught TypeError: html_entity_decode(): Argument #1 ($string) must be of type string, array given
```

### How to reproduce the issue
Here is the code I used to reproduce the issue:
```js
// templates/test.tpl
{$data|unescape:htmlall|json_encode}
```
```PHP
<?php

$this->smarty->data = ['test_1', 'test_2'];
$this->smarty->page = "templates/test";
```

Can we get a fix for this, please? 🙏
Thank you!

**Comment by ampmonteiro** [comment]
your `$data` is array type and unescape  requires a string. Please read the error.

And for passing data you should use `assign` method and for templates use `displa`y method

**Comment by wisskid** [comment]
I don't think `|escape` and `|unescape` were ever intended to work on arrays. But they did, and the documentation isn't clear on this. So I feel we should support this again, at least in v4, in order to maintain backwards compatibility as much as possible.

I'll work on a fix.

**Comment by wisskid** [comment]
It wasn't intended for sure. In fact, for half of the escape formats, arrays never worked. Also didn't work if Smarty was running in multibyte mode. 

@Alaa-MK I'm wondering if it's really worth to fix this. Would if be hard for you to switch to a `{for}` loop or create a `array_escape` and `array_unescape` modifier plugin?

**Comment by Alaa-MK** [comment]
@wisskid Thanks for taking a look at this!
The codebase is huge, so we cannot refactor and switch to a for loop. We avoided upgrading the package for the time being, but I assume we can implement a modifier plugin if needed in the future.
