### ISSUE TITLE
@iteration variable error in include

### ISSUE THREAD

**Issue by elvispdosreis** [smarty-php/smarty#877]
I have a problem with an iteration variable, I need to somehow use it in the main template, if I try to use it in the include template without having used it in the main one, I get the error "Undefined property: Smarty_Variable::$iteration"

does not work
```
{foreach $produtos as $produto}
  {include file="item.tpl"}
{/foreach}
```

it works
```
{foreach $produtos as $produto}
  {if $produto@iteration >= 0}
   {include file="item.tpl"}
  {/if}
{/foreach}
```

item.tpl

```
{$produto@iteration}
```

PHP: 8.1
Smarty: 4.3.1

**Comment by wisskid** [comment]
Have you tried passing it as a variable? This might work:
```smarty
{foreach $produtos as $produto}
  {include file="item.tpl" iteration=$produto@iteration}
{/foreach}
```

And change item.tpl so it used `$iteration` instead of `$produto@iteration`.

**Comment by elvispdosreis** [comment]
in version 3.1 I didn't have this behavior, more in the way you suggested also works

smarty/smarty: 3.1
php 7.4

**Comment by wisskid** [comment]
Actually, I have the same error "Undefined property: Smarty_Variable::$iteration" with Smarty 3.1.46. Which version are you using?

**Comment by wisskid** [comment]
Closed because of inactivity.
