### ISSUE TITLE
Since PHP 5.5.22 date_format error: Warning: date_format() expects parameter 1 to be DateTimeInterface, string given in

### ISSUE THREAD

**Issue by jsonjuri** [smarty-php/smarty#88]
Hi, Since i upgraded from PHP 5 to 5.5.22, after that the date format modifier doesn't work anymore.
I read on the smarty forum: http://www.smarty.net/forums/viewtopic.php?p=40290 that since 5.2: http://www.php.net/manual/en/function.date-format.php maybe cause a conflict?

input date: 2015-09-01
{$request.vessel_departure|date_format:"%d-%m-%Y"}

Warning: date_format() expects parameter 1 to be DateTimeInterface, string given in myurl/cache/compile/9d33c5b66c20f76243eb6af5d7fe2b244a6b3446.file.dropdown.tpl.php on line 69

Template structure:

<label class="control-label">Vessel arrival date {$request.vessel_arrival}</label>
<div class="input-group date" id="datepicker-vessel-arrival-{$request.request_id}" data-date-format="dd-mm-yyyy">
<input type="text" class="form-control" name="vessel_arrival" id="vessel-arrival-{$request.request_id}" placeholder="Select Date" value="{if $request.vessel_arrival != '0000-00-00'}{$request.vessel_arrival|date_format:"%d-%m-%Y"}{/if}" />
<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
</div>

**Comment by jsonjuri** [comment]
After long research i found out the problem was caused because the plugins folder was not set right.

**Comment by muyuren** [comment]
what is your method to fix this issue？

**Comment by jsonjuri** [comment]
What i remember is check if the plugin directory set to the right path.
