### ISSUE TITLE
[Unescape modifier] not working when call / use normal function

### ISSUE THREAD

**Issue by ampmonteiro** [smarty-php/smarty#888]
Hi,

I was trying include smarty 4 in CodeIgniter 4 App where i have the `$smarty->setEscapeHtml(true);` and for some function of CI i dont want that to be escaped, so i used  unescape modifier:

```php
       {* Not working *}
        {form_open('news/delete',[],['news_id' => {$news['id']}])|unescape}
            <button>Delete</button>
        {form_close()|unescape}
```
 the result is: 

![image](https://github.com/smarty-php/smarty/assets/31895754/535c6a99-02ae-4b35-bce5-528cd5bc2b01)

you can see the full code of CI4 + smarty 4 [here](https://github.com/ampmonteiro/ci4-with-smarty4-template-engine)

Also tried with a simple example:

```php

<?php
    require 'vendor/autoload.php';
    $smarty = new Smarty;
    
    $smarty->setTemplateDir('templates/');
    $smarty->setCompileDir('templates_c/');
    $smarty->setConfigDir('configs/');
    $smarty->setCacheDir('cache/');
    
    #$smarty->default_modifiers = ['escape:"htmlall"'];
    $smarty->setEscapeHtml(true);
    
    $name = '<strong>HTML STRONGs</strong>';
    $list = ['<li>one</li>', 'two'];
    
    function test(): string
    {
        return "<h1> ola </h1>";
    }
    
    $smarty->assign(compact('name', 'list'));
    $smarty->display('index.tpl');

```

and the template:

```php

  {* Smarty *}
  <p>Hello {$name}, welcome to Smarty!</p>
  
  {foreach $list as $item}
      <p>{$item}</p>
  {/foreach}
  
{* Not working *}
{test()|unescape} 

```

result:

![image](https://github.com/smarty-php/smarty/assets/31895754/9f7ef1e8-2d6e-4caf-8667-d04ab255ad25)

thanks

**Comment by wisskid** [comment]
That is not was unescape is for. 

> Template designers can choose to selectively disable this feature by adding the nofilter flag: {$variable nofilter}.

**Comment by ampmonteiro** [comment]
```php
       {* Not working *}
        {form_open('news/delete',[],['news_id' => {$news['id']}]) nofilter}
            <button>Delete</button>
        {form_close()  nofilter}

```


and

```php
  {* Smarty *}
  <p>Hello {$name}, welcome to Smarty!</p>
  
  {foreach $list as $item}
      <p>{$item}</p>
  {/foreach}
  
{* no escape*}
{test()  nofilter} 

```
thanks, it works.

However the word `unescape` is misleading because it not related to `escape`. The correct naming should be decode
as mention: 

> unescape is used to ***decode*** entity, html and htmlall. It counters the effects of the [escape modifier](https://smarty-php.github.io/smarty/4.x/designers/language-modifiers/language-modifier-escape/) for the given types.

And `nofilter` key word  should be a modifier as well or using `$smarty.nofilter` to be more clear.

Thanks. 
 I will close the issue tomorrow or Monday

**Comment by ampmonteiro** [comment]
And another thing that maybe i will create a issue: 

this is not possible with smarty:

```php 

{form_open('news/delete',  hidden:['news_id' => {$news['id']}]) nofilter}
        <button>Delete</button>
{form_close() nofilter}
```

i am using php 8.0 feature called [***Named Arguments***](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments), in this case ` hidden` name parameter and give me this error:

![image](https://github.com/smarty-php/smarty/assets/31895754/37561717-e86f-4a25-980e-f17299b2ddbb)

**Comment by wisskid** [comment]
Well, Smarty is not PHP. Although the syntax is clearly inspired by PHP, their syntaxes differ greatly. Thus, I would not consider this a bug, but it might be considered as a new feature.

**Comment by ampmonteiro** [comment]
@wisskid 

ok, but in requirements said:
> Requirements: Smarty can be run with PHP 7.1 to PHP 8.2.

however it is not fully compatible with few new features like [Named Arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments) which should be mention in the docs.

I still didn't try this with twig but tried with `Nette/Latte` template  which works perfectly fine:

```php  

    {form_open(
        'news/delete',
        hidden: ['news_id' => esc($news['id'])]
    )|noescape}
```  

you can see my full code [here](https://github.com/ampmonteiro/ci4-with-latte-template-engine/tree/main)

**Comment by wisskid** [comment]
Smarty is not PHP. The fact that Smarty can be run with PHP 7.1 to PHP 8.2 does not mean that the Syntax of Smarty is equal to the syntax of PHP. It is not, in many respects. There are some PHP language constructs that also work in Smarty and vice versa, but the similarities are in fact very limited.
