### ISSUE TITLE
date('d.m.Y') - not work!!!!!!!!!!

### ISSUE THREAD

**Issue by AlexJMcloud** [smarty-php/smarty#896]
ruined even what worked normally. So use composer. Set up and come .... when you want to add something. Removed standard php compare functions. The date format is also done in one place. For what?????

**Comment by AlexJMcloud** [comment]
Maybe you made it easier for designers, but complicated for programmers. Now all perversions with dates will have to be done before passing to the template.(((((

**Comment by AlexJMcloud** [comment]
[strftime()](https://www.php.net/strftime) format - in 8.2 depricated

**Comment by wisskid** [comment]
I have no idea what you are trying to say. Is there a bug?

If so, please let us know what version you are using, what happened (with steps to reproduce) and what you expected to happen.

**Comment by AlexJMcloud** [comment]
you have removed the standard comparison functions. Now I don't have to check the type of a variable. since I made a universal form. and I have one and the same variable in two types. either object or bool

**Comment by AlexJMcloud** [comment]
now you need to do everything separately, as they say under each comma a new template.

**Comment by AlexJMcloud** [comment]
now it is impossible to make a form with dynamic data. Only static

**Comment by AlexJMcloud** [comment]
It's easier to write in the changes that you have completely removed support for php functions.
I have installed version 5.0

**Comment by AlexJMcloud** [comment]
Although it is written in your concept: - you need to give the editing of the template to the secretary. Let him write whatever he wants. I didn’t put down the html tags, well, okay, let it just be a text.

**Comment by AlexJMcloud** [comment]
javascript can also be disabled.

**Comment by scottchiefbaker** [comment]
@AlexJMcloud is this a bug report or a rant? I'm not sure what the heck you're expecting here. Either get to the point, or move on.

**Comment by cYbercOsmOnauT** [comment]
First of all: As far as I know v5.0 is not released yet. You are working with a beta release at best. Right?
Second: v4.x is still available and all you need to do is to remove your v5.0 Smarty directory and overwrite it with 4.x.

In my opinion you have a suggestion that something should stay. I understood that you want to be able to use PHP functions directly in a template. I don't like to work like this. A template is to show something. Data is created in the script(s). Correct me if I am wrong.

**Comment by wisskid** [comment]
@cYbercOsmOnauT you are not wrong. But you will still need to call some functions in your code. Luckily, smarty provides several modifiers for this and you can also add your own.

This is not necessary here, since we have the date_format modifier: 

{$myVar|date_format:"%Y-%m-%d"}
