### ISSUE TITLE
Smarty 5: `registerPlugin()` no longer working with names containing non-lowercase characters

### ISSUE THREAD

**Issue by m-ober** [smarty-php/smarty#907]
This should output "Test" but gives the following error in Smarty 5 / dev-master. Working with latest 4.x version.

> Smarty\CompilerException: Syntax error in template "string:{customTag}" on line 1 "{customTag}" unknown tag 'customtag' in string:{customTag} on line 1

```php
<?php

require 'vendor/autoload.php';

use Smarty\Smarty;
//use \Smarty;

class Functions
{
    public static function customTag()
    {
        return 'Test';
    }
}

$smarty = new Smarty();
$smarty->registerPlugin(Smarty::PLUGIN_FUNCTION, 'customTag', [Functions::class, 'customTag']);
$smarty->display('string:{customTag}');
```

**Comment by wisskid** [comment]
Might be problem with case sensitivity. Does it work when you change the registerPlugin line as follows?
`$smarty->registerPlugin(Smarty::PLUGIN_FUNCTION, 'customtag', [Functions::class, 'customTag']);`

**Comment by m-ober** [comment]
Yes, with this change it's working again. But that would require _a lot_ of refactoring in all templates...

**Comment by wisskid** [comment]
No worries, we'll fix this. Should be easy! Thank you for your bug report.
