### ISSUE TITLE
Fetch recursion

### ISSUE THREAD

**Issue by andyburton** [smarty-php/smarty#91]
Calling fetch() on the $tpl argument passed to a function plugin is causing recursion after updating from 3.1.21 to 3.1.27

Previously this would run happily but since the update it is causing a seg fault due to recursion!

```
function smarty_function_messages ($params, &$tpl)
{
    $messages = null;
    foreach (Message::get() as $message) {
        $tpl->assign ('message', $message);
        $messages .= $tpl->fetch ('message.tpl');
    }
    return $messages;
}
```

The call to fetch now appears to re-render the template already defined on $tpl resulting in the original template containing the function call to {messages} being re-executed and hence recursion.

I've not delved too far into the Smarty code but copy/pasting bits from the fetch function into this does get things working without recursion -

```
function smarty_function_messages ($params, &$tpl)
{
    $messages = null;
    foreach (Message::get() as $message) {
        $newTpl = $tpl->createTemplate('message.tpl');
        $newTpl->caching = $tpl->caching;
        $newTpl->assign ('message', $message);
        $messages .= $newTpl->render();
    }
    return $messages;
}
```

**Comment by uwetews** [comment]
This is a bug. It should not get into re recursion. I will fix that

However to fetch the current template multiple times just call fetch() without any parameter.

```
function smarty_function_messages ($params, &$tpl)
{
    $messages = null;
    foreach (Message::get() as $message) {
        $tpl->assign ('message', $message);
        $messages .= $tpl->fetch ();
    }
    return $messages;
```

**Comment by uwetews** [comment]
Its a bug. I will try to fix this asap

**Comment by uwetews** [comment]
Same as here https://github.com/smarty-php/smarty/issues/70.
Its already covered in the master branch. However some work is in progress there for the 3.1.28 release. 

Looking at your code the following should have even better performance as the original one 

```
function smarty_function_messages ($params, &$tpl)
{
    $messages = null;
        $newTpl = $tpl->createTemplate('message.tpl');
        $newTpl->caching = $tpl->caching;
    foreach (Message::get() as $message) {
        $newTpl->assign ('message', $message);
        $messages .= $newTpl->render();
    }
    return $messages;
}
```

**Comment by andyburton** [comment]
Thanks for looking into this :)

The example code i provided is massively slimmed down to demonstrate the bug - but yes i appreciate you do not need to re-create the same template each time.
