### ISSUE TITLE
Wrong compilation for variables treated as constant

### ISSUE THREAD

**Issue by dpighin82** [smarty-php/smarty#93]
Hi,
I updated smarty from version "v3.1.21" to "v3.1.27" After doing that I have some issues related with PHP errors like below:
"PHP Notice:  Undefined index: Descripci\xc3\xb3n in C:\\..."

I found that the template file compilation ".....file.filename.tpl.php" have some variables compiled as
$_smarty_tpl->tpl_vars['ad']->value[DESCRIPTION] . 
The correct way should be with '' like $_smarty_tpl->tpl_vars['ad']->value['DESCRIPTION'] 

I think when compiling the key DESCRIPTION is treated as constant instead of variable. 
Because DESCRIPTION is a constant in the application with the value "Descripción"

The variable are set in the php file as follow:
$fArray[$ad_id]["DESCRIPTION"]   = $ad_description;
..
$tplList->assign("ads",$fArray);

Thanks in advance!

Regards

**Comment by uwetews** [comment]
Meanwhile Smarty does support constants in template files. If you use
```
{$ad_id.DESCRIPTION}
```
There is now an ambiguity between the constant and the intended string index.
In this case you must change your template code to PHP syntax
```
{$ad_id['DESCRIPTION']}
```
In the older Smarty syntax the compiler now checks if the index name is defined as constant and generates conformig compiled code.
