### ISSUE TITLE
Containment operators

### ISSUE THREAD

**Issue by wisskid** [smarty-php/smarty#937]
Support for:

```smarty
{if $i in [1, 2, 3]}...{/if}
```

and 

```smarty
{if $j not in [1, 2, 3]}...{/if}
```

**Comment by wisskid** [comment]
This could be extended to strings as well: `{if 'im' in $name}..{/if}`

**Comment by scottchiefbaker** [comment]
I like this idea a lot... Would it also work for:

```
{if $needle in $haystack_array}
```

**Comment by wisskid** [comment]
@scottchiefbaker yes

**Comment by wisskid** [comment]
It seems Smarty v5 also supports in_array as a function. (implemented as FunctionHandler.) This is undocumented.

**Comment by wisskid** [comment]
Wow, this is funny. From the changelog in 2009: `- added  {if  'expression' is in 'array'}  syntax`
This is undocumented, and we do not have `{if  'expression' is not in 'array'}` yet.
