### ISSUE TITLE
last version that supports php v7.0.x?

### ISSUE THREAD

**Issue by kosuodhmwa** [smarty-php/smarty#944]
hi

which is last version that supports php v7.0.x?

thx for feedback.

best regards,
jan

**Comment by kosuodhmwa** [comment]
doesnt work: https://github.com/smarty-php/smarty/releases/tag/v4.4.1 - but you write <Smarty v5 can be run with PHP 7.2 to PHP 8.3>

so v4.4.1 needs php 7.1.x at least to work?

**Comment by klaoun** [comment]
Hi
Try version 4.3.1

**Comment by kosuodhmwa** [comment]
thank you very much - i tried it, but it does not work; and i've found that page https://www.smarty.net/download which describes that smarty 4.1 need higher php version than 7.0.x...

**Comment by kosuodhmwa** [comment]
maybe there is a fork of smarty 4.x which is compatible?

**Comment by wisskid** [comment]
Smarty v4 has never supported PHP7.0. You'd have to go al the way back to v3.1.48. @kosuodhmwa

**Comment by kosuodhmwa** [comment]
hi 

thank you very much, i used google to search for a zip (without composer) & found that page here:
https://github.com/smarty-php/smarty/releases/tag/v3.1.48

seems not to be in the "official" release list on https://github.com/smarty-php/smarty/releases?page=3 - is that v3.1.48 a "special" version?

but it seems to work, :-)

**Comment by KarelWintersky** [comment]
is Smarty5 supports PHP 7.4 ?

**Comment by scottchiefbaker** [comment]
@KarelWintersky check the documentation here: https://github.com/smarty-php/smarty?tab=readme-ov-file#requirements
