### ISSUE TITLE
Function scoped variables overwriting parent scope in v5.0.0-rc3

### ISSUE THREAD

**Issue by Snor** [smarty-php/smarty#952]
In this example, the $var assignment inside the function persists outside of the function:

````
{function name=test}
    {$var="b"}
{/function}

{$var="a"}

{test}

{$var}
````

So Smarty 4 would output "a" as you'd expect, but Smarty v5.0.0-rc3 outputs "b".

**Comment by m-ober** [comment]
This issue still exists when using `extends:` - see #1196
