### ISSUE TITLE
Custom Extension not working since v5 release

### ISSUE THREAD

**Issue by TeamRBMedia** [smarty-php/smarty#957]
Hi,

The custom extensions are not working since the v5 update today. In v5 RC everything seemed to be working fine.  Is there something we need to change?

**Comment by wisskid** [comment]
No, there should be no change between the last release candidate (rc3) and the released version.

**Comment by wisskid** [comment]
@TeamRBMedia do you have any more details?

**Comment by wisskid** [comment]
Closed because of inactivity.
