### ISSUE TITLE
How to disable deprecation warning? 

### ISSUE THREAD

**Issue by KarelWintersky** [smarty-php/smarty#958]
> Using unregistered function "getenv" in a template is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

> Using unregistered static method "Arris\AppRouter::getRouter('ajax.view.poi.info')" in a template is deprecated and will be removed in a future release. Use Smarty::registerClass to explicitly register a class for access.

how to suppress such message in latest Smarty Releases? 

Yes, I know what I'm doing. 

No, I am not able to declare these methods due to certain architectural limitations of the project.

**Comment by wisskid** [comment]
See https://www.php.net/manual/en/function.error-reporting.php

**Comment by jszczypk** [comment]
You can mute E_USER_DEPRECATED globally or just in Smarty using something like:
```
$smarty->error_reporting = error_reporting() & ~E_USER_DEPRECATED;
```
