### ISSUE TITLE
Function declared, but NOT

### ISSUE THREAD

**Issue by KarelWintersky** [smarty-php/smarty#959]
PHP 7.4, Smarty 4.5.1 

```
$this->smarty->registerPlugin('function', 'getenv', 'getenv');
```
then

```
var_dump($smarty->registered_plugins);
```

returns:
```
array(2) {
  ["function"]=>
  array(1) {
    ["getenv"]=>
    array(3) {
      [0]=>
      string(6) "getenv"
      [1]=>
      bool(true)
      [2]=>
      array(0) {
      }
    }
  }
}
```

but:

> Using unregistered function "getenv" in a template is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

**Comment by KarelWintersky** [comment]
Used somewhere in templates like:

```
{if getenv('ENV_STATE') == 'dev'}
 ... 
{else}
...
{/if}
```

**Comment by wisskid** [comment]
The error message could have been clearer: you nees to register it as a modifier, not as a function.

**Comment by KarelWintersky** [comment]
It works. Thank you. Is it declared anywhere in documentation?

**Comment by wisskid** [comment]
https://smarty-php.github.io/smarty/stable/api/extending/modifiers/

**Comment by KarelWintersky** [comment]
But it's is not a like modifier...

```
{if getenv('ENV_STATE') == 'dev'}
 ... 
{else}
...
{/if}
```

**Comment by AlexPashley** [comment]
I think modifiers are classed as both {$var|get_env} and {if get_env()}{/if}

if it was {getEnv} it would be a block not a modifier 
https://smarty-php.github.io/smarty/stable/api/extending/block-tags/

**Comment by Gemorroj** [comment]
@KarelWintersky it's variant of modifier. see https://smarty-php.github.io/smarty/stable/designers/language-modifiers/#using-modifiers-in-expressions
but I agree, it's not obvious and at first glance it looks like a mistake.
