### ISSUE TITLE
smarty 2.6.29

### ISSUE THREAD

**Issue by glensc** [smarty-php/smarty#97]
i see it's tagged in git:
https://github.com/smarty-php/smarty/releases/tag/v2.6.29

but no download:
http://www.smarty.net/files/

have the downloads moved to github, the old place is no longer updated?

**Comment by uwetews** [comment]
http://www.smarty.net/files/  is no longer updated.

See http://www.smarty.net/download

**Comment by glensc** [comment]
thanks for clarifying!

**Comment by glensc** [comment]
@uwetews http://www.smarty.net/download does not mention 2.6.29, but still releases/tag/v2.6.28

![screenshot at 2015-12-14 23 09 34](https://cloud.githubusercontent.com/assets/199095/11794023/c80ec5cc-a2b7-11e5-94a9-9153c402359d.png)
