### ISSUE TITLE
Q/A - Smarty Plugins v4 > v5

### ISSUE THREAD

**Issue by ce-ju** [smarty-php/smarty#971]
Hello, first thank you for your work on Smarty (v5) @wisskid 

I have read the documentation, but don't really understand how to add plugins (modifier/function) from v4 to v5.

Something with `$smarty->registerPlugin();` but where do I save my plugins? In v4 I have the plugins all in the folder `/includes/smarty/plugins/` which I have included with `$smarty->addPluginsDir('./includes/smarty/plugins');`.

But this will soon be deprecated.

Thanks!

**Comment by wisskid** [comment]
Sound like you want to use `$smarty->addPluginsDir()`. If you want to get rid of the deprecation notice that this triggers, please refer to https://smarty-php.github.io/smarty/5.x/api/extending/introduction/
