### ISSUE TITLE
Changelog is incomplete

### ISSUE THREAD

**Issue by Chrissyx** [smarty-php/smarty#974]
Just a minor issue, I noticed that the current CHANGELOG.md does not list the releases between 4.3.2 and 5.0.0-rc1.

On another note, there is a changelog _folder_ having some issues referenced without any version assignment. Is this intended?

**Comment by wisskid** [comment]
Yes this is intended and the changelog is not incomplete. The two versions are maintained separately. The changelogs folder is for temporarily managing unreleased entries for the changelog. See the make-release.sh script.

**Comment by Chrissyx** [comment]
There is still something odd. While the v4 changelog is complete in terms of all releases up the newest 4.x one, it is listing the latest entry as unreleased:
https://github.com/smarty-php/smarty/blob/v4.5.2/CHANGELOG.md

However I still don't get it why you would want to have that gap between 4.3.2 and 5.x in the master branch and consequently in all v5 releases? Maybe omit all pre-v5 releases in the changelog instead to mitigate the effects of separated maintenance? Or eventually add them back once support for v4 has ended?

**Comment by wisskid** [comment]
@Chrissyx v4 in still being maintained while we also support v5. This means that the v4 branch may receive changes that will actually never end up in v5. It's not chronological. For example: v5.0.0 doesn't come after v4.5.2, but before it.

The "Unreleased" placeholder is always there. When a release is made, the new version number is added under the placeholder.

**Comment by Chrissyx** [comment]
> The "Unreleased" placeholder is always there. When a release is made, the new version number is added under the placeholder.

I know, but the v4.5.2 is released under "[Unreleased]" placeholder - there is no "[4.5.2]" title with the release date.

**Comment by wisskid** [comment]
@Chrissyx aah, sorry, you are absolutely right. Will fix it in support/4 now.
