### ISSUE TITLE
smarty.net down

### ISSUE THREAD

**Issue by boppy** [smarty-php/smarty#989]
All it shows is "No Sponsors".

Same for any browser and true for connections from Germany and Finland.

![image](https://github.com/smarty-php/smarty/assets/749141/450ece9e-ab09-4f94-8ac6-a501083a4eea)

**Comment by mrd83** [comment]
+1
I tried firefox, edge and mercury - result is as shown above

**Comment by wisskid** [comment]
I am aware of this issue. I've tried contacting @mohrt who manages the website but haven't heard from him yet. The official Smarty documentation is still available at https://smarty-php.github.io/smarty

**Comment by scottchiefbaker** [comment]
@mx03 I like the new documentation, but it has room for improvement as well. 

You mention a couple of good points. Why don't you open a separate issue about documentation improvements and we can all comment and get the docs in a good state for everyone.

**Comment by romain-cm** [comment]
In case you need older documentations (Smarty 2, 3, 4)... 

Think Wayback Machine! For example here Smarty 3 docs in english first page. [Web Archive Wayback Machine, Smarty 3 docs](https://web.archive.org/web/20230928175000/https://www.smarty.net/docs/en/)

**Comment by mohrt** [comment]
website DNS is fixed, website is up.

**Comment by romain-cm** [comment]
> website DNS is fixed, website is up.
> […](#)
> On Thu, Apr 11, 2024 at 8:30 AM romain-cm ***@***.***> wrote: In case you need older documentations (Smarty 2, 3, 4)... Think Wayback Machine! For example here Smarty 3 docs in english first page. Web Archive Wayback Machine, Smarty 3 docs — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Heep heep heep huray !

Thank you Monte Ohrt!

**Comment by lkppo** [comment]
Hello mohrt,

> website DNS is fixed, website is up.

Would you be interested in either receiving help with this hosting or transferring all elements and ownership of the domain name to release yourself from hosting the project?

Regards,

**Comment by alexandrebrubeyonds** [comment]
it works on www : https://www.smarty.net/
