### ISSUE TITLE
getTemplateVars - why the change in return signature in smarty 5?

### ISSUE THREAD

**Issue by demeritcowboy** [smarty-php/smarty#994]
Short version: Any code that calls getTemplateVars() breaks with smarty5 because it's expecting an array of values, and instead getting an array of objects.

Slightly longer version: At the very least the change seems inconsistent. If you pass in a variable name, it returns its value not the object. Either it should always return an object, or not be a breaking change and do what it did before.

What was the reason for the change, and should it be made more consistent (either way)?

**Comment by wisskid** [comment]
You are correct, this was never intended. I've created https://github.com/smarty-php/smarty/pull/995
Does that fix this issue?

**Comment by demeritcowboy** [comment]
Yes it does. Great! Thank you.
